// Code generated by testkit. DO NOT EDIT.
//
// Source:    corpus/iface/detector/streamconsumer/iface.go
// Plugins:   golang 1.0.0, suite 1.24.0, backend.golang 1.0.0
// Command:   testkit run ./corpus/...

package streamconsumertest_test

import (
	"testing"

	"go.thesmos.sh/testkit/conformance/corpus/iface/detector/streamconsumer/streamconsumertest"
	"go.thesmos.sh/testkit/engine/suite"
)

// The planted defects live in the file beside this one, on ProveSource.
//
// They were here once, and could not stay: a check may need a capability,
// and only your harness answers it. A defect stands in for a real subject
// and borrows the same answer — which a test function in this package has
// no way to reach, because the harness is written in yours. So the map
// went where the entry point that takes it lives, and ProveSource
// drives every defect below alongside the ones your own rows name:
//
//	Next.Smoke — a Source whose Next panics
//
//	Next.Cancels — a Source whose Next ignores the context it is handed
//
//	Next.NilContext — a Source whose Next forgives a nil context and answers
//
//	Next.Deadline — a Source whose Next ignores the context it is handed
//
//	Next.ZeroOnError — a Source whose Next answers a believable value beside its error

// TestSourceInvariants holds this package to what it says about itself.
//
// Four claims, none of which a consumer writes and none of which any
// other gate makes. The manifest pins the assertion SET, so a check that
// stops being emitted reads as a removed row in review rather than as a
// suite that quietly got smaller. The index and the drop hints pin the
// two ways a check is NAMED — an index entry pointing at nothing
// compiles, and a drop hint that falls back to the string form forfeits
// exactly the compile-break the index exists to give. The distinct-ID
// check catches two interfaces in one package claiming one identity,
// which method-name scopes make possible.
func TestSourceInvariants(t *testing.T) {
	t.Parallel()

	s := streamconsumertest.SourceSuite.Suite()

	rows, err := suite.LockLines(s)
	if err != nil {
		t.Fatalf("render the manifest rows: %v", err)
	}
	suite.VerifyLock(t, "source.checks.lock", rows)
	suite.VerifyIndex(t, "Source",
		streamconsumertest.SourceSuite.Checks.All(), s.IDs())
	suite.VerifyDropHints(t, "Source", s.IDs(), s.DropHint)
	suite.VerifyDistinctIDs(t, s.IDs())
}

// The planted defects live in the file beside this one, on ProveStreamConsumer.
//
// They were here once, and could not stay: a check may need a capability,
// and only your harness answers it. A defect stands in for a real subject
// and borrows the same answer — which a test function in this package has
// no way to reach, because the harness is written in yours. So the map
// went where the entry point that takes it lives, and ProveStreamConsumer
// drives every defect below alongside the ones your own rows name:
//
//	Ingest.Smoke — a StreamConsumer whose Ingest panics

// TestStreamConsumerInvariants holds this package to what it says about itself.
//
// Four claims, none of which a consumer writes and none of which any
// other gate makes. The manifest pins the assertion SET, so a check that
// stops being emitted reads as a removed row in review rather than as a
// suite that quietly got smaller. The index and the drop hints pin the
// two ways a check is NAMED — an index entry pointing at nothing
// compiles, and a drop hint that falls back to the string form forfeits
// exactly the compile-break the index exists to give. The distinct-ID
// check catches two interfaces in one package claiming one identity,
// which method-name scopes make possible.
func TestStreamConsumerInvariants(t *testing.T) {
	t.Parallel()

	s := streamconsumertest.StreamConsumerSuite.Suite(streamconsumertest.DefaultStreamConsumerFixture())

	rows, err := suite.LockLines(s)
	if err != nil {
		t.Fatalf("render the manifest rows: %v", err)
	}
	suite.VerifyLock(t, "streamConsumer.checks.lock", rows)
	suite.VerifyIndex(t, "StreamConsumer",
		streamconsumertest.StreamConsumerSuite.Checks.All(), s.IDs())
	suite.VerifyDropHints(t, "StreamConsumer", s.IDs(), s.DropHint)
	suite.VerifyDistinctIDs(t, s.IDs())
}

// testkit: end of generated content.
// testkit:provenance 5bfcea91a64201834afb725b06a205e61101643f051db8e1bf8ef64fdc6bce90
