// Code generated by testkit. DO NOT EDIT.
//
// Source:    corpus/iface/detector/compositewriter/iface.go
// Plugins:   golang 1.0.0, stub 1.4.0, backend.golang 1.0.0
// Command:   testkit run ./corpus/...

package compositewritertest_test

import (
	"context"
	"testing"
	"time"

	"go.thesmos.sh/testkit"
	"go.thesmos.sh/testkit/clock"
	"go.thesmos.sh/testkit/conformance/corpus/iface/detector/compositewriter"
	"go.thesmos.sh/testkit/conformance/corpus/iface/detector/compositewriter/compositewritertest"
	"go.thesmos.sh/testkit/rand"
	"go.thesmos.sh/testkit/stub"
)

// compositeWriterStubSetSubject binds Set into the shape
// [stub.Behaviour] drives: how to call it, what it answers with, and how to
// override it.
//
// Each call builds a fresh double, because several of the checks assert on
// failure and need one bound to a failable TB rather than to the running
// test.
func compositeWriterStubSetSubject(tb testing.TB) stub.Subject[compositewritertest.CompositeWriterSetCall, compositewritertest.CompositeWriterSetReturn] {
	tb.Helper()
	s := compositewritertest.NewCompositeWriterStub(tb)
	return stub.Subject[compositewritertest.CompositeWriterSetCall, compositewritertest.CompositeWriterSetReturn]{
		Stub: s.OnSet.MethodStub,
		Call: func() {
			var a0 context.Context
			var a1 string = "test-key"
			var a2 compositewriter.Value
			_ = s.Set(a0, a1, a2)
		},
		Result: func() compositewritertest.CompositeWriterSetReturn {
			var a0 context.Context
			var a1 string = "test-key"
			var a2 compositewriter.Value
			got0 := s.Set(a0, a1, a2)
			return compositewritertest.CompositeWriterSetReturn{Err: got0}
		},
		Override: func(mark func()) {
			s.OnSet.Func(func(_ context.Context, _ string, _ compositewriter.Value) error {
				mark()
				var z0 error
				return z0
			})
		},
		Fails: func() error {
			var a0 context.Context
			var a1 string = "test-key"
			var a2 compositewriter.Value
			r0 := s.Set(a0, a1, a2)
			return r0
		},
	}
}

// TestCompositeWriterStubSet pins how Set answers.
//
// Recording, resetting, call-count expectations, strict mode, fault injection
// and zero-value dispatch are the same contract for every method, so they are
// asserted once in [stub.Behaviour] rather than restated here. What remains
// below needs a value this method's signature can tell apart from a zero one.
func TestCompositeWriterStubSet(t *testing.T) {
	t.Parallel()

	stub.Behaviour(t, "Set", compositeWriterStubSetSubject)

	// No check that Set answers what Returns pinned: no result of
	// its signature admits a literal this generator can write, so the only
	// value available to pin is the zero — which an unconfigured double
	// answers anyway. stub.Behaviour asserts that half honestly.
	t.Run("records what it was called with", func(t *testing.T) {
		t.Parallel()
		// Asserting only that a call happened would pass against a double
		// that recorded the wrong arguments, which is the failure a reader
		// most needs the log to surface.
		s := compositewritertest.NewCompositeWriterStub(t)
		var a0 context.Context
		var a1 string = "test-key"
		var a2 compositewriter.Value
		_ = s.Set(a0, a1, a2)
		got := s.OnSet.AssertCalledOnce(t, "Set must record the call")
		testkit.Equal(t, got.Ctx, a0, "the recorded call carries Ctx")
		testkit.Equal(t, got.Key, a1, "the recorded call carries Key")
		testkit.Equal(t, got.V, a2, "the recorded call carries V")
	})

	t.Run("fires the OnRecord hook for every call", func(t *testing.T) {
		t.Parallel()
		// The hook fires synchronously as each call lands, which is what a
		// concurrency test observes progress with — polling the log instead
		// races the thing under test.
		s := compositewritertest.NewCompositeWriterStub(t)
		var seen []compositewritertest.CompositeWriterSetCall
		s.OnSet.OnRecord(func(c compositewritertest.CompositeWriterSetCall) { seen = append(seen, c) })
		var a0 context.Context
		var a1 string = "test-key"
		var a2 compositewriter.Value
		_ = s.Set(a0, a1, a2)
		_ = s.Set(a0, a1, a2)
		testkit.Len(t, seen, 2, "OnRecord must fire once per Set call")
	})

	t.Run("wires WithCompositeWriterSet at construction", func(t *testing.T) {
		t.Parallel()
		called := false
		s := compositewritertest.NewCompositeWriterStub(t, compositewritertest.WithCompositeWriterSet(func(_ context.Context, _ string, _ compositewriter.Value) error {
			called = true
			var z0 error
			return z0
		}))
		var a0 context.Context
		var a1 string = "test-key"
		var a2 compositewriter.Value
		_ = s.Set(a0, a1, a2)
		testkit.True(t, called, "WithCompositeWriterSet must install the override")
	})

	t.Run("keeps recording across a reset", func(t *testing.T) {
		t.Parallel()
		// The weaker claim, and the honest one for this signature. No result
		// of Set admits a literal, so what Returns pinned cannot be
		// told from the zero and comparing them would pass either way.
		//
		// What a reset can still be held to is that it clears the log without
		// taking the double with it: configure, call, reset, call again, and
		// exactly one call is recorded. A reset that dropped the whole
		// configuration fails that, which is the failure the value comparison
		// was reaching for and could not state.
		s := compositewritertest.NewCompositeWriterStub(t)
		var want0 error
		s.OnSet.Returns(want0)
		var a0 context.Context
		var a1 string = "test-key"
		var a2 compositewriter.Value
		_ = s.Set(a0, a1, a2)
		s.ResetCalls()
		_ = s.Set(a0, a1, a2)
		s.OnSet.AssertCalledOnce(t, "Set must record the call that followed the reset")
	})
}

// compositeWriterStubDouble describes how to build a CompositeWriterStub under each
// option whose effect is the same whatever a method's signature.
//
// Set stands in for the double as a whole: what these checks assert
// is that an option reached it at all, and the first method witnesses that as
// well as any other would.
func compositeWriterStubDouble() stub.Double[compositewritertest.CompositeWriterSetCall] {
	instance := func(s *compositewritertest.CompositeWriterStub) stub.Instance[compositewritertest.CompositeWriterSetCall] {
		return stub.Instance[compositewritertest.CompositeWriterSetCall]{
			Stub: s.OnSet.MethodStub,
			Call: func() {
				var a0 context.Context
				var a1 string = "test-key"
				var a2 compositewriter.Value
				_ = s.Set(a0, a1, a2)
			},
			Reset: s.ResetCalls,
		}
	}
	return stub.Double[compositewritertest.CompositeWriterSetCall]{
		New: func(tb testing.TB) stub.Instance[compositewritertest.CompositeWriterSetCall] {
			return instance(compositewritertest.NewCompositeWriterStub(tb))
		},
		WithClock: func(tb testing.TB, clk clock.Clock) stub.Instance[compositewritertest.CompositeWriterSetCall] {
			return instance(compositewritertest.NewCompositeWriterStub(tb, compositewritertest.CompositeWriterStubWithClock(clk)))
		},
		WithRandSource: func(tb testing.TB, src rand.Source) stub.Instance[compositewritertest.CompositeWriterSetCall] {
			return instance(compositewritertest.NewCompositeWriterStub(tb, compositewritertest.CompositeWriterStubWithRandSource(src)))
		},
		BenchMode: func(tb testing.TB) stub.Instance[compositewritertest.CompositeWriterSetCall] {
			return instance(compositewritertest.NewCompositeWriterStub(tb, compositewritertest.CompositeWriterStubBenchMode()))
		},
		Strict: func(tb testing.TB) stub.Instance[compositewritertest.CompositeWriterSetCall] {
			return instance(compositewritertest.NewCompositeWriterStub(tb, compositewritertest.CompositeWriterStubStrict()))
		},
	}
}

// TestCompositeWriterStubOptions pins the settings that apply to the double rather
// than to one method: bench mode, the injected clock and random source, and
// what a reset clears.
func TestCompositeWriterStubOptions(t *testing.T) {
	t.Parallel()

	stub.DoubleBehaviour(t, compositeWriterStubDouble())
}

// TestCompositeWriterStubDelegateTo pins that a wrapped implementation is called
// through, and recorded on the way past.
//
// This is what lets one generated suite run against both the double and a
// production type, which is the point of conformance testing.
func TestCompositeWriterStubDelegateTo(t *testing.T) {
	t.Parallel()

	inner := compositewritertest.NewCompositeWriterStub(t)
	s := compositewritertest.NewCompositeWriterStub(t, compositewritertest.CompositeWriterStubDelegateTo(inner))

	t.Run("forwards Set to the wrapped implementation", func(t *testing.T) {
		var a0 context.Context
		var a1 string = "test-key"
		var a2 compositewriter.Value
		_ = s.Set(a0, a1, a2)
		inner.OnSet.AssertCalledOnce(t, "Set must reach the wrapped implementation")
	})

	t.Run("surfaces what Set answered", func(t *testing.T) {
		// Reaching the wrapped implementation is not enough: a double that
		// called through and then discarded the answer would pass the check
		// above while telling its caller nothing true.
		want := testkit.TestError("Set-delegate")
		inner.OnSet.FaultsFor(time.Hour, want)
		var a0 context.Context
		var a1 string = "test-key"
		var a2 compositewriter.Value
		r0 := s.Set(a0, a1, a2)
		testkit.ErrorIs(t, r0, want, "Set must surface the wrapped answer")
	})
}

// testkit: end of generated content.
// testkit:provenance f809e032d1269186da2b697f98c8d862cd26f5df5ba535aef80f7a4c53a850be
