// Code generated by testkit. DO NOT EDIT.
//
// Source:    corpus/iface/mixin/restrictedpool/iface.go
// Plugins:   golang 1.0.0, stub 1.4.0, backend.golang 1.0.0
// Command:   testkit run ./corpus/...

// Conformance checks worked out from the interfaces this package doubles.
//
// One call runs every check for an interface against one implementation.
// Describe the implementation in a literal and hand it over — each
// interface's own Run function is documented beside it, with the names
// to use.
//
// Nothing else is required to start. The rest is there when you need it:
// a harness field to add only when a check fails asking for it, checks of
// your own that run beside the generated ones, a Prove entry that drives
// each of yours against the broken implementation it names, and a typed
// index for dropping a check by identity rather than by string.
//
// Nothing here is written by hand. Regenerate rather than edit: an edit
// survives until the next run and no longer.
package restrictedpooltest

import (
	"context"
	"testing"

	"go.thesmos.sh/testkit/clock"
	"go.thesmos.sh/testkit/conformance/corpus/iface/mixin/restrictedpool"
	"go.thesmos.sh/testkit/rand"
	"go.thesmos.sh/testkit/stub"
)

// StorePutCall records one invocation of Store.Put.
//
// Fields take their names from the source signature — parameters and named
// returns alike — so a failure message names what the author named. A slot
// the source left unnamed or blank falls back to a positional name.
type StorePutCall struct {
	Ctx  context.Context
	Key  restrictedpool.Key
	Body restrictedpool.Body
	Err  error
}

// StoreGetCall records one invocation of Store.Get.
//
// Fields take their names from the source signature — parameters and named
// returns alike — so a failure message names what the author named. A slot
// the source left unnamed or blank falls back to a positional name.
type StoreGetCall struct {
	Ctx    context.Context
	Key    restrictedpool.Key
	Result restrictedpool.Body
	Err    error
}

// --- Per-method configuration ---

// StorePutStub controls how the double answers Put and records
// what it was asked.
//
// The embedded MethodStub supplies the machinery every method shares: call
// recording, fault injection, latency against a virtual clock, gates,
// call-count expectations, and strict mode.
type StorePutStub struct {
	*stub.MethodStub[StorePutCall]

	fn       func(context.Context, restrictedpool.Key, restrictedpool.Body) error
	fallback *StorePutReturn
}

// StorePutReturn holds the fixed answer configured through Returns.
type StorePutReturn struct {
	Err error
}

// Returns pins a fixed result for every call to Put. A Func
// override and an injected fault both take precedence over it.
func (s *StorePutStub) Returns(err error) *StorePutStub {
	s.fallback = &StorePutReturn{Err: err}
	return s
}

// Func supplies a body for Put, for when the answer depends on the
// arguments. An injected fault still takes precedence.
func (s *StorePutStub) Func(fn func(context.Context, restrictedpool.Key, restrictedpool.Body) error) *StorePutStub {
	s.fn = fn
	return s
}

// StoreGetStub controls how the double answers Get and records
// what it was asked.
//
// The embedded MethodStub supplies the machinery every method shares: call
// recording, fault injection, latency against a virtual clock, gates,
// call-count expectations, and strict mode.
type StoreGetStub struct {
	*stub.MethodStub[StoreGetCall]

	fn       func(context.Context, restrictedpool.Key) (restrictedpool.Body, error)
	fallback *StoreGetReturn
}

// StoreGetReturn holds the fixed answer configured through Returns.
type StoreGetReturn struct {
	Result restrictedpool.Body
	Err    error
}

// Returns pins a fixed result for every call to Get. A Func
// override and an injected fault both take precedence over it.
func (s *StoreGetStub) Returns(result restrictedpool.Body, err error) *StoreGetStub {
	s.fallback = &StoreGetReturn{Result: result, Err: err}
	return s
}

// Func supplies a body for Get, for when the answer depends on the
// arguments. An injected fault still takes precedence.
func (s *StoreGetStub) Func(fn func(context.Context, restrictedpool.Key) (restrictedpool.Body, error)) *StoreGetStub {
	s.fn = fn
	return s
}

// --- StoreStub ---

// The double-runtime witness for the surface this double rides. A
// breaking change to the runtime renames it, and this file stops
// compiling with the skew named.
var _ = stub.CompatV1

// StoreStubOption configures a [StoreStub] at construction time.
type StoreStubOption func(*StoreStub)

// StoreStubStrict makes an unconfigured method fail the test rather than
// return its zero value, which turns a call nobody planned for into a failure
// at the call site instead of a puzzling zero further downstream.
func StoreStubStrict() StoreStubOption {
	return func(s *StoreStub) { s.strict = true }
}

// StoreStubDelegateTo wraps a real implementation: every method forwards to
// impl and is recorded on the double on the way through.
//
// This is what lets one generated suite run against both the double and the
// production type, which is the point of conformance testing.
func StoreStubDelegateTo(impl restrictedpool.Store) StoreStubOption {
	return func(s *StoreStub) {
		s.OnPut.Func(impl.Put)
		s.OnGet.Func(impl.Get)
	}
}

// StoreStubWithClock drives latency and time-windowed faults from clk
// rather than from wall time, so a test asserting on a five-second timeout
// does not take five seconds.
func StoreStubWithClock(clk clock.Clock) StoreStubOption {
	return func(s *StoreStub) { s.group.SetClock(clk) }
}

// StoreStubWithRandSource makes probabilistic fault injection reproducible.
// A failure nobody can replay is not a finding.
func StoreStubWithRandSource(src rand.Source) StoreStubOption {
	return func(s *StoreStub) { s.group.SetRandSource(src) }
}

// StoreStubBenchMode disables call recording. Dispatch still works; only
// the accumulating call log is dropped, because its allocations are what a
// benchmark would otherwise be measuring.
func StoreStubBenchMode() StoreStubOption {
	return func(s *StoreStub) { s.group.BenchMode() }
}

// WithStorePut sets Put's body at construction
// time, for the common case of configuring one method and taking the
// defaults for the rest.
func WithStorePut(fn func(context.Context, restrictedpool.Key, restrictedpool.Body) error) StoreStubOption {
	return func(s *StoreStub) { s.OnPut.Func(fn) }
}

// WithStoreGet sets Get's body at construction
// time, for the common case of configuring one method and taking the
// defaults for the rest.
func WithStoreGet(fn func(context.Context, restrictedpool.Key) (restrictedpool.Body, error)) StoreStubOption {
	return func(s *StoreStub) { s.OnGet.Func(fn) }
}

// StoreStub is a recording test double for Store.
//
// Each On<Method> field is that method's configuration point. Left alone, a
// method returns its zero value and records the call.
type StoreStub struct {
	OnPut *StorePutStub
	OnGet *StoreGetStub

	// group is every method stub above, viewed through the surface that
	// does not depend on a signature — one home for the settings and the
	// lifecycle that apply to the whole double.
	group  *stub.Group
	strict bool
}

// Compile-time proof that StoreStub satisfies Store.
//
// It lives here rather than in the companion so a drifted signature fails
// `go build` rather than waiting for a test run — the double is unusable the
// moment it stops satisfying the interface, and that is worth learning at the
// earliest point it can be known.
var _ restrictedpool.Store = (*StoreStub)(nil)

// NewStoreStub returns a double bound to tb.
//
// Passing tb registers a cleanup that verifies every method's call-count
// expectations when the test ends, so an unmet Times is reported without the
// caller remembering to check. A nil tb skips that, which is what benchmarks
// and non-test callers want.
func NewStoreStub(tb testing.TB, opts ...StoreStubOption) *StoreStub {
	s := &StoreStub{
		OnPut: &StorePutStub{MethodStub: stub.NewMethodStub[StorePutCall](tb, "Store.Put")},
		OnGet: &StoreGetStub{MethodStub: stub.NewMethodStub[StoreGetCall](tb, "Store.Get")},
	}
	s.group = stub.NewGroup(
		s.OnPut.MethodStub,
		s.OnGet.MethodStub,
	)
	for _, opt := range opts {
		opt(s)
	}
	if s.strict {
		s.group.StrictAll()
	}
	s.group.Bind(tb)
	return s
}

// ResetCalls clears recorded calls, fault counters, and call-count
// expectations. Func and Returns configuration is deliberately preserved, so
// a test can reuse one double across phases without rebuilding it.
func (s *StoreStub) ResetCalls() {
	s.group.Reset()
}

// --- Interface methods ---

// invoke adapts the Func override to the shape [stub.Answer] consumes, or
// returns nil when no override is set — which is how Answer tells "no
// override" from "an override that returns zero".
func (s *StorePutStub) invoke(ctx context.Context, key restrictedpool.Key, body restrictedpool.Body) func() StorePutReturn {
	if s.fn == nil {
		return nil
	}
	return func() StorePutReturn {
		r0 := s.fn(ctx, key, body)
		return StorePutReturn{Err: r0}
	}
}

// Put records the call and answers it.
//
// Which arm answers — injected fault, Func override, Returns fallback, or the
// zero value — is [stub.Answer]'s to decide, so every generated double
// resolves a call the same way and the ordering is tested once rather than
// restated per method.
func (s *StoreStub) Put(ctx context.Context, key restrictedpool.Key, body restrictedpool.Body) error {
	call := StorePutCall{Ctx: ctx, Key: key, Body: body}
	r := stub.Answer(s.OnPut.MethodStub, &call, stub.Arms[StorePutCall, StorePutReturn]{
		Invoke:   s.OnPut.invoke(ctx, key, body),
		Fallback: s.OnPut.fallback,
		Fault:    func(err error) StorePutReturn { return StorePutReturn{Err: err} },
		Stamp: func(c *StorePutCall, r StorePutReturn) {
			c.Err = r.Err
		},
	})
	return r.Err
}

// invoke adapts the Func override to the shape [stub.Answer] consumes, or
// returns nil when no override is set — which is how Answer tells "no
// override" from "an override that returns zero".
func (s *StoreGetStub) invoke(ctx context.Context, key restrictedpool.Key) func() StoreGetReturn {
	if s.fn == nil {
		return nil
	}
	return func() StoreGetReturn {
		r0, r1 := s.fn(ctx, key)
		return StoreGetReturn{Result: r0, Err: r1}
	}
}

// Get records the call and answers it.
//
// Which arm answers — injected fault, Func override, Returns fallback, or the
// zero value — is [stub.Answer]'s to decide, so every generated double
// resolves a call the same way and the ordering is tested once rather than
// restated per method.
func (s *StoreStub) Get(ctx context.Context, key restrictedpool.Key) (restrictedpool.Body, error) {
	call := StoreGetCall{Ctx: ctx, Key: key}
	r := stub.Answer(s.OnGet.MethodStub, &call, stub.Arms[StoreGetCall, StoreGetReturn]{
		Invoke:   s.OnGet.invoke(ctx, key),
		Fallback: s.OnGet.fallback,
		Fault:    func(err error) StoreGetReturn { return StoreGetReturn{Err: err} },
		Stamp: func(c *StoreGetCall, r StoreGetReturn) {
			c.Result = r.Result
			c.Err = r.Err
		},
	})
	return r.Result, r.Err
}

// testkit: end of generated content.
// testkit:provenance dfc539899360d8f9208ff315c4b42a4f2cf4fd8e27c543bc2ecd4b17294e06ca
