// Code generated by testkit. DO NOT EDIT.
//
// Source:    corpus/iface/contract/lease/iface.go
// Plugins:   golang 1.0.0, stub 1.4.0, backend.golang 1.0.0
// Command:   testkit run ./corpus/...

// Conformance checks worked out from the interfaces this package doubles.
//
// One call runs every check for an interface against one implementation.
// Describe the implementation in a literal and hand it over — each
// interface's own Run function is documented beside it, with the names
// to use.
//
// Nothing else is required to start. The rest is there when you need it:
// a harness field to add only when a check fails asking for it, checks of
// your own that run beside the generated ones, a Prove entry that drives
// each of yours against the broken implementation it names, and a typed
// index for dropping a check by identity rather than by string.
//
// Nothing here is written by hand. Regenerate rather than edit: an edit
// survives until the next run and no longer.
package leasetest

import (
	"context"
	"testing"

	"go.thesmos.sh/testkit/clock"
	"go.thesmos.sh/testkit/conformance/corpus/iface/contract/lease"
	"go.thesmos.sh/testkit/rand"
	"go.thesmos.sh/testkit/stub"
)

// ContractAcquireCall records one invocation of Contract.Acquire.
//
// Fields take their names from the source signature — parameters and named
// returns alike — so a failure message names what the author named. A slot
// the source left unnamed or blank falls back to a positional name.
type ContractAcquireCall struct {
	Ctx context.Context
	Key string
	Err error
}

// ContractReleaseCall records one invocation of Contract.Release.
//
// Fields take their names from the source signature — parameters and named
// returns alike — so a failure message names what the author named. A slot
// the source left unnamed or blank falls back to a positional name.
type ContractReleaseCall struct {
	Ctx context.Context
	Key string
	Err error
}

// --- Per-method configuration ---

// ContractAcquireStub controls how the double answers Acquire and records
// what it was asked.
//
// The embedded MethodStub supplies the machinery every method shares: call
// recording, fault injection, latency against a virtual clock, gates,
// call-count expectations, and strict mode.
type ContractAcquireStub struct {
	*stub.MethodStub[ContractAcquireCall]

	fn       func(context.Context, string) error
	fallback *ContractAcquireReturn
}

// ContractAcquireReturn holds the fixed answer configured through Returns.
type ContractAcquireReturn struct {
	Err error
}

// Returns pins a fixed result for every call to Acquire. A Func
// override and an injected fault both take precedence over it.
func (s *ContractAcquireStub) Returns(err error) *ContractAcquireStub {
	s.fallback = &ContractAcquireReturn{Err: err}
	return s
}

// Func supplies a body for Acquire, for when the answer depends on the
// arguments. An injected fault still takes precedence.
func (s *ContractAcquireStub) Func(fn func(context.Context, string) error) *ContractAcquireStub {
	s.fn = fn
	return s
}

// ContractReleaseStub controls how the double answers Release and records
// what it was asked.
//
// The embedded MethodStub supplies the machinery every method shares: call
// recording, fault injection, latency against a virtual clock, gates,
// call-count expectations, and strict mode.
type ContractReleaseStub struct {
	*stub.MethodStub[ContractReleaseCall]

	fn       func(context.Context, string) error
	fallback *ContractReleaseReturn
}

// ContractReleaseReturn holds the fixed answer configured through Returns.
type ContractReleaseReturn struct {
	Err error
}

// Returns pins a fixed result for every call to Release. A Func
// override and an injected fault both take precedence over it.
func (s *ContractReleaseStub) Returns(err error) *ContractReleaseStub {
	s.fallback = &ContractReleaseReturn{Err: err}
	return s
}

// Func supplies a body for Release, for when the answer depends on the
// arguments. An injected fault still takes precedence.
func (s *ContractReleaseStub) Func(fn func(context.Context, string) error) *ContractReleaseStub {
	s.fn = fn
	return s
}

// --- ContractStub ---

// The double-runtime witness for the surface this double rides. A
// breaking change to the runtime renames it, and this file stops
// compiling with the skew named.
var _ = stub.CompatV1

// ContractStubOption configures a [ContractStub] at construction time.
type ContractStubOption func(*ContractStub)

// ContractStubStrict makes an unconfigured method fail the test rather than
// return its zero value, which turns a call nobody planned for into a failure
// at the call site instead of a puzzling zero further downstream.
func ContractStubStrict() ContractStubOption {
	return func(s *ContractStub) { s.strict = true }
}

// ContractStubDelegateTo wraps a real implementation: every method forwards to
// impl and is recorded on the double on the way through.
//
// This is what lets one generated suite run against both the double and the
// production type, which is the point of conformance testing.
func ContractStubDelegateTo(impl lease.Contract) ContractStubOption {
	return func(s *ContractStub) {
		s.OnAcquire.Func(impl.Acquire)
		s.OnRelease.Func(impl.Release)
	}
}

// ContractStubWithClock drives latency and time-windowed faults from clk
// rather than from wall time, so a test asserting on a five-second timeout
// does not take five seconds.
func ContractStubWithClock(clk clock.Clock) ContractStubOption {
	return func(s *ContractStub) { s.group.SetClock(clk) }
}

// ContractStubWithRandSource makes probabilistic fault injection reproducible.
// A failure nobody can replay is not a finding.
func ContractStubWithRandSource(src rand.Source) ContractStubOption {
	return func(s *ContractStub) { s.group.SetRandSource(src) }
}

// ContractStubBenchMode disables call recording. Dispatch still works; only
// the accumulating call log is dropped, because its allocations are what a
// benchmark would otherwise be measuring.
func ContractStubBenchMode() ContractStubOption {
	return func(s *ContractStub) { s.group.BenchMode() }
}

// WithContractAcquire sets Acquire's body at construction
// time, for the common case of configuring one method and taking the
// defaults for the rest.
func WithContractAcquire(fn func(context.Context, string) error) ContractStubOption {
	return func(s *ContractStub) { s.OnAcquire.Func(fn) }
}

// WithContractRelease sets Release's body at construction
// time, for the common case of configuring one method and taking the
// defaults for the rest.
func WithContractRelease(fn func(context.Context, string) error) ContractStubOption {
	return func(s *ContractStub) { s.OnRelease.Func(fn) }
}

// ContractStub is a recording test double for Contract.
//
// Each On<Method> field is that method's configuration point. Left alone, a
// method returns its zero value and records the call.
type ContractStub struct {
	OnAcquire *ContractAcquireStub
	OnRelease *ContractReleaseStub

	// group is every method stub above, viewed through the surface that
	// does not depend on a signature — one home for the settings and the
	// lifecycle that apply to the whole double.
	group  *stub.Group
	strict bool
}

// Compile-time proof that ContractStub satisfies Contract.
//
// It lives here rather than in the companion so a drifted signature fails
// `go build` rather than waiting for a test run — the double is unusable the
// moment it stops satisfying the interface, and that is worth learning at the
// earliest point it can be known.
var _ lease.Contract = (*ContractStub)(nil)

// NewContractStub returns a double bound to tb.
//
// Passing tb registers a cleanup that verifies every method's call-count
// expectations when the test ends, so an unmet Times is reported without the
// caller remembering to check. A nil tb skips that, which is what benchmarks
// and non-test callers want.
func NewContractStub(tb testing.TB, opts ...ContractStubOption) *ContractStub {
	s := &ContractStub{
		OnAcquire: &ContractAcquireStub{MethodStub: stub.NewMethodStub[ContractAcquireCall](tb, "Contract.Acquire")},
		OnRelease: &ContractReleaseStub{MethodStub: stub.NewMethodStub[ContractReleaseCall](tb, "Contract.Release")},
	}
	s.group = stub.NewGroup(
		s.OnAcquire.MethodStub,
		s.OnRelease.MethodStub,
	)
	for _, opt := range opts {
		opt(s)
	}
	if s.strict {
		s.group.StrictAll()
	}
	s.group.Bind(tb)
	return s
}

// ResetCalls clears recorded calls, fault counters, and call-count
// expectations. Func and Returns configuration is deliberately preserved, so
// a test can reuse one double across phases without rebuilding it.
func (s *ContractStub) ResetCalls() {
	s.group.Reset()
}

// --- Interface methods ---

// invoke adapts the Func override to the shape [stub.Answer] consumes, or
// returns nil when no override is set — which is how Answer tells "no
// override" from "an override that returns zero".
func (s *ContractAcquireStub) invoke(ctx context.Context, key string) func() ContractAcquireReturn {
	if s.fn == nil {
		return nil
	}
	return func() ContractAcquireReturn {
		r0 := s.fn(ctx, key)
		return ContractAcquireReturn{Err: r0}
	}
}

// Acquire records the call and answers it.
//
// Which arm answers — injected fault, Func override, Returns fallback, or the
// zero value — is [stub.Answer]'s to decide, so every generated double
// resolves a call the same way and the ordering is tested once rather than
// restated per method.
func (s *ContractStub) Acquire(ctx context.Context, key string) error {
	call := ContractAcquireCall{Ctx: ctx, Key: key}
	r := stub.Answer(s.OnAcquire.MethodStub, &call, stub.Arms[ContractAcquireCall, ContractAcquireReturn]{
		Invoke:   s.OnAcquire.invoke(ctx, key),
		Fallback: s.OnAcquire.fallback,
		Fault:    func(err error) ContractAcquireReturn { return ContractAcquireReturn{Err: err} },
		Stamp: func(c *ContractAcquireCall, r ContractAcquireReturn) {
			c.Err = r.Err
		},
	})
	return r.Err
}

// invoke adapts the Func override to the shape [stub.Answer] consumes, or
// returns nil when no override is set — which is how Answer tells "no
// override" from "an override that returns zero".
func (s *ContractReleaseStub) invoke(ctx context.Context, key string) func() ContractReleaseReturn {
	if s.fn == nil {
		return nil
	}
	return func() ContractReleaseReturn {
		r0 := s.fn(ctx, key)
		return ContractReleaseReturn{Err: r0}
	}
}

// Release records the call and answers it.
//
// Which arm answers — injected fault, Func override, Returns fallback, or the
// zero value — is [stub.Answer]'s to decide, so every generated double
// resolves a call the same way and the ordering is tested once rather than
// restated per method.
func (s *ContractStub) Release(ctx context.Context, key string) error {
	call := ContractReleaseCall{Ctx: ctx, Key: key}
	r := stub.Answer(s.OnRelease.MethodStub, &call, stub.Arms[ContractReleaseCall, ContractReleaseReturn]{
		Invoke:   s.OnRelease.invoke(ctx, key),
		Fallback: s.OnRelease.fallback,
		Fault:    func(err error) ContractReleaseReturn { return ContractReleaseReturn{Err: err} },
		Stamp: func(c *ContractReleaseCall, r ContractReleaseReturn) {
			c.Err = r.Err
		},
	})
	return r.Err
}

// testkit: end of generated content.
// testkit:provenance cf5f0782f3fd9b794a9daf8d398ce87da191ddbc279841f7f76139f4ce240bd7
