// Code generated by testkit. DO NOT EDIT.
//
// Source:    corpus/iface/mixin/crdtmerge/iface.go
// Plugins:   golang 1.0.0, stub 1.4.0, backend.golang 1.0.0
// Command:   testkit run ./corpus/...

package crdtmergetest_test

import (
	"context"
	"testing"
	"time"

	"go.thesmos.sh/testkit"
	"go.thesmos.sh/testkit/clock"
	"go.thesmos.sh/testkit/conformance/corpus/iface/mixin/crdtmerge"
	"go.thesmos.sh/testkit/conformance/corpus/iface/mixin/crdtmerge/crdtmergetest"
	"go.thesmos.sh/testkit/rand"
	"go.thesmos.sh/testkit/stub"
)

// replicaStubItemsSubject binds Items into the shape
// [stub.Behaviour] drives: how to call it, what it answers with, and how to
// override it.
//
// Each call builds a fresh double, because several of the checks assert on
// failure and need one bound to a failable TB rather than to the running
// test.
func replicaStubItemsSubject(tb testing.TB) stub.Subject[crdtmergetest.ReplicaItemsCall, crdtmergetest.ReplicaItemsReturn] {
	tb.Helper()
	s := crdtmergetest.NewReplicaStub(tb)
	return stub.Subject[crdtmergetest.ReplicaItemsCall, crdtmergetest.ReplicaItemsReturn]{
		Stub: s.OnItems.MethodStub,
		Call: func() {
			var a0 context.Context
			_, _ = s.Items(a0)
		},
		Result: func() crdtmergetest.ReplicaItemsReturn {
			var a0 context.Context
			got0, got1 := s.Items(a0)
			return crdtmergetest.ReplicaItemsReturn{Result: got0, Err: got1}
		},
		Override: func(mark func()) {
			s.OnItems.Func(func(_ context.Context) ([]string, error) {
				mark()
				var z0 []string
				var z1 error
				return z0, z1
			})
		},
		Fails: func() error {
			var a0 context.Context
			_, r1 := s.Items(a0)
			return r1
		},
	}
}

// TestReplicaStubItems pins how Items answers.
//
// Recording, resetting, call-count expectations, strict mode, fault injection
// and zero-value dispatch are the same contract for every method, so they are
// asserted once in [stub.Behaviour] rather than restated here. What remains
// below needs a value this method's signature can tell apart from a zero one.
func TestReplicaStubItems(t *testing.T) {
	t.Parallel()

	stub.Behaviour(t, "Items", replicaStubItemsSubject)

	// No check that Items answers what Returns pinned: no result of
	// its signature admits a literal this generator can write, so the only
	// value available to pin is the zero — which an unconfigured double
	// answers anyway. stub.Behaviour asserts that half honestly.
	t.Run("records what it was called with", func(t *testing.T) {
		t.Parallel()
		// Asserting only that a call happened would pass against a double
		// that recorded the wrong arguments, which is the failure a reader
		// most needs the log to surface.
		s := crdtmergetest.NewReplicaStub(t)
		var a0 context.Context
		_, _ = s.Items(a0)
		got := s.OnItems.AssertCalledOnce(t, "Items must record the call")
		testkit.Equal(t, got.Ctx, a0, "the recorded call carries Ctx")
	})

	t.Run("fires the OnRecord hook for every call", func(t *testing.T) {
		t.Parallel()
		// The hook fires synchronously as each call lands, which is what a
		// concurrency test observes progress with — polling the log instead
		// races the thing under test.
		s := crdtmergetest.NewReplicaStub(t)
		var seen []crdtmergetest.ReplicaItemsCall
		s.OnItems.OnRecord(func(c crdtmergetest.ReplicaItemsCall) { seen = append(seen, c) })
		var a0 context.Context
		_, _ = s.Items(a0)
		_, _ = s.Items(a0)
		testkit.Len(t, seen, 2, "OnRecord must fire once per Items call")
	})

	t.Run("wires WithReplicaItems at construction", func(t *testing.T) {
		t.Parallel()
		called := false
		s := crdtmergetest.NewReplicaStub(t, crdtmergetest.WithReplicaItems(func(_ context.Context) ([]string, error) {
			called = true
			var z0 []string
			var z1 error
			return z0, z1
		}))
		var a0 context.Context
		_, _ = s.Items(a0)
		testkit.True(t, called, "WithReplicaItems must install the override")
	})

	t.Run("keeps recording across a reset", func(t *testing.T) {
		t.Parallel()
		// The weaker claim, and the honest one for this signature. No result
		// of Items admits a literal, so what Returns pinned cannot be
		// told from the zero and comparing them would pass either way.
		//
		// What a reset can still be held to is that it clears the log without
		// taking the double with it: configure, call, reset, call again, and
		// exactly one call is recorded. A reset that dropped the whole
		// configuration fails that, which is the failure the value comparison
		// was reaching for and could not state.
		s := crdtmergetest.NewReplicaStub(t)
		var want0 []string
		var want1 error
		s.OnItems.Returns(want0, want1)
		var a0 context.Context
		_, _ = s.Items(a0)
		s.ResetCalls()
		_, _ = s.Items(a0)
		s.OnItems.AssertCalledOnce(t, "Items must record the call that followed the reset")
	})
}

// replicaStubDouble describes how to build a ReplicaStub under each
// option whose effect is the same whatever a method's signature.
//
// Items stands in for the double as a whole: what these checks assert
// is that an option reached it at all, and the first method witnesses that as
// well as any other would.
func replicaStubDouble() stub.Double[crdtmergetest.ReplicaItemsCall] {
	instance := func(s *crdtmergetest.ReplicaStub) stub.Instance[crdtmergetest.ReplicaItemsCall] {
		return stub.Instance[crdtmergetest.ReplicaItemsCall]{
			Stub: s.OnItems.MethodStub,
			Call: func() {
				var a0 context.Context
				_, _ = s.Items(a0)
			},
			Reset: s.ResetCalls,
		}
	}
	return stub.Double[crdtmergetest.ReplicaItemsCall]{
		New: func(tb testing.TB) stub.Instance[crdtmergetest.ReplicaItemsCall] {
			return instance(crdtmergetest.NewReplicaStub(tb))
		},
		WithClock: func(tb testing.TB, clk clock.Clock) stub.Instance[crdtmergetest.ReplicaItemsCall] {
			return instance(crdtmergetest.NewReplicaStub(tb, crdtmergetest.ReplicaStubWithClock(clk)))
		},
		WithRandSource: func(tb testing.TB, src rand.Source) stub.Instance[crdtmergetest.ReplicaItemsCall] {
			return instance(crdtmergetest.NewReplicaStub(tb, crdtmergetest.ReplicaStubWithRandSource(src)))
		},
		BenchMode: func(tb testing.TB) stub.Instance[crdtmergetest.ReplicaItemsCall] {
			return instance(crdtmergetest.NewReplicaStub(tb, crdtmergetest.ReplicaStubBenchMode()))
		},
		Strict: func(tb testing.TB) stub.Instance[crdtmergetest.ReplicaItemsCall] {
			return instance(crdtmergetest.NewReplicaStub(tb, crdtmergetest.ReplicaStubStrict()))
		},
	}
}

// TestReplicaStubOptions pins the settings that apply to the double rather
// than to one method: bench mode, the injected clock and random source, and
// what a reset clears.
func TestReplicaStubOptions(t *testing.T) {
	t.Parallel()

	stub.DoubleBehaviour(t, replicaStubDouble())
}

// TestReplicaStubDelegateTo pins that a wrapped implementation is called
// through, and recorded on the way past.
//
// This is what lets one generated suite run against both the double and a
// production type, which is the point of conformance testing.
func TestReplicaStubDelegateTo(t *testing.T) {
	t.Parallel()

	inner := crdtmergetest.NewReplicaStub(t)
	s := crdtmergetest.NewReplicaStub(t, crdtmergetest.ReplicaStubDelegateTo(inner))

	t.Run("forwards Items to the wrapped implementation", func(t *testing.T) {
		var a0 context.Context
		_, _ = s.Items(a0)
		inner.OnItems.AssertCalledOnce(t, "Items must reach the wrapped implementation")
	})

	t.Run("surfaces what Items answered", func(t *testing.T) {
		// Reaching the wrapped implementation is not enough: a double that
		// called through and then discarded the answer would pass the check
		// above while telling its caller nothing true.
		want := testkit.TestError("Items-delegate")
		inner.OnItems.FaultsFor(time.Hour, want)
		var a0 context.Context
		_, r1 := s.Items(a0)
		testkit.ErrorIs(t, r1, want, "Items must surface the wrapped answer")
	})
}

// mixedStubMergeSubject binds Merge into the shape
// [stub.Behaviour] drives: how to call it, what it answers with, and how to
// override it.
//
// Each call builds a fresh double, because several of the checks assert on
// failure and need one bound to a failable TB rather than to the running
// test.
func mixedStubMergeSubject(tb testing.TB) stub.Subject[crdtmergetest.MixedMergeCall, crdtmergetest.MixedMergeReturn] {
	tb.Helper()
	s := crdtmergetest.NewMixedStub(tb)
	return stub.Subject[crdtmergetest.MixedMergeCall, crdtmergetest.MixedMergeReturn]{
		Stub: s.OnMerge.MethodStub,
		Call: func() {
			var a0 context.Context
			var a1 crdtmerge.Replica
			_ = s.Merge(a0, a1)
		},
		Result: func() crdtmergetest.MixedMergeReturn {
			var a0 context.Context
			var a1 crdtmerge.Replica
			got0 := s.Merge(a0, a1)
			return crdtmergetest.MixedMergeReturn{Err: got0}
		},
		Override: func(mark func()) {
			s.OnMerge.Func(func(_ context.Context, _ crdtmerge.Replica) error {
				mark()
				var z0 error
				return z0
			})
		},
		Fails: func() error {
			var a0 context.Context
			var a1 crdtmerge.Replica
			r0 := s.Merge(a0, a1)
			return r0
		},
	}
}

// TestMixedStubMerge pins how Merge answers.
//
// Recording, resetting, call-count expectations, strict mode, fault injection
// and zero-value dispatch are the same contract for every method, so they are
// asserted once in [stub.Behaviour] rather than restated here. What remains
// below needs a value this method's signature can tell apart from a zero one.
func TestMixedStubMerge(t *testing.T) {
	t.Parallel()

	stub.Behaviour(t, "Merge", mixedStubMergeSubject)

	// No check that Merge answers what Returns pinned: no result of
	// its signature admits a literal this generator can write, so the only
	// value available to pin is the zero — which an unconfigured double
	// answers anyway. stub.Behaviour asserts that half honestly.
	t.Run("records what it was called with", func(t *testing.T) {
		t.Parallel()
		// Asserting only that a call happened would pass against a double
		// that recorded the wrong arguments, which is the failure a reader
		// most needs the log to surface.
		s := crdtmergetest.NewMixedStub(t)
		var a0 context.Context
		var a1 crdtmerge.Replica
		_ = s.Merge(a0, a1)
		got := s.OnMerge.AssertCalledOnce(t, "Merge must record the call")
		testkit.Equal(t, got.Ctx, a0, "the recorded call carries Ctx")
		testkit.Equal(t, got.Peer, a1, "the recorded call carries Peer")
	})

	t.Run("fires the OnRecord hook for every call", func(t *testing.T) {
		t.Parallel()
		// The hook fires synchronously as each call lands, which is what a
		// concurrency test observes progress with — polling the log instead
		// races the thing under test.
		s := crdtmergetest.NewMixedStub(t)
		var seen []crdtmergetest.MixedMergeCall
		s.OnMerge.OnRecord(func(c crdtmergetest.MixedMergeCall) { seen = append(seen, c) })
		var a0 context.Context
		var a1 crdtmerge.Replica
		_ = s.Merge(a0, a1)
		_ = s.Merge(a0, a1)
		testkit.Len(t, seen, 2, "OnRecord must fire once per Merge call")
	})

	t.Run("wires WithMixedMerge at construction", func(t *testing.T) {
		t.Parallel()
		called := false
		s := crdtmergetest.NewMixedStub(t, crdtmergetest.WithMixedMerge(func(_ context.Context, _ crdtmerge.Replica) error {
			called = true
			var z0 error
			return z0
		}))
		var a0 context.Context
		var a1 crdtmerge.Replica
		_ = s.Merge(a0, a1)
		testkit.True(t, called, "WithMixedMerge must install the override")
	})

	t.Run("keeps recording across a reset", func(t *testing.T) {
		t.Parallel()
		// The weaker claim, and the honest one for this signature. No result
		// of Merge admits a literal, so what Returns pinned cannot be
		// told from the zero and comparing them would pass either way.
		//
		// What a reset can still be held to is that it clears the log without
		// taking the double with it: configure, call, reset, call again, and
		// exactly one call is recorded. A reset that dropped the whole
		// configuration fails that, which is the failure the value comparison
		// was reaching for and could not state.
		s := crdtmergetest.NewMixedStub(t)
		var want0 error
		s.OnMerge.Returns(want0)
		var a0 context.Context
		var a1 crdtmerge.Replica
		_ = s.Merge(a0, a1)
		s.ResetCalls()
		_ = s.Merge(a0, a1)
		s.OnMerge.AssertCalledOnce(t, "Merge must record the call that followed the reset")
	})
}

// mixedStubAddSubject binds Add into the shape
// [stub.Behaviour] drives: how to call it, what it answers with, and how to
// override it.
//
// Each call builds a fresh double, because several of the checks assert on
// failure and need one bound to a failable TB rather than to the running
// test.
func mixedStubAddSubject(tb testing.TB) stub.Subject[crdtmergetest.MixedAddCall, crdtmergetest.MixedAddReturn] {
	tb.Helper()
	s := crdtmergetest.NewMixedStub(tb)
	return stub.Subject[crdtmergetest.MixedAddCall, crdtmergetest.MixedAddReturn]{
		Stub: s.OnAdd.MethodStub,
		Call: func() {
			var a0 context.Context
			var a1 string = "test-item"
			_ = s.Add(a0, a1)
		},
		Result: func() crdtmergetest.MixedAddReturn {
			var a0 context.Context
			var a1 string = "test-item"
			got0 := s.Add(a0, a1)
			return crdtmergetest.MixedAddReturn{Err: got0}
		},
		Override: func(mark func()) {
			s.OnAdd.Func(func(_ context.Context, _ string) error {
				mark()
				var z0 error
				return z0
			})
		},
		Fails: func() error {
			var a0 context.Context
			var a1 string = "test-item"
			r0 := s.Add(a0, a1)
			return r0
		},
	}
}

// TestMixedStubAdd pins how Add answers.
//
// Recording, resetting, call-count expectations, strict mode, fault injection
// and zero-value dispatch are the same contract for every method, so they are
// asserted once in [stub.Behaviour] rather than restated here. What remains
// below needs a value this method's signature can tell apart from a zero one.
func TestMixedStubAdd(t *testing.T) {
	t.Parallel()

	stub.Behaviour(t, "Add", mixedStubAddSubject)

	// No check that Add answers what Returns pinned: no result of
	// its signature admits a literal this generator can write, so the only
	// value available to pin is the zero — which an unconfigured double
	// answers anyway. stub.Behaviour asserts that half honestly.
	t.Run("records what it was called with", func(t *testing.T) {
		t.Parallel()
		// Asserting only that a call happened would pass against a double
		// that recorded the wrong arguments, which is the failure a reader
		// most needs the log to surface.
		s := crdtmergetest.NewMixedStub(t)
		var a0 context.Context
		var a1 string = "test-item"
		_ = s.Add(a0, a1)
		got := s.OnAdd.AssertCalledOnce(t, "Add must record the call")
		testkit.Equal(t, got.Ctx, a0, "the recorded call carries Ctx")
		testkit.Equal(t, got.Item, a1, "the recorded call carries Item")
	})

	t.Run("fires the OnRecord hook for every call", func(t *testing.T) {
		t.Parallel()
		// The hook fires synchronously as each call lands, which is what a
		// concurrency test observes progress with — polling the log instead
		// races the thing under test.
		s := crdtmergetest.NewMixedStub(t)
		var seen []crdtmergetest.MixedAddCall
		s.OnAdd.OnRecord(func(c crdtmergetest.MixedAddCall) { seen = append(seen, c) })
		var a0 context.Context
		var a1 string = "test-item"
		_ = s.Add(a0, a1)
		_ = s.Add(a0, a1)
		testkit.Len(t, seen, 2, "OnRecord must fire once per Add call")
	})

	t.Run("wires WithMixedAdd at construction", func(t *testing.T) {
		t.Parallel()
		called := false
		s := crdtmergetest.NewMixedStub(t, crdtmergetest.WithMixedAdd(func(_ context.Context, _ string) error {
			called = true
			var z0 error
			return z0
		}))
		var a0 context.Context
		var a1 string = "test-item"
		_ = s.Add(a0, a1)
		testkit.True(t, called, "WithMixedAdd must install the override")
	})

	t.Run("keeps recording across a reset", func(t *testing.T) {
		t.Parallel()
		// The weaker claim, and the honest one for this signature. No result
		// of Add admits a literal, so what Returns pinned cannot be
		// told from the zero and comparing them would pass either way.
		//
		// What a reset can still be held to is that it clears the log without
		// taking the double with it: configure, call, reset, call again, and
		// exactly one call is recorded. A reset that dropped the whole
		// configuration fails that, which is the failure the value comparison
		// was reaching for and could not state.
		s := crdtmergetest.NewMixedStub(t)
		var want0 error
		s.OnAdd.Returns(want0)
		var a0 context.Context
		var a1 string = "test-item"
		_ = s.Add(a0, a1)
		s.ResetCalls()
		_ = s.Add(a0, a1)
		s.OnAdd.AssertCalledOnce(t, "Add must record the call that followed the reset")
	})
}

// mixedStubItemsSubject binds Items into the shape
// [stub.Behaviour] drives: how to call it, what it answers with, and how to
// override it.
//
// Each call builds a fresh double, because several of the checks assert on
// failure and need one bound to a failable TB rather than to the running
// test.
func mixedStubItemsSubject(tb testing.TB) stub.Subject[crdtmergetest.MixedItemsCall, crdtmergetest.MixedItemsReturn] {
	tb.Helper()
	s := crdtmergetest.NewMixedStub(tb)
	return stub.Subject[crdtmergetest.MixedItemsCall, crdtmergetest.MixedItemsReturn]{
		Stub: s.OnItems.MethodStub,
		Call: func() {
			var a0 context.Context
			_, _ = s.Items(a0)
		},
		Result: func() crdtmergetest.MixedItemsReturn {
			var a0 context.Context
			got0, got1 := s.Items(a0)
			return crdtmergetest.MixedItemsReturn{Result: got0, Err: got1}
		},
		Override: func(mark func()) {
			s.OnItems.Func(func(_ context.Context) ([]string, error) {
				mark()
				var z0 []string
				var z1 error
				return z0, z1
			})
		},
		Fails: func() error {
			var a0 context.Context
			_, r1 := s.Items(a0)
			return r1
		},
	}
}

// TestMixedStubItems pins how Items answers.
//
// Recording, resetting, call-count expectations, strict mode, fault injection
// and zero-value dispatch are the same contract for every method, so they are
// asserted once in [stub.Behaviour] rather than restated here. What remains
// below needs a value this method's signature can tell apart from a zero one.
func TestMixedStubItems(t *testing.T) {
	t.Parallel()

	stub.Behaviour(t, "Items", mixedStubItemsSubject)

	// No check that Items answers what Returns pinned: no result of
	// its signature admits a literal this generator can write, so the only
	// value available to pin is the zero — which an unconfigured double
	// answers anyway. stub.Behaviour asserts that half honestly.
	t.Run("records what it was called with", func(t *testing.T) {
		t.Parallel()
		// Asserting only that a call happened would pass against a double
		// that recorded the wrong arguments, which is the failure a reader
		// most needs the log to surface.
		s := crdtmergetest.NewMixedStub(t)
		var a0 context.Context
		_, _ = s.Items(a0)
		got := s.OnItems.AssertCalledOnce(t, "Items must record the call")
		testkit.Equal(t, got.Ctx, a0, "the recorded call carries Ctx")
	})

	t.Run("fires the OnRecord hook for every call", func(t *testing.T) {
		t.Parallel()
		// The hook fires synchronously as each call lands, which is what a
		// concurrency test observes progress with — polling the log instead
		// races the thing under test.
		s := crdtmergetest.NewMixedStub(t)
		var seen []crdtmergetest.MixedItemsCall
		s.OnItems.OnRecord(func(c crdtmergetest.MixedItemsCall) { seen = append(seen, c) })
		var a0 context.Context
		_, _ = s.Items(a0)
		_, _ = s.Items(a0)
		testkit.Len(t, seen, 2, "OnRecord must fire once per Items call")
	})

	t.Run("wires WithMixedItems at construction", func(t *testing.T) {
		t.Parallel()
		called := false
		s := crdtmergetest.NewMixedStub(t, crdtmergetest.WithMixedItems(func(_ context.Context) ([]string, error) {
			called = true
			var z0 []string
			var z1 error
			return z0, z1
		}))
		var a0 context.Context
		_, _ = s.Items(a0)
		testkit.True(t, called, "WithMixedItems must install the override")
	})

	t.Run("keeps recording across a reset", func(t *testing.T) {
		t.Parallel()
		// The weaker claim, and the honest one for this signature. No result
		// of Items admits a literal, so what Returns pinned cannot be
		// told from the zero and comparing them would pass either way.
		//
		// What a reset can still be held to is that it clears the log without
		// taking the double with it: configure, call, reset, call again, and
		// exactly one call is recorded. A reset that dropped the whole
		// configuration fails that, which is the failure the value comparison
		// was reaching for and could not state.
		s := crdtmergetest.NewMixedStub(t)
		var want0 []string
		var want1 error
		s.OnItems.Returns(want0, want1)
		var a0 context.Context
		_, _ = s.Items(a0)
		s.ResetCalls()
		_, _ = s.Items(a0)
		s.OnItems.AssertCalledOnce(t, "Items must record the call that followed the reset")
	})
}

// mixedStubDouble describes how to build a MixedStub under each
// option whose effect is the same whatever a method's signature.
//
// Merge stands in for the double as a whole: what these checks assert
// is that an option reached it at all, and the first method witnesses that as
// well as any other would.
func mixedStubDouble() stub.Double[crdtmergetest.MixedMergeCall] {
	instance := func(s *crdtmergetest.MixedStub) stub.Instance[crdtmergetest.MixedMergeCall] {
		return stub.Instance[crdtmergetest.MixedMergeCall]{
			Stub: s.OnMerge.MethodStub,
			Call: func() {
				var a0 context.Context
				var a1 crdtmerge.Replica
				_ = s.Merge(a0, a1)
			},
			Reset: s.ResetCalls,
		}
	}
	return stub.Double[crdtmergetest.MixedMergeCall]{
		New: func(tb testing.TB) stub.Instance[crdtmergetest.MixedMergeCall] {
			return instance(crdtmergetest.NewMixedStub(tb))
		},
		WithClock: func(tb testing.TB, clk clock.Clock) stub.Instance[crdtmergetest.MixedMergeCall] {
			return instance(crdtmergetest.NewMixedStub(tb, crdtmergetest.MixedStubWithClock(clk)))
		},
		WithRandSource: func(tb testing.TB, src rand.Source) stub.Instance[crdtmergetest.MixedMergeCall] {
			return instance(crdtmergetest.NewMixedStub(tb, crdtmergetest.MixedStubWithRandSource(src)))
		},
		BenchMode: func(tb testing.TB) stub.Instance[crdtmergetest.MixedMergeCall] {
			return instance(crdtmergetest.NewMixedStub(tb, crdtmergetest.MixedStubBenchMode()))
		},
		Strict: func(tb testing.TB) stub.Instance[crdtmergetest.MixedMergeCall] {
			return instance(crdtmergetest.NewMixedStub(tb, crdtmergetest.MixedStubStrict()))
		},
	}
}

// TestMixedStubOptions pins the settings that apply to the double rather
// than to one method: bench mode, the injected clock and random source, and
// what a reset clears.
func TestMixedStubOptions(t *testing.T) {
	t.Parallel()

	stub.DoubleBehaviour(t, mixedStubDouble())
}

// TestMixedStubDelegateTo pins that a wrapped implementation is called
// through, and recorded on the way past.
//
// This is what lets one generated suite run against both the double and a
// production type, which is the point of conformance testing.
func TestMixedStubDelegateTo(t *testing.T) {
	t.Parallel()

	inner := crdtmergetest.NewMixedStub(t)
	s := crdtmergetest.NewMixedStub(t, crdtmergetest.MixedStubDelegateTo(inner))

	t.Run("forwards Merge to the wrapped implementation", func(t *testing.T) {
		var a0 context.Context
		var a1 crdtmerge.Replica
		_ = s.Merge(a0, a1)
		inner.OnMerge.AssertCalledOnce(t, "Merge must reach the wrapped implementation")
	})

	t.Run("surfaces what Merge answered", func(t *testing.T) {
		// Reaching the wrapped implementation is not enough: a double that
		// called through and then discarded the answer would pass the check
		// above while telling its caller nothing true.
		want := testkit.TestError("Merge-delegate")
		inner.OnMerge.FaultsFor(time.Hour, want)
		var a0 context.Context
		var a1 crdtmerge.Replica
		r0 := s.Merge(a0, a1)
		testkit.ErrorIs(t, r0, want, "Merge must surface the wrapped answer")
	})

	t.Run("forwards Add to the wrapped implementation", func(t *testing.T) {
		var a0 context.Context
		var a1 string = "test-item"
		_ = s.Add(a0, a1)
		inner.OnAdd.AssertCalledOnce(t, "Add must reach the wrapped implementation")
	})

	t.Run("surfaces what Add answered", func(t *testing.T) {
		// Reaching the wrapped implementation is not enough: a double that
		// called through and then discarded the answer would pass the check
		// above while telling its caller nothing true.
		want := testkit.TestError("Add-delegate")
		inner.OnAdd.FaultsFor(time.Hour, want)
		var a0 context.Context
		var a1 string = "test-item"
		r0 := s.Add(a0, a1)
		testkit.ErrorIs(t, r0, want, "Add must surface the wrapped answer")
	})

	t.Run("forwards Items to the wrapped implementation", func(t *testing.T) {
		var a0 context.Context
		_, _ = s.Items(a0)
		inner.OnItems.AssertCalledOnce(t, "Items must reach the wrapped implementation")
	})

	t.Run("surfaces what Items answered", func(t *testing.T) {
		// Reaching the wrapped implementation is not enough: a double that
		// called through and then discarded the answer would pass the check
		// above while telling its caller nothing true.
		want := testkit.TestError("Items-delegate")
		inner.OnItems.FaultsFor(time.Hour, want)
		var a0 context.Context
		_, r1 := s.Items(a0)
		testkit.ErrorIs(t, r1, want, "Items must surface the wrapped answer")
	})
}

// testkit: end of generated content.
// testkit:provenance 0cde025054d34e0b6533828b1badfc1ab39fde1cf5b5dfa102022825744d7e53
