// Code generated by testkit. DO NOT EDIT.
//
// Source:    corpus/iface/composite/batched-mixins/iface.go
// Plugins:   golang 1.0.0, suite 1.24.0, backend.golang 1.0.0
// Command:   testkit run ./corpus/...

package batchedmixinstest

import (
	"context"
	"fmt"
	"testing"

	batchedmixins "go.thesmos.sh/testkit/conformance/corpus/iface/composite/batched-mixins"
	"go.thesmos.sh/testkit/core/lawid"
	"go.thesmos.sh/testkit/engine/legs"
	"go.thesmos.sh/testkit/engine/model"
	"go.thesmos.sh/testkit/engine/model/action"
	"go.thesmos.sh/testkit/engine/model/law"
	"go.thesmos.sh/testkit/engine/suite"
	"go.thesmos.sh/testkit/engine/suite/prove"
)

// Conformance checks for Batched, worked out from its declaration.
//
// One call runs all of them against one implementation. Describe the
// implementation in a literal and hand it over:
//
//	func TestMine(t *testing.T) {
//		RunBatched(t, BatchedHarness[*Mine]{Name: "mine", New: NewMine})
//	}
//
// Nothing else is required to start. The rest is here when you need it:
//
//	BatchedHarness
//	    one implementation under test. Add a field only when a check
//	    fails asking for it — the failure names the field to fill in.
//	BatchedChecks
//	    checks you write yourself, for the claims only you can make.
//	    They run beside the generated ones and are the same kind of value.
//	ProveBatched
//	    runs each of your checks against the broken implementation it
//	    names, and fails if the check does not catch it.
//	BatchedSuite.Checks.<Method>.<Check>()
//	    names one check, so you can drop it. Written this way it stops
//	    compiling if a later regeneration no longer emits that check,
//	    rather than silently dropping nothing.
//
// The checks this file runs:
//
//	List/cancel
//	List/deadline
//	List/nilcontext
//	List/smoke
//	List/zero-on-error
//	Put/cancel
//	Put/deadline
//	Put/idempotent
//	Put/nilcontext
//	Put/smoke
//	Read/cancel
//	Read/deadline
//	Read/miss
//	Read/nilcontext
//	Read/smoke
//	Read/zero-on-error
//
// Declared on this interface and checked by testkit's model tier rather
// than by this file, which judges one call at a time. Nothing for you to
// do — listed so that a directive you wrote is accounted for:
//
//	bounded on List — stating it needs sequences of calls judged against a reference, which this file does not build.
//	cacheable on List — stating it needs sequences of calls judged against a reference, which this file does not build.
//	idempotent on Put, for call sequences this file does not write — the check above runs one fixed sequence, and your directive claims the same of every other.
//	pure on List — stating it needs sequences of calls judged against a reference, which this file does not build.
//	readafterwrite on Read — stating it needs sequences of calls judged against a reference, which this file does not build.
//
// Claims this file does NOT make. Each was worked out from your
// declaration and then declined, because something needed to state it
// is missing. The reason and the fix are given for each: the list above
// tells you what you have, and this tells you what you do not.
//
//	Put's side-effect check — the mixin names no partner to observe the effect through. To close it: name a readable partner with //testkit:mixin sideeffect observe=…, on a line of its own — a directive naming several mixins takes no parameters, because the owner of one would be a guess.
//
// A version check, performed by the compiler. If this file was generated
// against a testkit whose check format differs from the one you are
// building with, this line fails to compile and names the mismatch —
// instead of the two disagreeing quietly while the tests still pass.
// Regenerate the file to clear it.
var _ = suite.CompatV2

// BatchedFixture holds the sample inputs the checks call your
// implementation with, worked out from each method's parameter types.
//
// Every input comes as a pair: a value, and a second one guaranteed to
// differ from it. Both are needed for a check to mean anything — looking
// up a key that was just stored proves nothing on its own unless there
// is also a key that was never stored.
//
// A parameter whose type has no value that can be written down — a func,
// a channel, a type your declaration does not import — is left at its
// zero value, and the checks that needed it were not emitted at all
// rather than run against something meaningless. Those are listed above.
// A check you write yourself is handed this either way.
type BatchedFixture struct {
	key        string
	keyOther   string
	value      string
	valueOther string
}

// DefaultBatchedFixture is what a run with no config draws.
func DefaultBatchedFixture() BatchedFixture {
	return batchedNewFixture()
}

// batchedNewFixture builds the sample inputs for one run.
//
// Read these through the methods below rather than as fields. A value you
// supplied through the config and one worked out from the type are read
// the same way, and no check should be able to tell them apart.
func batchedNewFixture() BatchedFixture {
	return BatchedFixture{
		key:        "test-key",
		keyOther:   "other-key",
		value:      "test-value",
		valueOther: "other-value",
	}
}

// Key is the key the checks call your implementation with.
func (f BatchedFixture) Key() string { return f.key }

// KeyOther is a second key, guaranteed to differ from the
// first — so a check that expects to find nothing is asking about
// something your implementation has genuinely never been given.
func (f BatchedFixture) KeyOther() string { return f.keyOther }

// Value is the value the checks call your implementation with.
func (f BatchedFixture) Value() string { return f.value }

// ValueOther is a second value, guaranteed to differ from the
// first — so a check that expects to find nothing is asking about
// something your implementation has genuinely never been given.
func (f BatchedFixture) ValueOther() string { return f.valueOther }

// Batched is your interface, under a local name.
//
// An alias, so it is the same type — this is here only so the rest of
// this file can refer to it without repeating its import path, and so a
// check you write can name it too.
type Batched = batchedmixins.Batched

// batchedCapacity is the capacity your declaration gave as
// limit=50, and the capacity your constructor is called with.
//
// It is passed in rather than left for you to repeat, because an
// implementation built at some other capacity would be measured against a
// limit it was never given — and that check would pass without meaning
// anything.
const batchedCapacity = 50

// BatchedSubject is what a RunWith check receives instead of a single
// instance: a handle that can build more of them.
//
// Use it for a claim one instance cannot state on its own — that two
// instances do not share state, that a value survives being closed and
// reopened.
type BatchedSubject = suite.Subject[Batched]

// BatchedRunOpt is anything you can pass to RunBatched: an
// implementation to test, a table of your own checks, a config, or a
// check to drop. Order does not matter.
type BatchedRunOpt interface {
	applyTo(*batchedRunConfig)
}

type batchedRunConfig struct {
	suite.Bundle[Batched]

	// rows are the checks you wrote, held until every argument has been
	// read and then tied to this run's inputs. Tying them on arrival
	// would bind them to inputs a later argument replaces.
	rows BatchedChecks
}

// BatchedHarness describes one Batched implementation to test.
//
// Name and one constructor are all that is required. Every other field
// unlocks the checks that need it, and you do not have to work out which
// in advance: run it, and any check that needs more fails saying which
// field to add.
type BatchedHarness[T Batched] struct {
	Name string

	// Set exactly one. Both are called with the declared capacity.
	//
	// Use New if construction cannot fail; use Start if it needs the
	// test's lifetime — a temp directory to clean up, a connection to
	// close. Start is handed the testing.TB to register that on.
	New   func(capacity int) T
	Start func(tb testing.TB, capacity int) T

	// Excuse lists checks this implementation cannot meaningfully take —
	// not ones it fails, ones it has no way to answer. An in-memory
	// implementation has no storage to survive a restart, so a check
	// about restarting it is asking the impossible.
	//
	// Excused checks are reported as excused, never as passed.
	Excuse []suite.ID

	// Oracle marks this implementation as the one others are compared
	// against, when you are testing more than one. At most one may set it.
	// Pick the implementation you trust most.
	Oracle bool

	// Serial runs this implementation's checks one at a time, and never
	// alongside another implementation's. Set it for something that
	// cannot take being constructed many times at once — a real database,
	// a fixed port.
	Serial bool

	// Provide supplies anything a check needs that has no field of its
	// own above. You will not need it unless a check fails asking for a
	// named capability, and that failure tells you the name to use here.
	Provide map[suite.Capability]any
}

// Subject converts this description into the form the runner uses, and
// reports anything wrong with it — no constructor, or two.
func (h BatchedHarness[T]) Subject() (suite.Subject[Batched], error) {
	// The capacity is bound in before the constructors are checked, so
	// your constructor and the checks agree about what it is.
	var plain func() T
	if h.New != nil {
		plain = func() T { return h.New(batchedCapacity) }
	}
	var start func(tb testing.TB) T
	if h.Start != nil {
		start = func(tb testing.TB) T { return h.Start(tb, batchedCapacity) }
	}
	build, err := suite.OneCtor(h.Name, plain, start)
	if err != nil {
		return suite.Subject[Batched]{}, err
	}
	return suite.Subject[Batched]{
		Name:     h.Name,
		Provides: h.Provide,
		New:      func(tb testing.TB) Batched { return build(tb) },
		Oracle:   h.Oracle,
		Serial:   h.Serial,
		Excused:  suite.ExcuseSet(h.Excuse),
	}, nil
}

func (h BatchedHarness[T]) applyTo(rc *batchedRunConfig) {
	rc.AddSubject(h.Subject())
}

type batchedDropOpt []suite.ID

func (d batchedDropOpt) applyTo(rc *batchedRunConfig) {
	rc.AddDrops(d...)
}

// batchedWithout drops the named checks from the run.
func batchedWithout(ids ...suite.ID) BatchedRunOpt {
	return batchedDropOpt(ids)
}

// --- Naming checks ----------------------------------------------------------

// BatchedSuite is how you name a check — to drop it, or to
// point at it from a tool.
var BatchedSuite = batchedVeneer{Checks: batchedCheckIndex}

type batchedVeneer struct {
	// Checks names every check this file runs, by method:
	//
	//	BatchedSuite.Checks.<Method>.<Check>()
	//
	// Prefer this over writing the check's name as a string. If a later
	// regeneration stops emitting that check, this stops compiling —
	// where the string would silently drop nothing.
	Checks batchedCheckIndexT
}

// Without drops the named checks from the run.
//
//	RunBatched(t, mine, BatchedSuite.Without(
//		BatchedSuite.Checks.Put.Smoke()))
//
// Dropping is recorded in the run's report, so a check you removed is
// visible rather than simply absent.
func (batchedVeneer) Without(ids ...suite.ID) BatchedRunOpt {
	return batchedWithout(ids...)
}

// Suite returns the checks as plain data, if you are building a tool over
// them or running them yourself.
//
// RunBatched is the normal way in; this is for when you need the
// checks as values rather than as a run.
func (batchedVeneer) Suite(fx BatchedFixture) suite.Suite[Batched] {
	return batchedSuite(fx)
}

// --- Failure messages -------------------------------------------------------

// batchedIndexPath maps each check to the expression you would
// write to drop it, so that a check which cannot run tells you what to
// type rather than only what went wrong.
var batchedIndexPath = map[suite.ID]string{
	batchedCheckIndex.Put.Smoke():             "BatchedSuite.Checks.Put.Smoke()",
	batchedCheckIndex.Put.Cancels():           "BatchedSuite.Checks.Put.Cancels()",
	batchedCheckIndex.Put.NilContext():        "BatchedSuite.Checks.Put.NilContext()",
	batchedCheckIndex.Put.Deadline():          "BatchedSuite.Checks.Put.Deadline()",
	batchedCheckIndex.Put.Idempotent():        "BatchedSuite.Checks.Put.Idempotent()",
	batchedCheckIndex.Read.Smoke():            "BatchedSuite.Checks.Read.Smoke()",
	batchedCheckIndex.Read.Cancels():          "BatchedSuite.Checks.Read.Cancels()",
	batchedCheckIndex.Read.NilContext():       "BatchedSuite.Checks.Read.NilContext()",
	batchedCheckIndex.Read.Deadline():         "BatchedSuite.Checks.Read.Deadline()",
	batchedCheckIndex.Read.ZeroOnError():      "BatchedSuite.Checks.Read.ZeroOnError()",
	batchedCheckIndex.Read.Miss():             "BatchedSuite.Checks.Read.Miss()",
	batchedCheckIndex.List.Smoke():            "BatchedSuite.Checks.List.Smoke()",
	batchedCheckIndex.List.Cancels():          "BatchedSuite.Checks.List.Cancels()",
	batchedCheckIndex.List.NilContext():       "BatchedSuite.Checks.List.NilContext()",
	batchedCheckIndex.List.Deadline():         "BatchedSuite.Checks.List.Deadline()",
	batchedCheckIndex.List.ZeroOnError():      "BatchedSuite.Checks.List.ZeroOnError()",
	batchedCheckIndex.Model.IdempotentWrite(): "BatchedSuite.Checks.Model.IdempotentWrite()",
	batchedCheckIndex.Model.ReadsAgree():      "BatchedSuite.Checks.Model.ReadsAgree()",
	batchedCheckIndex.Model.Counts():          "BatchedSuite.Checks.Model.Counts()",
	batchedCheckIndex.Model.Bounded():         "BatchedSuite.Checks.Model.Bounded()",
}

var batchedDropHint = suite.DropHinter(
	"BatchedSuite", batchedIndexPath,
)

// The names this file uses in more than one place, declared once each so
// they cannot drift apart.
const (
	batchedPut  = "Put"
	batchedRead = "Read"
	batchedList = "List"

	// The interface's word inside a family-scoped identity.
	batchedQualifier = "batched"
)

// batchedCheckIndex names every check in this file, grouped by method.
// Reach it through BatchedSuite.Checks.
var batchedCheckIndex = batchedCheckIndexT{
	Put:   batchedPutChecks{},
	Read:  batchedReadChecks{},
	List:  batchedListChecks{},
	Model: batchedModelChecks{},
}

type batchedCheckIndexT struct {
	Put   batchedPutChecks
	Read  batchedReadChecks
	List  batchedListChecks
	Model batchedModelChecks
}

// All returns every ID this package emits.
func (batchedCheckIndexT) All() []suite.ID {
	var out []suite.ID
	out = append(out, batchedPutChecks{}.All()...)
	out = append(out, batchedReadChecks{}.All()...)
	out = append(out, batchedListChecks{}.All()...)
	out = append(out, batchedModelChecks{}.All()...)
	return out
}

type batchedPutChecks struct{}

func (batchedPutChecks) Smoke() suite.ID {
	return suite.MethodID(batchedPut, suite.SegSmoke)
}

func (batchedPutChecks) Cancels() suite.ID {
	return suite.MethodID(batchedPut, suite.SegCancel)
}

func (batchedPutChecks) NilContext() suite.ID {
	return suite.MethodID(batchedPut, suite.SegNilContext)
}

func (batchedPutChecks) Deadline() suite.ID {
	return suite.MethodID(batchedPut, suite.SegDeadline)
}

func (batchedPutChecks) Idempotent() suite.ID {
	return suite.MethodID(batchedPut, suite.SegIdempotent)
}

func (batchedPutChecks) All() []suite.ID {
	return []suite.ID{
		batchedPutChecks{}.Smoke(),
		batchedPutChecks{}.Cancels(),
		batchedPutChecks{}.NilContext(),
		batchedPutChecks{}.Deadline(),
		batchedPutChecks{}.Idempotent(),
	}
}

type batchedReadChecks struct{}

func (batchedReadChecks) Smoke() suite.ID {
	return suite.MethodID(batchedRead, suite.SegSmoke)
}

func (batchedReadChecks) Cancels() suite.ID {
	return suite.MethodID(batchedRead, suite.SegCancel)
}

func (batchedReadChecks) NilContext() suite.ID {
	return suite.MethodID(batchedRead, suite.SegNilContext)
}

func (batchedReadChecks) Deadline() suite.ID {
	return suite.MethodID(batchedRead, suite.SegDeadline)
}

func (batchedReadChecks) ZeroOnError() suite.ID {
	return suite.MethodID(batchedRead, suite.SegZeroValue)
}

func (batchedReadChecks) Miss() suite.ID {
	return suite.MethodID(batchedRead, suite.SegMiss)
}

func (batchedReadChecks) All() []suite.ID {
	return []suite.ID{
		batchedReadChecks{}.Smoke(),
		batchedReadChecks{}.Cancels(),
		batchedReadChecks{}.NilContext(),
		batchedReadChecks{}.Deadline(),
		batchedReadChecks{}.ZeroOnError(),
		batchedReadChecks{}.Miss(),
	}
}

type batchedListChecks struct{}

func (batchedListChecks) Smoke() suite.ID {
	return suite.MethodID(batchedList, suite.SegSmoke)
}

func (batchedListChecks) Cancels() suite.ID {
	return suite.MethodID(batchedList, suite.SegCancel)
}

func (batchedListChecks) NilContext() suite.ID {
	return suite.MethodID(batchedList, suite.SegNilContext)
}

func (batchedListChecks) Deadline() suite.ID {
	return suite.MethodID(batchedList, suite.SegDeadline)
}

func (batchedListChecks) ZeroOnError() suite.ID {
	return suite.MethodID(batchedList, suite.SegZeroValue)
}

func (batchedListChecks) All() []suite.ID {
	return []suite.ID{
		batchedListChecks{}.Smoke(),
		batchedListChecks{}.Cancels(),
		batchedListChecks{}.NilContext(),
		batchedListChecks{}.Deadline(),
		batchedListChecks{}.ZeroOnError(),
	}
}

type batchedModelChecks struct{}

func (batchedModelChecks) IdempotentWrite() suite.ID {
	return suite.FamilyID(suite.FamilyModel, batchedQualifier, lawid.IdempotentWrite)
}

func (batchedModelChecks) ReadsAgree() suite.ID {
	return suite.FamilyID(suite.FamilyModel, batchedQualifier, lawid.ReadAfterWrite)
}

func (batchedModelChecks) Counts() suite.ID {
	return suite.FamilyID(suite.FamilyModel, batchedQualifier, lawid.CountEqualsReference)
}

func (batchedModelChecks) Bounded() suite.ID {
	return suite.FamilyID(suite.FamilyModel, batchedQualifier, lawid.AggregatorBounded)
}

func (batchedModelChecks) All() []suite.ID {
	return []suite.ID{
		batchedModelChecks{}.IdempotentWrite(),
		batchedModelChecks{}.ReadsAgree(),
		batchedModelChecks{}.Counts(),
		batchedModelChecks{}.Bounded(),
	}
}

// batchedSuite returns the checks as data, using the given inputs.
//
// It takes the built inputs rather than a config, because that is what
// the checks read. To start from the defaults, pass what a default run
// passes — BatchedSuite.Suite does exactly that.
func batchedSuite(fx BatchedFixture) suite.Suite[Batched] {
	return suite.Suite[Batched]{
		Name:     "Batched",
		DropHint: batchedDropHint,
		Checks: append(batchedSignatureChecks(fx),
			batchedModelRows(fx)...),
	}
}

// batchedSignatureChecks builds every check in this file.
//
// A check is marked as proven able to fail only when a deliberately
// broken implementation for it exists in the file beside this one.
// Where none could be built, the check says so instead — claiming proof
// without the evidence is refused, in both directions.
func batchedSignatureChecks(fx BatchedFixture) []suite.Check[Batched] {
	sig := suite.ProvenCheck[Batched]
	ix := batchedCheckIndex
	return []suite.Check[Batched]{
		sig(ix.Put.Smoke(), suite.ClassSmoke,
			"Put survives a call with derived inputs",
			func(tb testing.TB, b Batched) {
				batchedAssertPutSmoke(tb, b, fx)
			}).At(suite.StrengthErrorOnly),
		sig(ix.Put.Cancels(), suite.ClassCancel,
			"Put reports a cancelled context as cancelled",
			func(tb testing.TB, b Batched) {
				batchedAssertPutCancels(tb, b, fx)
			}).At(suite.StrengthErrorOnly),
		sig(ix.Put.NilContext(), suite.ClassNilContext,
			"Put returns an error rather than panicking on a nil context",
			func(tb testing.TB, b Batched) {
				batchedAssertPutToleratesNilContext(tb, b, fx)
			}).At(suite.StrengthErrorOnly),
		sig(ix.Put.Deadline(), suite.ClassDeadline,
			"Put reports an expired deadline as exceeded",
			func(tb testing.TB, b Batched) {
				batchedAssertPutHonoursDeadline(tb, b, fx)
			}).At(suite.StrengthErrorOnly),
		sig(ix.Read.Smoke(), suite.ClassSmoke,
			"Read survives a call with a derived key",
			func(tb testing.TB, b Batched) {
				batchedAssertReadSmoke(tb, b, fx)
			}).At(suite.StrengthErrorOnly),
		sig(ix.Read.Cancels(), suite.ClassCancel,
			"Read reports a cancelled context as cancelled",
			func(tb testing.TB, b Batched) {
				batchedAssertReadCancels(tb, b, fx)
			}).At(suite.StrengthErrorOnly),
		sig(ix.Read.NilContext(), suite.ClassNilContext,
			"Read returns an error rather than panicking on a nil context",
			func(tb testing.TB, b Batched) {
				batchedAssertReadToleratesNilContext(tb, b, fx)
			}).At(suite.StrengthErrorOnly),
		sig(ix.Read.Deadline(), suite.ClassDeadline,
			"Read reports an expired deadline as exceeded",
			func(tb testing.TB, b Batched) {
				batchedAssertReadHonoursDeadline(tb, b, fx)
			}).At(suite.StrengthErrorOnly),
		sig(ix.Read.ZeroOnError(), suite.ClassZeroValue,
			"Read returns zero alongside any error",
			func(tb testing.TB, b Batched) {
				batchedAssertReadZeroOnError(tb, b, fx)
			}).At(suite.StrengthObserved),
		sig(ix.List.Smoke(), suite.ClassSmoke,
			"List survives a call",
			func(tb testing.TB, b Batched) {
				batchedAssertListSmoke(tb, b)
			}).At(suite.StrengthErrorOnly),
		sig(ix.List.Cancels(), suite.ClassCancel,
			"List reports a cancelled context as cancelled",
			func(tb testing.TB, b Batched) {
				batchedAssertListCancels(tb, b)
			}).At(suite.StrengthErrorOnly),
		sig(ix.List.NilContext(), suite.ClassNilContext,
			"List returns an error rather than panicking on a nil context",
			func(tb testing.TB, b Batched) {
				batchedAssertListToleratesNilContext(tb, b)
			}).At(suite.StrengthErrorOnly),
		sig(ix.List.Deadline(), suite.ClassDeadline,
			"List reports an expired deadline as exceeded",
			func(tb testing.TB, b Batched) {
				batchedAssertListHonoursDeadline(tb, b)
			}).At(suite.StrengthErrorOnly),
		sig(ix.List.ZeroOnError(), suite.ClassZeroValue,
			"List returns nothing alongside any error",
			func(tb testing.TB, b Batched) {
				batchedAssertListZeroOnError(tb, b)
			}).At(suite.StrengthObserved),
		sig(ix.Put.Idempotent(), suite.ClassIdempotent,
			"a second Put after a clean one is accepted",
			func(tb testing.TB, b Batched) {
				batchedAssertPutIdempotent(tb, b, fx)
			}).At(suite.StrengthErrorOnly),
		sig(ix.Read.Miss(), suite.ClassReader,
			"Read reports zero for a key nothing has written",
			func(tb testing.TB, b Batched) {
				batchedAssertReadMiss(tb, b, fx)
			}).At(suite.StrengthObserved),
	}
}

// batchedAssertPutSmoke asserts Put survives a call with derived inputs.
func batchedAssertPutSmoke(
	tb testing.TB,
	b Batched,
	fx BatchedFixture,
) {
	tb.Helper()
	suite.Survives(tb, batchedPut, func(ctx context.Context) {
		_ = b.Put(ctx, fx.Key(), fx.Value())
	})
}

// batchedAssertPutCancels asserts Put reports a cancelled context as cancelled.
func batchedAssertPutCancels(
	tb testing.TB,
	b Batched,
	fx BatchedFixture,
) {
	tb.Helper()
	suite.ReportsCancelled(tb, batchedPut, func(ctx context.Context) error {
		return b.Put(ctx, fx.Key(), fx.Value())
	})
}

// batchedAssertPutToleratesNilContext asserts Put returns an error rather than panicking on a nil context.
func batchedAssertPutToleratesNilContext(
	tb testing.TB,
	b Batched,
	fx BatchedFixture,
) {
	tb.Helper()
	suite.ToleratesNilContext(tb, batchedPut, func(ctx context.Context) error {
		return b.Put(ctx, fx.Key(), fx.Value())
	})
}

// batchedAssertPutHonoursDeadline asserts Put reports an expired deadline as exceeded.
func batchedAssertPutHonoursDeadline(
	tb testing.TB,
	b Batched,
	fx BatchedFixture,
) {
	tb.Helper()
	suite.ReportsDeadlineExceeded(tb, batchedPut, func(ctx context.Context) error {
		return b.Put(ctx, fx.Key(), fx.Value())
	})
}

// batchedAssertReadSmoke asserts Read survives a call with a derived key.
func batchedAssertReadSmoke(
	tb testing.TB,
	b Batched,
	fx BatchedFixture,
) {
	tb.Helper()
	suite.Survives(tb, batchedRead, func(ctx context.Context) {
		_, _ = b.Read(ctx, fx.Key())
	})
}

// batchedAssertReadCancels asserts Read reports a cancelled context as cancelled.
func batchedAssertReadCancels(
	tb testing.TB,
	b Batched,
	fx BatchedFixture,
) {
	tb.Helper()
	suite.ReportsCancelled(tb, batchedRead, func(ctx context.Context) error {
		_, err := b.Read(ctx, fx.Key())
		return err
	})
}

// batchedAssertReadToleratesNilContext asserts Read returns an error rather than panicking on a nil context.
func batchedAssertReadToleratesNilContext(
	tb testing.TB,
	b Batched,
	fx BatchedFixture,
) {
	tb.Helper()
	suite.ToleratesNilContext(tb, batchedRead, func(ctx context.Context) error {
		_, err := b.Read(ctx, fx.Key())
		return err
	})
}

// batchedAssertReadHonoursDeadline asserts Read reports an expired deadline as exceeded.
func batchedAssertReadHonoursDeadline(
	tb testing.TB,
	b Batched,
	fx BatchedFixture,
) {
	tb.Helper()
	suite.ReportsDeadlineExceeded(tb, batchedRead, func(ctx context.Context) error {
		_, err := b.Read(ctx, fx.Key())
		return err
	})
}

// batchedAssertReadZeroOnError asserts Read returns zero alongside any error.
func batchedAssertReadZeroOnError(
	tb testing.TB,
	b Batched,
	fx BatchedFixture,
) {
	tb.Helper()
	ctx, cancel := context.WithCancel(tb.Context())
	cancel()
	got, err := b.Read(ctx, fx.Key())
	if err == nil {
		tb.Skip("Read answered for a cancelled context, so this check has no error to inspect")
	}

	var zero string
	if got != zero {
		tb.Errorf("Read must return the zero value alongside an error: got %+v, want %+v (err %v)",
			got, zero, err)
	}
}

// batchedAssertListSmoke asserts List survives a call.
func batchedAssertListSmoke(
	tb testing.TB,
	b Batched,
) {
	tb.Helper()
	suite.Survives(tb, batchedList, func(ctx context.Context) {
		_, _ = b.List(ctx)
	})
}

// batchedAssertListCancels asserts List reports a cancelled context as cancelled.
func batchedAssertListCancels(
	tb testing.TB,
	b Batched,
) {
	tb.Helper()
	suite.ReportsCancelled(tb, batchedList, func(ctx context.Context) error {
		_, err := b.List(ctx)
		return err
	})
}

// batchedAssertListToleratesNilContext asserts List returns an error rather than panicking on a nil context.
func batchedAssertListToleratesNilContext(
	tb testing.TB,
	b Batched,
) {
	tb.Helper()
	suite.ToleratesNilContext(tb, batchedList, func(ctx context.Context) error {
		_, err := b.List(ctx)
		return err
	})
}

// batchedAssertListHonoursDeadline asserts List reports an expired deadline as exceeded.
func batchedAssertListHonoursDeadline(
	tb testing.TB,
	b Batched,
) {
	tb.Helper()
	suite.ReportsDeadlineExceeded(tb, batchedList, func(ctx context.Context) error {
		_, err := b.List(ctx)
		return err
	})
}

// batchedAssertListZeroOnError asserts List returns nothing alongside any error.
func batchedAssertListZeroOnError(
	tb testing.TB,
	b Batched,
) {
	tb.Helper()
	ctx, cancel := context.WithCancel(tb.Context())
	cancel()
	got, err := b.List(ctx)
	if err == nil {
		tb.Skip("List answered for a cancelled context, so this check has no error to inspect")
	}

	if got != nil {
		tb.Errorf("List must return nothing alongside an error (err %v)", err)
	}
}

// batchedAssertPutIdempotent asserts a second Put after a clean one is accepted.
func batchedAssertPutIdempotent(
	tb testing.TB,
	b Batched,
	fx BatchedFixture,
) {
	tb.Helper()
	ctx := tb.Context()

	if err := b.Put(ctx, fx.Key(), fx.Value()); err != nil {
		tb.Fatalf("Put must succeed before its repeat can be judged: got %v", err)
	}
	if err := b.Put(ctx, fx.Key(), fx.Value()); err != nil {
		tb.Errorf("a second Put after a clean one must change nothing: got %v", err)
	}
}

// batchedAssertReadMiss asserts Read reports zero for a key nothing has written.
func batchedAssertReadMiss(
	tb testing.TB,
	b Batched,
	fx BatchedFixture,
) {
	tb.Helper()
	ctx := tb.Context()

	got, err := b.Read(ctx, fx.KeyOther())

	var zero string
	if got != zero {
		tb.Errorf("Read must return the zero value for an input nothing supplied: got %+v, want %+v (err %v)",
			got, zero, err)
	}
}

// BatchedDefect is a deliberately broken implementation, used as
// evidence that a check can fail. In practice you build one with
// BrokenBatched over the generated test double.
type BatchedDefect interface {
	Subject() (BatchedSubject, error)
}

// BrokenBatched describes an implementation built to break one
// specific claim, so that a check can be shown to catch it.
//
// Give it a name saying what is wrong, and a constructor. The best
// broken implementation is the generated double wrapping a correct one,
// with a single method overridden — correct everywhere except the one
// place the check is about.
func BrokenBatched[T Batched](
	name string, build func(capacity int) T,
) BatchedHarness[T] {
	return BatchedHarness[T]{
		Name: name, New: build,
	}
}

// BatchedChecks is a table of checks you write yourself, for the
// claims that cannot be worked out from the declaration — the ones that
// carry your domain.
//
// They are the same kind of value as the generated checks: they appear
// in the report, they can be dropped by name, and they can say what they
// need from an implementation. There is no second mechanism for them.
//
//	var myChecks = BatchedChecks{
//		{Method: "Put", Name: "my-claim",
//			Claim:    "a sentence stating exactly what this check proves",
//			Run:      myClaimBody,
//			ProvenBy: BrokenBatched("an implementation that breaks it", newBroken)},
//	}
type BatchedChecks []BatchedCheck

func (c BatchedChecks) applyTo(rc *batchedRunConfig) {
	rc.rows = append(rc.rows, c...)
}

// BatchedCheck is one check you wrote. The body is a plain named
// function; which field you put it in decides what it is handed.
type BatchedCheck struct {
	// Method groups this check under one of your methods, so it is named
	// Put/<Name> in output and reruns with the rest of that
	// method's checks. Leave it empty for a check that is not about one
	// method in particular.
	Method string

	// Name identifies this check, in output and when dropping it. Keep it
	// stable: it is what a colleague's Without call refers to.
	Name string

	// Claim is one sentence saying exactly what this check proves. It is
	// recorded in the manifest and read out in the report.
	//
	// Write only what the body actually establishes. "a second write
	// leaves the value unchanged" is a promise that something reads the
	// value back; if the body only checks the write returned no error,
	// say that instead. Nothing here can catch a claim that is wider
	// than its check, and a claim nobody verifies is worse than none.
	Claim string

	// Set exactly one.
	//
	// Run is handed one fresh instance, which suits nearly every check.
	// RunWith is handed something that can build instances, for a claim
	// one instance cannot state on its own: build two and compare them,
	// move the clock forward, put one into a failure state.
	//
	// Both are also handed the sample inputs, so a check you write draws
	// from the same values the generated ones do — override an input and
	// your check sees the override too.
	Run     func(tb testing.TB, s Batched, fx BatchedFixture)
	RunWith func(tb testing.TB, sub BatchedSubject, fx BatchedFixture)

	// Class groups this check in the report's summary. Optional; checks
	// you write are grouped as hand-written by default.
	Class suite.Class

	// Needs says what this check requires from an implementation beyond
	// being constructed — a clock it can move, a failure it can induce.
	//
	// An implementation that cannot supply it fails this check by name,
	// with the field to fill in named in the message. It never skips: a
	// check that quietly skipped for want of wiring would look exactly
	// like one that passed.
	Needs suite.Caps

	// ProvenBy is an implementation built to break this check and nothing
	// else. Setting it makes two statements at once — that the check can
	// fail, and here is the proof — and ProveBatched fails unless the
	// broken implementation really does turn this check red.
	//
	// ProvenReason, if set, is text the failure must contain. Use it so
	// that a broken implementation which fails for some unrelated reason
	// stops counting as evidence.
	//
	// Argued is for when no such implementation can be built: record why,
	// in a sentence. Set at most one of the two. Setting neither is
	// allowed and the report says so — the check is unproven, which is
	// honest, and different from proven.
	ProvenBy     BatchedDefect
	ProvenReason string
	Argued       string
}

// batchedMethods is the interface's method names, used to catch a typo in
// a check's Method field before the run starts.
//
// Without it a misspelled name would be accepted — it looks like any
// other method name — and the check would be filed under a method that
// does not exist, where nobody could find or drop it.
var batchedMethods = suite.NewNameSet("Batched", batchedPut, batchedRead, batchedList)

// bind converts one of your checks into the form the runner uses, tying
// it to this run's sample inputs — which is what lets a check you wrote
// see the same values, and the same overrides, as the generated ones.
func (c BatchedCheck) bind(
	fx BatchedFixture,
) (suite.Check[Batched], error) {
	out := suite.Check[Batched]{
		Claim: c.Claim, Class: c.Class, Needs: c.Needs,
	}
	if out.Class == "" {
		out.Class = suite.ClassHandWritten
	}

	var err error
	bodies := 0
	if c.Run != nil {
		bodies++
		if out.ID, err = suite.RowID("Run", c.Method, c.Name, batchedMethods); err != nil {
			return out, err
		}
		run := c.Run
		out.Run = func(tb testing.TB, s Batched) {
			run(tb, s, fx)
		}
	}
	if c.RunWith != nil {
		bodies++
		out.ID = suite.HandRowID(c.Name)
		rw := c.RunWith
		out.RunWith = func(tb testing.TB, sub BatchedSubject) {
			rw(tb, sub, fx)
		}
	}
	if err := suite.OneBody(c.Name, bodies, "Run, RunWith"); err != nil {
		return out, err
	}
	if c.Method != "" && c.Run == nil {
		return out, fmt.Errorf(
			"check %q sets Method, but its body fixes its own scope; drop Method", c.Name)
	}
	if out.Falsifiable, err = suite.Falsify(c.Name, c.ProvenBy != nil, c.Argued); err != nil {
		return out, err
	}
	return out, nil
}

// RunBatched runs every check — the generated ones and any you
// wrote — against every implementation you pass it.
//
// Each argument describes one thing to do, in any order: an
// implementation to test, a table of your own checks, sample inputs to
// use, or checks to leave out.
//
//	RunBatched(t,
//		BatchedHarness[*InMemory]{Name: "in-memory", New: NewInMemory},
//		BatchedSuite.Without(BatchedSuite.Checks.Put.Smoke()),
//	)
//
// Pass two implementations to compare them against each other, and mark
// the one you trust as the Oracle. Every check runs as its own subtest
// named after the implementation and the check, so `go test -run` can
// select one.
//
// A check that needs something your implementation has not supplied
// fails rather than skipping, and says which field to fill in. That is
// deliberate: a skipped check is how a claim goes unchecked while the
// run stays green.
func RunBatched(
	t *testing.T, opts ...BatchedRunOpt,
) {
	t.Helper()
	var rc batchedRunConfig
	for _, o := range opts {
		o.applyTo(&rc)
	}
	fx := batchedNewFixture()
	for _, row := range rc.rows {
		rc.AddCheck(row.bind(fx))
	}
	// Checked here, after reading every argument and before running
	// anything: a misconfigured run reports all of its problems at once
	// rather than one per attempt.
	rc.Fail(t, "RunBatched")
	suite.Run(t,
		batchedSuite(fx).With(rc.Extra...).Without(rc.Drops...),
		rc.Subjects...)
}

// ProveBatched runs each of your checks against the deliberately
// broken implementation it names, and fails if the check does not catch
// it.
//
//	func TestMyChecksCanFail(t *testing.T) { ProveBatched(t, myChecks) }
//
// A check that always passes is indistinguishable from a working one
// until something breaks in production. This is what tells them apart:
// give each check a ProvenBy, and this proves the check can fail.
//
// A check with no ProvenBy is not ignored — it has to say why, in
// Argued. The two are held level in both directions: claiming proof
// without a broken implementation fails here, and supplying one for a
// check that claims nothing fails too.
func ProveBatched(
	t *testing.T, checks BatchedChecks,
) {
	t.Helper()
	// The RUN's config, not the derived one: a check proven at default
	// pools carries no evidence about the pools a run actually uses.
	fx := batchedNewFixture()
	bound := make([]suite.Check[Batched], 0, len(checks))
	defects := prove.Defects[Batched]{}
	for _, row := range checks {
		bd, err := row.bind(fx)
		if err != nil {
			t.Fatalf("ProveBatched: %v", err)
		}
		bound = append(bound, bd)
		if row.ProvenBy == nil {
			continue
		}
		sub, err := row.ProvenBy.Subject()
		if err != nil {
			t.Fatalf("ProveBatched: check %q: defect: %v", bd.ID, err)
		}
		defects[bd.ID] = prove.Defect[Batched]{
			Subject: sub, Reason: row.ProvenReason,
		}
	}
	prove.All(t, bound, defects)
}

// batchedModelRows is what this package's model tier claims.
//
// Every row here needs sequences of calls judged against something
// outside the subject, which is what separates them from the rows
// above: those settle a claim with a fixed call sequence, and these
// cannot be stated that way at all. That is also why each takes the
// Subject rather than an instance — a sequence run builds its own, and
// some of them build two.
func batchedModelRows(fx BatchedFixture) []suite.Check[Batched] {
	return []suite.Check[Batched]{
		{
			ID:    batchedCheckIndex.Model.IdempotentWrite(),
			Class: suite.ClassLaws,
			Claim: "writing the same value twice leaves what writing it once left",
			Binds: []string{
				lawid.IdempotentWrite,
			},
			Falsifiable: suite.Argued("no mechanical rule plants a defect for this claim; the ones that would are domain composites, which no rule reaches from shape and stamps alone"),
			Strength:    suite.StrengthDifferential,
			RunWith: func(tb testing.TB, sub suite.Subject[Batched]) {
				batchedAssertIdempotentWrite(tb, sub, fx)
			},
		},
		{
			ID:    batchedCheckIndex.Model.ReadsAgree(),
			Class: suite.ClassLaws,
			Claim: "every key reads the same on the subject as on the reference",
			Binds: []string{
				lawid.ReadAfterWrite,
			},
			Falsifiable: suite.Argued("no mechanical rule plants a defect for this claim; the ones that would are domain composites, which no rule reaches from shape and stamps alone"),
			Strength:    suite.StrengthDifferential,
			RunWith: func(tb testing.TB, sub suite.Subject[Batched]) {
				batchedAssertReadsAgree(tb, sub, fx)
			},
		},
		{
			ID:    batchedCheckIndex.Model.Counts(),
			Class: suite.ClassLaws,
			Claim: "the subject counts what the reference counts",
			Binds: []string{
				lawid.CountEqualsReference,
			},
			Falsifiable: suite.Argued("no mechanical rule plants a defect for this claim; the ones that would are domain composites, which no rule reaches from shape and stamps alone"),
			Strength:    suite.StrengthDifferential,
			RunWith: func(tb testing.TB, sub suite.Subject[Batched]) {
				batchedAssertCounts(tb, sub, fx)
			},
		},
		{
			ID:    batchedCheckIndex.Model.Bounded(),
			Class: suite.ClassLaws,
			Claim: "the count stays inside the declared bound",
			Binds: []string{
				lawid.AggregatorBounded,
			},
			Falsifiable: suite.Argued("no mechanical rule plants a defect for this claim; the ones that would are domain composites, which no rule reaches from shape and stamps alone"),
			Strength:    suite.StrengthDifferential,
			RunWith: func(tb testing.TB, sub suite.Subject[Batched]) {
				batchedAssertBounded(tb, sub, fx)
			},
		},
	}
}

// --- Batched's model tier -------------------------------------------
//
// Random sequences of Batched's methods, run against every subject and
// something that judges them from outside. The rows on the run surface
// above carry it, and BatchedSuite.Without declines any of them by name.
//
//	Reference: the subject's own factory — the bounded claim clamps what the reader answers, and a derived collection clamps nothing,
//	           so a second instance driven identically stands in: twins must
//	           agree, which catches nondeterminism and hidden shared state but
//	           not a subject wrong the same way twice; ref= raises the floor
//	Sequences: Put (compositewriter), Read (reader), List (collector)
//	Values:    the fixture pair blended with arbitrary draws
//	Not bound:
//	           AUTO-WRITE-OBSERVABLE — KeyOf needs the key projection, which was not derivable here
//	           AUTO-PURE-DETERMINISTIC — Call closes over List, which is not a bare pure call
//	           AUTO-CACHEABLE — Read closes over List, whose shape is collector rather than a keyed reader

// batchedModelKeys is the key pool every key slot draws from.
//
// Two keys, and deliberately not more: collision density is what makes a
// read revisit a write and an overwrite land on held state. A wide key
// pool would pass every comparison over a history that never collides.
func batchedModelKeys(fx BatchedFixture) *model.Generator[string] {
	return model.SampledFrom([]string{fx.Key(), fx.KeyOther()})
}

// batchedModelValues is the value pool every value slot draws from.
//
// The fixture pair blended with arbitrary draws: the pair keeps identical
// rewrites frequent, the wide arm reaches values no fixture spells, and
// nothing in the claims licenses refusing either.
func batchedModelValues(fx BatchedFixture) *model.Generator[string] {
	bodies := model.OneOf(
		model.SampledFrom([]string{fx.Value(), fx.ValueOther()}),
		model.Make[string](),
	)
	return bodies
}

// batchedModelActions is the operation vocabulary both legs drive.
//
// One constructor per method shape, from the engine's action set rather
// than hand-written closures: the constructors record inputs and outputs
// into the trace a law reads, compare the two sides the same way for every
// action, and shrink a failing sequence to the shortest one that still
// fails.
func batchedModelActions(fx BatchedFixture) []model.Action[Batched] {
	keys := batchedModelKeys(fx)
	values := batchedModelValues(fx)
	return []model.Action[Batched]{
		action.CompositeWriter("Put", keys, values,
			func(ctx context.Context, s batchedmixins.Batched, k string, v string) error {
				return s.Put(ctx, k, v)
			}),
		action.Reader("Read", keys,
			func(ctx context.Context, s batchedmixins.Batched, k string) (string, error) {
				return s.Read(ctx, k)
			}),
		action.Stream("List",
			func(ctx context.Context, s batchedmixins.Batched) ([]string, error) {
				return s.List(ctx)
			}),
	}
}

// batchedAssertIdempotentWrite binds AUTO-IDEMPOTENT-WRITE over the shared sequences.
//
// One law, and the run's only oracle. The differential is off here, as
// on every law leg: with it armed a subject broken anywhere disagrees at
// step 0, and whether THIS law can catch a defect stays unanswerable.
func batchedAssertIdempotentWrite(
	tb testing.TB,
	sub suite.Subject[Batched],
	fx BatchedFixture,
) {
	tb.Helper()
	values := batchedModelValues(fx)

	buildRef, tier := legs.Reference(tb, sub, func() Batched { return sub.New(tb) })
	sub.NoteTier(tier)
	legs.Law(tb, sub,
		func() Batched { return sub.New(tb) }, buildRef,
		batchedModelActions(fx),
		[]law.Law[Batched]{
			law.IdempotentWrite[batchedmixins.Batched, string, []string]{
				Write: func(rt *model.T, s batchedmixins.Batched, v string) error {
					return s.Put(rt.Context(), fx.Key(), v)
				},
				Values: values,
				Observe: func(rt *model.T, s batchedmixins.Batched) []string {
					v, err := s.List(rt.Context())
					if err != nil {
						rt.Fatalf("Observe observation failed: %v", err)
					}
					return v
				},
			},
		})
}

// batchedAssertReadsAgree binds AUTO-READ-AFTER-WRITE over the shared sequences.
//
// One law, and the run's only oracle. The differential is off here, as
// on every law leg: with it armed a subject broken anywhere disagrees at
// step 0, and whether THIS law can catch a defect stays unanswerable.
func batchedAssertReadsAgree(
	tb testing.TB,
	sub suite.Subject[Batched],
	fx BatchedFixture,
) {
	tb.Helper()
	keys := batchedModelKeys(fx)

	buildRef, tier := legs.Reference(tb, sub, func() Batched { return sub.New(tb) })
	sub.NoteTier(tier)
	legs.Law(tb, sub,
		func() Batched { return sub.New(tb) }, buildRef,
		batchedModelActions(fx),
		[]law.Law[Batched]{
			law.ReadAfterWrite[batchedmixins.Batched, string, string]{
				Read: func(rt *model.T, s batchedmixins.Batched, k string) (string, error) {
					return s.Read(rt.Context(), k)
				},
				Keys: keys,
			},
		})
}

// batchedAssertCounts binds AUTO-COUNT-EQUALS-REFERENCE over the shared sequences.
//
// One law, and the run's only oracle. The differential is off here, as
// on every law leg: with it armed a subject broken anywhere disagrees at
// step 0, and whether THIS law can catch a defect stays unanswerable.
func batchedAssertCounts(
	tb testing.TB,
	sub suite.Subject[Batched],
	fx BatchedFixture,
) {
	tb.Helper()

	buildRef, tier := legs.Reference(tb, sub, func() Batched { return sub.New(tb) })
	sub.NoteTier(tier)
	legs.Law(tb, sub,
		func() Batched { return sub.New(tb) }, buildRef,
		batchedModelActions(fx),
		[]law.Law[Batched]{
			law.CountEqualsReference[batchedmixins.Batched, int]{
				Count: func(rt *model.T, s batchedmixins.Batched) (int, error) {
					items, err := s.List(rt.Context())
					return len(items), err
				},
			},
		})
}

// batchedAssertBounded binds AUTO-AGGREGATOR-BOUNDED over the shared sequences.
//
// One law, and the run's only oracle. The differential is off here, as
// on every law leg: with it armed a subject broken anywhere disagrees at
// step 0, and whether THIS law can catch a defect stays unanswerable.
func batchedAssertBounded(
	tb testing.TB,
	sub suite.Subject[Batched],
	fx BatchedFixture,
) {
	tb.Helper()

	buildRef, tier := legs.Reference(tb, sub, func() Batched { return sub.New(tb) })
	sub.NoteTier(tier)
	legs.Law(tb, sub,
		func() Batched { return sub.New(tb) }, buildRef,
		batchedModelActions(fx),
		[]law.Law[Batched]{
			law.AggregatorBounded[batchedmixins.Batched, int]{
				Read: func(rt *model.T, s batchedmixins.Batched) (int, error) {
					items, err := s.List(rt.Context())
					return len(items), err
				},
				Max: 50,
			},
		})
}

// testkit: end of generated content.
// testkit:provenance 5669a30d33f5a6b5097138fa815d870d15b6daf8b699d163e2ce511c845dfa00
