// Code generated by testkit. DO NOT EDIT.
//
// Source:    corpus/iface/mixin/accumulates/iface.go
// Plugins:   golang 1.0.0, suite 1.23.0, backend.golang 1.0.0
// Command:   testkit run ./corpus/...

package accumulatestest_test

import (
	"context"
	"errors"
	"testing"

	"go.thesmos.sh/testkit/conformance/corpus/iface/mixin/accumulates/accumulatestest"
	"go.thesmos.sh/testkit/engine/suite"
	"go.thesmos.sh/testkit/engine/suite/prove"
)

// TestMixedProofs drives every planted defect through the check it is
// evidence for.
//
// A red here is the expected outcome for each one; a GREEN is the finding.
// It means a check tolerated the implementation built to break it, and a
// check that cannot fail is a line in a report rather than a claim about
// the subject.
func TestMixedProofs(t *testing.T) {
	t.Parallel()
	prove.All(t,
		accumulatestest.MixedSuite.Suite(accumulatestest.DefaultMixedFixture()).Checks,
		mixedProofs())
}

// mixedProofs is every defect this run derived and can spell.
//
// Each is the smallest implementation that breaks exactly one claim: the
// generated double with one method overridden, and nothing else changed.
// The reason beside it is the substring the red must contain, so a defect
// that died on an unrelated guard stops counting as evidence.
func mixedProofs() prove.Defects[accumulatestest.Mixed] {
	ix := accumulatestest.MixedSuite.Checks
	return prove.Defects[accumulatestest.Mixed]{
		ix.Add.Smoke(): prove.One("a Mixed whose Add panics",
			func(tb testing.TB) accumulatestest.Mixed {
				return accumulatestest.NewMixedStub(tb, accumulatestest.WithMixedAdd(
					func(_ context.Context, _ string, _ int) error {
						panic("planted: Add panics")
					}))
			}).Reasoned(suite.RedPanicked),
		ix.Add.Cancels(): prove.One("a Mixed whose Add ignores the context it is handed",
			func(tb testing.TB) accumulatestest.Mixed {
				return accumulatestest.NewMixedStub(tb, accumulatestest.WithMixedAdd(
					func(_ context.Context, _ string, _ int) (err error) {
						// The call arrives and nothing is done with it; the bare
						// return answers every slot's zero, which for the error
						// slot is the nil this claim forbids.
						return
					}))
			}).Reasoned(suite.RedCancelled),
		ix.Add.NilContext(): prove.One("a Mixed whose Add forgives a nil context and answers",
			func(tb testing.TB) accumulatestest.Mixed {
				return accumulatestest.NewMixedStub(tb, accumulatestest.WithMixedAdd(
					func(_ context.Context, _ string, _ int) (err error) {
						// The call arrives and nothing is done with it; the bare
						// return answers every slot's zero, which for the error
						// slot is the nil this claim forbids.
						return
					}))
			}).Reasoned(suite.RedNilContext),
		ix.Add.Deadline(): prove.One("a Mixed whose Add ignores the context it is handed",
			func(tb testing.TB) accumulatestest.Mixed {
				return accumulatestest.NewMixedStub(tb, accumulatestest.WithMixedAdd(
					func(_ context.Context, _ string, _ int) (err error) {
						// The call arrives and nothing is done with it; the bare
						// return answers every slot's zero, which for the error
						// slot is the nil this claim forbids.
						return
					}))
			}).Reasoned(suite.RedDeadline),
		ix.Total.Smoke(): prove.One("a Mixed whose Total panics",
			func(tb testing.TB) accumulatestest.Mixed {
				return accumulatestest.NewMixedStub(tb, accumulatestest.WithMixedTotal(
					func(_ context.Context, _ string) (int, error) {
						panic("planted: Total panics")
					}))
			}).Reasoned(suite.RedPanicked),
		ix.Total.Cancels(): prove.One("a Mixed whose Total ignores the context it is handed",
			func(tb testing.TB) accumulatestest.Mixed {
				return accumulatestest.NewMixedStub(tb, accumulatestest.WithMixedTotal(
					func(_ context.Context, _ string) (r0 int, err error) {
						// The call arrives and nothing is done with it; the bare
						// return answers every slot's zero, which for the error
						// slot is the nil this claim forbids.
						return
					}))
			}).Reasoned(suite.RedCancelled),
		ix.Total.NilContext(): prove.One("a Mixed whose Total forgives a nil context and answers",
			func(tb testing.TB) accumulatestest.Mixed {
				return accumulatestest.NewMixedStub(tb, accumulatestest.WithMixedTotal(
					func(_ context.Context, _ string) (r0 int, err error) {
						// The call arrives and nothing is done with it; the bare
						// return answers every slot's zero, which for the error
						// slot is the nil this claim forbids.
						return
					}))
			}).Reasoned(suite.RedNilContext),
		ix.Total.Deadline(): prove.One("a Mixed whose Total ignores the context it is handed",
			func(tb testing.TB) accumulatestest.Mixed {
				return accumulatestest.NewMixedStub(tb, accumulatestest.WithMixedTotal(
					func(_ context.Context, _ string) (r0 int, err error) {
						// The call arrives and nothing is done with it; the bare
						// return answers every slot's zero, which for the error
						// slot is the nil this claim forbids.
						return
					}))
			}).Reasoned(suite.RedDeadline),
		ix.Total.ZeroOnError(): prove.One("a Mixed whose Total answers a believable value beside its error",
			func(tb testing.TB) accumulatestest.Mixed {
				return accumulatestest.NewMixedStub(tb, accumulatestest.WithMixedTotal(
					func(_ context.Context, _ string) (r0 int, err error) {
						// A believable answer beside the refusal. A caller
						// reading the error and one reading the value disagree
						// about what happened, which is the claim's own
						// violation rather than a subject that merely failed.
						r0 = 2
						err = errors.New("planted: Total refused with a believable value")
						return
					}))
			}),
		ix.Add.Accumulates(): prove.One("a Mixed whose Add second-call-errs",
			func(tb testing.TB) accumulatestest.Mixed {
				called := false
				return accumulatestest.NewMixedStub(tb, accumulatestest.WithMixedAdd(
					func(_ context.Context, _ string, _ int) (err error) {
						if called {
							err = errors.New("planted: Add refuses its repeat")
							return
						}
						called = true
						return
					}))
			}),
		ix.Total.Miss(): prove.One("a Mixed whose Total answers for an input nothing wrote",
			func(tb testing.TB) accumulatestest.Mixed {
				return accumulatestest.NewMixedStub(tb, accumulatestest.WithMixedTotal(
					func(_ context.Context, _ string) (r0 int, err error) {
						// A value for a call a correct subject answers nothing for.
						r0 = 2
						return
					}))
			}),
	}
}

// TestMixedInvariants holds this package to what it says about itself.
//
// Four claims, none of which a consumer writes and none of which any
// other gate makes. The manifest pins the assertion SET, so a check that
// stops being emitted reads as a removed row in review rather than as a
// suite that quietly got smaller. The index and the drop hints pin the
// two ways a check is NAMED — an index entry pointing at nothing
// compiles, and a drop hint that falls back to the string form forfeits
// exactly the compile-break the index exists to give. The distinct-ID
// check catches two interfaces in one package claiming one identity,
// which method-name scopes make possible.
func TestMixedInvariants(t *testing.T) {
	t.Parallel()

	s := accumulatestest.MixedSuite.Suite(accumulatestest.DefaultMixedFixture())

	rows, err := suite.LockLines(s)
	if err != nil {
		t.Fatalf("render the manifest rows: %v", err)
	}
	suite.VerifyLock(t, "mixed.checks.lock", rows)
	suite.VerifyIndex(t, "Mixed",
		accumulatestest.MixedSuite.Checks.All(), s.IDs())
	suite.VerifyDropHints(t, "Mixed", s.IDs(), s.DropHint)
	suite.VerifyDistinctIDs(t, s.IDs())
}

// testkit: end of generated content.
// testkit:provenance 01a1ebc8f7c5328eaf9e7c9cdf63c6fece4e804f7a1bbf1be49d947cd75ad83f
