// Code generated by testkit. DO NOT EDIT.
//
// Source:    corpus/iface/contract/leader-election/iface.go
// Plugins:   golang 1.0.0, stub 1.4.0, backend.golang 1.0.0
// Command:   testkit run ./corpus/...

// Conformance checks worked out from the interfaces this package doubles.
//
// One call runs every check for an interface against one implementation.
// Describe the implementation in a literal and hand it over — each
// interface's own Run function is documented beside it, with the names
// to use.
//
// Nothing else is required to start. The rest is there when you need it:
// a harness field to add only when a check fails asking for it, checks of
// your own that run beside the generated ones, a Prove entry that drives
// each of yours against the broken implementation it names, and a typed
// index for dropping a check by identity rather than by string.
//
// Nothing here is written by hand. Regenerate rather than edit: an edit
// survives until the next run and no longer.
package leaderelectiontest

import (
	"context"
	"testing"

	"go.thesmos.sh/testkit/clock"
	leaderelection "go.thesmos.sh/testkit/conformance/corpus/iface/contract/leader-election"
	"go.thesmos.sh/testkit/rand"
	"go.thesmos.sh/testkit/stub"
)

// ContractCampaignCall records one invocation of Contract.Campaign.
//
// Fields take their names from the source signature — parameters and named
// returns alike — so a failure message names what the author named. A slot
// the source left unnamed or blank falls back to a positional name.
type ContractCampaignCall struct {
	Ctx context.Context
	Err error
}

// ContractResignCall records one invocation of Contract.Resign.
//
// Fields take their names from the source signature — parameters and named
// returns alike — so a failure message names what the author named. A slot
// the source left unnamed or blank falls back to a positional name.
type ContractResignCall struct {
	Ctx context.Context
	Err error
}

// ContractIsLeaderCall records one invocation of Contract.IsLeader.
//
// Fields take their names from the source signature — parameters and named
// returns alike — so a failure message names what the author named. A slot
// the source left unnamed or blank falls back to a positional name.
type ContractIsLeaderCall struct {
	Ctx    context.Context
	Result bool
}

// --- Per-method configuration ---

// ContractCampaignStub controls how the double answers Campaign and records
// what it was asked.
//
// The embedded MethodStub supplies the machinery every method shares: call
// recording, fault injection, latency against a virtual clock, gates,
// call-count expectations, and strict mode.
type ContractCampaignStub struct {
	*stub.MethodStub[ContractCampaignCall]

	fn       func(context.Context) error
	fallback *ContractCampaignReturn
}

// ContractCampaignReturn holds the fixed answer configured through Returns.
type ContractCampaignReturn struct {
	Err error
}

// Returns pins a fixed result for every call to Campaign. A Func
// override and an injected fault both take precedence over it.
func (s *ContractCampaignStub) Returns(err error) *ContractCampaignStub {
	s.fallback = &ContractCampaignReturn{Err: err}
	return s
}

// Func supplies a body for Campaign, for when the answer depends on the
// arguments. An injected fault still takes precedence.
func (s *ContractCampaignStub) Func(fn func(context.Context) error) *ContractCampaignStub {
	s.fn = fn
	return s
}

// ContractResignStub controls how the double answers Resign and records
// what it was asked.
//
// The embedded MethodStub supplies the machinery every method shares: call
// recording, fault injection, latency against a virtual clock, gates,
// call-count expectations, and strict mode.
type ContractResignStub struct {
	*stub.MethodStub[ContractResignCall]

	fn       func(context.Context) error
	fallback *ContractResignReturn
}

// ContractResignReturn holds the fixed answer configured through Returns.
type ContractResignReturn struct {
	Err error
}

// Returns pins a fixed result for every call to Resign. A Func
// override and an injected fault both take precedence over it.
func (s *ContractResignStub) Returns(err error) *ContractResignStub {
	s.fallback = &ContractResignReturn{Err: err}
	return s
}

// Func supplies a body for Resign, for when the answer depends on the
// arguments. An injected fault still takes precedence.
func (s *ContractResignStub) Func(fn func(context.Context) error) *ContractResignStub {
	s.fn = fn
	return s
}

// ContractIsLeaderStub controls how the double answers IsLeader and records
// what it was asked.
//
// The embedded MethodStub supplies the machinery every method shares: call
// recording, fault injection, latency against a virtual clock, gates,
// call-count expectations, and strict mode.
type ContractIsLeaderStub struct {
	*stub.MethodStub[ContractIsLeaderCall]

	fn       func(context.Context) bool
	fallback *ContractIsLeaderReturn
}

// ContractIsLeaderReturn holds the fixed answer configured through Returns.
type ContractIsLeaderReturn struct {
	Result bool
}

// Returns pins a fixed result for every call to IsLeader. A Func
// override and an injected fault both take precedence over it.
func (s *ContractIsLeaderStub) Returns(result bool) *ContractIsLeaderStub {
	s.fallback = &ContractIsLeaderReturn{Result: result}
	return s
}

// Func supplies a body for IsLeader, for when the answer depends on the
// arguments. An injected fault still takes precedence.
func (s *ContractIsLeaderStub) Func(fn func(context.Context) bool) *ContractIsLeaderStub {
	s.fn = fn
	return s
}

// --- ContractStub ---

// The double-runtime witness for the surface this double rides. A
// breaking change to the runtime renames it, and this file stops
// compiling with the skew named.
var _ = stub.CompatV1

// ContractStubOption configures a [ContractStub] at construction time.
type ContractStubOption func(*ContractStub)

// ContractStubStrict makes an unconfigured method fail the test rather than
// return its zero value, which turns a call nobody planned for into a failure
// at the call site instead of a puzzling zero further downstream.
func ContractStubStrict() ContractStubOption {
	return func(s *ContractStub) { s.strict = true }
}

// ContractStubDelegateTo wraps a real implementation: every method forwards to
// impl and is recorded on the double on the way through.
//
// This is what lets one generated suite run against both the double and the
// production type, which is the point of conformance testing.
func ContractStubDelegateTo(impl leaderelection.Contract) ContractStubOption {
	return func(s *ContractStub) {
		s.OnCampaign.Func(impl.Campaign)
		s.OnResign.Func(impl.Resign)
		s.OnIsLeader.Func(impl.IsLeader)
	}
}

// ContractStubWithClock drives latency and time-windowed faults from clk
// rather than from wall time, so a test asserting on a five-second timeout
// does not take five seconds.
func ContractStubWithClock(clk clock.Clock) ContractStubOption {
	return func(s *ContractStub) { s.group.SetClock(clk) }
}

// ContractStubWithRandSource makes probabilistic fault injection reproducible.
// A failure nobody can replay is not a finding.
func ContractStubWithRandSource(src rand.Source) ContractStubOption {
	return func(s *ContractStub) { s.group.SetRandSource(src) }
}

// ContractStubBenchMode disables call recording. Dispatch still works; only
// the accumulating call log is dropped, because its allocations are what a
// benchmark would otherwise be measuring.
func ContractStubBenchMode() ContractStubOption {
	return func(s *ContractStub) { s.group.BenchMode() }
}

// WithContractCampaign sets Campaign's body at construction
// time, for the common case of configuring one method and taking the
// defaults for the rest.
func WithContractCampaign(fn func(context.Context) error) ContractStubOption {
	return func(s *ContractStub) { s.OnCampaign.Func(fn) }
}

// WithContractResign sets Resign's body at construction
// time, for the common case of configuring one method and taking the
// defaults for the rest.
func WithContractResign(fn func(context.Context) error) ContractStubOption {
	return func(s *ContractStub) { s.OnResign.Func(fn) }
}

// WithContractIsLeader sets IsLeader's body at construction
// time, for the common case of configuring one method and taking the
// defaults for the rest.
func WithContractIsLeader(fn func(context.Context) bool) ContractStubOption {
	return func(s *ContractStub) { s.OnIsLeader.Func(fn) }
}

// ContractStub is a recording test double for Contract.
//
// Each On<Method> field is that method's configuration point. Left alone, a
// method returns its zero value and records the call.
type ContractStub struct {
	OnCampaign *ContractCampaignStub
	OnResign   *ContractResignStub
	OnIsLeader *ContractIsLeaderStub

	// group is every method stub above, viewed through the surface that
	// does not depend on a signature — one home for the settings and the
	// lifecycle that apply to the whole double.
	group  *stub.Group
	strict bool
}

// Compile-time proof that ContractStub satisfies Contract.
//
// It lives here rather than in the companion so a drifted signature fails
// `go build` rather than waiting for a test run — the double is unusable the
// moment it stops satisfying the interface, and that is worth learning at the
// earliest point it can be known.
var _ leaderelection.Contract = (*ContractStub)(nil)

// NewContractStub returns a double bound to tb.
//
// Passing tb registers a cleanup that verifies every method's call-count
// expectations when the test ends, so an unmet Times is reported without the
// caller remembering to check. A nil tb skips that, which is what benchmarks
// and non-test callers want.
func NewContractStub(tb testing.TB, opts ...ContractStubOption) *ContractStub {
	s := &ContractStub{
		OnCampaign: &ContractCampaignStub{MethodStub: stub.NewMethodStub[ContractCampaignCall](tb, "Contract.Campaign")},
		OnResign:   &ContractResignStub{MethodStub: stub.NewMethodStub[ContractResignCall](tb, "Contract.Resign")},
		OnIsLeader: &ContractIsLeaderStub{MethodStub: stub.NewMethodStub[ContractIsLeaderCall](tb, "Contract.IsLeader")},
	}
	s.group = stub.NewGroup(
		s.OnCampaign.MethodStub,
		s.OnResign.MethodStub,
		s.OnIsLeader.MethodStub,
	)
	for _, opt := range opts {
		opt(s)
	}
	if s.strict {
		s.group.StrictAll()
	}
	s.group.Bind(tb)
	return s
}

// ResetCalls clears recorded calls, fault counters, and call-count
// expectations. Func and Returns configuration is deliberately preserved, so
// a test can reuse one double across phases without rebuilding it.
func (s *ContractStub) ResetCalls() {
	s.group.Reset()
}

// --- Interface methods ---

// invoke adapts the Func override to the shape [stub.Answer] consumes, or
// returns nil when no override is set — which is how Answer tells "no
// override" from "an override that returns zero".
func (s *ContractCampaignStub) invoke(ctx context.Context) func() ContractCampaignReturn {
	if s.fn == nil {
		return nil
	}
	return func() ContractCampaignReturn {
		r0 := s.fn(ctx)
		return ContractCampaignReturn{Err: r0}
	}
}

// Campaign records the call and answers it.
//
// Which arm answers — injected fault, Func override, Returns fallback, or the
// zero value — is [stub.Answer]'s to decide, so every generated double
// resolves a call the same way and the ordering is tested once rather than
// restated per method.
func (s *ContractStub) Campaign(ctx context.Context) error {
	call := ContractCampaignCall{Ctx: ctx}
	r := stub.Answer(s.OnCampaign.MethodStub, &call, stub.Arms[ContractCampaignCall, ContractCampaignReturn]{
		Invoke:   s.OnCampaign.invoke(ctx),
		Fallback: s.OnCampaign.fallback,
		Fault:    func(err error) ContractCampaignReturn { return ContractCampaignReturn{Err: err} },
		Stamp: func(c *ContractCampaignCall, r ContractCampaignReturn) {
			c.Err = r.Err
		},
	})
	return r.Err
}

// invoke adapts the Func override to the shape [stub.Answer] consumes, or
// returns nil when no override is set — which is how Answer tells "no
// override" from "an override that returns zero".
func (s *ContractResignStub) invoke(ctx context.Context) func() ContractResignReturn {
	if s.fn == nil {
		return nil
	}
	return func() ContractResignReturn {
		r0 := s.fn(ctx)
		return ContractResignReturn{Err: r0}
	}
}

// Resign records the call and answers it.
//
// Which arm answers — injected fault, Func override, Returns fallback, or the
// zero value — is [stub.Answer]'s to decide, so every generated double
// resolves a call the same way and the ordering is tested once rather than
// restated per method.
func (s *ContractStub) Resign(ctx context.Context) error {
	call := ContractResignCall{Ctx: ctx}
	r := stub.Answer(s.OnResign.MethodStub, &call, stub.Arms[ContractResignCall, ContractResignReturn]{
		Invoke:   s.OnResign.invoke(ctx),
		Fallback: s.OnResign.fallback,
		Fault:    func(err error) ContractResignReturn { return ContractResignReturn{Err: err} },
		Stamp: func(c *ContractResignCall, r ContractResignReturn) {
			c.Err = r.Err
		},
	})
	return r.Err
}

// invoke adapts the Func override to the shape [stub.Answer] consumes, or
// returns nil when no override is set — which is how Answer tells "no
// override" from "an override that returns zero".
func (s *ContractIsLeaderStub) invoke(ctx context.Context) func() ContractIsLeaderReturn {
	if s.fn == nil {
		return nil
	}
	return func() ContractIsLeaderReturn {
		r0 := s.fn(ctx)
		return ContractIsLeaderReturn{Result: r0}
	}
}

// IsLeader records the call and answers it.
//
// Which arm answers — injected fault, Func override, Returns fallback, or the
// zero value — is [stub.Answer]'s to decide, so every generated double
// resolves a call the same way and the ordering is tested once rather than
// restated per method.
func (s *ContractStub) IsLeader(ctx context.Context) bool {
	call := ContractIsLeaderCall{Ctx: ctx}
	r := stub.Answer(s.OnIsLeader.MethodStub, &call, stub.Arms[ContractIsLeaderCall, ContractIsLeaderReturn]{
		Invoke:   s.OnIsLeader.invoke(ctx),
		Fallback: s.OnIsLeader.fallback,
		Stamp: func(c *ContractIsLeaderCall, r ContractIsLeaderReturn) {
			c.Result = r.Result
		},
	})
	return r.Result
}

// testkit: end of generated content.
// testkit:provenance 0094c651c12a21b16541b877710cda678f78959dae00ecc933d6e2d0fa4074d3
