// Code generated by testkit. DO NOT EDIT.
//
// Source:    corpus/iface/mixin/ttl/iface.go
// Plugins:   golang 1.0.0, stub 1.4.0, backend.golang 1.0.0
// Command:   testkit run ./corpus/...

package ttltest_test

import (
	"context"
	"testing"
	"time"

	"go.thesmos.sh/testkit"
	"go.thesmos.sh/testkit/clock"
	"go.thesmos.sh/testkit/conformance/corpus/iface/mixin/ttl"
	"go.thesmos.sh/testkit/conformance/corpus/iface/mixin/ttl/ttltest"
	"go.thesmos.sh/testkit/rand"
	"go.thesmos.sh/testkit/stub"
)

// mixedStubPutSubject binds Put into the shape
// [stub.Behaviour] drives: how to call it, what it answers with, and how to
// override it.
//
// Each call builds a fresh double, because several of the checks assert on
// failure and need one bound to a failable TB rather than to the running
// test.
func mixedStubPutSubject(tb testing.TB) stub.Subject[ttltest.MixedPutCall, ttltest.MixedPutReturn] {
	tb.Helper()
	s := ttltest.NewMixedStub(tb)
	return stub.Subject[ttltest.MixedPutCall, ttltest.MixedPutReturn]{
		Stub: s.OnPut.MethodStub,
		Call: func() {
			var a0 context.Context
			var a1 ttl.Value
			_ = s.Put(a0, a1)
		},
		Result: func() ttltest.MixedPutReturn {
			var a0 context.Context
			var a1 ttl.Value
			got0 := s.Put(a0, a1)
			return ttltest.MixedPutReturn{Err: got0}
		},
		Override: func(mark func()) {
			s.OnPut.Func(func(_ context.Context, _ ttl.Value) error {
				mark()
				var z0 error
				return z0
			})
		},
		Fails: func() error {
			var a0 context.Context
			var a1 ttl.Value
			r0 := s.Put(a0, a1)
			return r0
		},
	}
}

// TestMixedStubPut pins how Put answers.
//
// Recording, resetting, call-count expectations, strict mode, fault injection
// and zero-value dispatch are the same contract for every method, so they are
// asserted once in [stub.Behaviour] rather than restated here. What remains
// below needs a value this method's signature can tell apart from a zero one.
func TestMixedStubPut(t *testing.T) {
	t.Parallel()

	stub.Behaviour(t, "Put", mixedStubPutSubject)

	// No check that Put answers what Returns pinned: no result of
	// its signature admits a literal this generator can write, so the only
	// value available to pin is the zero — which an unconfigured double
	// answers anyway. stub.Behaviour asserts that half honestly.
	t.Run("records what it was called with", func(t *testing.T) {
		t.Parallel()
		// Asserting only that a call happened would pass against a double
		// that recorded the wrong arguments, which is the failure a reader
		// most needs the log to surface.
		s := ttltest.NewMixedStub(t)
		var a0 context.Context
		var a1 ttl.Value
		_ = s.Put(a0, a1)
		got := s.OnPut.AssertCalledOnce(t, "Put must record the call")
		testkit.Equal(t, got.Ctx, a0, "the recorded call carries Ctx")
		testkit.Equal(t, got.V, a1, "the recorded call carries V")
	})

	t.Run("fires the OnRecord hook for every call", func(t *testing.T) {
		t.Parallel()
		// The hook fires synchronously as each call lands, which is what a
		// concurrency test observes progress with — polling the log instead
		// races the thing under test.
		s := ttltest.NewMixedStub(t)
		var seen []ttltest.MixedPutCall
		s.OnPut.OnRecord(func(c ttltest.MixedPutCall) { seen = append(seen, c) })
		var a0 context.Context
		var a1 ttl.Value
		_ = s.Put(a0, a1)
		_ = s.Put(a0, a1)
		testkit.Len(t, seen, 2, "OnRecord must fire once per Put call")
	})

	t.Run("wires WithMixedPut at construction", func(t *testing.T) {
		t.Parallel()
		called := false
		s := ttltest.NewMixedStub(t, ttltest.WithMixedPut(func(_ context.Context, _ ttl.Value) error {
			called = true
			var z0 error
			return z0
		}))
		var a0 context.Context
		var a1 ttl.Value
		_ = s.Put(a0, a1)
		testkit.True(t, called, "WithMixedPut must install the override")
	})

	t.Run("keeps recording across a reset", func(t *testing.T) {
		t.Parallel()
		// The weaker claim, and the honest one for this signature. No result
		// of Put admits a literal, so what Returns pinned cannot be
		// told from the zero and comparing them would pass either way.
		//
		// What a reset can still be held to is that it clears the log without
		// taking the double with it: configure, call, reset, call again, and
		// exactly one call is recorded. A reset that dropped the whole
		// configuration fails that, which is the failure the value comparison
		// was reaching for and could not state.
		s := ttltest.NewMixedStub(t)
		var want0 error
		s.OnPut.Returns(want0)
		var a0 context.Context
		var a1 ttl.Value
		_ = s.Put(a0, a1)
		s.ResetCalls()
		_ = s.Put(a0, a1)
		s.OnPut.AssertCalledOnce(t, "Put must record the call that followed the reset")
	})
}

// mixedStubReadSubject binds Read into the shape
// [stub.Behaviour] drives: how to call it, what it answers with, and how to
// override it.
//
// Each call builds a fresh double, because several of the checks assert on
// failure and need one bound to a failable TB rather than to the running
// test.
func mixedStubReadSubject(tb testing.TB) stub.Subject[ttltest.MixedReadCall, ttltest.MixedReadReturn] {
	tb.Helper()
	s := ttltest.NewMixedStub(tb)
	return stub.Subject[ttltest.MixedReadCall, ttltest.MixedReadReturn]{
		Stub: s.OnRead.MethodStub,
		Call: func() {
			var a0 context.Context
			var a1 string = "test-key"
			_, _ = s.Read(a0, a1)
		},
		Result: func() ttltest.MixedReadReturn {
			var a0 context.Context
			var a1 string = "test-key"
			got0, got1 := s.Read(a0, a1)
			return ttltest.MixedReadReturn{Result: got0, Err: got1}
		},
		Override: func(mark func()) {
			s.OnRead.Func(func(_ context.Context, _ string) (ttl.Value, error) {
				mark()
				var z0 ttl.Value
				var z1 error
				return z0, z1
			})
		},
		Fails: func() error {
			var a0 context.Context
			var a1 string = "test-key"
			_, r1 := s.Read(a0, a1)
			return r1
		},
	}
}

// TestMixedStubRead pins how Read answers.
//
// Recording, resetting, call-count expectations, strict mode, fault injection
// and zero-value dispatch are the same contract for every method, so they are
// asserted once in [stub.Behaviour] rather than restated here. What remains
// below needs a value this method's signature can tell apart from a zero one.
func TestMixedStubRead(t *testing.T) {
	t.Parallel()

	stub.Behaviour(t, "Read", mixedStubReadSubject)

	// No check that Read answers what Returns pinned: no result of
	// its signature admits a literal this generator can write, so the only
	// value available to pin is the zero — which an unconfigured double
	// answers anyway. stub.Behaviour asserts that half honestly.
	t.Run("records what it was called with", func(t *testing.T) {
		t.Parallel()
		// Asserting only that a call happened would pass against a double
		// that recorded the wrong arguments, which is the failure a reader
		// most needs the log to surface.
		s := ttltest.NewMixedStub(t)
		var a0 context.Context
		var a1 string = "test-key"
		_, _ = s.Read(a0, a1)
		got := s.OnRead.AssertCalledOnce(t, "Read must record the call")
		testkit.Equal(t, got.Ctx, a0, "the recorded call carries Ctx")
		testkit.Equal(t, got.Key, a1, "the recorded call carries Key")
	})

	t.Run("fires the OnRecord hook for every call", func(t *testing.T) {
		t.Parallel()
		// The hook fires synchronously as each call lands, which is what a
		// concurrency test observes progress with — polling the log instead
		// races the thing under test.
		s := ttltest.NewMixedStub(t)
		var seen []ttltest.MixedReadCall
		s.OnRead.OnRecord(func(c ttltest.MixedReadCall) { seen = append(seen, c) })
		var a0 context.Context
		var a1 string = "test-key"
		_, _ = s.Read(a0, a1)
		_, _ = s.Read(a0, a1)
		testkit.Len(t, seen, 2, "OnRecord must fire once per Read call")
	})

	t.Run("wires WithMixedRead at construction", func(t *testing.T) {
		t.Parallel()
		called := false
		s := ttltest.NewMixedStub(t, ttltest.WithMixedRead(func(_ context.Context, _ string) (ttl.Value, error) {
			called = true
			var z0 ttl.Value
			var z1 error
			return z0, z1
		}))
		var a0 context.Context
		var a1 string = "test-key"
		_, _ = s.Read(a0, a1)
		testkit.True(t, called, "WithMixedRead must install the override")
	})

	t.Run("keeps recording across a reset", func(t *testing.T) {
		t.Parallel()
		// The weaker claim, and the honest one for this signature. No result
		// of Read admits a literal, so what Returns pinned cannot be
		// told from the zero and comparing them would pass either way.
		//
		// What a reset can still be held to is that it clears the log without
		// taking the double with it: configure, call, reset, call again, and
		// exactly one call is recorded. A reset that dropped the whole
		// configuration fails that, which is the failure the value comparison
		// was reaching for and could not state.
		s := ttltest.NewMixedStub(t)
		var want0 ttl.Value
		var want1 error
		s.OnRead.Returns(want0, want1)
		var a0 context.Context
		var a1 string = "test-key"
		_, _ = s.Read(a0, a1)
		s.ResetCalls()
		_, _ = s.Read(a0, a1)
		s.OnRead.AssertCalledOnce(t, "Read must record the call that followed the reset")
	})
}

// mixedStubDouble describes how to build a MixedStub under each
// option whose effect is the same whatever a method's signature.
//
// Put stands in for the double as a whole: what these checks assert
// is that an option reached it at all, and the first method witnesses that as
// well as any other would.
func mixedStubDouble() stub.Double[ttltest.MixedPutCall] {
	instance := func(s *ttltest.MixedStub) stub.Instance[ttltest.MixedPutCall] {
		return stub.Instance[ttltest.MixedPutCall]{
			Stub: s.OnPut.MethodStub,
			Call: func() {
				var a0 context.Context
				var a1 ttl.Value
				_ = s.Put(a0, a1)
			},
			Reset: s.ResetCalls,
		}
	}
	return stub.Double[ttltest.MixedPutCall]{
		New: func(tb testing.TB) stub.Instance[ttltest.MixedPutCall] {
			return instance(ttltest.NewMixedStub(tb))
		},
		WithClock: func(tb testing.TB, clk clock.Clock) stub.Instance[ttltest.MixedPutCall] {
			return instance(ttltest.NewMixedStub(tb, ttltest.MixedStubWithClock(clk)))
		},
		WithRandSource: func(tb testing.TB, src rand.Source) stub.Instance[ttltest.MixedPutCall] {
			return instance(ttltest.NewMixedStub(tb, ttltest.MixedStubWithRandSource(src)))
		},
		BenchMode: func(tb testing.TB) stub.Instance[ttltest.MixedPutCall] {
			return instance(ttltest.NewMixedStub(tb, ttltest.MixedStubBenchMode()))
		},
		Strict: func(tb testing.TB) stub.Instance[ttltest.MixedPutCall] {
			return instance(ttltest.NewMixedStub(tb, ttltest.MixedStubStrict()))
		},
	}
}

// TestMixedStubOptions pins the settings that apply to the double rather
// than to one method: bench mode, the injected clock and random source, and
// what a reset clears.
func TestMixedStubOptions(t *testing.T) {
	t.Parallel()

	stub.DoubleBehaviour(t, mixedStubDouble())
}

// TestMixedStubDelegateTo pins that a wrapped implementation is called
// through, and recorded on the way past.
//
// This is what lets one generated suite run against both the double and a
// production type, which is the point of conformance testing.
func TestMixedStubDelegateTo(t *testing.T) {
	t.Parallel()

	inner := ttltest.NewMixedStub(t)
	s := ttltest.NewMixedStub(t, ttltest.MixedStubDelegateTo(inner))

	t.Run("forwards Put to the wrapped implementation", func(t *testing.T) {
		var a0 context.Context
		var a1 ttl.Value
		_ = s.Put(a0, a1)
		inner.OnPut.AssertCalledOnce(t, "Put must reach the wrapped implementation")
	})

	t.Run("surfaces what Put answered", func(t *testing.T) {
		// Reaching the wrapped implementation is not enough: a double that
		// called through and then discarded the answer would pass the check
		// above while telling its caller nothing true.
		want := testkit.TestError("Put-delegate")
		inner.OnPut.FaultsFor(time.Hour, want)
		var a0 context.Context
		var a1 ttl.Value
		r0 := s.Put(a0, a1)
		testkit.ErrorIs(t, r0, want, "Put must surface the wrapped answer")
	})

	t.Run("forwards Read to the wrapped implementation", func(t *testing.T) {
		var a0 context.Context
		var a1 string = "test-key"
		_, _ = s.Read(a0, a1)
		inner.OnRead.AssertCalledOnce(t, "Read must reach the wrapped implementation")
	})

	t.Run("surfaces what Read answered", func(t *testing.T) {
		// Reaching the wrapped implementation is not enough: a double that
		// called through and then discarded the answer would pass the check
		// above while telling its caller nothing true.
		want := testkit.TestError("Read-delegate")
		inner.OnRead.FaultsFor(time.Hour, want)
		var a0 context.Context
		var a1 string = "test-key"
		_, r1 := s.Read(a0, a1)
		testkit.ErrorIs(t, r1, want, "Read must surface the wrapped answer")
	})
}

// testkit: end of generated content.
// testkit:provenance c0308cda1ccb799454e131f7f1f96508fcbe4ea200cf49679415dabfda7faad8
