// Code generated by testkit. DO NOT EDIT.
//
// Source:    corpus/iface/mixin/ttl/iface.go
// Plugins:   golang 1.0.0, suite 1.23.0, backend.golang 1.0.0
// Command:   testkit run ./corpus/...

package ttltest_test

import (
	"context"
	"errors"
	"testing"

	"go.thesmos.sh/testkit/conformance/corpus/iface/mixin/ttl"
	"go.thesmos.sh/testkit/conformance/corpus/iface/mixin/ttl/ttltest"
	"go.thesmos.sh/testkit/engine/suite"
	"go.thesmos.sh/testkit/engine/suite/prove"
)

// TestMixedProofs drives every planted defect through the check it is
// evidence for.
//
// A red here is the expected outcome for each one; a GREEN is the finding.
// It means a check tolerated the implementation built to break it, and a
// check that cannot fail is a line in a report rather than a claim about
// the subject.
func TestMixedProofs(t *testing.T) {
	t.Parallel()
	prove.All(t,
		ttltest.MixedSuite.Suite(ttltest.DefaultMixedFixture()).Checks,
		mixedProofs())
}

// mixedProofs is every defect this run derived and can spell.
//
// Each is the smallest implementation that breaks exactly one claim: the
// generated double with one method overridden, and nothing else changed.
// The reason beside it is the substring the red must contain, so a defect
// that died on an unrelated guard stops counting as evidence.
func mixedProofs() prove.Defects[ttltest.Mixed] {
	ix := ttltest.MixedSuite.Checks
	return prove.Defects[ttltest.Mixed]{
		ix.Put.Smoke(): prove.One("a Mixed whose Put panics",
			func(tb testing.TB) ttltest.Mixed {
				return ttltest.NewMixedStub(tb, ttltest.WithMixedPut(
					func(_ context.Context, _ ttl.Value) error {
						panic("planted: Put panics")
					}))
			}).Reasoned(suite.RedPanicked),
		ix.Put.Cancels(): prove.One("a Mixed whose Put ignores the context it is handed",
			func(tb testing.TB) ttltest.Mixed {
				return ttltest.NewMixedStub(tb, ttltest.WithMixedPut(
					func(_ context.Context, _ ttl.Value) (err error) {
						// The call arrives and nothing is done with it; the bare
						// return answers every slot's zero, which for the error
						// slot is the nil this claim forbids.
						return
					}))
			}).Reasoned(suite.RedCancelled),
		ix.Put.NilContext(): prove.One("a Mixed whose Put forgives a nil context and answers",
			func(tb testing.TB) ttltest.Mixed {
				return ttltest.NewMixedStub(tb, ttltest.WithMixedPut(
					func(_ context.Context, _ ttl.Value) (err error) {
						// The call arrives and nothing is done with it; the bare
						// return answers every slot's zero, which for the error
						// slot is the nil this claim forbids.
						return
					}))
			}).Reasoned(suite.RedNilContext),
		ix.Put.Deadline(): prove.One("a Mixed whose Put ignores the context it is handed",
			func(tb testing.TB) ttltest.Mixed {
				return ttltest.NewMixedStub(tb, ttltest.WithMixedPut(
					func(_ context.Context, _ ttl.Value) (err error) {
						// The call arrives and nothing is done with it; the bare
						// return answers every slot's zero, which for the error
						// slot is the nil this claim forbids.
						return
					}))
			}).Reasoned(suite.RedDeadline),
		ix.Read.Smoke(): prove.One("a Mixed whose Read panics",
			func(tb testing.TB) ttltest.Mixed {
				return ttltest.NewMixedStub(tb, ttltest.WithMixedRead(
					func(_ context.Context, _ string) (ttl.Value, error) {
						panic("planted: Read panics")
					}))
			}).Reasoned(suite.RedPanicked),
		ix.Read.Cancels(): prove.One("a Mixed whose Read ignores the context it is handed",
			func(tb testing.TB) ttltest.Mixed {
				return ttltest.NewMixedStub(tb, ttltest.WithMixedRead(
					func(_ context.Context, _ string) (r0 ttl.Value, err error) {
						// The call arrives and nothing is done with it; the bare
						// return answers every slot's zero, which for the error
						// slot is the nil this claim forbids.
						return
					}))
			}).Reasoned(suite.RedCancelled),
		ix.Read.NilContext(): prove.One("a Mixed whose Read forgives a nil context and answers",
			func(tb testing.TB) ttltest.Mixed {
				return ttltest.NewMixedStub(tb, ttltest.WithMixedRead(
					func(_ context.Context, _ string) (r0 ttl.Value, err error) {
						// The call arrives and nothing is done with it; the bare
						// return answers every slot's zero, which for the error
						// slot is the nil this claim forbids.
						return
					}))
			}).Reasoned(suite.RedNilContext),
		ix.Read.Deadline(): prove.One("a Mixed whose Read ignores the context it is handed",
			func(tb testing.TB) ttltest.Mixed {
				return ttltest.NewMixedStub(tb, ttltest.WithMixedRead(
					func(_ context.Context, _ string) (r0 ttl.Value, err error) {
						// The call arrives and nothing is done with it; the bare
						// return answers every slot's zero, which for the error
						// slot is the nil this claim forbids.
						return
					}))
			}).Reasoned(suite.RedDeadline),
		ix.Read.ZeroOnError(): prove.One("a Mixed whose Read answers a believable value beside its error",
			func(tb testing.TB) ttltest.Mixed {
				return ttltest.NewMixedStub(tb, ttltest.WithMixedRead(
					func(_ context.Context, _ string) (r0 ttl.Value, err error) {
						// A believable answer beside the refusal. A caller
						// reading the error and one reading the value disagree
						// about what happened, which is the claim's own
						// violation rather than a subject that merely failed.
						r0 = ttl.Value{Key: "other-value"}
						err = errors.New("planted: Read refused with a believable value")
						return
					}))
			}),
		ix.Read.Miss(): prove.One("a Mixed whose Read answers for an input nothing wrote",
			func(tb testing.TB) ttltest.Mixed {
				return ttltest.NewMixedStub(tb, ttltest.WithMixedRead(
					func(_ context.Context, _ string) (r0 ttl.Value, err error) {
						// The call arrives and nothing is done with it; the bare
						// return answers every slot's zero, which for the error
						// slot is the nil this claim forbids.
						return
					}))
			}),
		ix.Model.Agrees(): prove.One("a Mixed whose Put reports success and keeps nothing",
			func(tb testing.TB) ttltest.Mixed {
				return ttltest.NewMixedStub(tb, ttltest.WithMixedPut(
					func(_ context.Context, _ ttl.Value) (err error) {
						// The call arrives and nothing is done with it; the bare
						// return answers every slot's zero, which for the error
						// slot is the nil this claim forbids.
						return
					}))
			}),
	}
}

// TestMixedInvariants holds this package to what it says about itself.
//
// Four claims, none of which a consumer writes and none of which any
// other gate makes. The manifest pins the assertion SET, so a check that
// stops being emitted reads as a removed row in review rather than as a
// suite that quietly got smaller. The index and the drop hints pin the
// two ways a check is NAMED — an index entry pointing at nothing
// compiles, and a drop hint that falls back to the string form forfeits
// exactly the compile-break the index exists to give. The distinct-ID
// check catches two interfaces in one package claiming one identity,
// which method-name scopes make possible.
func TestMixedInvariants(t *testing.T) {
	t.Parallel()

	s := ttltest.MixedSuite.Suite(ttltest.DefaultMixedFixture())

	rows, err := suite.LockLines(s)
	if err != nil {
		t.Fatalf("render the manifest rows: %v", err)
	}
	suite.VerifyLock(t, "mixed.checks.lock", rows)
	suite.VerifyIndex(t, "Mixed",
		ttltest.MixedSuite.Checks.All(), s.IDs())
	suite.VerifyDropHints(t, "Mixed", s.IDs(), s.DropHint)
	suite.VerifyDistinctIDs(t, s.IDs())
}

// testkit: end of generated content.
// testkit:provenance ab79cd0b5d58fa3d73a45db568a9f44ee0dd6627e0dc0eceb1662fd720e21622
