// Code generated by testkit. DO NOT EDIT.
//
// Source:    corpus/iface/lang/variadic/iface.go
// Plugins:   golang 1.0.0, stub 1.4.0, backend.golang 1.0.0
// Command:   testkit run ./corpus/...

package variadictest_test

import (
	"context"
	"testing"
	"time"

	"go.thesmos.sh/testkit"
	"go.thesmos.sh/testkit/clock"
	"go.thesmos.sh/testkit/conformance/corpus/iface/lang/variadic/variadictest"
	"go.thesmos.sh/testkit/rand"
	"go.thesmos.sh/testkit/stub"
)

// finderStubFindSubject binds Find into the shape
// [stub.Behaviour] drives: how to call it, what it answers with, and how to
// override it.
//
// Each call builds a fresh double, because several of the checks assert on
// failure and need one bound to a failable TB rather than to the running
// test.
func finderStubFindSubject(tb testing.TB) stub.Subject[variadictest.FinderFindCall, variadictest.FinderFindReturn] {
	tb.Helper()
	s := variadictest.NewFinderStub(tb)
	return stub.Subject[variadictest.FinderFindCall, variadictest.FinderFindReturn]{
		Stub: s.OnFind.MethodStub,
		Call: func() {
			var a0 context.Context
			var a1 []string
			_, _ = s.Find(a0, a1...)
		},
		Result: func() variadictest.FinderFindReturn {
			var a0 context.Context
			var a1 []string
			got0, got1 := s.Find(a0, a1...)
			return variadictest.FinderFindReturn{Result: got0, Err: got1}
		},
		Override: func(mark func()) {
			s.OnFind.Func(func(_ context.Context, _ ...string) ([]string, error) {
				mark()
				var z0 []string
				var z1 error
				return z0, z1
			})
		},
		Fails: func() error {
			var a0 context.Context
			var a1 []string
			_, r1 := s.Find(a0, a1...)
			return r1
		},
	}
}

// TestFinderStubFind pins how Find answers.
//
// Recording, resetting, call-count expectations, strict mode, fault injection
// and zero-value dispatch are the same contract for every method, so they are
// asserted once in [stub.Behaviour] rather than restated here. What remains
// below needs a value this method's signature can tell apart from a zero one.
func TestFinderStubFind(t *testing.T) {
	t.Parallel()

	stub.Behaviour(t, "Find", finderStubFindSubject)

	// No check that Find answers what Returns pinned: no result of
	// its signature admits a literal this generator can write, so the only
	// value available to pin is the zero — which an unconfigured double
	// answers anyway. stub.Behaviour asserts that half honestly.
	t.Run("records what it was called with", func(t *testing.T) {
		t.Parallel()
		// Asserting only that a call happened would pass against a double
		// that recorded the wrong arguments, which is the failure a reader
		// most needs the log to surface.
		s := variadictest.NewFinderStub(t)
		var a0 context.Context
		var a1 []string
		_, _ = s.Find(a0, a1...)
		got := s.OnFind.AssertCalledOnce(t, "Find must record the call")
		testkit.Equal(t, got.Ctx, a0, "the recorded call carries Ctx")
		testkit.Equal(t, got.Keys, a1, "the recorded call carries Keys")
	})

	t.Run("fires the OnRecord hook for every call", func(t *testing.T) {
		t.Parallel()
		// The hook fires synchronously as each call lands, which is what a
		// concurrency test observes progress with — polling the log instead
		// races the thing under test.
		s := variadictest.NewFinderStub(t)
		var seen []variadictest.FinderFindCall
		s.OnFind.OnRecord(func(c variadictest.FinderFindCall) { seen = append(seen, c) })
		var a0 context.Context
		var a1 []string
		_, _ = s.Find(a0, a1...)
		_, _ = s.Find(a0, a1...)
		testkit.Len(t, seen, 2, "OnRecord must fire once per Find call")
	})

	t.Run("wires WithFinderFind at construction", func(t *testing.T) {
		t.Parallel()
		called := false
		s := variadictest.NewFinderStub(t, variadictest.WithFinderFind(func(_ context.Context, _ ...string) ([]string, error) {
			called = true
			var z0 []string
			var z1 error
			return z0, z1
		}))
		var a0 context.Context
		var a1 []string
		_, _ = s.Find(a0, a1...)
		testkit.True(t, called, "WithFinderFind must install the override")
	})

	t.Run("keeps recording across a reset", func(t *testing.T) {
		t.Parallel()
		// The weaker claim, and the honest one for this signature. No result
		// of Find admits a literal, so what Returns pinned cannot be
		// told from the zero and comparing them would pass either way.
		//
		// What a reset can still be held to is that it clears the log without
		// taking the double with it: configure, call, reset, call again, and
		// exactly one call is recorded. A reset that dropped the whole
		// configuration fails that, which is the failure the value comparison
		// was reaching for and could not state.
		s := variadictest.NewFinderStub(t)
		var want0 []string
		var want1 error
		s.OnFind.Returns(want0, want1)
		var a0 context.Context
		var a1 []string
		_, _ = s.Find(a0, a1...)
		s.ResetCalls()
		_, _ = s.Find(a0, a1...)
		s.OnFind.AssertCalledOnce(t, "Find must record the call that followed the reset")
	})
}

// finderStubFindWithLimitSubject binds FindWithLimit into the shape
// [stub.Behaviour] drives: how to call it, what it answers with, and how to
// override it.
//
// Each call builds a fresh double, because several of the checks assert on
// failure and need one bound to a failable TB rather than to the running
// test.
func finderStubFindWithLimitSubject(tb testing.TB) stub.Subject[variadictest.FinderFindWithLimitCall, variadictest.FinderFindWithLimitReturn] {
	tb.Helper()
	s := variadictest.NewFinderStub(tb)
	return stub.Subject[variadictest.FinderFindWithLimitCall, variadictest.FinderFindWithLimitReturn]{
		Stub: s.OnFindWithLimit.MethodStub,
		Call: func() {
			var a0 context.Context
			var a1 int = 42
			var a2 []string
			_, _ = s.FindWithLimit(a0, a1, a2...)
		},
		Result: func() variadictest.FinderFindWithLimitReturn {
			var a0 context.Context
			var a1 int = 42
			var a2 []string
			got0, got1 := s.FindWithLimit(a0, a1, a2...)
			return variadictest.FinderFindWithLimitReturn{Result: got0, Err: got1}
		},
		Override: func(mark func()) {
			s.OnFindWithLimit.Func(func(_ context.Context, _ int, _ ...string) ([]string, error) {
				mark()
				var z0 []string
				var z1 error
				return z0, z1
			})
		},
		Fails: func() error {
			var a0 context.Context
			var a1 int = 42
			var a2 []string
			_, r1 := s.FindWithLimit(a0, a1, a2...)
			return r1
		},
	}
}

// TestFinderStubFindWithLimit pins how FindWithLimit answers.
//
// Recording, resetting, call-count expectations, strict mode, fault injection
// and zero-value dispatch are the same contract for every method, so they are
// asserted once in [stub.Behaviour] rather than restated here. What remains
// below needs a value this method's signature can tell apart from a zero one.
func TestFinderStubFindWithLimit(t *testing.T) {
	t.Parallel()

	stub.Behaviour(t, "FindWithLimit", finderStubFindWithLimitSubject)

	// No check that FindWithLimit answers what Returns pinned: no result of
	// its signature admits a literal this generator can write, so the only
	// value available to pin is the zero — which an unconfigured double
	// answers anyway. stub.Behaviour asserts that half honestly.
	t.Run("records what it was called with", func(t *testing.T) {
		t.Parallel()
		// Asserting only that a call happened would pass against a double
		// that recorded the wrong arguments, which is the failure a reader
		// most needs the log to surface.
		s := variadictest.NewFinderStub(t)
		var a0 context.Context
		var a1 int = 42
		var a2 []string
		_, _ = s.FindWithLimit(a0, a1, a2...)
		got := s.OnFindWithLimit.AssertCalledOnce(t, "FindWithLimit must record the call")
		testkit.Equal(t, got.Ctx, a0, "the recorded call carries Ctx")
		testkit.Equal(t, got.Limit, a1, "the recorded call carries Limit")
		testkit.Equal(t, got.Keys, a2, "the recorded call carries Keys")
	})

	t.Run("fires the OnRecord hook for every call", func(t *testing.T) {
		t.Parallel()
		// The hook fires synchronously as each call lands, which is what a
		// concurrency test observes progress with — polling the log instead
		// races the thing under test.
		s := variadictest.NewFinderStub(t)
		var seen []variadictest.FinderFindWithLimitCall
		s.OnFindWithLimit.OnRecord(func(c variadictest.FinderFindWithLimitCall) { seen = append(seen, c) })
		var a0 context.Context
		var a1 int = 42
		var a2 []string
		_, _ = s.FindWithLimit(a0, a1, a2...)
		_, _ = s.FindWithLimit(a0, a1, a2...)
		testkit.Len(t, seen, 2, "OnRecord must fire once per FindWithLimit call")
	})

	t.Run("wires WithFinderFindWithLimit at construction", func(t *testing.T) {
		t.Parallel()
		called := false
		s := variadictest.NewFinderStub(t, variadictest.WithFinderFindWithLimit(func(_ context.Context, _ int, _ ...string) ([]string, error) {
			called = true
			var z0 []string
			var z1 error
			return z0, z1
		}))
		var a0 context.Context
		var a1 int = 42
		var a2 []string
		_, _ = s.FindWithLimit(a0, a1, a2...)
		testkit.True(t, called, "WithFinderFindWithLimit must install the override")
	})

	t.Run("keeps recording across a reset", func(t *testing.T) {
		t.Parallel()
		// The weaker claim, and the honest one for this signature. No result
		// of FindWithLimit admits a literal, so what Returns pinned cannot be
		// told from the zero and comparing them would pass either way.
		//
		// What a reset can still be held to is that it clears the log without
		// taking the double with it: configure, call, reset, call again, and
		// exactly one call is recorded. A reset that dropped the whole
		// configuration fails that, which is the failure the value comparison
		// was reaching for and could not state.
		s := variadictest.NewFinderStub(t)
		var want0 []string
		var want1 error
		s.OnFindWithLimit.Returns(want0, want1)
		var a0 context.Context
		var a1 int = 42
		var a2 []string
		_, _ = s.FindWithLimit(a0, a1, a2...)
		s.ResetCalls()
		_, _ = s.FindWithLimit(a0, a1, a2...)
		s.OnFindWithLimit.AssertCalledOnce(t, "FindWithLimit must record the call that followed the reset")
	})
}

// finderStubDouble describes how to build a FinderStub under each
// option whose effect is the same whatever a method's signature.
//
// Find stands in for the double as a whole: what these checks assert
// is that an option reached it at all, and the first method witnesses that as
// well as any other would.
func finderStubDouble() stub.Double[variadictest.FinderFindCall] {
	instance := func(s *variadictest.FinderStub) stub.Instance[variadictest.FinderFindCall] {
		return stub.Instance[variadictest.FinderFindCall]{
			Stub: s.OnFind.MethodStub,
			Call: func() {
				var a0 context.Context
				var a1 []string
				_, _ = s.Find(a0, a1...)
			},
			Reset: s.ResetCalls,
		}
	}
	return stub.Double[variadictest.FinderFindCall]{
		New: func(tb testing.TB) stub.Instance[variadictest.FinderFindCall] {
			return instance(variadictest.NewFinderStub(tb))
		},
		WithClock: func(tb testing.TB, clk clock.Clock) stub.Instance[variadictest.FinderFindCall] {
			return instance(variadictest.NewFinderStub(tb, variadictest.FinderStubWithClock(clk)))
		},
		WithRandSource: func(tb testing.TB, src rand.Source) stub.Instance[variadictest.FinderFindCall] {
			return instance(variadictest.NewFinderStub(tb, variadictest.FinderStubWithRandSource(src)))
		},
		BenchMode: func(tb testing.TB) stub.Instance[variadictest.FinderFindCall] {
			return instance(variadictest.NewFinderStub(tb, variadictest.FinderStubBenchMode()))
		},
		Strict: func(tb testing.TB) stub.Instance[variadictest.FinderFindCall] {
			return instance(variadictest.NewFinderStub(tb, variadictest.FinderStubStrict()))
		},
	}
}

// TestFinderStubOptions pins the settings that apply to the double rather
// than to one method: bench mode, the injected clock and random source, and
// what a reset clears.
func TestFinderStubOptions(t *testing.T) {
	t.Parallel()

	stub.DoubleBehaviour(t, finderStubDouble())
}

// TestFinderStubDelegateTo pins that a wrapped implementation is called
// through, and recorded on the way past.
//
// This is what lets one generated suite run against both the double and a
// production type, which is the point of conformance testing.
func TestFinderStubDelegateTo(t *testing.T) {
	t.Parallel()

	inner := variadictest.NewFinderStub(t)
	s := variadictest.NewFinderStub(t, variadictest.FinderStubDelegateTo(inner))

	t.Run("forwards Find to the wrapped implementation", func(t *testing.T) {
		var a0 context.Context
		var a1 []string
		_, _ = s.Find(a0, a1...)
		inner.OnFind.AssertCalledOnce(t, "Find must reach the wrapped implementation")
	})

	t.Run("surfaces what Find answered", func(t *testing.T) {
		// Reaching the wrapped implementation is not enough: a double that
		// called through and then discarded the answer would pass the check
		// above while telling its caller nothing true.
		want := testkit.TestError("Find-delegate")
		inner.OnFind.FaultsFor(time.Hour, want)
		var a0 context.Context
		var a1 []string
		_, r1 := s.Find(a0, a1...)
		testkit.ErrorIs(t, r1, want, "Find must surface the wrapped answer")
	})

	t.Run("forwards FindWithLimit to the wrapped implementation", func(t *testing.T) {
		var a0 context.Context
		var a1 int = 42
		var a2 []string
		_, _ = s.FindWithLimit(a0, a1, a2...)
		inner.OnFindWithLimit.AssertCalledOnce(t, "FindWithLimit must reach the wrapped implementation")
	})

	t.Run("surfaces what FindWithLimit answered", func(t *testing.T) {
		// Reaching the wrapped implementation is not enough: a double that
		// called through and then discarded the answer would pass the check
		// above while telling its caller nothing true.
		want := testkit.TestError("FindWithLimit-delegate")
		inner.OnFindWithLimit.FaultsFor(time.Hour, want)
		var a0 context.Context
		var a1 int = 42
		var a2 []string
		_, r1 := s.FindWithLimit(a0, a1, a2...)
		testkit.ErrorIs(t, r1, want, "FindWithLimit must surface the wrapped answer")
	})
}

// testkit: end of generated content.
// testkit:provenance 885b1d0b3364110fb04565ec4279fedc47be4ec361456cd9fad08e41fc857720
