// Code generated by testkit. DO NOT EDIT.
//
// Source:    corpus/iface/mixin/orderafter/iface.go
// Plugins:   golang 1.0.0, stub 1.4.0, backend.golang 1.0.0
// Command:   testkit run ./corpus/...

// Conformance checks worked out from the interfaces this package doubles.
//
// One call runs every check for an interface against one implementation.
// Describe the implementation in a literal and hand it over — each
// interface's own Run function is documented beside it, with the names
// to use.
//
// Nothing else is required to start. The rest is there when you need it:
// a harness field to add only when a check fails asking for it, checks of
// your own that run beside the generated ones, a Prove entry that drives
// each of yours against the broken implementation it names, and a typed
// index for dropping a check by identity rather than by string.
//
// Nothing here is written by hand. Regenerate rather than edit: an edit
// survives until the next run and no longer.
package orderaftertest

import (
	"context"
	"testing"

	"go.thesmos.sh/testkit/clock"
	"go.thesmos.sh/testkit/conformance/corpus/iface/mixin/orderafter"
	"go.thesmos.sh/testkit/rand"
	"go.thesmos.sh/testkit/stub"
)

// MixedCommitCall records one invocation of Mixed.Commit.
//
// Fields take their names from the source signature — parameters and named
// returns alike — so a failure message names what the author named. A slot
// the source left unnamed or blank falls back to a positional name.
type MixedCommitCall struct {
	Ctx context.Context
	Err error
}

// MixedPrepareCall records one invocation of Mixed.Prepare.
//
// Fields take their names from the source signature — parameters and named
// returns alike — so a failure message names what the author named. A slot
// the source left unnamed or blank falls back to a positional name.
type MixedPrepareCall struct {
	Ctx context.Context
	Err error
}

// --- Per-method configuration ---

// MixedCommitStub controls how the double answers Commit and records
// what it was asked.
//
// The embedded MethodStub supplies the machinery every method shares: call
// recording, fault injection, latency against a virtual clock, gates,
// call-count expectations, and strict mode.
type MixedCommitStub struct {
	*stub.MethodStub[MixedCommitCall]

	fn       func(context.Context) error
	fallback *MixedCommitReturn
}

// MixedCommitReturn holds the fixed answer configured through Returns.
type MixedCommitReturn struct {
	Err error
}

// Returns pins a fixed result for every call to Commit. A Func
// override and an injected fault both take precedence over it.
func (s *MixedCommitStub) Returns(err error) *MixedCommitStub {
	s.fallback = &MixedCommitReturn{Err: err}
	return s
}

// Func supplies a body for Commit, for when the answer depends on the
// arguments. An injected fault still takes precedence.
func (s *MixedCommitStub) Func(fn func(context.Context) error) *MixedCommitStub {
	s.fn = fn
	return s
}

// MixedPrepareStub controls how the double answers Prepare and records
// what it was asked.
//
// The embedded MethodStub supplies the machinery every method shares: call
// recording, fault injection, latency against a virtual clock, gates,
// call-count expectations, and strict mode.
type MixedPrepareStub struct {
	*stub.MethodStub[MixedPrepareCall]

	fn       func(context.Context) error
	fallback *MixedPrepareReturn
}

// MixedPrepareReturn holds the fixed answer configured through Returns.
type MixedPrepareReturn struct {
	Err error
}

// Returns pins a fixed result for every call to Prepare. A Func
// override and an injected fault both take precedence over it.
func (s *MixedPrepareStub) Returns(err error) *MixedPrepareStub {
	s.fallback = &MixedPrepareReturn{Err: err}
	return s
}

// Func supplies a body for Prepare, for when the answer depends on the
// arguments. An injected fault still takes precedence.
func (s *MixedPrepareStub) Func(fn func(context.Context) error) *MixedPrepareStub {
	s.fn = fn
	return s
}

// --- MixedStub ---

// The double-runtime witness for the surface this double rides. A
// breaking change to the runtime renames it, and this file stops
// compiling with the skew named.
var _ = stub.CompatV1

// MixedStubOption configures a [MixedStub] at construction time.
type MixedStubOption func(*MixedStub)

// MixedStubStrict makes an unconfigured method fail the test rather than
// return its zero value, which turns a call nobody planned for into a failure
// at the call site instead of a puzzling zero further downstream.
func MixedStubStrict() MixedStubOption {
	return func(s *MixedStub) { s.strict = true }
}

// MixedStubDelegateTo wraps a real implementation: every method forwards to
// impl and is recorded on the double on the way through.
//
// This is what lets one generated suite run against both the double and the
// production type, which is the point of conformance testing.
func MixedStubDelegateTo(impl orderafter.Mixed) MixedStubOption {
	return func(s *MixedStub) {
		s.OnCommit.Func(impl.Commit)
		s.OnPrepare.Func(impl.Prepare)
	}
}

// MixedStubWithClock drives latency and time-windowed faults from clk
// rather than from wall time, so a test asserting on a five-second timeout
// does not take five seconds.
func MixedStubWithClock(clk clock.Clock) MixedStubOption {
	return func(s *MixedStub) { s.group.SetClock(clk) }
}

// MixedStubWithRandSource makes probabilistic fault injection reproducible.
// A failure nobody can replay is not a finding.
func MixedStubWithRandSource(src rand.Source) MixedStubOption {
	return func(s *MixedStub) { s.group.SetRandSource(src) }
}

// MixedStubBenchMode disables call recording. Dispatch still works; only
// the accumulating call log is dropped, because its allocations are what a
// benchmark would otherwise be measuring.
func MixedStubBenchMode() MixedStubOption {
	return func(s *MixedStub) { s.group.BenchMode() }
}

// WithMixedCommit sets Commit's body at construction
// time, for the common case of configuring one method and taking the
// defaults for the rest.
func WithMixedCommit(fn func(context.Context) error) MixedStubOption {
	return func(s *MixedStub) { s.OnCommit.Func(fn) }
}

// WithMixedPrepare sets Prepare's body at construction
// time, for the common case of configuring one method and taking the
// defaults for the rest.
func WithMixedPrepare(fn func(context.Context) error) MixedStubOption {
	return func(s *MixedStub) { s.OnPrepare.Func(fn) }
}

// MixedStub is a recording test double for Mixed.
//
// Each On<Method> field is that method's configuration point. Left alone, a
// method returns its zero value and records the call.
type MixedStub struct {
	OnCommit  *MixedCommitStub
	OnPrepare *MixedPrepareStub

	// group is every method stub above, viewed through the surface that
	// does not depend on a signature — one home for the settings and the
	// lifecycle that apply to the whole double.
	group *stub.Group

	order  *stub.OrderTracker
	strict bool
}

// Compile-time proof that MixedStub satisfies Mixed.
//
// It lives here rather than in the companion so a drifted signature fails
// `go build` rather than waiting for a test run — the double is unusable the
// moment it stops satisfying the interface, and that is worth learning at the
// earliest point it can be known.
var _ orderafter.Mixed = (*MixedStub)(nil)

// NewMixedStub returns a double bound to tb.
//
// Passing tb registers a cleanup that verifies every method's call-count
// expectations when the test ends, so an unmet Times is reported without the
// caller remembering to check. A nil tb skips that, which is what benchmarks
// and non-test callers want.
func NewMixedStub(tb testing.TB, opts ...MixedStubOption) *MixedStub {
	s := &MixedStub{
		OnCommit:  &MixedCommitStub{MethodStub: stub.NewMethodStub[MixedCommitCall](tb, "Mixed.Commit")},
		OnPrepare: &MixedPrepareStub{MethodStub: stub.NewMethodStub[MixedPrepareCall](tb, "Mixed.Prepare")},
	}
	s.group = stub.NewGroup(
		s.OnCommit.MethodStub,
		s.OnPrepare.MethodStub,
	)
	for _, opt := range opts {
		opt(s)
	}
	if s.strict {
		s.group.StrictAll()
	}
	// Allocated after the options run: the tracker only fails the test in
	// strict mode, so it has to be told which mode it is in.
	s.order = stub.NewOrderTracker(tb, s.strict)
	s.group.Bind(tb)
	return s
}

// ResetCalls clears recorded calls, fault counters, and call-count
// expectations. Func and Returns configuration is deliberately preserved, so
// a test can reuse one double across phases without rebuilding it.
func (s *MixedStub) ResetCalls() {
	s.group.Reset()
	s.order.Reset()
}

// --- Interface methods ---

// invoke adapts the Func override to the shape [stub.Answer] consumes, or
// returns nil when no override is set — which is how Answer tells "no
// override" from "an override that returns zero".
func (s *MixedCommitStub) invoke(ctx context.Context) func() MixedCommitReturn {
	if s.fn == nil {
		return nil
	}
	return func() MixedCommitReturn {
		r0 := s.fn(ctx)
		return MixedCommitReturn{Err: r0}
	}
}

// Commit records the call and answers it.
//
// Which arm answers — injected fault, Func override, Returns fallback, or the
// zero value — is [stub.Answer]'s to decide, so every generated double
// resolves a call the same way and the ordering is tested once rather than
// restated per method.
func (s *MixedStub) Commit(ctx context.Context) error {
	s.order.AssertAfter("Commit", "Prepare")
	defer s.order.Record("Commit")
	call := MixedCommitCall{Ctx: ctx}
	r := stub.Answer(s.OnCommit.MethodStub, &call, stub.Arms[MixedCommitCall, MixedCommitReturn]{
		Invoke:   s.OnCommit.invoke(ctx),
		Fallback: s.OnCommit.fallback,
		Fault:    func(err error) MixedCommitReturn { return MixedCommitReturn{Err: err} },
		Stamp: func(c *MixedCommitCall, r MixedCommitReturn) {
			c.Err = r.Err
		},
	})
	return r.Err
}

// invoke adapts the Func override to the shape [stub.Answer] consumes, or
// returns nil when no override is set — which is how Answer tells "no
// override" from "an override that returns zero".
func (s *MixedPrepareStub) invoke(ctx context.Context) func() MixedPrepareReturn {
	if s.fn == nil {
		return nil
	}
	return func() MixedPrepareReturn {
		r0 := s.fn(ctx)
		return MixedPrepareReturn{Err: r0}
	}
}

// Prepare records the call and answers it.
//
// Which arm answers — injected fault, Func override, Returns fallback, or the
// zero value — is [stub.Answer]'s to decide, so every generated double
// resolves a call the same way and the ordering is tested once rather than
// restated per method.
func (s *MixedStub) Prepare(ctx context.Context) error {
	defer s.order.Record("Prepare")
	call := MixedPrepareCall{Ctx: ctx}
	r := stub.Answer(s.OnPrepare.MethodStub, &call, stub.Arms[MixedPrepareCall, MixedPrepareReturn]{
		Invoke:   s.OnPrepare.invoke(ctx),
		Fallback: s.OnPrepare.fallback,
		Fault:    func(err error) MixedPrepareReturn { return MixedPrepareReturn{Err: err} },
		Stamp: func(c *MixedPrepareCall, r MixedPrepareReturn) {
			c.Err = r.Err
		},
	})
	return r.Err
}

// testkit: end of generated content.
// testkit:provenance ab02b66fa75680ec041da93b60f04ba1f378494479dba1423d76963f2e6cf101
