// Code generated by testkit. DO NOT EDIT.
//
// Source:    corpus/iface/mixin/orderafter/iface.go
// Plugins:   golang 1.0.0, suite 1.19.0, backend.golang 1.0.0
// Command:   testkit run ./corpus/...

package orderaftertest

import (
	"context"
	"errors"
	"fmt"
	"testing"

	"go.thesmos.sh/testkit/conformance/corpus/iface/mixin/orderafter"
	"go.thesmos.sh/testkit/engine/legs"
	"go.thesmos.sh/testkit/engine/model"
	"go.thesmos.sh/testkit/engine/model/action"
	"go.thesmos.sh/testkit/engine/model/law"
	"go.thesmos.sh/testkit/engine/suite"
	"go.thesmos.sh/testkit/engine/suite/prove"
)

// Conformance checks for Mixed, worked out from its declaration.
//
// One call runs all of them against one implementation. Describe the
// implementation in a literal and hand it over:
//
//	func TestMine(t *testing.T) {
//		RunMixed(t, MixedHarness[*Mine]{Name: "mine", New: NewMine})
//	}
//
// Nothing else is required to start. The rest is here when you need it:
//
//	MixedHarness
//	    one implementation under test. Add a field only when a check
//	    fails asking for it — the failure names the field to fill in.
//	MixedChecks
//	    checks you write yourself, for the claims only you can make.
//	    They run beside the generated ones and are the same kind of value.
//	ProveMixed
//	    runs each of your checks against the broken implementation it
//	    names, and fails if the check does not catch it.
//	MixedSuite.Checks.<Method>.<Check>()
//	    names one check, so you can drop it. Written this way it stops
//	    compiling if a later regeneration no longer emits that check,
//	    rather than silently dropping nothing.
//
// The checks this file runs:
//
//	Commit/cancel
//	Commit/nilcontext
//	Commit/orderafter
//	Commit/smoke
//	Prepare/cancel
//	Prepare/nilcontext
//	Prepare/smoke
//
// A version check, performed by the compiler. If this file was generated
// against a testkit whose check format differs from the one you are
// building with, this line fails to compile and names the mismatch —
// instead of the two disagreeing quietly while the tests still pass.
// Regenerate the file to clear it.
var _ = suite.CompatV2

// MixedFixture holds the sample inputs the checks call your
// implementation with, worked out from each method's parameter types.
//
// Every input comes as a pair: a value, and a second one guaranteed to
// differ from it. Both are needed for a check to mean anything — looking
// up a key that was just stored proves nothing on its own unless there
// is also a key that was never stored.
//
// A parameter whose type has no value that can be written down — a func,
// a channel, a type your declaration does not import — is left at its
// zero value, and the checks that needed it were not emitted at all
// rather than run against something meaningless. Those are listed above.
// A check you write yourself is handed this either way.
type MixedFixture struct {
}

// DefaultMixedFixture is what a run with no config draws.
func DefaultMixedFixture() MixedFixture {
	return mixedNewFixture()
}

// mixedNewFixture builds the sample inputs for one run.
//
// Read these through the methods below rather than as fields. A value you
// supplied through the config and one worked out from the type are read
// the same way, and no check should be able to tell them apart.
func mixedNewFixture() MixedFixture {
	return MixedFixture{}
}

// Mixed is your interface, under a local name.
//
// An alias, so it is the same type — this is here only so the rest of
// this file can refer to it without repeating its import path, and so a
// check you write can name it too.
type Mixed = orderafter.Mixed

// MixedSubject is what a RunWith check receives instead of a single
// instance: a handle that can build more of them.
//
// Use it for a claim one instance cannot state on its own — that two
// instances do not share state, that a value survives being closed and
// reopened.
type MixedSubject = suite.Subject[Mixed]

// MixedRunOpt is anything you can pass to RunMixed: an
// implementation to test, a table of your own checks, a config, or a
// check to drop. Order does not matter.
type MixedRunOpt interface {
	applyTo(*mixedRunConfig)
}

type mixedRunConfig struct {
	suite.Bundle[Mixed]

	// rows are the checks you wrote, held until every argument has been
	// read and then tied to this run's inputs. Tying them on arrival
	// would bind them to inputs a later argument replaces.
	rows MixedChecks
}

// MixedHarness describes one Mixed implementation to test.
//
// Name and one constructor are all that is required. Every other field
// unlocks the checks that need it, and you do not have to work out which
// in advance: run it, and any check that needs more fails saying which
// field to add.
type MixedHarness[T Mixed] struct {
	Name string

	// Set exactly one.
	//
	// Use New if construction cannot fail; use Start if it needs the
	// test's lifetime — a temp directory to clean up, a connection to
	// close. Start is handed the testing.TB to register that on.
	New   func() T
	Start func(tb testing.TB) T

	// Excuse lists checks this implementation cannot meaningfully take —
	// not ones it fails, ones it has no way to answer. An in-memory
	// implementation has no storage to survive a restart, so a check
	// about restarting it is asking the impossible.
	//
	// Excused checks are reported as excused, never as passed.
	Excuse []suite.ID

	// Oracle marks this implementation as the one others are compared
	// against, when you are testing more than one. At most one may set it.
	// Pick the implementation you trust most.
	Oracle bool

	// Serial runs this implementation's checks one at a time, and never
	// alongside another implementation's. Set it for something that
	// cannot take being constructed many times at once — a real database,
	// a fixed port.
	Serial bool

	// Provide supplies anything a check needs that has no field of its
	// own above. You will not need it unless a check fails asking for a
	// named capability, and that failure tells you the name to use here.
	Provide map[suite.Capability]any
}

// Subject converts this description into the form the runner uses, and
// reports anything wrong with it — no constructor, or two.
func (h MixedHarness[T]) Subject() (suite.Subject[Mixed], error) {
	build, err := suite.OneCtor(h.Name, h.New, h.Start)
	if err != nil {
		return suite.Subject[Mixed]{}, err
	}
	return suite.Subject[Mixed]{
		Name:     h.Name,
		Provides: h.Provide,
		New:      func(tb testing.TB) Mixed { return build(tb) },
		Oracle:   h.Oracle,
		Serial:   h.Serial,
		Excused:  suite.ExcuseSet(h.Excuse),
	}, nil
}

func (h MixedHarness[T]) applyTo(rc *mixedRunConfig) {
	rc.AddSubject(h.Subject())
}

type mixedDropOpt []suite.ID

func (d mixedDropOpt) applyTo(rc *mixedRunConfig) {
	rc.AddDrops(d...)
}

// mixedWithout drops the named checks from the run.
func mixedWithout(ids ...suite.ID) MixedRunOpt {
	return mixedDropOpt(ids)
}

// --- Naming checks ----------------------------------------------------------

// MixedSuite is how you name a check — to drop it, or to
// point at it from a tool.
var MixedSuite = mixedVeneer{Checks: mixedCheckIndex}

type mixedVeneer struct {
	// Checks names every check this file runs, by method:
	//
	//	MixedSuite.Checks.<Method>.<Check>()
	//
	// Prefer this over writing the check's name as a string. If a later
	// regeneration stops emitting that check, this stops compiling —
	// where the string would silently drop nothing.
	Checks mixedCheckIndexT
}

// Without drops the named checks from the run.
//
//	RunMixed(t, mine, MixedSuite.Without(
//		MixedSuite.Checks.Commit.Smoke()))
//
// Dropping is recorded in the run's report, so a check you removed is
// visible rather than simply absent.
func (mixedVeneer) Without(ids ...suite.ID) MixedRunOpt {
	return mixedWithout(ids...)
}

// Suite returns the checks as plain data, if you are building a tool over
// them or running them yourself.
//
// RunMixed is the normal way in; this is for when you need the
// checks as values rather than as a run.
func (mixedVeneer) Suite() suite.Suite[Mixed] {
	return mixedSuite()
}

// --- Failure messages -------------------------------------------------------

// mixedIndexPath maps each check to the expression you would
// write to drop it, so that a check which cannot run tells you what to
// type rather than only what went wrong.
var mixedIndexPath = map[suite.ID]string{
	mixedCheckIndex.Commit.Smoke():       "MixedSuite.Checks.Commit.Smoke()",
	mixedCheckIndex.Commit.Cancels():     "MixedSuite.Checks.Commit.Cancels()",
	mixedCheckIndex.Commit.NilContext():  "MixedSuite.Checks.Commit.NilContext()",
	mixedCheckIndex.Commit.Orderafter():  "MixedSuite.Checks.Commit.Orderafter()",
	mixedCheckIndex.Prepare.Smoke():      "MixedSuite.Checks.Prepare.Smoke()",
	mixedCheckIndex.Prepare.Cancels():    "MixedSuite.Checks.Prepare.Cancels()",
	mixedCheckIndex.Prepare.NilContext(): "MixedSuite.Checks.Prepare.NilContext()",
	mixedCheckIndex.Model.Laws():         "MixedSuite.Checks.Model.Laws()",
}

var mixedDropHint = suite.DropHinter(
	"MixedSuite", mixedIndexPath,
)

// The names this file uses in more than one place, declared once each so
// they cannot drift apart.
const (
	mixedCommit  = "Commit"
	mixedPrepare = "Prepare"

	// The interface's word inside a family-scoped identity.
	mixedQualifier = "mixed"
)

// mixedCheckIndex names every check in this file, grouped by method.
// Reach it through MixedSuite.Checks.
var mixedCheckIndex = mixedCheckIndexT{
	Commit:  mixedCommitChecks{},
	Prepare: mixedPrepareChecks{},
	Model:   mixedModelChecks{},
}

type mixedCheckIndexT struct {
	Commit  mixedCommitChecks
	Prepare mixedPrepareChecks
	Model   mixedModelChecks
}

// All returns every ID this package emits.
func (mixedCheckIndexT) All() []suite.ID {
	var out []suite.ID
	out = append(out, mixedCommitChecks{}.All()...)
	out = append(out, mixedPrepareChecks{}.All()...)
	out = append(out, mixedModelChecks{}.All()...)
	return out
}

type mixedCommitChecks struct{}

func (mixedCommitChecks) Smoke() suite.ID {
	return suite.MethodID(mixedCommit, suite.SegSmoke)
}

func (mixedCommitChecks) Cancels() suite.ID {
	return suite.MethodID(mixedCommit, suite.SegCancel)
}

func (mixedCommitChecks) NilContext() suite.ID {
	return suite.MethodID(mixedCommit, suite.SegNilContext)
}

func (mixedCommitChecks) Orderafter() suite.ID {
	return suite.MethodID(mixedCommit, suite.SegOrderAfter)
}

func (mixedCommitChecks) All() []suite.ID {
	return []suite.ID{
		mixedCommitChecks{}.Smoke(),
		mixedCommitChecks{}.Cancels(),
		mixedCommitChecks{}.NilContext(),
		mixedCommitChecks{}.Orderafter(),
	}
}

type mixedPrepareChecks struct{}

func (mixedPrepareChecks) Smoke() suite.ID {
	return suite.MethodID(mixedPrepare, suite.SegSmoke)
}

func (mixedPrepareChecks) Cancels() suite.ID {
	return suite.MethodID(mixedPrepare, suite.SegCancel)
}

func (mixedPrepareChecks) NilContext() suite.ID {
	return suite.MethodID(mixedPrepare, suite.SegNilContext)
}

func (mixedPrepareChecks) All() []suite.ID {
	return []suite.ID{
		mixedPrepareChecks{}.Smoke(),
		mixedPrepareChecks{}.Cancels(),
		mixedPrepareChecks{}.NilContext(),
	}
}

type mixedModelChecks struct{}

func (mixedModelChecks) Laws() suite.ID {
	return suite.FamilyID(suite.FamilyModel, mixedQualifier, suite.SegLaws)
}

func (mixedModelChecks) All() []suite.ID {
	return []suite.ID{
		mixedModelChecks{}.Laws(),
	}
}

// mixedSuite returns the checks as data, using the given inputs.
//
// It takes the built inputs rather than a config, because that is what
// the checks read. To start from the defaults, pass what a default run
// passes — MixedSuite.Suite does exactly that.
func mixedSuite() suite.Suite[Mixed] {
	return suite.Suite[Mixed]{
		Name:     "Mixed",
		DropHint: mixedDropHint,
		Checks: append(mixedSignatureChecks(),
			mixedModelRows()...),
	}
}

// mixedSignatureChecks builds every check in this file.
//
// A check is marked as proven able to fail only when a deliberately
// broken implementation for it exists in the file beside this one.
// Where none could be built, the check says so instead — claiming proof
// without the evidence is refused, in both directions.
func mixedSignatureChecks() []suite.Check[Mixed] {
	sig := suite.ProvenCheck[Mixed]
	ix := mixedCheckIndex
	return []suite.Check[Mixed]{
		sig(ix.Commit.Smoke(), suite.ClassSmoke,
			"Commit survives a call",
			func(tb testing.TB, m Mixed) {
				mixedAssertCommitSmoke(tb, m)
			}).At(suite.StrengthErrorOnly),
		sig(ix.Commit.Cancels(), suite.ClassCancel,
			"Commit reports a cancelled context as cancelled",
			func(tb testing.TB, m Mixed) {
				mixedAssertCommitCancels(tb, m)
			}).At(suite.StrengthErrorOnly),
		sig(ix.Commit.NilContext(), suite.ClassNilContext,
			"Commit returns an error rather than panicking on a nil context",
			func(tb testing.TB, m Mixed) {
				mixedAssertCommitToleratesNilContext(tb, m)
			}).At(suite.StrengthErrorOnly),
		sig(ix.Prepare.Smoke(), suite.ClassSmoke,
			"Prepare survives a call",
			func(tb testing.TB, m Mixed) {
				mixedAssertPrepareSmoke(tb, m)
			}).At(suite.StrengthErrorOnly),
		sig(ix.Prepare.Cancels(), suite.ClassCancel,
			"Prepare reports a cancelled context as cancelled",
			func(tb testing.TB, m Mixed) {
				mixedAssertPrepareCancels(tb, m)
			}).At(suite.StrengthErrorOnly),
		sig(ix.Prepare.NilContext(), suite.ClassNilContext,
			"Prepare returns an error rather than panicking on a nil context",
			func(tb testing.TB, m Mixed) {
				mixedAssertPrepareToleratesNilContext(tb, m)
			}).At(suite.StrengthErrorOnly),
		sig(ix.Commit.Orderafter(), suite.ClassOrderAfter,
			"Commit reports ErrNotReady until Prepare has run",
			func(tb testing.TB, m Mixed) {
				mixedAssertCommitOrderafter(tb, m)
			}).At(suite.StrengthErrorOnly),
	}
}

// mixedAssertCommitSmoke asserts Commit survives a call.
func mixedAssertCommitSmoke(
	tb testing.TB,
	m Mixed,
) {
	tb.Helper()
	suite.Survives(tb, mixedCommit, func(ctx context.Context) {
		_ = m.Commit(ctx)
	})
}

// mixedAssertCommitCancels asserts Commit reports a cancelled context as cancelled.
func mixedAssertCommitCancels(
	tb testing.TB,
	m Mixed,
) {
	tb.Helper()
	suite.ReportsCancelled(tb, mixedCommit, func(ctx context.Context) error {
		return m.Commit(ctx)
	})
}

// mixedAssertCommitToleratesNilContext asserts Commit returns an error rather than panicking on a nil context.
func mixedAssertCommitToleratesNilContext(
	tb testing.TB,
	m Mixed,
) {
	tb.Helper()
	suite.ToleratesNilContext(tb, mixedCommit, func(ctx context.Context) error {
		return m.Commit(ctx)
	})
}

// mixedAssertPrepareSmoke asserts Prepare survives a call.
func mixedAssertPrepareSmoke(
	tb testing.TB,
	m Mixed,
) {
	tb.Helper()
	suite.Survives(tb, mixedPrepare, func(ctx context.Context) {
		_ = m.Prepare(ctx)
	})
}

// mixedAssertPrepareCancels asserts Prepare reports a cancelled context as cancelled.
func mixedAssertPrepareCancels(
	tb testing.TB,
	m Mixed,
) {
	tb.Helper()
	suite.ReportsCancelled(tb, mixedPrepare, func(ctx context.Context) error {
		return m.Prepare(ctx)
	})
}

// mixedAssertPrepareToleratesNilContext asserts Prepare returns an error rather than panicking on a nil context.
func mixedAssertPrepareToleratesNilContext(
	tb testing.TB,
	m Mixed,
) {
	tb.Helper()
	suite.ToleratesNilContext(tb, mixedPrepare, func(ctx context.Context) error {
		return m.Prepare(ctx)
	})
}

// mixedAssertCommitOrderafter asserts Commit reports ErrNotReady until Prepare has run.
func mixedAssertCommitOrderafter(
	tb testing.TB,
	m Mixed,
) {
	tb.Helper()
	ctx := tb.Context()
	err := m.Commit(ctx)
	if !errors.Is(err, orderafter.ErrNotReady) {
		tb.Errorf("Commit must report %v: got %v", orderafter.ErrNotReady, err)
	}
}

// MixedDefect is a deliberately broken implementation, used as
// evidence that a check can fail. In practice you build one with
// BrokenMixed over the generated test double.
type MixedDefect interface {
	Subject() (MixedSubject, error)
}

// BrokenMixed describes an implementation built to break one
// specific claim, so that a check can be shown to catch it.
//
// Give it a name saying what is wrong, and a constructor. The best
// broken implementation is the generated double wrapping a correct one,
// with a single method overridden — correct everywhere except the one
// place the check is about.
func BrokenMixed[T Mixed](
	name string, build func() T,
) MixedHarness[T] {
	return MixedHarness[T]{
		Name: name, New: build,
	}
}

// MixedChecks is a table of checks you write yourself, for the
// claims that cannot be worked out from the declaration — the ones that
// carry your domain.
//
// They are the same kind of value as the generated checks: they appear
// in the report, they can be dropped by name, and they can say what they
// need from an implementation. There is no second mechanism for them.
//
//	var myChecks = MixedChecks{
//		{Method: "Commit", Name: "my-claim",
//			Claim:    "a sentence stating exactly what this check proves",
//			Run:      myClaimBody,
//			ProvenBy: BrokenMixed("an implementation that breaks it", newBroken)},
//	}
type MixedChecks []MixedCheck

func (c MixedChecks) applyTo(rc *mixedRunConfig) {
	rc.rows = append(rc.rows, c...)
}

// MixedCheck is one check you wrote. The body is a plain named
// function; which field you put it in decides what it is handed.
type MixedCheck struct {
	// Method groups this check under one of your methods, so it is named
	// Commit/<Name> in output and reruns with the rest of that
	// method's checks. Leave it empty for a check that is not about one
	// method in particular.
	Method string

	// Name identifies this check, in output and when dropping it. Keep it
	// stable: it is what a colleague's Without call refers to.
	Name string

	// Claim is one sentence saying exactly what this check proves. It is
	// recorded in the manifest and read out in the report.
	//
	// Write only what the body actually establishes. "a second write
	// leaves the value unchanged" is a promise that something reads the
	// value back; if the body only checks the write returned no error,
	// say that instead. Nothing here can catch a claim that is wider
	// than its check, and a claim nobody verifies is worse than none.
	Claim string

	// Set exactly one.
	//
	// Run is handed one fresh instance, which suits nearly every check.
	// RunWith is handed something that can build instances, for a claim
	// one instance cannot state on its own: build two and compare them,
	// move the clock forward, put one into a failure state.
	//
	// Both are also handed the sample inputs, so a check you write draws
	// from the same values the generated ones do — override an input and
	// your check sees the override too.
	Run     func(tb testing.TB, s Mixed, fx MixedFixture)
	RunWith func(tb testing.TB, sub MixedSubject, fx MixedFixture)

	// Class groups this check in the report's summary. Optional; checks
	// you write are grouped as hand-written by default.
	Class suite.Class

	// Needs says what this check requires from an implementation beyond
	// being constructed — a clock it can move, a failure it can induce.
	//
	// An implementation that cannot supply it fails this check by name,
	// with the field to fill in named in the message. It never skips: a
	// check that quietly skipped for want of wiring would look exactly
	// like one that passed.
	Needs suite.Caps

	// ProvenBy is an implementation built to break this check and nothing
	// else. Setting it makes two statements at once — that the check can
	// fail, and here is the proof — and ProveMixed fails unless the
	// broken implementation really does turn this check red.
	//
	// ProvenReason, if set, is text the failure must contain. Use it so
	// that a broken implementation which fails for some unrelated reason
	// stops counting as evidence.
	//
	// Argued is for when no such implementation can be built: record why,
	// in a sentence. Set at most one of the two. Setting neither is
	// allowed and the report says so — the check is unproven, which is
	// honest, and different from proven.
	ProvenBy     MixedDefect
	ProvenReason string
	Argued       string
}

// mixedMethods is the interface's method names, used to catch a typo in
// a check's Method field before the run starts.
//
// Without it a misspelled name would be accepted — it looks like any
// other method name — and the check would be filed under a method that
// does not exist, where nobody could find or drop it.
var mixedMethods = suite.NewNameSet("Mixed", mixedCommit, mixedPrepare)

// bind converts one of your checks into the form the runner uses, tying
// it to this run's sample inputs — which is what lets a check you wrote
// see the same values, and the same overrides, as the generated ones.
func (c MixedCheck) bind(
	fx MixedFixture,
) (suite.Check[Mixed], error) {
	out := suite.Check[Mixed]{
		Claim: c.Claim, Class: c.Class, Needs: c.Needs,
	}
	if out.Class == "" {
		out.Class = suite.ClassHandWritten
	}

	var err error
	bodies := 0
	if c.Run != nil {
		bodies++
		if out.ID, err = suite.RowID("Run", c.Method, c.Name, mixedMethods); err != nil {
			return out, err
		}
		run := c.Run
		out.Run = func(tb testing.TB, s Mixed) {
			run(tb, s, fx)
		}
	}
	if c.RunWith != nil {
		bodies++
		out.ID = suite.HandRowID(c.Name)
		rw := c.RunWith
		out.RunWith = func(tb testing.TB, sub MixedSubject) {
			rw(tb, sub, fx)
		}
	}
	if err := suite.OneBody(c.Name, bodies, "Run, RunWith"); err != nil {
		return out, err
	}
	if c.Method != "" && c.Run == nil {
		return out, fmt.Errorf(
			"check %q sets Method, but its body fixes its own scope; drop Method", c.Name)
	}
	if out.Falsifiable, err = suite.Falsify(c.Name, c.ProvenBy != nil, c.Argued); err != nil {
		return out, err
	}
	return out, nil
}

// RunMixed runs every check — the generated ones and any you
// wrote — against every implementation you pass it.
//
// Each argument describes one thing to do, in any order: an
// implementation to test, a table of your own checks, sample inputs to
// use, or checks to leave out.
//
//	RunMixed(t,
//		MixedHarness[*InMemory]{Name: "in-memory", New: NewInMemory},
//		MixedSuite.Without(MixedSuite.Checks.Commit.Smoke()),
//	)
//
// Pass two implementations to compare them against each other, and mark
// the one you trust as the Oracle. Every check runs as its own subtest
// named after the implementation and the check, so `go test -run` can
// select one.
//
// A check that needs something your implementation has not supplied
// fails rather than skipping, and says which field to fill in. That is
// deliberate: a skipped check is how a claim goes unchecked while the
// run stays green.
func RunMixed(
	t *testing.T, opts ...MixedRunOpt,
) {
	t.Helper()
	var rc mixedRunConfig
	for _, o := range opts {
		o.applyTo(&rc)
	}
	fx := mixedNewFixture()
	for _, row := range rc.rows {
		rc.AddCheck(row.bind(fx))
	}
	// Checked here, after reading every argument and before running
	// anything: a misconfigured run reports all of its problems at once
	// rather than one per attempt.
	rc.Fail(t, "RunMixed")
	suite.Run(t,
		mixedSuite().With(rc.Extra...).Without(rc.Drops...),
		rc.Subjects...)
}

// ProveMixed runs each of your checks against the deliberately
// broken implementation it names, and fails if the check does not catch
// it.
//
//	func TestMyChecksCanFail(t *testing.T) { ProveMixed(t, myChecks) }
//
// A check that always passes is indistinguishable from a working one
// until something breaks in production. This is what tells them apart:
// give each check a ProvenBy, and this proves the check can fail.
//
// A check with no ProvenBy is not ignored — it has to say why, in
// Argued. The two are held level in both directions: claiming proof
// without a broken implementation fails here, and supplying one for a
// check that claims nothing fails too.
func ProveMixed(
	t *testing.T, checks MixedChecks,
) {
	t.Helper()
	// The RUN's config, not the derived one: a check proven at default
	// pools carries no evidence about the pools a run actually uses.
	fx := mixedNewFixture()
	bound := make([]suite.Check[Mixed], 0, len(checks))
	defects := prove.Defects[Mixed]{}
	for _, row := range checks {
		bd, err := row.bind(fx)
		if err != nil {
			t.Fatalf("ProveMixed: %v", err)
		}
		bound = append(bound, bd)
		if row.ProvenBy == nil {
			continue
		}
		sub, err := row.ProvenBy.Subject()
		if err != nil {
			t.Fatalf("ProveMixed: check %q: defect: %v", bd.ID, err)
		}
		defects[bd.ID] = prove.Defect[Mixed]{
			Subject: sub, Reason: row.ProvenReason,
		}
	}
	prove.All(t, bound, defects)
}

// mixedModelRows is what this package's model tier claims.
//
// Every row here needs sequences of calls judged against something
// outside the subject, which is what separates them from the rows
// above: those settle a claim with a fixed call sequence, and these
// cannot be stated that way at all. That is also why each takes the
// Subject rather than an instance — a sequence run builds its own, and
// some of them build two.
func mixedModelRows() []suite.Check[Mixed] {
	return []suite.Check[Mixed]{
		{
			ID:          mixedCheckIndex.Model.Laws(),
			Class:       suite.ClassLaws,
			Claim:       "every bound law holds over random operation sequences",
			Falsifiable: suite.Argued("no defect is planted for it: the proofs beside this file break one method at a time, and a claim about sequences needs a subject that is wrong over a history"),
			Strength:    suite.StrengthDifferential,
			RunWith: func(tb testing.TB, sub suite.Subject[Mixed]) {
				mixedAssertLaws(tb, sub)
			},
		},
	}
}

// --- Mixed's model tier -------------------------------------------
//
// Random sequences of Mixed's methods, run against every subject and
// something that judges them from outside. The rows on the run surface
// above carry it, and MixedSuite.Without declines any of them by name.
//
//	Reference: the subject's own factory — no reader/writer pair derives a store,
//	           so a second instance driven identically stands in: twins must
//	           agree, which catches nondeterminism and hidden shared state but
//	           not a subject wrong the same way twice; ref= raises the floor
//	Sequences: Commit (lifecycle)
//	Laws:      AUTO-LIFECYCLE-RESPECTS-CONTEXT
//	Not driven:
//	           Prepare — the orderafter.fn partner — an ordering constraint, not an operation to drive at random
//
// mixedModelActions is the operation vocabulary both legs drive.
//
// One constructor per method shape, from the engine's action set rather
// than hand-written closures: the constructors record inputs and outputs
// into the trace a law reads, compare the two sides the same way for every
// action, and shrink a failing sequence to the shortest one that still
// fails.
func mixedModelActions() []model.Action[Mixed] {
	return []model.Action[Mixed]{
		action.Lifecycle("Commit",
			func(ctx context.Context, s orderafter.Mixed) error {
				return s.Commit(ctx)
			}),
	}
}

// mixedModelLaws is the laws the classifications earned and this build
// could fill.
//
// Observational, every one of them: a law never mutates, so running them
// inside the sequences is safe for every step that follows. What they
// judge is the subject's own behaviour, which is why they are a separate
// leg from the reference comparison rather than more oracles on it.
func mixedModelLaws() []law.Law[Mixed] {
	return []law.Law[Mixed]{
		law.LifecycleRespectsContext[orderafter.Mixed]{
			Op: func(ctx context.Context, s orderafter.Mixed) error {
				return s.Commit(ctx)
			},
		},
	}
}

// mixedAssertLaws drives the same sequences with the bound laws as the only
// oracle, and reports when they engaged nothing.
//
// The differential verdict is off here, and that is the whole reason this
// is a second leg rather than more options on the first: with it armed, a
// subject broken anywhere disagrees at step 0 and no law is ever reached,
// which makes "can this law catch a defect" unanswerable.
//
// The report is the other half. A law behind a precondition the subject
// refuses on every draw passes every time and asserts nothing, and from
// outside that is indistinguishable from a law that held.
func mixedAssertLaws(
	tb testing.TB,
	sub suite.Subject[Mixed],
) {
	tb.Helper()

	// The run's declared oracle where one exists, the derived reference
	// otherwise — and the report says which, because a law held against a
	// second copy of the subject is a weaker claim than the same law held
	// against something written independently.
	buildRef, tier := legs.Reference(tb, sub, func() Mixed { return sub.New(tb) })
	sub.NoteTier(tier)
	legs.Law(tb, sub,
		func() Mixed { return sub.New(tb) }, buildRef,
		mixedModelActions(),
		mixedModelLaws())
}

// testkit: end of generated content.
// testkit:provenance d0f2a53acbf7c9bb348b4ee8272a1b0372f2aace1c1ecb31d79ab294a07c8d36
