// Code generated by testkit. DO NOT EDIT.
//
// Source:    corpus/iface/mixin/commutative/iface.go
// Plugins:   golang 1.0.0, stub 1.4.0, backend.golang 1.0.0
// Command:   testkit run ./corpus/...

// Conformance checks worked out from the interfaces this package doubles.
//
// One call runs every check for an interface against one implementation.
// Describe the implementation in a literal and hand it over — each
// interface's own Run function is documented beside it, with the names
// to use.
//
// Nothing else is required to start. The rest is there when you need it:
// a harness field to add only when a check fails asking for it, checks of
// your own that run beside the generated ones, a Prove entry that drives
// each of yours against the broken implementation it names, and a typed
// index for dropping a check by identity rather than by string.
//
// Nothing here is written by hand. Regenerate rather than edit: an edit
// survives until the next run and no longer.
package commutativetest

import (
	"context"
	"testing"

	"go.thesmos.sh/testkit/clock"
	"go.thesmos.sh/testkit/conformance/corpus/iface/mixin/commutative"
	"go.thesmos.sh/testkit/rand"
	"go.thesmos.sh/testkit/stub"
)

// MixedApplyCall records one invocation of Mixed.Apply.
//
// Fields take their names from the source signature — parameters and named
// returns alike — so a failure message names what the author named. A slot
// the source left unnamed or blank falls back to a positional name.
type MixedApplyCall struct {
	Ctx context.Context
	D   commutative.Delta
	Err error
}

// MixedTotalCall records one invocation of Mixed.Total.
//
// Fields take their names from the source signature — parameters and named
// returns alike — so a failure message names what the author named. A slot
// the source left unnamed or blank falls back to a positional name.
type MixedTotalCall struct {
	Ctx    context.Context
	Result int
	Err    error
}

// --- Per-method configuration ---

// MixedApplyStub controls how the double answers Apply and records
// what it was asked.
//
// The embedded MethodStub supplies the machinery every method shares: call
// recording, fault injection, latency against a virtual clock, gates,
// call-count expectations, and strict mode.
type MixedApplyStub struct {
	*stub.MethodStub[MixedApplyCall]

	fn       func(context.Context, commutative.Delta) error
	fallback *MixedApplyReturn
}

// MixedApplyReturn holds the fixed answer configured through Returns.
type MixedApplyReturn struct {
	Err error
}

// Returns pins a fixed result for every call to Apply. A Func
// override and an injected fault both take precedence over it.
func (s *MixedApplyStub) Returns(err error) *MixedApplyStub {
	s.fallback = &MixedApplyReturn{Err: err}
	return s
}

// Func supplies a body for Apply, for when the answer depends on the
// arguments. An injected fault still takes precedence.
func (s *MixedApplyStub) Func(fn func(context.Context, commutative.Delta) error) *MixedApplyStub {
	s.fn = fn
	return s
}

// MixedTotalStub controls how the double answers Total and records
// what it was asked.
//
// The embedded MethodStub supplies the machinery every method shares: call
// recording, fault injection, latency against a virtual clock, gates,
// call-count expectations, and strict mode.
type MixedTotalStub struct {
	*stub.MethodStub[MixedTotalCall]

	fn       func(context.Context) (int, error)
	fallback *MixedTotalReturn
}

// MixedTotalReturn holds the fixed answer configured through Returns.
type MixedTotalReturn struct {
	Result int
	Err    error
}

// Returns pins a fixed result for every call to Total. A Func
// override and an injected fault both take precedence over it.
func (s *MixedTotalStub) Returns(result int, err error) *MixedTotalStub {
	s.fallback = &MixedTotalReturn{Result: result, Err: err}
	return s
}

// Func supplies a body for Total, for when the answer depends on the
// arguments. An injected fault still takes precedence.
func (s *MixedTotalStub) Func(fn func(context.Context) (int, error)) *MixedTotalStub {
	s.fn = fn
	return s
}

// --- MixedStub ---

// The double-runtime witness for the surface this double rides. A
// breaking change to the runtime renames it, and this file stops
// compiling with the skew named.
var _ = stub.CompatV1

// MixedStubOption configures a [MixedStub] at construction time.
type MixedStubOption func(*MixedStub)

// MixedStubStrict makes an unconfigured method fail the test rather than
// return its zero value, which turns a call nobody planned for into a failure
// at the call site instead of a puzzling zero further downstream.
func MixedStubStrict() MixedStubOption {
	return func(s *MixedStub) { s.strict = true }
}

// MixedStubDelegateTo wraps a real implementation: every method forwards to
// impl and is recorded on the double on the way through.
//
// This is what lets one generated suite run against both the double and the
// production type, which is the point of conformance testing.
func MixedStubDelegateTo(impl commutative.Mixed) MixedStubOption {
	return func(s *MixedStub) {
		s.OnApply.Func(impl.Apply)
		s.OnTotal.Func(impl.Total)
	}
}

// MixedStubWithClock drives latency and time-windowed faults from clk
// rather than from wall time, so a test asserting on a five-second timeout
// does not take five seconds.
func MixedStubWithClock(clk clock.Clock) MixedStubOption {
	return func(s *MixedStub) { s.group.SetClock(clk) }
}

// MixedStubWithRandSource makes probabilistic fault injection reproducible.
// A failure nobody can replay is not a finding.
func MixedStubWithRandSource(src rand.Source) MixedStubOption {
	return func(s *MixedStub) { s.group.SetRandSource(src) }
}

// MixedStubBenchMode disables call recording. Dispatch still works; only
// the accumulating call log is dropped, because its allocations are what a
// benchmark would otherwise be measuring.
func MixedStubBenchMode() MixedStubOption {
	return func(s *MixedStub) { s.group.BenchMode() }
}

// WithMixedApply sets Apply's body at construction
// time, for the common case of configuring one method and taking the
// defaults for the rest.
func WithMixedApply(fn func(context.Context, commutative.Delta) error) MixedStubOption {
	return func(s *MixedStub) { s.OnApply.Func(fn) }
}

// WithMixedTotal sets Total's body at construction
// time, for the common case of configuring one method and taking the
// defaults for the rest.
func WithMixedTotal(fn func(context.Context) (int, error)) MixedStubOption {
	return func(s *MixedStub) { s.OnTotal.Func(fn) }
}

// MixedStub is a recording test double for Mixed.
//
// Each On<Method> field is that method's configuration point. Left alone, a
// method returns its zero value and records the call.
type MixedStub struct {
	OnApply *MixedApplyStub
	OnTotal *MixedTotalStub

	// group is every method stub above, viewed through the surface that
	// does not depend on a signature — one home for the settings and the
	// lifecycle that apply to the whole double.
	group  *stub.Group
	strict bool
}

// Compile-time proof that MixedStub satisfies Mixed.
//
// It lives here rather than in the companion so a drifted signature fails
// `go build` rather than waiting for a test run — the double is unusable the
// moment it stops satisfying the interface, and that is worth learning at the
// earliest point it can be known.
var _ commutative.Mixed = (*MixedStub)(nil)

// NewMixedStub returns a double bound to tb.
//
// Passing tb registers a cleanup that verifies every method's call-count
// expectations when the test ends, so an unmet Times is reported without the
// caller remembering to check. A nil tb skips that, which is what benchmarks
// and non-test callers want.
func NewMixedStub(tb testing.TB, opts ...MixedStubOption) *MixedStub {
	s := &MixedStub{
		OnApply: &MixedApplyStub{MethodStub: stub.NewMethodStub[MixedApplyCall](tb, "Mixed.Apply")},
		OnTotal: &MixedTotalStub{MethodStub: stub.NewMethodStub[MixedTotalCall](tb, "Mixed.Total")},
	}
	s.group = stub.NewGroup(
		s.OnApply.MethodStub,
		s.OnTotal.MethodStub,
	)
	for _, opt := range opts {
		opt(s)
	}
	if s.strict {
		s.group.StrictAll()
	}
	s.group.Bind(tb)
	return s
}

// ResetCalls clears recorded calls, fault counters, and call-count
// expectations. Func and Returns configuration is deliberately preserved, so
// a test can reuse one double across phases without rebuilding it.
func (s *MixedStub) ResetCalls() {
	s.group.Reset()
}

// --- Interface methods ---

// invoke adapts the Func override to the shape [stub.Answer] consumes, or
// returns nil when no override is set — which is how Answer tells "no
// override" from "an override that returns zero".
func (s *MixedApplyStub) invoke(ctx context.Context, d commutative.Delta) func() MixedApplyReturn {
	if s.fn == nil {
		return nil
	}
	return func() MixedApplyReturn {
		r0 := s.fn(ctx, d)
		return MixedApplyReturn{Err: r0}
	}
}

// Apply records the call and answers it.
//
// Which arm answers — injected fault, Func override, Returns fallback, or the
// zero value — is [stub.Answer]'s to decide, so every generated double
// resolves a call the same way and the ordering is tested once rather than
// restated per method.
func (s *MixedStub) Apply(ctx context.Context, d commutative.Delta) error {
	call := MixedApplyCall{Ctx: ctx, D: d}
	r := stub.Answer(s.OnApply.MethodStub, &call, stub.Arms[MixedApplyCall, MixedApplyReturn]{
		Invoke:   s.OnApply.invoke(ctx, d),
		Fallback: s.OnApply.fallback,
		Fault:    func(err error) MixedApplyReturn { return MixedApplyReturn{Err: err} },
		Stamp: func(c *MixedApplyCall, r MixedApplyReturn) {
			c.Err = r.Err
		},
	})
	return r.Err
}

// invoke adapts the Func override to the shape [stub.Answer] consumes, or
// returns nil when no override is set — which is how Answer tells "no
// override" from "an override that returns zero".
func (s *MixedTotalStub) invoke(ctx context.Context) func() MixedTotalReturn {
	if s.fn == nil {
		return nil
	}
	return func() MixedTotalReturn {
		r0, r1 := s.fn(ctx)
		return MixedTotalReturn{Result: r0, Err: r1}
	}
}

// Total records the call and answers it.
//
// Which arm answers — injected fault, Func override, Returns fallback, or the
// zero value — is [stub.Answer]'s to decide, so every generated double
// resolves a call the same way and the ordering is tested once rather than
// restated per method.
func (s *MixedStub) Total(ctx context.Context) (int, error) {
	call := MixedTotalCall{Ctx: ctx}
	r := stub.Answer(s.OnTotal.MethodStub, &call, stub.Arms[MixedTotalCall, MixedTotalReturn]{
		Invoke:   s.OnTotal.invoke(ctx),
		Fallback: s.OnTotal.fallback,
		Fault:    func(err error) MixedTotalReturn { return MixedTotalReturn{Err: err} },
		Stamp: func(c *MixedTotalCall, r MixedTotalReturn) {
			c.Result = r.Result
			c.Err = r.Err
		},
	})
	return r.Result, r.Err
}

// testkit: end of generated content.
// testkit:provenance 69a6d685a8c42b619b840686e18e32de0549e1f7c59f9ed734a6b5a319fa7e88
