// Code generated by testkit. DO NOT EDIT.
//
// Source:    corpus/iface/mixin/commutative/iface.go
// Plugins:   golang 1.0.0, suite 1.24.0, backend.golang 1.0.0
// Command:   testkit run ./corpus/...

package commutativetest_test

import (
	"context"
	"errors"
	"testing"

	"go.thesmos.sh/testkit/conformance/corpus/iface/mixin/commutative"
	"go.thesmos.sh/testkit/conformance/corpus/iface/mixin/commutative/commutativetest"
	"go.thesmos.sh/testkit/engine/suite"
	"go.thesmos.sh/testkit/engine/suite/prove"
)

// TestMixedProofs drives every planted defect through the check it is
// evidence for.
//
// A red here is the expected outcome for each one; a GREEN is the finding.
// It means a check tolerated the implementation built to break it, and a
// check that cannot fail is a line in a report rather than a claim about
// the subject.
func TestMixedProofs(t *testing.T) {
	t.Parallel()
	prove.All(t,
		commutativetest.MixedSuite.Suite(commutativetest.DefaultMixedFixture()).Checks,
		mixedProofs())
}

// mixedProofs is every defect this run derived and can spell.
//
// Each is the smallest implementation that breaks exactly one claim: the
// generated double with one method overridden, and nothing else changed.
// The reason beside it is the substring the red must contain, so a defect
// that died on an unrelated guard stops counting as evidence.
func mixedProofs() prove.Defects[commutativetest.Mixed] {
	ix := commutativetest.MixedSuite.Checks
	return prove.Defects[commutativetest.Mixed]{
		ix.Apply.Smoke(): prove.One("a Mixed whose Apply panics",
			func(tb testing.TB) commutativetest.Mixed {
				return commutativetest.NewMixedStub(tb, commutativetest.WithMixedApply(
					func(_ context.Context, _ commutative.Delta) error {
						panic("planted: Apply panics")
					}))
			}).Reasoned(suite.RedPanicked),
		ix.Apply.Cancels(): prove.One("a Mixed whose Apply ignores the context it is handed",
			func(tb testing.TB) commutativetest.Mixed {
				return commutativetest.NewMixedStub(tb, commutativetest.WithMixedApply(
					func(_ context.Context, _ commutative.Delta) (err error) {
						// The call arrives and nothing is done with it; the bare
						// return answers every slot's zero, which for the error
						// slot is the nil this claim forbids.
						return
					}))
			}).Reasoned(suite.RedCancelled),
		ix.Apply.NilContext(): prove.One("a Mixed whose Apply forgives a nil context and answers",
			func(tb testing.TB) commutativetest.Mixed {
				return commutativetest.NewMixedStub(tb, commutativetest.WithMixedApply(
					func(_ context.Context, _ commutative.Delta) (err error) {
						// The call arrives and nothing is done with it; the bare
						// return answers every slot's zero, which for the error
						// slot is the nil this claim forbids.
						return
					}))
			}).Reasoned(suite.RedNilContext),
		ix.Apply.Deadline(): prove.One("a Mixed whose Apply ignores the context it is handed",
			func(tb testing.TB) commutativetest.Mixed {
				return commutativetest.NewMixedStub(tb, commutativetest.WithMixedApply(
					func(_ context.Context, _ commutative.Delta) (err error) {
						// The call arrives and nothing is done with it; the bare
						// return answers every slot's zero, which for the error
						// slot is the nil this claim forbids.
						return
					}))
			}).Reasoned(suite.RedDeadline),
		ix.Total.Smoke(): prove.One("a Mixed whose Total panics",
			func(tb testing.TB) commutativetest.Mixed {
				return commutativetest.NewMixedStub(tb, commutativetest.WithMixedTotal(
					func(_ context.Context) (int, error) {
						panic("planted: Total panics")
					}))
			}).Reasoned(suite.RedPanicked),
		ix.Total.Cancels(): prove.One("a Mixed whose Total ignores the context it is handed",
			func(tb testing.TB) commutativetest.Mixed {
				return commutativetest.NewMixedStub(tb, commutativetest.WithMixedTotal(
					func(_ context.Context) (r0 int, err error) {
						// The call arrives and nothing is done with it; the bare
						// return answers every slot's zero, which for the error
						// slot is the nil this claim forbids.
						return
					}))
			}).Reasoned(suite.RedCancelled),
		ix.Total.NilContext(): prove.One("a Mixed whose Total forgives a nil context and answers",
			func(tb testing.TB) commutativetest.Mixed {
				return commutativetest.NewMixedStub(tb, commutativetest.WithMixedTotal(
					func(_ context.Context) (r0 int, err error) {
						// The call arrives and nothing is done with it; the bare
						// return answers every slot's zero, which for the error
						// slot is the nil this claim forbids.
						return
					}))
			}).Reasoned(suite.RedNilContext),
		ix.Total.Deadline(): prove.One("a Mixed whose Total ignores the context it is handed",
			func(tb testing.TB) commutativetest.Mixed {
				return commutativetest.NewMixedStub(tb, commutativetest.WithMixedTotal(
					func(_ context.Context) (r0 int, err error) {
						// The call arrives and nothing is done with it; the bare
						// return answers every slot's zero, which for the error
						// slot is the nil this claim forbids.
						return
					}))
			}).Reasoned(suite.RedDeadline),
		ix.Total.ZeroOnError(): prove.One("a Mixed whose Total answers a believable value beside its error",
			func(tb testing.TB) commutativetest.Mixed {
				return commutativetest.NewMixedStub(tb, commutativetest.WithMixedTotal(
					func(_ context.Context) (r0 int, err error) {
						// A believable answer beside the refusal. A caller
						// reading the error and one reading the value disagree
						// about what happened, which is the claim's own
						// violation rather than a subject that merely failed.
						r0 = 2
						err = errors.New("planted: Total refused with a believable value")
						return
					}))
			}),
	}
}

// TestMixedInvariants holds this package to what it says about itself.
//
// Four claims, none of which a consumer writes and none of which any
// other gate makes. The manifest pins the assertion SET, so a check that
// stops being emitted reads as a removed row in review rather than as a
// suite that quietly got smaller. The index and the drop hints pin the
// two ways a check is NAMED — an index entry pointing at nothing
// compiles, and a drop hint that falls back to the string form forfeits
// exactly the compile-break the index exists to give. The distinct-ID
// check catches two interfaces in one package claiming one identity,
// which method-name scopes make possible.
func TestMixedInvariants(t *testing.T) {
	t.Parallel()

	s := commutativetest.MixedSuite.Suite(commutativetest.DefaultMixedFixture())

	rows, err := suite.LockLines(s)
	if err != nil {
		t.Fatalf("render the manifest rows: %v", err)
	}
	suite.VerifyLock(t, "mixed.checks.lock", rows)
	suite.VerifyIndex(t, "Mixed",
		commutativetest.MixedSuite.Checks.All(), s.IDs())
	suite.VerifyDropHints(t, "Mixed", s.IDs(), s.DropHint)
	suite.VerifyDistinctIDs(t, s.IDs())
}

// testkit: end of generated content.
// testkit:provenance 0d0a75396adf0003a152fa8c2ff0429f85cbc5e3256e7f8fe29cd34d8d55097c
