// Code generated by testkit. DO NOT EDIT.
//
// Source:    corpus/iface/detector/mutator/iface.go
// Plugins:   golang 1.0.0, stub 1.4.0, backend.golang 1.0.0
// Command:   testkit run ./corpus/...

package mutatortest_test

import (
	"context"
	"testing"

	"go.thesmos.sh/testkit"
	"go.thesmos.sh/testkit/clock"
	"go.thesmos.sh/testkit/conformance/corpus/iface/detector/mutator/mutatortest"
	"go.thesmos.sh/testkit/rand"
	"go.thesmos.sh/testkit/stub"
)

// mutatorStubTouchSubject binds Touch into the shape
// [stub.Behaviour] drives: how to call it, what it answers with, and how to
// override it.
//
// Each call builds a fresh double, because several of the checks assert on
// failure and need one bound to a failable TB rather than to the running
// test.
func mutatorStubTouchSubject(tb testing.TB) stub.Subject[mutatortest.MutatorTouchCall, struct{}] {
	tb.Helper()
	s := mutatortest.NewMutatorStub(tb)
	return stub.Subject[mutatortest.MutatorTouchCall, struct{}]{
		Stub: s.OnTouch.MethodStub,
		Call: func() {
			var a0 context.Context
			var a1 string = "test-key"
			s.Touch(a0, a1)
		},
		Override: func(mark func()) {
			s.OnTouch.Func(func(_ context.Context, _ string) {
				mark()
			})
		},
	}
}

// TestMutatorStubTouch pins how Touch answers.
//
// Recording, resetting, call-count expectations, strict mode, fault injection
// and zero-value dispatch are the same contract for every method, so they are
// asserted once in [stub.Behaviour] rather than restated here. What remains
// below needs a value this method's signature can tell apart from a zero one.
func TestMutatorStubTouch(t *testing.T) {
	t.Parallel()

	stub.Behaviour(t, "Touch", mutatorStubTouchSubject)
	t.Run("records what it was called with", func(t *testing.T) {
		t.Parallel()
		// Asserting only that a call happened would pass against a double
		// that recorded the wrong arguments, which is the failure a reader
		// most needs the log to surface.
		s := mutatortest.NewMutatorStub(t)
		var a0 context.Context
		var a1 string = "test-key"
		s.Touch(a0, a1)
		got := s.OnTouch.AssertCalledOnce(t, "Touch must record the call")
		testkit.Equal(t, got.Ctx, a0, "the recorded call carries Ctx")
		testkit.Equal(t, got.Key, a1, "the recorded call carries Key")
	})

	t.Run("fires the OnRecord hook for every call", func(t *testing.T) {
		t.Parallel()
		// The hook fires synchronously as each call lands, which is what a
		// concurrency test observes progress with — polling the log instead
		// races the thing under test.
		s := mutatortest.NewMutatorStub(t)
		var seen []mutatortest.MutatorTouchCall
		s.OnTouch.OnRecord(func(c mutatortest.MutatorTouchCall) { seen = append(seen, c) })
		var a0 context.Context
		var a1 string = "test-key"
		s.Touch(a0, a1)
		s.Touch(a0, a1)
		testkit.Len(t, seen, 2, "OnRecord must fire once per Touch call")
	})

	t.Run("wires WithMutatorTouch at construction", func(t *testing.T) {
		t.Parallel()
		called := false
		s := mutatortest.NewMutatorStub(t, mutatortest.WithMutatorTouch(func(_ context.Context, _ string) {
			called = true
		}))
		var a0 context.Context
		var a1 string = "test-key"
		s.Touch(a0, a1)
		testkit.True(t, called, "WithMutatorTouch must install the override")
	})
}

// mutatorStubDouble describes how to build a MutatorStub under each
// option whose effect is the same whatever a method's signature.
//
// Touch stands in for the double as a whole: what these checks assert
// is that an option reached it at all, and the first method witnesses that as
// well as any other would.
func mutatorStubDouble() stub.Double[mutatortest.MutatorTouchCall] {
	instance := func(s *mutatortest.MutatorStub) stub.Instance[mutatortest.MutatorTouchCall] {
		return stub.Instance[mutatortest.MutatorTouchCall]{
			Stub: s.OnTouch.MethodStub,
			Call: func() {
				var a0 context.Context
				var a1 string = "test-key"
				s.Touch(a0, a1)
			},
			Reset: s.ResetCalls,
		}
	}
	return stub.Double[mutatortest.MutatorTouchCall]{
		New: func(tb testing.TB) stub.Instance[mutatortest.MutatorTouchCall] {
			return instance(mutatortest.NewMutatorStub(tb))
		},
		WithClock: func(tb testing.TB, clk clock.Clock) stub.Instance[mutatortest.MutatorTouchCall] {
			return instance(mutatortest.NewMutatorStub(tb, mutatortest.MutatorStubWithClock(clk)))
		},
		WithRandSource: func(tb testing.TB, src rand.Source) stub.Instance[mutatortest.MutatorTouchCall] {
			return instance(mutatortest.NewMutatorStub(tb, mutatortest.MutatorStubWithRandSource(src)))
		},
		BenchMode: func(tb testing.TB) stub.Instance[mutatortest.MutatorTouchCall] {
			return instance(mutatortest.NewMutatorStub(tb, mutatortest.MutatorStubBenchMode()))
		},
		Strict: func(tb testing.TB) stub.Instance[mutatortest.MutatorTouchCall] {
			return instance(mutatortest.NewMutatorStub(tb, mutatortest.MutatorStubStrict()))
		},
	}
}

// TestMutatorStubOptions pins the settings that apply to the double rather
// than to one method: bench mode, the injected clock and random source, and
// what a reset clears.
func TestMutatorStubOptions(t *testing.T) {
	t.Parallel()

	stub.DoubleBehaviour(t, mutatorStubDouble())
}

// TestMutatorStubDelegateTo pins that a wrapped implementation is called
// through, and recorded on the way past.
//
// This is what lets one generated suite run against both the double and a
// production type, which is the point of conformance testing.
func TestMutatorStubDelegateTo(t *testing.T) {
	t.Parallel()

	inner := mutatortest.NewMutatorStub(t)
	s := mutatortest.NewMutatorStub(t, mutatortest.MutatorStubDelegateTo(inner))

	t.Run("forwards Touch to the wrapped implementation", func(t *testing.T) {
		var a0 context.Context
		var a1 string = "test-key"
		s.Touch(a0, a1)
		inner.OnTouch.AssertCalledOnce(t, "Touch must reach the wrapped implementation")
	})
}

// testkit: end of generated content.
// testkit:provenance 685c491a71ecae75b4264264db79a8d487ecc9207e4980f850b9515890a7a607
