// Code generated by testkit. DO NOT EDIT.
//
// Source:    corpus/iface/mixin/validates/iface.go
// Plugins:   golang 1.0.0, suite 1.24.0, backend.golang 1.0.0
// Command:   testkit run ./corpus/...

// Conformance checks worked out from the interfaces this package doubles.
//
// One call runs every check for an interface against one implementation.
// Describe the implementation in a literal and hand it over — each
// interface's own Run function is documented beside it, with the names
// to use.
//
// Nothing else is required to start. The rest is there when you need it:
// a harness field to add only when a check fails asking for it, checks of
// your own that run beside the generated ones, a Prove entry that drives
// each of yours against the broken implementation it names, and a typed
// index for dropping a check by identity rather than by string.
//
// Nothing here is written by hand. Regenerate rather than edit: an edit
// survives until the next run and no longer.
package validatestest

import (
	"context"
	"errors"
	"fmt"
	"testing"

	"go.thesmos.sh/testkit/conformance/corpus/iface/mixin/validates"
	"go.thesmos.sh/testkit/core/lawid"
	"go.thesmos.sh/testkit/engine/legs"
	"go.thesmos.sh/testkit/engine/model"
	"go.thesmos.sh/testkit/engine/model/action"
	"go.thesmos.sh/testkit/engine/model/crash"
	"go.thesmos.sh/testkit/engine/model/law"
	"go.thesmos.sh/testkit/engine/model/linearize"
	"go.thesmos.sh/testkit/engine/model/ref"
	"go.thesmos.sh/testkit/engine/suite"
	"go.thesmos.sh/testkit/engine/suite/prove"
)

// Conformance checks for Mixed, worked out from its declaration.
//
// The package comment above says what these are and how to start. This is
// Mixed's half of it — the names to use:
//
//	func TestMine(t *testing.T) {
//		RunMixed(t, MixedHarness[*Mine]{Name: "mine", New: NewMine})
//	}
//
//	MixedHarness
//	    one implementation under test.
//	MixedChecks
//	    checks you write yourself, run beside the generated ones.
//	ProveMixed
//	    drives each of yours against the broken implementation it names.
//	GreenMixed
//	    drives them all against one that is correct but different, and
//	    fails if a check rejects it.
//	MixedSuite.Checks.<Method>.<Check>()
//	    names one check, so you can drop it. Written this way it stops
//	    compiling if a later regeneration no longer emits that check,
//	    rather than silently dropping nothing.
//
// The checks this file runs:
//
//	Read/cancel
//	Read/deadline
//	Read/miss
//	Read/nilcontext
//	Read/smoke
//	Read/zero-on-error
//	Store/cancel
//	Store/deadline
//	Store/nilcontext
//	Store/smoke
//	Store/validates
//	Validate/smoke
//	model/mixed/AUTO-LINEARIZABLE
//	model/mixed/AUTO-WRITE-OBSERVABLE
//	model/mixed/differential
//	sim/mixed/recovery
//
// A version check, performed by the compiler. If this file was generated
// against a testkit whose check format differs from the one you are
// building with, this line fails to compile and names the mismatch —
// instead of the two disagreeing quietly while the tests still pass.
// Regenerate the file to clear it.
var _ = suite.CompatV2

// MixedFixture holds the sample inputs the checks call your
// implementation with, worked out from each method's parameter types.
//
// Every input comes as a pair: a value, and a second one guaranteed to
// differ from it. Both are needed for a check to mean anything — looking
// up a key that was just stored proves nothing on its own unless there
// is also a key that was never stored.
//
// A parameter whose type has no value that can be written down — a func,
// a channel, a type your declaration does not import — is left at its
// zero value, and the checks that needed it were not emitted at all
// rather than run against something meaningless. Those are listed above.
// A check you write yourself is handed this either way.
type MixedFixture struct {
	payload      validates.Payload
	payloadOther validates.Payload
	key          string
	keyOther     string
}

// DefaultMixedFixture is what a run with no config draws.
func DefaultMixedFixture() MixedFixture {
	return mixedNewFixture()
}

// mixedNewFixture builds the sample inputs for one run.
//
// Read these through the methods below rather than as fields. A value you
// supplied through the config and one worked out from the type are read
// the same way, and no check should be able to tell them apart.
func mixedNewFixture() MixedFixture {
	return MixedFixture{
		payload:      validates.Payload{Key: "test-key", Body: "test-body"},
		payloadOther: validates.Payload{Key: "other-key", Body: "other-body"},
		key:          "test-key",
		keyOther:     "other-key",
	}
}

// Payload is the payload the checks call your implementation with.
func (f MixedFixture) Payload() validates.Payload { return f.payload }

// PayloadOther is a second payload, guaranteed to differ from the
// first — so a check that expects to find nothing is asking about
// something your implementation has genuinely never been given.
func (f MixedFixture) PayloadOther() validates.Payload { return f.payloadOther }

// Key is the key the checks call your implementation with.
func (f MixedFixture) Key() string { return f.key }

// KeyOther is a second key, guaranteed to differ from the
// first — so a check that expects to find nothing is asking about
// something your implementation has genuinely never been given.
func (f MixedFixture) KeyOther() string { return f.keyOther }

// Mixed is your interface, under a local name.
//
// An alias, so it is the same type — this is here only so the rest of
// this file can refer to it without repeating its import path, and so a
// check you write can name it too.
type Mixed = validates.Mixed

// MixedSubject is what a RunWith check receives instead of a single
// instance: a handle that can build more of them.
//
// Use it for a claim one instance cannot state on its own — that two
// instances do not share state, that a value survives being closed and
// reopened.
type MixedSubject = suite.Subject[Mixed]

// MixedRunOpt is anything you can pass to RunMixed: an
// implementation to test, a table of your own checks, a config, or a
// check to drop. Order does not matter.
type MixedRunOpt interface {
	applyTo(*mixedRunConfig)
}

type mixedRunConfig struct {
	suite.Bundle[Mixed]

	// rows are the checks you wrote, held until every argument has been
	// read and then tied to this run's inputs. Tying them on arrival
	// would bind them to inputs a later argument replaces.
	rows MixedChecks
}

// MixedHarness describes one Mixed implementation to test.
//
// Name and one constructor are all that is required. Every other field
// unlocks the checks that need it, and you do not have to work out which
// in advance: run it, and any check that needs more fails saying which
// field to add.
type MixedHarness[T Mixed] struct {
	Name string

	// Set exactly one.
	//
	// Use New if construction cannot fail; use Start if it needs the
	// test's lifetime — a temp directory to clean up, a connection to
	// close. Start is handed the testing.TB to register that on.
	New   func() T
	Start func(tb testing.TB) T

	// Excuse lists checks this implementation cannot meaningfully take —
	// not ones it fails, ones it has no way to answer. An in-memory
	// implementation has no storage to survive a restart, so a check
	// about restarting it is asking the impossible.
	//
	// Excused checks are reported as excused, never as passed.
	Excuse []suite.ID

	// Oracle marks this implementation as the one others are compared
	// against, when you are testing more than one. At most one may set it.
	// Pick the implementation you trust most.
	Oracle bool

	// Serial runs this implementation's checks one at a time, and never
	// alongside another implementation's. Set it for something that
	// cannot take being constructed many times at once — a real database,
	// a fixed port.
	Serial bool

	// Recover builds the process again over the medium the prior instance
	// left behind — no Close first, because a crash is the goodbye that
	// never happens. Checks that kill the process need it, and fail
	// naming this field when it is nil. StartRecover is its Start-shaped
	// sibling, for a reopen that also needs the test's lifetime; set at
	// most one of the two.
	//
	// If your implementation keeps everything in memory, it has no medium
	// to recover and this is the wrong answer: list the check in Excuse
	// instead, which reports it as excused rather than as passed.
	Recover      func(prior T) T
	StartRecover func(tb testing.TB, prior T) T

	// Provide supplies anything a check needs that has no field of its
	// own above. You will not need it unless a check fails asking for a
	// named capability, and that failure tells you the name to use here.
	Provide map[suite.Capability]any
}

// Subject converts this description into the form the runner uses, and
// reports anything wrong with it — no constructor, or two.
func (h MixedHarness[T]) Subject() (suite.Subject[Mixed], error) {
	build, err := suite.OneCtor(h.Name, h.New, h.Start)
	if err != nil {
		return suite.Subject[Mixed]{}, err
	}
	out := suite.Subject[Mixed]{
		Name:     h.Name,
		Provides: h.Provide,
		New:      func(tb testing.TB) Mixed { return build(tb) },
		Oracle:   h.Oracle,
		Serial:   h.Serial,
		Excused:  suite.ExcuseSet(h.Excuse),
	}
	if err := suite.ExclusivePair(h.Name, "Recover", "StartRecover",
		h.Recover != nil, h.StartRecover != nil); err != nil {
		return suite.Subject[Mixed]{}, err
	}
	if reopen := h.Recover; reopen != nil {
		out.Recover = func(tb testing.TB, prior Mixed) Mixed {
			return reopen(legs.AsBuilt[T](tb, h.Name, prior))
		}
	}
	if reopen := h.StartRecover; reopen != nil {
		out.Recover = func(tb testing.TB, prior Mixed) Mixed {
			return reopen(tb, legs.AsBuilt[T](tb, h.Name, prior))
		}
	}
	return out, nil
}

func (h MixedHarness[T]) applyTo(rc *mixedRunConfig) {
	rc.AddSubject(h.Subject())
}

type mixedDropOpt []suite.ID

func (d mixedDropOpt) applyTo(rc *mixedRunConfig) {
	rc.AddDrops(d...)
}

// mixedWithout drops the named checks from the run.
func mixedWithout(ids ...suite.ID) MixedRunOpt {
	return mixedDropOpt(ids)
}

// --- Naming checks ----------------------------------------------------------

// MixedSuite is how you name a check — to drop it, or to
// point at it from a tool.
var MixedSuite = mixedVeneer{Checks: mixedCheckIndex}

type mixedVeneer struct {
	// Checks names every check this file runs, by method:
	//
	//	MixedSuite.Checks.<Method>.<Check>()
	//
	// Prefer this over writing the check's name as a string. If a later
	// regeneration stops emitting that check, this stops compiling —
	// where the string would silently drop nothing.
	Checks mixedCheckIndexT
}

// Without drops the named checks from the run.
//
//	RunMixed(t, mine, MixedSuite.Without(
//		MixedSuite.Checks.Store.Smoke()))
//
// Dropping is recorded in the run's report, so a check you removed is
// visible rather than simply absent.
func (mixedVeneer) Without(ids ...suite.ID) MixedRunOpt {
	return mixedWithout(ids...)
}

// Suite returns the checks as plain data, if you are building a tool over
// them or running them yourself.
//
// RunMixed is the normal way in; this is for when you need the
// checks as values rather than as a run.
func (mixedVeneer) Suite(fx MixedFixture) suite.Suite[Mixed] {
	return mixedSuite(fx)
}

// --- Failure messages -------------------------------------------------------

// mixedIndexPath maps each check to the expression you would
// write to drop it, so that a check which cannot run tells you what to
// type rather than only what went wrong.
var mixedIndexPath = map[suite.ID]string{
	mixedCheckIndex.Store.Smoke():           "MixedSuite.Checks.Store.Smoke()",
	mixedCheckIndex.Store.Cancels():         "MixedSuite.Checks.Store.Cancels()",
	mixedCheckIndex.Store.NilContext():      "MixedSuite.Checks.Store.NilContext()",
	mixedCheckIndex.Store.Deadline():        "MixedSuite.Checks.Store.Deadline()",
	mixedCheckIndex.Store.Validates():       "MixedSuite.Checks.Store.Validates()",
	mixedCheckIndex.Validate.Smoke():        "MixedSuite.Checks.Validate.Smoke()",
	mixedCheckIndex.Read.Smoke():            "MixedSuite.Checks.Read.Smoke()",
	mixedCheckIndex.Read.Cancels():          "MixedSuite.Checks.Read.Cancels()",
	mixedCheckIndex.Read.NilContext():       "MixedSuite.Checks.Read.NilContext()",
	mixedCheckIndex.Read.Deadline():         "MixedSuite.Checks.Read.Deadline()",
	mixedCheckIndex.Read.ZeroOnError():      "MixedSuite.Checks.Read.ZeroOnError()",
	mixedCheckIndex.Read.Miss():             "MixedSuite.Checks.Read.Miss()",
	mixedCheckIndex.Model.Agrees():          "MixedSuite.Checks.Model.Agrees()",
	mixedCheckIndex.Model.Linearizable():    "MixedSuite.Checks.Model.Linearizable()",
	mixedCheckIndex.Model.WriteObservable(): "MixedSuite.Checks.Model.WriteObservable()",
	mixedCheckIndex.Sim.Recovery():          "MixedSuite.Checks.Sim.Recovery()",
}

var mixedDropHint = suite.DropHinter(
	"MixedSuite", mixedIndexPath,
)

// The names this file uses in more than one place, declared once each so
// they cannot drift apart.
const (
	mixedStore    = "Store"
	mixedValidate = "Validate"
	mixedRead     = "Read"

	// The interface's word inside a family-scoped identity.
	mixedQualifier = "mixed"
)

// mixedCheckIndex names every check in this file, grouped by method.
// Reach it through MixedSuite.Checks.
var mixedCheckIndex = mixedCheckIndexT{
	Store:    mixedStoreChecks{},
	Validate: mixedValidateChecks{},
	Read:     mixedReadChecks{},
	Model:    mixedModelChecks{},
	Sim:      mixedSimChecks{},
}

type mixedCheckIndexT struct {
	Store    mixedStoreChecks
	Validate mixedValidateChecks
	Read     mixedReadChecks
	Model    mixedModelChecks
	Sim      mixedSimChecks
}

// All returns every ID this package emits.
func (mixedCheckIndexT) All() []suite.ID {
	var out []suite.ID
	out = append(out, mixedStoreChecks{}.All()...)
	out = append(out, mixedValidateChecks{}.All()...)
	out = append(out, mixedReadChecks{}.All()...)
	out = append(out, mixedModelChecks{}.All()...)
	out = append(out, mixedSimChecks{}.All()...)
	return out
}

type mixedStoreChecks struct{}

func (mixedStoreChecks) Smoke() suite.ID {
	return suite.MethodID(mixedStore, suite.SegSmoke)
}

func (mixedStoreChecks) Cancels() suite.ID {
	return suite.MethodID(mixedStore, suite.SegCancel)
}

func (mixedStoreChecks) NilContext() suite.ID {
	return suite.MethodID(mixedStore, suite.SegNilContext)
}

func (mixedStoreChecks) Deadline() suite.ID {
	return suite.MethodID(mixedStore, suite.SegDeadline)
}

func (mixedStoreChecks) Validates() suite.ID {
	return suite.MethodID(mixedStore, suite.SegValidates)
}

func (mixedStoreChecks) All() []suite.ID {
	return []suite.ID{
		mixedStoreChecks{}.Smoke(),
		mixedStoreChecks{}.Cancels(),
		mixedStoreChecks{}.NilContext(),
		mixedStoreChecks{}.Deadline(),
		mixedStoreChecks{}.Validates(),
	}
}

type mixedValidateChecks struct{}

func (mixedValidateChecks) Smoke() suite.ID {
	return suite.MethodID(mixedValidate, suite.SegSmoke)
}

func (mixedValidateChecks) All() []suite.ID {
	return []suite.ID{
		mixedValidateChecks{}.Smoke(),
	}
}

type mixedReadChecks struct{}

func (mixedReadChecks) Smoke() suite.ID {
	return suite.MethodID(mixedRead, suite.SegSmoke)
}

func (mixedReadChecks) Cancels() suite.ID {
	return suite.MethodID(mixedRead, suite.SegCancel)
}

func (mixedReadChecks) NilContext() suite.ID {
	return suite.MethodID(mixedRead, suite.SegNilContext)
}

func (mixedReadChecks) Deadline() suite.ID {
	return suite.MethodID(mixedRead, suite.SegDeadline)
}

func (mixedReadChecks) ZeroOnError() suite.ID {
	return suite.MethodID(mixedRead, suite.SegZeroValue)
}

func (mixedReadChecks) Miss() suite.ID {
	return suite.MethodID(mixedRead, suite.SegMiss)
}

func (mixedReadChecks) All() []suite.ID {
	return []suite.ID{
		mixedReadChecks{}.Smoke(),
		mixedReadChecks{}.Cancels(),
		mixedReadChecks{}.NilContext(),
		mixedReadChecks{}.Deadline(),
		mixedReadChecks{}.ZeroOnError(),
		mixedReadChecks{}.Miss(),
	}
}

type mixedModelChecks struct{}

func (mixedModelChecks) Agrees() suite.ID {
	return suite.FamilyID(suite.FamilyModel, mixedQualifier, suite.SegDifferential)
}

func (mixedModelChecks) Linearizable() suite.ID {
	return suite.FamilyID(suite.FamilyModel, mixedQualifier, suite.SegLinearizable)
}

func (mixedModelChecks) WriteObservable() suite.ID {
	return suite.FamilyID(suite.FamilyModel, mixedQualifier, lawid.WriteObservable)
}

func (mixedModelChecks) All() []suite.ID {
	return []suite.ID{
		mixedModelChecks{}.Agrees(),
		mixedModelChecks{}.Linearizable(),
		mixedModelChecks{}.WriteObservable(),
	}
}

type mixedSimChecks struct{}

func (mixedSimChecks) Recovery() suite.ID {
	return suite.FamilyID(suite.FamilySim, mixedQualifier, suite.SegRecovery)
}

func (mixedSimChecks) All() []suite.ID {
	return []suite.ID{
		mixedSimChecks{}.Recovery(),
	}
}

// mixedSuite returns the checks as data, using the given inputs.
//
// It takes the built inputs rather than a config, because that is what
// the checks read. To start from the defaults, pass what a default run
// passes — MixedSuite.Suite does exactly that.
func mixedSuite(fx MixedFixture) suite.Suite[Mixed] {
	return suite.Suite[Mixed]{
		Name:     "Mixed",
		DropHint: mixedDropHint,
		Checks: append(mixedSignatureChecks(fx),
			mixedModelRows(fx)...),
	}
}

// mixedSignatureChecks builds every check in this file.
//
// A check is marked as proven able to fail only when a deliberately
// broken implementation for it exists in the file beside this one.
// Where none could be built, the check says so instead — claiming proof
// without the evidence is refused, in both directions.
func mixedSignatureChecks(fx MixedFixture) []suite.Check[Mixed] {
	sig := suite.ProvenCheck[Mixed]
	ix := mixedCheckIndex
	return []suite.Check[Mixed]{
		sig(ix.Store.Smoke(), suite.ClassSmoke,
			"Store survives a call with a derived payload",
			func(tb testing.TB, m Mixed) {
				mixedAssertStoreSmoke(tb, m, fx)
			}).At(suite.StrengthErrorOnly),
		sig(ix.Store.Cancels(), suite.ClassCancel,
			"Store reports a cancelled context as cancelled",
			func(tb testing.TB, m Mixed) {
				mixedAssertStoreCancels(tb, m, fx)
			}).At(suite.StrengthErrorOnly),
		sig(ix.Store.NilContext(), suite.ClassNilContext,
			"Store returns an error rather than panicking on a nil context",
			func(tb testing.TB, m Mixed) {
				mixedAssertStoreToleratesNilContext(tb, m, fx)
			}).At(suite.StrengthErrorOnly),
		sig(ix.Store.Deadline(), suite.ClassDeadline,
			"Store reports an expired deadline as exceeded",
			func(tb testing.TB, m Mixed) {
				mixedAssertStoreHonoursDeadline(tb, m, fx)
			}).At(suite.StrengthErrorOnly),
		sig(ix.Validate.Smoke(), suite.ClassSmoke,
			"Validate survives a call with a derived payload",
			func(tb testing.TB, m Mixed) {
				mixedAssertValidateSmoke(tb, m, fx)
			}).At(suite.StrengthErrorOnly),
		sig(ix.Read.Smoke(), suite.ClassSmoke,
			"Read survives a call with a derived key",
			func(tb testing.TB, m Mixed) {
				mixedAssertReadSmoke(tb, m, fx)
			}).At(suite.StrengthErrorOnly),
		sig(ix.Read.Cancels(), suite.ClassCancel,
			"Read reports a cancelled context as cancelled",
			func(tb testing.TB, m Mixed) {
				mixedAssertReadCancels(tb, m, fx)
			}).At(suite.StrengthErrorOnly),
		sig(ix.Read.NilContext(), suite.ClassNilContext,
			"Read returns an error rather than panicking on a nil context",
			func(tb testing.TB, m Mixed) {
				mixedAssertReadToleratesNilContext(tb, m, fx)
			}).At(suite.StrengthErrorOnly),
		sig(ix.Read.Deadline(), suite.ClassDeadline,
			"Read reports an expired deadline as exceeded",
			func(tb testing.TB, m Mixed) {
				mixedAssertReadHonoursDeadline(tb, m, fx)
			}).At(suite.StrengthErrorOnly),
		sig(ix.Read.ZeroOnError(), suite.ClassZeroValue,
			"Read returns the zero Payload alongside any error",
			func(tb testing.TB, m Mixed) {
				mixedAssertReadZeroOnError(tb, m, fx)
			}).At(suite.StrengthObserved),
		sig(ix.Store.Validates(), suite.ClassValidates,
			"Store agrees with Validate about the values this run draws",
			func(tb testing.TB, m Mixed) {
				mixedAssertStoreValidates(tb, m, fx)
			}).At(suite.StrengthErrorOnly),
		sig(ix.Read.Miss(), suite.ClassReader,
			"Read reports zero for a key nothing has written",
			func(tb testing.TB, m Mixed) {
				mixedAssertReadMiss(tb, m, fx)
			}).At(suite.StrengthObserved),
	}
}

// mixedAssertStoreSmoke asserts Store survives a call with a derived payload.
func mixedAssertStoreSmoke(
	tb testing.TB,
	m Mixed,
	fx MixedFixture,
) {
	tb.Helper()
	suite.Survives(tb, mixedStore, func(ctx context.Context) {
		_ = m.Store(ctx, fx.Payload())
	})
}

// mixedAssertStoreCancels asserts Store reports a cancelled context as cancelled.
func mixedAssertStoreCancels(
	tb testing.TB,
	m Mixed,
	fx MixedFixture,
) {
	tb.Helper()
	suite.ReportsCancelled(tb, mixedStore, func(ctx context.Context) error {
		return m.Store(ctx, fx.Payload())
	})
}

// mixedAssertStoreToleratesNilContext asserts Store returns an error rather than panicking on a nil context.
func mixedAssertStoreToleratesNilContext(
	tb testing.TB,
	m Mixed,
	fx MixedFixture,
) {
	tb.Helper()
	suite.ToleratesNilContext(tb, mixedStore, func(ctx context.Context) error {
		return m.Store(ctx, fx.Payload())
	})
}

// mixedAssertStoreHonoursDeadline asserts Store reports an expired deadline as exceeded.
func mixedAssertStoreHonoursDeadline(
	tb testing.TB,
	m Mixed,
	fx MixedFixture,
) {
	tb.Helper()
	suite.ReportsDeadlineExceeded(tb, mixedStore, func(ctx context.Context) error {
		return m.Store(ctx, fx.Payload())
	})
}

// mixedAssertValidateSmoke asserts Validate survives a call with a derived payload.
func mixedAssertValidateSmoke(
	tb testing.TB,
	m Mixed,
	fx MixedFixture,
) {
	tb.Helper()
	suite.Survives(tb, mixedValidate, func(ctx context.Context) {
		_ = m.Validate(fx.Payload())
	})
}

// mixedAssertReadSmoke asserts Read survives a call with a derived key.
func mixedAssertReadSmoke(
	tb testing.TB,
	m Mixed,
	fx MixedFixture,
) {
	tb.Helper()
	suite.Survives(tb, mixedRead, func(ctx context.Context) {
		_, _ = m.Read(ctx, fx.Key())
	})
}

// mixedAssertReadCancels asserts Read reports a cancelled context as cancelled.
func mixedAssertReadCancels(
	tb testing.TB,
	m Mixed,
	fx MixedFixture,
) {
	tb.Helper()
	suite.ReportsCancelled(tb, mixedRead, func(ctx context.Context) error {
		_, err := m.Read(ctx, fx.Key())
		return err
	})
}

// mixedAssertReadToleratesNilContext asserts Read returns an error rather than panicking on a nil context.
func mixedAssertReadToleratesNilContext(
	tb testing.TB,
	m Mixed,
	fx MixedFixture,
) {
	tb.Helper()
	suite.ToleratesNilContext(tb, mixedRead, func(ctx context.Context) error {
		_, err := m.Read(ctx, fx.Key())
		return err
	})
}

// mixedAssertReadHonoursDeadline asserts Read reports an expired deadline as exceeded.
func mixedAssertReadHonoursDeadline(
	tb testing.TB,
	m Mixed,
	fx MixedFixture,
) {
	tb.Helper()
	suite.ReportsDeadlineExceeded(tb, mixedRead, func(ctx context.Context) error {
		_, err := m.Read(ctx, fx.Key())
		return err
	})
}

// mixedAssertReadZeroOnError asserts Read returns the zero Payload alongside any error.
func mixedAssertReadZeroOnError(
	tb testing.TB,
	m Mixed,
	fx MixedFixture,
) {
	tb.Helper()
	ctx, cancel := context.WithCancel(tb.Context())
	cancel()
	got, err := m.Read(ctx, fx.Key())
	if err == nil {
		tb.Skip("Read answered for a cancelled context, so this check has no error to inspect")
	}

	var zero validates.Payload
	if got != zero {
		tb.Errorf("Read must return the zero value alongside an error: got %+v, want %+v (err %v)",
			got, zero, err)
	}
}

// mixedAssertStoreValidates asserts Store agrees with Validate about the values this run draws.
func mixedAssertStoreValidates(
	tb testing.TB,
	m Mixed,
	fx MixedFixture,
) {
	tb.Helper()
	ctx := tb.Context()

	verdict := m.Validate(fx.Payload())
	err := m.Store(ctx, fx.Payload())
	if (verdict != nil) != (err != nil) {
		tb.Errorf("Store must refuse exactly what Validate refuses: Validate said %v, Store said %v",
			verdict, err)
	}
}

// mixedAssertReadMiss asserts Read reports zero for a key nothing has written.
func mixedAssertReadMiss(
	tb testing.TB,
	m Mixed,
	fx MixedFixture,
) {
	tb.Helper()
	ctx := tb.Context()

	got, err := m.Read(ctx, fx.KeyOther())

	var zero validates.Payload
	if got != zero {
		tb.Errorf("Read must return the zero value for an input nothing supplied: got %+v, want %+v (err %v)",
			got, zero, err)
	}
}

// MixedDefect is a deliberately broken implementation, used as
// evidence that a check can fail. In practice you build one with
// BrokenMixed over the generated test double.
type MixedDefect interface {
	Subject() (MixedSubject, error)
}

// BrokenMixed describes an implementation built to break one
// specific claim, so that a check can be shown to catch it.
//
// Give it a name saying what is wrong, and a constructor. The best
// broken implementation is the generated double wrapping a correct one,
// with a single method overridden — correct everywhere except the one
// place the check is about.
func BrokenMixed[T Mixed](
	name string, build func() T,
) MixedHarness[T] {
	return MixedHarness[T]{
		Name: name, New: build,
	}
}

// MixedChecks is a table of checks you write yourself, for the
// claims that cannot be worked out from the declaration — the ones that
// carry your domain.
//
// They are the same kind of value as the generated checks: they appear
// in the report, they can be dropped by name, and they can say what they
// need from an implementation. There is no second mechanism for them.
//
//	var myChecks = MixedChecks{
//		{Method: "Store", Name: "my-claim",
//			Claim:    "a sentence stating exactly what this check proves",
//			Run:      myClaimBody,
//			ProvenBy: BrokenMixed("an implementation that breaks it", newBroken)},
//	}
type MixedChecks []MixedCheck

func (c MixedChecks) applyTo(rc *mixedRunConfig) {
	rc.rows = append(rc.rows, c...)
}

// MixedCheck is one check you wrote. The body is a plain named
// function; which field you put it in decides what it is handed.
type MixedCheck struct {
	// Method groups this check under one of your methods, so it is named
	// Store/<Name> in output and reruns with the rest of that
	// method's checks. Leave it empty for a check that is not about one
	// method in particular.
	Method string

	// Name identifies this check, in output and when dropping it. Keep it
	// stable: it is what a colleague's Without call refers to.
	Name string

	// Claim is one sentence saying exactly what this check proves. It is
	// recorded in the manifest and read out in the report.
	//
	// Write only what the body actually establishes. "a second write
	// leaves the value unchanged" is a promise that something reads the
	// value back; if the body only checks the write returned no error,
	// say that instead. Nothing here can catch a claim that is wider
	// than its check, and a claim nobody verifies is worse than none.
	Claim string

	// Set exactly one.
	//
	// Run is handed one fresh instance, which suits nearly every check.
	// RunWith is handed something that can build instances, for a claim
	// one instance cannot state on its own: build two and compare them,
	// move the clock forward, put one into a failure state.
	//
	// Both are also handed the sample inputs, so a check you write draws
	// from the same values the generated ones do.
	Run     func(tb testing.TB, s Mixed, fx MixedFixture)
	RunWith func(tb testing.TB, sub MixedSubject, fx MixedFixture)

	// Class groups this check in the report's summary. Optional; checks
	// you write are grouped as hand-written by default.
	Class suite.Class

	// Needs says what this check requires from an implementation beyond
	// being constructed — a clock it can move, a failure it can induce.
	//
	// An implementation that cannot supply it fails this check by name,
	// with the field to fill in named in the message. It never skips: a
	// check that quietly skipped for want of wiring would look exactly
	// like one that passed.
	Needs suite.Caps

	// ProvenBy is an implementation built to break this check and nothing
	// else. Setting it makes two statements at once — that the check can
	// fail, and here is the proof — and ProveMixed fails unless the
	// broken implementation really does turn this check red.
	//
	// ProvenReason, if set, is text the failure must contain. Use it so
	// that a broken implementation which fails for some unrelated reason
	// stops counting as evidence.
	//
	// Argued is for when no such implementation can be built: record why,
	// in a sentence. Set at most one of the two. Setting neither is
	// allowed and the report says so — the check is unproven, which is
	// honest, and different from proven.
	ProvenBy     MixedDefect
	ProvenReason string
	Argued       string

	// Prop is a body whose inputs are drawn rather than fixed, run many
	// times with the draws shrunk on failure. Report through the PropT
	// and not through a testing.TB: shrinking works by replaying draws, and
	// a failure raised anywhere else is one the run cannot narrow.
	//
	// Requires Method, like Run.
	Prop func(rt *PropT, s Mixed, fx MixedFixture)

	// PropStore is Prop with Store's own argument already drawn
	// from the pool the generated checks draw it from — so an override you
	// set on the run reaches your property too. Fixes the check's scope to
	// Store, so leave Method empty.
	PropStore func(rt *PropT, s Mixed, value validates.Payload)

	// PropRead is Prop with Read's own argument already drawn
	// from the pool the generated checks draw it from — so an override you
	// set on the run reaches your property too. Fixes the check's scope to
	// Read, so leave Method empty.
	PropRead func(rt *PropT, s Mixed, key string)
}

// mixedMethods is the interface's method names, used to catch a typo in
// a check's Method field before the run starts.
//
// Without it a misspelled name would be accepted — it looks like any
// other method name — and the check would be filed under a method that
// does not exist, where nobody could find or drop it.
var mixedMethods = suite.NewNameSet("Mixed", mixedStore, mixedValidate, mixedRead)

// bind converts one of your checks into the form the runner uses, tying
// it to this run's sample inputs — which is what lets a check you wrote
// see the same values, and the same overrides, as the generated ones.
func (c MixedCheck) bind(
	fx MixedFixture,
) (suite.Check[Mixed], error) {
	out := suite.Check[Mixed]{
		Claim: c.Claim, Class: c.Class, Needs: c.Needs,
	}
	if out.Class == "" {
		out.Class = suite.ClassHandWritten
	}

	var err error

	// bodies counts what this row set and the runtime refuses any answer
	// but one; fields is the listing that refusal offers, which has to
	// name what THIS interface can set; scoped says the body it set is
	// one that reads the row's Method. A contributing tier's dispatch
	// lands below and may move all three.
	bodies, fields, scoped := 0, "Run, RunWith", false
	if c.Run != nil {
		scoped = true
		bodies++
		if out.ID, err = suite.RowID("Run", c.Method, c.Name, mixedMethods); err != nil {
			return out, err
		}
		run := c.Run
		out.Run = func(tb testing.TB, s Mixed) {
			run(tb, s, fx)
		}
	}
	if c.RunWith != nil {
		bodies++
		out.ID = suite.HandRowID(c.Name)
		rw := c.RunWith
		out.RunWith = func(tb testing.TB, sub MixedSubject) {
			rw(tb, sub, fx)
		}
	}
	fields += ", Prop, PropStore, PropRead"
	if c.Prop != nil {
		scoped = true
		bodies++
		if out.ID, err = suite.RowID("Prop", c.Method, c.Name, mixedMethods); err != nil {
			return out, err
		}
		fn := c.Prop
		out.RunWith = func(tb testing.TB, sub suite.Subject[Mixed]) {
			model.Check(tb, func(rt *PropT) {
				fn(rt, sub.New(tb), fx)
			})
		}
	}
	if c.PropStore != nil {
		bodies++
		out.ID = suite.MethodID(mixedStore, c.Name)
		fn := c.PropStore
		out.RunWith = func(tb testing.TB, sub suite.Subject[Mixed]) {
			model.Check(tb, func(rt *PropT) {
				fn(rt, sub.New(tb), mixedModelValues(fx).Draw(rt, "value"))
			})
		}
	}
	if c.PropRead != nil {
		bodies++
		out.ID = suite.MethodID(mixedRead, c.Name)
		fn := c.PropRead
		out.RunWith = func(tb testing.TB, sub suite.Subject[Mixed]) {
			model.Check(tb, func(rt *PropT) {
				fn(rt, sub.New(tb), mixedModelKeys(fx).Draw(rt, "key"))
			})
		}
	}
	if err := suite.OneBody(c.Name, bodies, fields); err != nil {
		return out, err
	}
	if c.Method != "" && !scoped {
		return out, fmt.Errorf(
			"check %q sets Method, but its body fixes its own scope; drop Method", c.Name)
	}
	if out.Falsifiable, err = suite.Falsify(c.Name, c.ProvenBy != nil, c.Argued); err != nil {
		return out, err
	}
	return out, nil
}

// RunMixed runs every check — the generated ones and any you
// wrote — against every implementation you pass it.
//
// Each argument describes one thing to do, in any order: an
// implementation to test, a table of your own checks, sample inputs to
// use, or checks to leave out.
//
//	RunMixed(t,
//		MixedHarness[*InMemory]{Name: "in-memory", New: NewInMemory},
//		MixedSuite.Without(MixedSuite.Checks.Store.Smoke()),
//	)
//
// Pass two implementations to compare them against each other, and mark
// the one you trust as the Oracle. Every check runs as its own subtest
// named after the implementation and the check, so `go test -run` can
// select one.
//
// A check that needs something your implementation has not supplied
// fails rather than skipping, and says which field to fill in. That is
// deliberate: a skipped check is how a claim goes unchecked while the
// run stays green.
func RunMixed(
	t *testing.T, opts ...MixedRunOpt,
) {
	t.Helper()
	var rc mixedRunConfig
	for _, o := range opts {
		o.applyTo(&rc)
	}
	fx := mixedNewFixture()
	for _, row := range rc.rows {
		rc.AddCheck(row.bind(fx))
	}
	// Checked here, after reading every argument and before running
	// anything: a misconfigured run reports all of its problems at once
	// rather than one per attempt.
	rc.Fail(t, "RunMixed")
	suite.Run(t,
		mixedSuite(fx).With(rc.Extra...).Without(rc.Drops...),
		rc.Subjects...)
}

// mixedProofs is every defect this run derived and can spell.
//
// Each is the smallest implementation that breaks exactly one claim: the
// generated double with one method overridden, and nothing else changed.
// The reason beside it is the substring the red must contain, so a defect
// that died on an unrelated guard stops counting as evidence.
//
// Unexported and built fresh per call. A defect carries a constructor
// that registers cleanup on the test it is handed, so a shared map would
// hand one test's cleanup to the next.
func mixedProofs() prove.Defects[Mixed] {
	ix := MixedSuite.Checks
	return prove.Defects[Mixed]{
		ix.Store.Smoke(): prove.One("a Mixed whose Store panics",
			func(tb testing.TB) Mixed {
				return NewMixedStub(tb, WithMixedStore(
					func(_ context.Context, _ validates.Payload) error {
						panic("planted: Store panics")
					}))
			}).Reasoned(suite.RedPanicked),
		ix.Store.Cancels(): prove.One("a Mixed whose Store ignores the context it is handed",
			func(tb testing.TB) Mixed {
				return NewMixedStub(tb, WithMixedStore(
					func(_ context.Context, _ validates.Payload) (err error) {
						// The call arrives and nothing is done with it; the bare
						// return answers every slot's zero, which for the error
						// slot is the nil this claim forbids.
						return
					}))
			}).Reasoned(suite.RedCancelled),
		ix.Store.NilContext(): prove.One("a Mixed whose Store forgives a nil context and answers",
			func(tb testing.TB) Mixed {
				return NewMixedStub(tb, WithMixedStore(
					func(_ context.Context, _ validates.Payload) (err error) {
						// The call arrives and nothing is done with it; the bare
						// return answers every slot's zero, which for the error
						// slot is the nil this claim forbids.
						return
					}))
			}).Reasoned(suite.RedNilContext),
		ix.Store.Deadline(): prove.One("a Mixed whose Store ignores the context it is handed",
			func(tb testing.TB) Mixed {
				return NewMixedStub(tb, WithMixedStore(
					func(_ context.Context, _ validates.Payload) (err error) {
						// The call arrives and nothing is done with it; the bare
						// return answers every slot's zero, which for the error
						// slot is the nil this claim forbids.
						return
					}))
			}).Reasoned(suite.RedDeadline),
		ix.Validate.Smoke(): prove.One("a Mixed whose Validate panics",
			func(tb testing.TB) Mixed {
				return NewMixedStub(tb, WithMixedValidate(
					func(_ validates.Payload) error {
						panic("planted: Validate panics")
					}))
			}).Reasoned(suite.RedPanicked),
		ix.Read.Smoke(): prove.One("a Mixed whose Read panics",
			func(tb testing.TB) Mixed {
				return NewMixedStub(tb, WithMixedRead(
					func(_ context.Context, _ string) (validates.Payload, error) {
						panic("planted: Read panics")
					}))
			}).Reasoned(suite.RedPanicked),
		ix.Read.Cancels(): prove.One("a Mixed whose Read ignores the context it is handed",
			func(tb testing.TB) Mixed {
				return NewMixedStub(tb, WithMixedRead(
					func(_ context.Context, _ string) (r0 validates.Payload, err error) {
						// The call arrives and nothing is done with it; the bare
						// return answers every slot's zero, which for the error
						// slot is the nil this claim forbids.
						return
					}))
			}).Reasoned(suite.RedCancelled),
		ix.Read.NilContext(): prove.One("a Mixed whose Read forgives a nil context and answers",
			func(tb testing.TB) Mixed {
				return NewMixedStub(tb, WithMixedRead(
					func(_ context.Context, _ string) (r0 validates.Payload, err error) {
						// The call arrives and nothing is done with it; the bare
						// return answers every slot's zero, which for the error
						// slot is the nil this claim forbids.
						return
					}))
			}).Reasoned(suite.RedNilContext),
		ix.Read.Deadline(): prove.One("a Mixed whose Read ignores the context it is handed",
			func(tb testing.TB) Mixed {
				return NewMixedStub(tb, WithMixedRead(
					func(_ context.Context, _ string) (r0 validates.Payload, err error) {
						// The call arrives and nothing is done with it; the bare
						// return answers every slot's zero, which for the error
						// slot is the nil this claim forbids.
						return
					}))
			}).Reasoned(suite.RedDeadline),
		ix.Read.ZeroOnError(): prove.One("a Mixed whose Read answers a believable value beside its error",
			func(tb testing.TB) Mixed {
				return NewMixedStub(tb, WithMixedRead(
					func(_ context.Context, _ string) (r0 validates.Payload, err error) {
						// A believable answer beside the refusal. A caller
						// reading the error and one reading the value disagree
						// about what happened, which is the claim's own
						// violation rather than a subject that merely failed.
						r0 = validates.Payload{Key: "other-payload"}
						err = errors.New("planted: Read refused with a believable value")
						return
					}))
			}),
		ix.Store.Validates(): prove.One("a Mixed whose Store refuses everything it is handed",
			func(tb testing.TB) Mixed {
				return NewMixedStub(tb, WithMixedStore(
					func(_ context.Context, _ validates.Payload) (err error) {
						err = errors.New("planted: Store refuses everything it is handed")
						return
					}))
			}),
		ix.Read.Miss(): prove.One("a Mixed whose Read answers for an input nothing wrote",
			func(tb testing.TB) Mixed {
				return NewMixedStub(tb, WithMixedRead(
					func(_ context.Context, _ string) (r0 validates.Payload, err error) {
						// A value for a call a correct subject answers nothing for.
						r0 = validates.Payload{Key: "other-payload"}
						return
					}))
			}),
		ix.Model.Agrees(): prove.One("a Mixed whose Store reports success and keeps nothing",
			func(tb testing.TB) Mixed {
				return NewMixedStub(tb, WithMixedStore(
					func(_ context.Context, _ validates.Payload) (err error) {
						// The call arrives and nothing is done with it; the bare
						// return answers every slot's zero, which for the error
						// slot is the nil this claim forbids.
						return
					}))
			}),
		ix.Sim.Recovery(): prove.One("a Mixed whose rebuild finds an empty medium",
			func(testing.TB) Mixed {
				return NewMixedModelReference()
			}).RecoveringFresh(),
		ix.Model.WriteObservable(): prove.One("a Mixed whose Store reports success and keeps nothing",
			func(tb testing.TB) Mixed {
				return NewMixedStub(tb, WithMixedStore(
					func(_ context.Context, _ validates.Payload) (err error) {
						// The call arrives and nothing is done with it; the bare
						// return answers every slot's zero, which for the error
						// slot is the nil this claim forbids.
						return
					}))
			}),
	}
}

// ProveMixed runs every check — the generated ones and any you
// wrote — against the deliberately broken implementation it names, and
// fails if the check does not catch it.
//
//	func TestMyChecksCanFail(t *testing.T) {
//		ProveMixed(t, MixedHarness[*InMemory]{Name: "in-memory", New: NewInMemory}, myChecks)
//	}
//
// A check that always passes is indistinguishable from a working one
// until something breaks in production. This is what tells them apart:
// give each check a ProvenBy, and this proves the check can fail.
//
// A check with no ProvenBy is not ignored — it has to say why, in
// Argued. The two are held level in both directions: claiming proof
// without a broken implementation fails here, and supplying one for a
// check that claims nothing fails too.
//
// It takes the same arguments RunMixed does, and for one reason: a
// check may need a capability, and the answer is a fact about this
// interface rather than about any one implementation. The harness is
// where you write it once. A planted defect stands in for a real
// subject, so it borrows the same answer rather than being asked for one
// of its own — which nothing here could supply.
func ProveMixed(
	t *testing.T, opts ...MixedRunOpt,
) {
	t.Helper()
	var rc mixedRunConfig
	for _, o := range opts {
		o.applyTo(&rc)
	}
	// The RUN's config, not the derived one: a check proven at default
	// pools carries no evidence about the pools a run actually uses.
	fx := mixedNewFixture()
	for _, row := range rc.rows {
		rc.AddCheck(row.bind(fx))
	}
	rc.Fail(t, "ProveMixed")
	s := mixedSuite(fx).With(rc.Extra...).Without(rc.Drops...)
	// Read off the subjects, because a door is answered once for the
	// interface and every subject of it reads the same answer.
	doors := suite.Doors(rc.Subjects...)
	defects := mixedProofs()
	for _, row := range rc.rows {
		if row.ProvenBy == nil {
			continue
		}
		bd, err := row.bind(fx)
		if err != nil {
			t.Fatalf("ProveMixed: %v", err)
		}
		sub, err := row.ProvenBy.Subject()
		if err != nil {
			t.Fatalf("ProveMixed: check %q: defect: %v", bd.ID, err)
		}
		defects[bd.ID] = prove.Defect[Mixed]{
			Subject: sub, Reason: row.ProvenReason,
		}
	}
	// A declined check takes its proof with it: proving a row the run was
	// told to leave out reports on a claim this package no longer makes,
	// and the parity gate fails naming a check the set does not hold.
	for _, id := range rc.Drops {
		delete(defects, id)
	}
	prove.All(t, s.Checks, defects.Answering(doors))
}

// GreenMixed runs every check — the generated ones and any you
// wrote — against an implementation that is CORRECT but different, and
// fails if a check rejects it.
//
//	func TestAnotherPolicyIsAllowed(t *testing.T) {
//		GreenMixed(t, suite.Subject[Mixed]{
//			Name: "evicts the newest", New: newNewestFirst,
//		})
//	}
//
// ProveMixed measures whether these checks can fire. This measures
// whether they fire SELECTIVELY. Nothing else here can tell a check that
// is right from one that is too strong: a check forbidding something the
// declaration permits looks exactly like a suite working, until somebody
// writes a legal implementation and it fails.
//
// The control is a real alternative, not a broken one — a different
// eviction victim, a delivery that duplicates where the contract allows
// it, a lazier evaluation behind the same boundary. Where a check
// genuinely cannot apply to your control, put its ID in the subject's
// Excused map: an excused check is skipped by name, because it yields no
// evidence either way.
//
// Same arguments as RunMixed, so the control meets the checks
// the run does — including the ones you wrote, which no caller can bind
// for themselves.
func GreenMixed(
	t *testing.T,
	control suite.Subject[Mixed],
	opts ...MixedRunOpt,
) {
	t.Helper()
	var rc mixedRunConfig
	for _, o := range opts {
		o.applyTo(&rc)
	}
	fx := mixedNewFixture()
	for _, row := range rc.rows {
		rc.AddCheck(row.bind(fx))
	}
	rc.Fail(t, "GreenMixed")
	s := mixedSuite(fx).With(rc.Extra...).Without(rc.Drops...)
	// The doors the run answers, so a control is refused for being wrong
	// rather than for being unwired — a wiring red recorded as "the suite
	// rejected correct code" would poison the measurement it exists for.
	for door, answer := range suite.Doors(rc.Subjects...) {
		if control.Provides == nil {
			control.Provides = map[suite.Capability]any{}
		}
		if _, answered := control.Provides[door]; !answered {
			control.Provides[door] = answer
		}
	}
	prove.Green(t, s.Checks, control)
}

// A second version check, for the leg idioms the rows above ride. The
// harness's own covers the check format; this one covers what a model row
// does with it. Regenerate the file to clear a mismatch.
var _ = legs.CompatV1

// mixedModelRows is what this package's model tier claims.
//
// Every row here needs sequences of calls judged against something
// outside the subject, which is what separates them from the rows
// above: those settle a claim with a fixed call sequence, and these
// cannot be stated that way at all. That is also why each takes the
// Subject rather than an instance — a sequence run builds its own, and
// some of them build two.
func mixedModelRows(fx MixedFixture) []suite.Check[Mixed] {
	return []suite.Check[Mixed]{
		{
			ID:          mixedCheckIndex.Model.Agrees(),
			Class:       suite.ClassDifferential,
			Claim:       "every operation sequence leaves the subject agreeing with the reference",
			Falsifiable: suite.Proven(),
			Strength:    suite.StrengthDifferential,
			RunWith: func(tb testing.TB, sub suite.Subject[Mixed]) {
				mixedAssertAgrees(tb, sub, fx)
			},
		},
		{
			ID:          mixedCheckIndex.Model.Linearizable(),
			Class:       suite.ClassConcurrent,
			Claim:       "concurrent operation histories are linearizable",
			Falsifiable: suite.Argued("no mechanical rule plants a defect for this claim; the ones that would are domain composites, which no rule reaches from shape and stamps alone"),
			Strength:    suite.StrengthDifferential,
			RunWith: func(tb testing.TB, sub suite.Subject[Mixed]) {
				mixedAssertLinearizable(tb, sub, fx)
			},
		},
		{
			ID:    mixedCheckIndex.Sim.Recovery(),
			Class: suite.ClassSimRecovery,
			Claim: "every acknowledged write is still readable after the process is rebuilt over its medium",
			Needs: suite.Caps{
				suite.CapRecover: nil,
			},
			Falsifiable: suite.Proven(),
			Strength:    suite.StrengthDifferential,
			RunWith: func(tb testing.TB, sub suite.Subject[Mixed]) {
				mixedAssertRecovery(tb, sub, fx)
			},
		},
		{
			ID:    mixedCheckIndex.Model.WriteObservable(),
			Class: suite.ClassLaws,
			Claim: "a written value is readable under the key it was written with",
			Binds: []string{
				lawid.WriteObservable,
			},
			Falsifiable: suite.Proven(),
			Strength:    suite.StrengthDifferential,
			RunWith: func(tb testing.TB, sub suite.Subject[Mixed]) {
				mixedAssertWriteObservable(tb, sub, fx)
			},
		},
	}
}

// --- Mixed's model tier -------------------------------------------
//
// Random sequences of Mixed's methods, run against every subject and
// something that judges them from outside. The rows on the run surface
// above carry it, and MixedSuite.Without declines any of them by name.
//
//	Reference: derived — a keyed map over the Payload fixture pair,
//	           keyed on Key; NewMixedModelReference replaces it
//	Sequences: Store (writer), Read (reader)
//	Values:    the fixture pair — the validates claim on Store licenses refusing values no derivation can predict
//	Not driven:
//	           Validate — the validates.fn partner — a validator, whose call proves nothing its smoke check does not

// mixedModelKeys is the key pool every key slot draws from.
//
// Two keys, and deliberately not more: collision density is what makes a
// read revisit a write and an overwrite land on held state. A wide key
// pool would pass every comparison over a history that never collides.
func mixedModelKeys(fx MixedFixture) *model.Generator[string] {
	// Widened unconditionally: this run emits no config, so there is no
	// pool a consumer could have narrowed and nothing to gate on. The
	// provenance argument applies to a pool somebody passed, and nobody
	// can pass one here.
	return legs.Blend(true,
		model.SampledFrom([]string{fx.Key(), fx.KeyOther()}),
		func(s string) string { return string(s) },
	)
}

// mixedModelValues is the value pool every value slot draws from.
//
// The fixture pair alone — the validates claim on Store licenses refusing values no derivation can predict.
func mixedModelValues(fx MixedFixture) *model.Generator[validates.Payload] {
	bodies := model.SampledFrom([]validates.Payload{fx.Payload(), fx.PayloadOther()})
	return bodies
}

// mixedModelMiss is what the reference reports for a key nothing
// wrote. Only its presence is compared — a subject reports its own miss
// sentinel, and the run asks whether both sides missed, not how they spelled
// it. Where the declaration stamps a sentinel of its own, the oracle takes
// that identity instead and this var is not declared.
var mixedModelMiss = errors.New("mixed: the model reference holds nothing under the key")

// mixedModelKeyOf projects a value's identity — the one derivation the
// reference keys on and every keyed law reuses, so the two cannot disagree
// about which field is the key.
func mixedModelKeyOf(v validates.Payload) string {
	return v.Key
}

// mixedModelReference adapts the shipped MapStore oracle to Mixed.
// Deliberately simple: its correctness is read, not tested.
type mixedModelReference struct {
	store *ref.MapStore[string, validates.Payload]
}

// NewMixedModelReference builds one. Exported because a consumer whose
// semantics outrun their shape replaces it, and because the proof beside
// this file drives it as a subject of its own.
func NewMixedModelReference() Mixed {
	return &mixedModelReference{store: ref.NewMapStore[string, validates.Payload](
		mixedModelKeyOf,
		mixedModelMiss,
	)}
}

func (r *mixedModelReference) Store(ctx context.Context, v validates.Payload) error {
	return r.store.Put(ctx, v)
}

// Validate is inert: the validates.fn partner — a validator, whose call proves nothing its smoke check does not. The laws that would compare the
// subject against an inert body are not bound.
func (r *mixedModelReference) Validate(v validates.Payload) (r0 error) { return }

func (r *mixedModelReference) Read(ctx context.Context, key string) (validates.Payload, error) {
	return r.store.Get(ctx, key)
}

// mixedModelActions is the operation vocabulary both legs drive.
//
// One constructor per method shape, from the engine's action set rather
// than hand-written closures: the constructors record inputs and outputs
// into the trace a law reads, compare the two sides the same way for every
// action, and shrink a failing sequence to the shortest one that still
// fails.
func mixedModelActions(fx MixedFixture) []model.Action[Mixed] {
	keys := mixedModelKeys(fx)
	values := mixedModelValues(fx)
	return []model.Action[Mixed]{
		action.Writer("Store", values,
			func(ctx context.Context, s validates.Mixed, v validates.Payload) error {
				return s.Store(ctx, v)
			}),
		action.Reader("Read", keys,
			func(ctx context.Context, s validates.Mixed, k string) (validates.Payload, error) {
				return s.Read(ctx, k)
			}),
	}
}

// mixedAssertAgrees drives random operation sequences against the subject and
// the reference, comparing after every call.
//
// The differential is the strongest oracle this tier has, and it is this
// leg's whole job: no laws are registered, so nothing competes with it and
// a disagreement is what ends the run.
func mixedAssertAgrees(
	tb testing.TB,
	sub suite.Subject[Mixed],
	fx MixedFixture,
) {
	tb.Helper()
	legs.Differential(tb, sub,
		NewMixedModelReference,
		mixedModelActions(fx))
}

// mixedAssertLinearizable drives concurrent workers against one instance and asks
// whether the history they recorded has a serial explanation.
//
// A claim no sequential leg can state. The differential compares one
// ordered run against a reference and the laws hold after each step of
// one; this is about what a caller may observe when there is no single
// order at all, and the model is what decides whether one exists.
//
// The engine owns the interleaving, the property loop and the artifact a
// failing history is written to. This supplies the verbs and the model.
func mixedAssertLinearizable(
	tb testing.TB,
	sub suite.Subject[Mixed],
	fx MixedFixture,
) {
	tb.Helper()
	keys := mixedModelKeys(fx)
	values := mixedModelValues(fx)
	legs.Concurrent(tb, sub,
		NewMixedModelReference,
		model.ConcurrentConfig[Mixed]{
			Model: linearize.KV[string, validates.Payload](nil),
			Actions: []model.ConcurrentAction[Mixed]{
				linearize.ConcurrentReader(linearize.OpGet, keys,
					func(ctx context.Context, s validates.Mixed, k string) (validates.Payload, error) {
						return s.Read(ctx, k)
					}),
				linearize.ConcurrentWriter(linearize.OpPut, values,
					func(ctx context.Context, s validates.Mixed, v validates.Payload) error {
						return s.Store(ctx, v)
					},
					mixedModelKeyOf),
			},
		})
}

// mixedAssertRecovery drives a drawn schedule of writes, reads and crashes,
// and asks whether the medium still owes what the writes promised.
//
// A claim no other leg in this file can state. The differential compares
// two live instances and the laws hold after each step of one; this is
// about what is left when an instance stops existing mid-run, which is a
// question only the medium can answer.
//
// The engine owns the interleaving, the shrinking and the oracle. This
// supplies the verbs and the two pools they draw from.
func mixedAssertRecovery(
	tb testing.TB,
	sub suite.Subject[Mixed],
	fx MixedFixture,
) {
	tb.Helper()
	legs.Recover[Mixed, string, validates.Payload](tb, sub,
		crash.Schedule[Mixed, string, validates.Payload]{
			Values: mixedModelValues(fx),
			Keys:   mixedModelKeys(fx),
			KeyOf:  mixedModelKeyOf,
			Write: func(ctx context.Context, world Mixed, v validates.Payload) error {
				return validates.Mixed(world).Store(ctx, v)
			},
			Read: func(ctx context.Context, world Mixed, k string) (validates.Payload, error) {
				return validates.Mixed(world).Read(ctx, k)
			},
			Equal:  func(a, b validates.Payload) bool { return a == b },
			Absent: nil,
		})
}

// mixedAssertWriteObservable binds AUTO-WRITE-OBSERVABLE over the shared sequences.
//
// One law, and the run's only oracle. The differential is off here, as
// on every law leg: with it armed a subject broken anywhere disagrees at
// step 0, and whether THIS law can catch a defect stays unanswerable.
func mixedAssertWriteObservable(
	tb testing.TB,
	sub suite.Subject[Mixed],
	fx MixedFixture,
) {
	tb.Helper()
	values := mixedModelValues(fx)

	buildRef, tier := legs.Reference(tb, sub, NewMixedModelReference)
	sub.NoteTier(tier)
	legs.Law(tb, sub,
		func() Mixed { return sub.New(tb) }, buildRef,
		mixedModelActions(fx),
		[]law.Law[Mixed]{
			law.WriteObservable[validates.Mixed, validates.Payload, string]{
				Write: func(rt *model.T, s validates.Mixed, v validates.Payload) error {
					return s.Store(rt.Context(), v)
				},
				Read: func(rt *model.T, s validates.Mixed, k string) (validates.Payload, error) {
					return s.Read(rt.Context(), k)
				},
				Values: values,
				KeyOf:  mixedModelKeyOf,
			},
		})
}

// PropT is the property state a Prop body receives: the run's
// draws, and the failure reporting that shrinks a counterexample.
//
// An alias, so it is the engine's own type — this is here only so a
// property you write names PropT rather than obliging your test
// file to import the engine directly.
type PropT = model.T

// testkit: end of generated content.
// testkit:provenance 91b08f95125ce50e0132c43e7e993dc200208252326641ad24a99ec5dcf02338
