// Code generated by testkit. DO NOT EDIT.
//
// Source:    corpus/iface/mixin/xsssafe/iface.go
// Plugins:   golang 1.0.0, suite 1.24.0, backend.golang 1.0.0
// Command:   testkit run ./corpus/...

package xsssafetest_test

import (
	"testing"

	"go.thesmos.sh/testkit/conformance/corpus/iface/mixin/xsssafe/xsssafetest"
	"go.thesmos.sh/testkit/engine/suite"
)

// The planted defects live in the file beside this one, on ProveMixed.
//
// They were here once, and could not stay: a check may need a capability,
// and only your harness answers it. A defect stands in for a real subject
// and borrows the same answer — which a test function in this package has
// no way to reach, because the harness is written in yours. So the map
// went where the entry point that takes it lives, and ProveMixed
// drives every defect below alongside the ones your own rows name:
//
//	Render.Smoke — a Mixed whose Render panics
//
//	Render.Cancels — a Mixed whose Render ignores the context it is handed
//
//	Render.NilContext — a Mixed whose Render forgives a nil context and answers
//
//	Render.Deadline — a Mixed whose Render ignores the context it is handed
//
//	Render.ZeroOnError — a Mixed whose Render answers a believable value beside its error

// TestMixedInvariants holds this package to what it says about itself.
//
// Four claims, none of which a consumer writes and none of which any
// other gate makes. The manifest pins the assertion SET, so a check that
// stops being emitted reads as a removed row in review rather than as a
// suite that quietly got smaller. The index and the drop hints pin the
// two ways a check is NAMED — an index entry pointing at nothing
// compiles, and a drop hint that falls back to the string form forfeits
// exactly the compile-break the index exists to give. The distinct-ID
// check catches two interfaces in one package claiming one identity,
// which method-name scopes make possible.
func TestMixedInvariants(t *testing.T) {
	t.Parallel()

	s := xsssafetest.MixedSuite.Suite(xsssafetest.DefaultMixedFixture())

	rows, err := suite.LockLines(s)
	if err != nil {
		t.Fatalf("render the manifest rows: %v", err)
	}
	suite.VerifyLock(t, "mixed.checks.lock", rows)
	suite.VerifyIndex(t, "Mixed",
		xsssafetest.MixedSuite.Checks.All(), s.IDs())
	suite.VerifyDropHints(t, "Mixed", s.IDs(), s.DropHint)
	suite.VerifyDistinctIDs(t, s.IDs())
}

// testkit: end of generated content.
// testkit:provenance cd0faa404ad8fb6cf50618269408c2b82c1b8699383c7658aabc388da49c58c4
