// Code generated by testkit. DO NOT EDIT.
//
// Source:    corpus/iface/contract/cache/iface.go
// Plugins:   golang 1.0.0, stub 1.4.0, backend.golang 1.0.0
// Command:   testkit run ./corpus/...

package cachetest_test

import (
	"context"
	"testing"
	"time"

	"go.thesmos.sh/testkit"
	"go.thesmos.sh/testkit/clock"
	"go.thesmos.sh/testkit/conformance/corpus/iface/contract/cache"
	"go.thesmos.sh/testkit/conformance/corpus/iface/contract/cache/cachetest"
	"go.thesmos.sh/testkit/rand"
	"go.thesmos.sh/testkit/stub"
)

// contractStubLookupSubject binds Lookup into the shape
// [stub.Behaviour] drives: how to call it, what it answers with, and how to
// override it.
//
// Each call builds a fresh double, because several of the checks assert on
// failure and need one bound to a failable TB rather than to the running
// test.
func contractStubLookupSubject(tb testing.TB) stub.Subject[cachetest.ContractLookupCall, cachetest.ContractLookupReturn] {
	tb.Helper()
	s := cachetest.NewContractStub(tb)
	return stub.Subject[cachetest.ContractLookupCall, cachetest.ContractLookupReturn]{
		Stub: s.OnLookup.MethodStub,
		Call: func() {
			var a0 context.Context
			var a1 string = "test-key"
			_, _ = s.Lookup(a0, a1)
		},
		Result: func() cachetest.ContractLookupReturn {
			var a0 context.Context
			var a1 string = "test-key"
			got0, got1 := s.Lookup(a0, a1)
			return cachetest.ContractLookupReturn{Result: got0, Err: got1}
		},
		Override: func(mark func()) {
			s.OnLookup.Func(func(_ context.Context, _ string) (cache.Value, error) {
				mark()
				var z0 cache.Value
				var z1 error
				return z0, z1
			})
		},
		Fails: func() error {
			var a0 context.Context
			var a1 string = "test-key"
			_, r1 := s.Lookup(a0, a1)
			return r1
		},
	}
}

// TestContractStubLookup pins how Lookup answers.
//
// Recording, resetting, call-count expectations, strict mode, fault injection
// and zero-value dispatch are the same contract for every method, so they are
// asserted once in [stub.Behaviour] rather than restated here. What remains
// below needs a value this method's signature can tell apart from a zero one.
func TestContractStubLookup(t *testing.T) {
	t.Parallel()

	stub.Behaviour(t, "Lookup", contractStubLookupSubject)

	// No check that Lookup answers what Returns pinned: no result of
	// its signature admits a literal this generator can write, so the only
	// value available to pin is the zero — which an unconfigured double
	// answers anyway. stub.Behaviour asserts that half honestly.
	t.Run("records what it was called with", func(t *testing.T) {
		t.Parallel()
		// Asserting only that a call happened would pass against a double
		// that recorded the wrong arguments, which is the failure a reader
		// most needs the log to surface.
		s := cachetest.NewContractStub(t)
		var a0 context.Context
		var a1 string = "test-key"
		_, _ = s.Lookup(a0, a1)
		got := s.OnLookup.AssertCalledOnce(t, "Lookup must record the call")
		testkit.Equal(t, got.Ctx, a0, "the recorded call carries Ctx")
		testkit.Equal(t, got.Key, a1, "the recorded call carries Key")
	})

	t.Run("fires the OnRecord hook for every call", func(t *testing.T) {
		t.Parallel()
		// The hook fires synchronously as each call lands, which is what a
		// concurrency test observes progress with — polling the log instead
		// races the thing under test.
		s := cachetest.NewContractStub(t)
		var seen []cachetest.ContractLookupCall
		s.OnLookup.OnRecord(func(c cachetest.ContractLookupCall) { seen = append(seen, c) })
		var a0 context.Context
		var a1 string = "test-key"
		_, _ = s.Lookup(a0, a1)
		_, _ = s.Lookup(a0, a1)
		testkit.Len(t, seen, 2, "OnRecord must fire once per Lookup call")
	})

	t.Run("wires WithContractLookup at construction", func(t *testing.T) {
		t.Parallel()
		called := false
		s := cachetest.NewContractStub(t, cachetest.WithContractLookup(func(_ context.Context, _ string) (cache.Value, error) {
			called = true
			var z0 cache.Value
			var z1 error
			return z0, z1
		}))
		var a0 context.Context
		var a1 string = "test-key"
		_, _ = s.Lookup(a0, a1)
		testkit.True(t, called, "WithContractLookup must install the override")
	})

	t.Run("keeps recording across a reset", func(t *testing.T) {
		t.Parallel()
		// The weaker claim, and the honest one for this signature. No result
		// of Lookup admits a literal, so what Returns pinned cannot be
		// told from the zero and comparing them would pass either way.
		//
		// What a reset can still be held to is that it clears the log without
		// taking the double with it: configure, call, reset, call again, and
		// exactly one call is recorded. A reset that dropped the whole
		// configuration fails that, which is the failure the value comparison
		// was reaching for and could not state.
		s := cachetest.NewContractStub(t)
		var want0 cache.Value
		var want1 error
		s.OnLookup.Returns(want0, want1)
		var a0 context.Context
		var a1 string = "test-key"
		_, _ = s.Lookup(a0, a1)
		s.ResetCalls()
		_, _ = s.Lookup(a0, a1)
		s.OnLookup.AssertCalledOnce(t, "Lookup must record the call that followed the reset")
	})
}

// contractStubFetchSubject binds Fetch into the shape
// [stub.Behaviour] drives: how to call it, what it answers with, and how to
// override it.
//
// Each call builds a fresh double, because several of the checks assert on
// failure and need one bound to a failable TB rather than to the running
// test.
func contractStubFetchSubject(tb testing.TB) stub.Subject[cachetest.ContractFetchCall, cachetest.ContractFetchReturn] {
	tb.Helper()
	s := cachetest.NewContractStub(tb)
	return stub.Subject[cachetest.ContractFetchCall, cachetest.ContractFetchReturn]{
		Stub: s.OnFetch.MethodStub,
		Call: func() {
			var a0 context.Context
			var a1 string = "test-key"
			_, _ = s.Fetch(a0, a1)
		},
		Result: func() cachetest.ContractFetchReturn {
			var a0 context.Context
			var a1 string = "test-key"
			got0, got1 := s.Fetch(a0, a1)
			return cachetest.ContractFetchReturn{Result: got0, Err: got1}
		},
		Override: func(mark func()) {
			s.OnFetch.Func(func(_ context.Context, _ string) (cache.Value, error) {
				mark()
				var z0 cache.Value
				var z1 error
				return z0, z1
			})
		},
		Fails: func() error {
			var a0 context.Context
			var a1 string = "test-key"
			_, r1 := s.Fetch(a0, a1)
			return r1
		},
	}
}

// TestContractStubFetch pins how Fetch answers.
//
// Recording, resetting, call-count expectations, strict mode, fault injection
// and zero-value dispatch are the same contract for every method, so they are
// asserted once in [stub.Behaviour] rather than restated here. What remains
// below needs a value this method's signature can tell apart from a zero one.
func TestContractStubFetch(t *testing.T) {
	t.Parallel()

	stub.Behaviour(t, "Fetch", contractStubFetchSubject)

	// No check that Fetch answers what Returns pinned: no result of
	// its signature admits a literal this generator can write, so the only
	// value available to pin is the zero — which an unconfigured double
	// answers anyway. stub.Behaviour asserts that half honestly.
	t.Run("records what it was called with", func(t *testing.T) {
		t.Parallel()
		// Asserting only that a call happened would pass against a double
		// that recorded the wrong arguments, which is the failure a reader
		// most needs the log to surface.
		s := cachetest.NewContractStub(t)
		var a0 context.Context
		var a1 string = "test-key"
		_, _ = s.Fetch(a0, a1)
		got := s.OnFetch.AssertCalledOnce(t, "Fetch must record the call")
		testkit.Equal(t, got.Ctx, a0, "the recorded call carries Ctx")
		testkit.Equal(t, got.Key, a1, "the recorded call carries Key")
	})

	t.Run("fires the OnRecord hook for every call", func(t *testing.T) {
		t.Parallel()
		// The hook fires synchronously as each call lands, which is what a
		// concurrency test observes progress with — polling the log instead
		// races the thing under test.
		s := cachetest.NewContractStub(t)
		var seen []cachetest.ContractFetchCall
		s.OnFetch.OnRecord(func(c cachetest.ContractFetchCall) { seen = append(seen, c) })
		var a0 context.Context
		var a1 string = "test-key"
		_, _ = s.Fetch(a0, a1)
		_, _ = s.Fetch(a0, a1)
		testkit.Len(t, seen, 2, "OnRecord must fire once per Fetch call")
	})

	t.Run("wires WithContractFetch at construction", func(t *testing.T) {
		t.Parallel()
		called := false
		s := cachetest.NewContractStub(t, cachetest.WithContractFetch(func(_ context.Context, _ string) (cache.Value, error) {
			called = true
			var z0 cache.Value
			var z1 error
			return z0, z1
		}))
		var a0 context.Context
		var a1 string = "test-key"
		_, _ = s.Fetch(a0, a1)
		testkit.True(t, called, "WithContractFetch must install the override")
	})

	t.Run("keeps recording across a reset", func(t *testing.T) {
		t.Parallel()
		// The weaker claim, and the honest one for this signature. No result
		// of Fetch admits a literal, so what Returns pinned cannot be
		// told from the zero and comparing them would pass either way.
		//
		// What a reset can still be held to is that it clears the log without
		// taking the double with it: configure, call, reset, call again, and
		// exactly one call is recorded. A reset that dropped the whole
		// configuration fails that, which is the failure the value comparison
		// was reaching for and could not state.
		s := cachetest.NewContractStub(t)
		var want0 cache.Value
		var want1 error
		s.OnFetch.Returns(want0, want1)
		var a0 context.Context
		var a1 string = "test-key"
		_, _ = s.Fetch(a0, a1)
		s.ResetCalls()
		_, _ = s.Fetch(a0, a1)
		s.OnFetch.AssertCalledOnce(t, "Fetch must record the call that followed the reset")
	})
}

// contractStubDouble describes how to build a ContractStub under each
// option whose effect is the same whatever a method's signature.
//
// Lookup stands in for the double as a whole: what these checks assert
// is that an option reached it at all, and the first method witnesses that as
// well as any other would.
func contractStubDouble() stub.Double[cachetest.ContractLookupCall] {
	instance := func(s *cachetest.ContractStub) stub.Instance[cachetest.ContractLookupCall] {
		return stub.Instance[cachetest.ContractLookupCall]{
			Stub: s.OnLookup.MethodStub,
			Call: func() {
				var a0 context.Context
				var a1 string = "test-key"
				_, _ = s.Lookup(a0, a1)
			},
			Reset: s.ResetCalls,
		}
	}
	return stub.Double[cachetest.ContractLookupCall]{
		New: func(tb testing.TB) stub.Instance[cachetest.ContractLookupCall] {
			return instance(cachetest.NewContractStub(tb))
		},
		WithClock: func(tb testing.TB, clk clock.Clock) stub.Instance[cachetest.ContractLookupCall] {
			return instance(cachetest.NewContractStub(tb, cachetest.ContractStubWithClock(clk)))
		},
		WithRandSource: func(tb testing.TB, src rand.Source) stub.Instance[cachetest.ContractLookupCall] {
			return instance(cachetest.NewContractStub(tb, cachetest.ContractStubWithRandSource(src)))
		},
		BenchMode: func(tb testing.TB) stub.Instance[cachetest.ContractLookupCall] {
			return instance(cachetest.NewContractStub(tb, cachetest.ContractStubBenchMode()))
		},
		Strict: func(tb testing.TB) stub.Instance[cachetest.ContractLookupCall] {
			return instance(cachetest.NewContractStub(tb, cachetest.ContractStubStrict()))
		},
	}
}

// TestContractStubOptions pins the settings that apply to the double rather
// than to one method: bench mode, the injected clock and random source, and
// what a reset clears.
func TestContractStubOptions(t *testing.T) {
	t.Parallel()

	stub.DoubleBehaviour(t, contractStubDouble())
}

// TestContractStubDelegateTo pins that a wrapped implementation is called
// through, and recorded on the way past.
//
// This is what lets one generated suite run against both the double and a
// production type, which is the point of conformance testing.
func TestContractStubDelegateTo(t *testing.T) {
	t.Parallel()

	inner := cachetest.NewContractStub(t)
	s := cachetest.NewContractStub(t, cachetest.ContractStubDelegateTo(inner))

	t.Run("forwards Lookup to the wrapped implementation", func(t *testing.T) {
		var a0 context.Context
		var a1 string = "test-key"
		_, _ = s.Lookup(a0, a1)
		inner.OnLookup.AssertCalledOnce(t, "Lookup must reach the wrapped implementation")
	})

	t.Run("surfaces what Lookup answered", func(t *testing.T) {
		// Reaching the wrapped implementation is not enough: a double that
		// called through and then discarded the answer would pass the check
		// above while telling its caller nothing true.
		want := testkit.TestError("Lookup-delegate")
		inner.OnLookup.FaultsFor(time.Hour, want)
		var a0 context.Context
		var a1 string = "test-key"
		_, r1 := s.Lookup(a0, a1)
		testkit.ErrorIs(t, r1, want, "Lookup must surface the wrapped answer")
	})

	t.Run("forwards Fetch to the wrapped implementation", func(t *testing.T) {
		var a0 context.Context
		var a1 string = "test-key"
		_, _ = s.Fetch(a0, a1)
		inner.OnFetch.AssertCalledOnce(t, "Fetch must reach the wrapped implementation")
	})

	t.Run("surfaces what Fetch answered", func(t *testing.T) {
		// Reaching the wrapped implementation is not enough: a double that
		// called through and then discarded the answer would pass the check
		// above while telling its caller nothing true.
		want := testkit.TestError("Fetch-delegate")
		inner.OnFetch.FaultsFor(time.Hour, want)
		var a0 context.Context
		var a1 string = "test-key"
		_, r1 := s.Fetch(a0, a1)
		testkit.ErrorIs(t, r1, want, "Fetch must surface the wrapped answer")
	})
}

// testkit: end of generated content.
// testkit:provenance 27bd6bfab8f5e45c3c162a0ac6835c6d541ecec4588f1c66c6fca184deefb411
