// Code generated by testkit. DO NOT EDIT.
//
// Source:    corpus/iface/detector/reader/iface.go
// Plugins:   golang 1.0.0, suite 1.24.0, backend.golang 1.0.0
// Command:   testkit run ./corpus/...

package readertest_test

import (
	"testing"

	"go.thesmos.sh/testkit/conformance/corpus/iface/detector/reader/readertest"
	"go.thesmos.sh/testkit/engine/suite"
)

// The planted defects live in the file beside this one, on ProveReader.
//
// They were here once, and could not stay: a check may need a capability,
// and only your harness answers it. A defect stands in for a real subject
// and borrows the same answer — which a test function in this package has
// no way to reach, because the harness is written in yours. So the map
// went where the entry point that takes it lives, and ProveReader
// drives every defect below alongside the ones your own rows name:
//
//	Get.Smoke — a Reader whose Get panics
//
//	Get.Cancels — a Reader whose Get ignores the context it is handed
//
//	Get.NilContext — a Reader whose Get forgives a nil context and answers
//
//	Get.Deadline — a Reader whose Get ignores the context it is handed
//
//	Get.ZeroOnError — a Reader whose Get answers a believable value beside its error
//
//	Get.Miss — a Reader whose Get answers for an input nothing wrote

// TestReaderInvariants holds this package to what it says about itself.
//
// Four claims, none of which a consumer writes and none of which any
// other gate makes. The manifest pins the assertion SET, so a check that
// stops being emitted reads as a removed row in review rather than as a
// suite that quietly got smaller. The index and the drop hints pin the
// two ways a check is NAMED — an index entry pointing at nothing
// compiles, and a drop hint that falls back to the string form forfeits
// exactly the compile-break the index exists to give. The distinct-ID
// check catches two interfaces in one package claiming one identity,
// which method-name scopes make possible.
func TestReaderInvariants(t *testing.T) {
	t.Parallel()

	s := readertest.ReaderSuite.Suite(readertest.DefaultReaderFixture())

	rows, err := suite.LockLines(s)
	if err != nil {
		t.Fatalf("render the manifest rows: %v", err)
	}
	suite.VerifyLock(t, "reader.checks.lock", rows)
	suite.VerifyIndex(t, "Reader",
		readertest.ReaderSuite.Checks.All(), s.IDs())
	suite.VerifyDropHints(t, "Reader", s.IDs(), s.DropHint)
	suite.VerifyDistinctIDs(t, s.IDs())
}

// testkit: end of generated content.
// testkit:provenance 19ed910042c0b40722ba5e969a49f6386fa6544c80c637780a3d5ecc9d52a5e2
