// Code generated by testkit. DO NOT EDIT.
//
// Source:    corpus/iface/detector/reader/iface.go
// Plugins:   golang 1.0.0, suite 1.20.0, backend.golang 1.0.0
// Command:   testkit run ./corpus/...

package readertest

import (
	"context"
	"errors"
	"fmt"
	"testing"

	"go.thesmos.sh/testkit/conformance/corpus/iface/detector/reader"
	"go.thesmos.sh/testkit/engine/suite"
	"go.thesmos.sh/testkit/engine/suite/prove"
)

// Conformance checks for Reader, worked out from its declaration.
//
// One call runs all of them against one implementation. Describe the
// implementation in a literal and hand it over:
//
//	func TestMine(t *testing.T) {
//		RunReader(t, ReaderHarness[*Mine]{Name: "mine", New: NewMine})
//	}
//
// Nothing else is required to start. The rest is here when you need it:
//
//	ReaderHarness
//	    one implementation under test. Add a field only when a check
//	    fails asking for it — the failure names the field to fill in.
//	ReaderChecks
//	    checks you write yourself, for the claims only you can make.
//	    They run beside the generated ones and are the same kind of value.
//	ProveReader
//	    runs each of your checks against the broken implementation it
//	    names, and fails if the check does not catch it.
//	ReaderSuite.Checks.<Method>.<Check>()
//	    names one check, so you can drop it. Written this way it stops
//	    compiling if a later regeneration no longer emits that check,
//	    rather than silently dropping nothing.
//
// The checks this file runs:
//
//	Get/cancel
//	Get/deadline
//	Get/miss
//	Get/nilcontext
//	Get/smoke
//	Get/zero-on-error
//
// A version check, performed by the compiler. If this file was generated
// against a testkit whose check format differs from the one you are
// building with, this line fails to compile and names the mismatch —
// instead of the two disagreeing quietly while the tests still pass.
// Regenerate the file to clear it.
var _ = suite.CompatV2

// ReaderFixture holds the sample inputs the checks call your
// implementation with, worked out from each method's parameter types.
//
// Every input comes as a pair: a value, and a second one guaranteed to
// differ from it. Both are needed for a check to mean anything — looking
// up a key that was just stored proves nothing on its own unless there
// is also a key that was never stored.
//
// A parameter whose type has no value that can be written down — a func,
// a channel, a type your declaration does not import — is left at its
// zero value, and the checks that needed it were not emitted at all
// rather than run against something meaningless. Those are listed above.
// A check you write yourself is handed this either way.
type ReaderFixture struct {
	key      string
	keyOther string
}

// DefaultReaderFixture is what a run with no config draws.
func DefaultReaderFixture() ReaderFixture {
	return readerNewFixture()
}

// readerNewFixture builds the sample inputs for one run.
//
// Read these through the methods below rather than as fields. A value you
// supplied through the config and one worked out from the type are read
// the same way, and no check should be able to tell them apart.
func readerNewFixture() ReaderFixture {
	return ReaderFixture{
		key:      "test-key",
		keyOther: "other-key",
	}
}

// Key is the key the checks call your implementation with.
func (f ReaderFixture) Key() string { return f.key }

// KeyOther is a second key, guaranteed to differ from the
// first — so a check that expects to find nothing is asking about
// something your implementation has genuinely never been given.
func (f ReaderFixture) KeyOther() string { return f.keyOther }

// Reader is your interface, under a local name.
//
// An alias, so it is the same type — this is here only so the rest of
// this file can refer to it without repeating its import path, and so a
// check you write can name it too.
type Reader = reader.Reader

// ReaderSubject is what a RunWith check receives instead of a single
// instance: a handle that can build more of them.
//
// Use it for a claim one instance cannot state on its own — that two
// instances do not share state, that a value survives being closed and
// reopened.
type ReaderSubject = suite.Subject[Reader]

// ReaderRunOpt is anything you can pass to RunReader: an
// implementation to test, a table of your own checks, a config, or a
// check to drop. Order does not matter.
type ReaderRunOpt interface {
	applyTo(*readerRunConfig)
}

type readerRunConfig struct {
	suite.Bundle[Reader]

	// rows are the checks you wrote, held until every argument has been
	// read and then tied to this run's inputs. Tying them on arrival
	// would bind them to inputs a later argument replaces.
	rows ReaderChecks
}

// ReaderHarness describes one Reader implementation to test.
//
// Name and one constructor are all that is required. Every other field
// unlocks the checks that need it, and you do not have to work out which
// in advance: run it, and any check that needs more fails saying which
// field to add.
type ReaderHarness[T Reader] struct {
	Name string

	// Set exactly one.
	//
	// Use New if construction cannot fail; use Start if it needs the
	// test's lifetime — a temp directory to clean up, a connection to
	// close. Start is handed the testing.TB to register that on.
	New   func() T
	Start func(tb testing.TB) T

	// Excuse lists checks this implementation cannot meaningfully take —
	// not ones it fails, ones it has no way to answer. An in-memory
	// implementation has no storage to survive a restart, so a check
	// about restarting it is asking the impossible.
	//
	// Excused checks are reported as excused, never as passed.
	Excuse []suite.ID

	// Oracle marks this implementation as the one others are compared
	// against, when you are testing more than one. At most one may set it.
	// Pick the implementation you trust most.
	Oracle bool

	// Serial runs this implementation's checks one at a time, and never
	// alongside another implementation's. Set it for something that
	// cannot take being constructed many times at once — a real database,
	// a fixed port.
	Serial bool

	// Provide supplies anything a check needs that has no field of its
	// own above. You will not need it unless a check fails asking for a
	// named capability, and that failure tells you the name to use here.
	Provide map[suite.Capability]any
}

// Subject converts this description into the form the runner uses, and
// reports anything wrong with it — no constructor, or two.
func (h ReaderHarness[T]) Subject() (suite.Subject[Reader], error) {
	build, err := suite.OneCtor(h.Name, h.New, h.Start)
	if err != nil {
		return suite.Subject[Reader]{}, err
	}
	return suite.Subject[Reader]{
		Name:     h.Name,
		Provides: h.Provide,
		New:      func(tb testing.TB) Reader { return build(tb) },
		Oracle:   h.Oracle,
		Serial:   h.Serial,
		Excused:  suite.ExcuseSet(h.Excuse),
	}, nil
}

func (h ReaderHarness[T]) applyTo(rc *readerRunConfig) {
	rc.AddSubject(h.Subject())
}

type readerDropOpt []suite.ID

func (d readerDropOpt) applyTo(rc *readerRunConfig) {
	rc.AddDrops(d...)
}

// readerWithout drops the named checks from the run.
func readerWithout(ids ...suite.ID) ReaderRunOpt {
	return readerDropOpt(ids)
}

// --- Naming checks ----------------------------------------------------------

// ReaderSuite is how you name a check — to drop it, or to
// point at it from a tool.
var ReaderSuite = readerVeneer{Checks: readerCheckIndex}

type readerVeneer struct {
	// Checks names every check this file runs, by method:
	//
	//	ReaderSuite.Checks.<Method>.<Check>()
	//
	// Prefer this over writing the check's name as a string. If a later
	// regeneration stops emitting that check, this stops compiling —
	// where the string would silently drop nothing.
	Checks readerCheckIndexT
}

// Without drops the named checks from the run.
//
//	RunReader(t, mine, ReaderSuite.Without(
//		ReaderSuite.Checks.Get.Smoke()))
//
// Dropping is recorded in the run's report, so a check you removed is
// visible rather than simply absent.
func (readerVeneer) Without(ids ...suite.ID) ReaderRunOpt {
	return readerWithout(ids...)
}

// Suite returns the checks as plain data, if you are building a tool over
// them or running them yourself.
//
// RunReader is the normal way in; this is for when you need the
// checks as values rather than as a run.
func (readerVeneer) Suite(fx ReaderFixture) suite.Suite[Reader] {
	return readerSuite(fx)
}

// --- Failure messages -------------------------------------------------------

// readerIndexPath maps each check to the expression you would
// write to drop it, so that a check which cannot run tells you what to
// type rather than only what went wrong.
var readerIndexPath = map[suite.ID]string{
	readerCheckIndex.Get.Smoke():       "ReaderSuite.Checks.Get.Smoke()",
	readerCheckIndex.Get.Cancels():     "ReaderSuite.Checks.Get.Cancels()",
	readerCheckIndex.Get.NilContext():  "ReaderSuite.Checks.Get.NilContext()",
	readerCheckIndex.Get.Deadline():    "ReaderSuite.Checks.Get.Deadline()",
	readerCheckIndex.Get.ZeroOnError(): "ReaderSuite.Checks.Get.ZeroOnError()",
	readerCheckIndex.Get.Miss():        "ReaderSuite.Checks.Get.Miss()",
}

var readerDropHint = suite.DropHinter(
	"ReaderSuite", readerIndexPath,
)

// The names this file uses in more than one place, declared once each so
// they cannot drift apart.
const (
	readerGet = "Get"
)

// readerCheckIndex names every check in this file, grouped by method.
// Reach it through ReaderSuite.Checks.
var readerCheckIndex = readerCheckIndexT{
	Get: readerGetChecks{},
}

type readerCheckIndexT struct {
	Get readerGetChecks
}

// All returns every ID this package emits.
func (readerCheckIndexT) All() []suite.ID {
	var out []suite.ID
	out = append(out, readerGetChecks{}.All()...)
	return out
}

type readerGetChecks struct{}

func (readerGetChecks) Smoke() suite.ID {
	return suite.MethodID(readerGet, suite.SegSmoke)
}

func (readerGetChecks) Cancels() suite.ID {
	return suite.MethodID(readerGet, suite.SegCancel)
}

func (readerGetChecks) NilContext() suite.ID {
	return suite.MethodID(readerGet, suite.SegNilContext)
}

func (readerGetChecks) Deadline() suite.ID {
	return suite.MethodID(readerGet, suite.SegDeadline)
}

func (readerGetChecks) ZeroOnError() suite.ID {
	return suite.MethodID(readerGet, suite.SegZeroValue)
}

func (readerGetChecks) Miss() suite.ID {
	return suite.MethodID(readerGet, suite.SegMiss)
}

func (readerGetChecks) All() []suite.ID {
	return []suite.ID{
		readerGetChecks{}.Smoke(),
		readerGetChecks{}.Cancels(),
		readerGetChecks{}.NilContext(),
		readerGetChecks{}.Deadline(),
		readerGetChecks{}.ZeroOnError(),
		readerGetChecks{}.Miss(),
	}
}

// readerSuite returns the checks as data, using the given inputs.
//
// It takes the built inputs rather than a config, because that is what
// the checks read. To start from the defaults, pass what a default run
// passes — ReaderSuite.Suite does exactly that.
func readerSuite(fx ReaderFixture) suite.Suite[Reader] {
	return suite.Suite[Reader]{
		Name:     "Reader",
		DropHint: readerDropHint,
		Checks:   readerSignatureChecks(fx),
	}
}

// readerSignatureChecks builds every check in this file.
//
// A check is marked as proven able to fail only when a deliberately
// broken implementation for it exists in the file beside this one.
// Where none could be built, the check says so instead — claiming proof
// without the evidence is refused, in both directions.
func readerSignatureChecks(fx ReaderFixture) []suite.Check[Reader] {
	sig := suite.ProvenCheck[Reader]
	ix := readerCheckIndex
	return []suite.Check[Reader]{
		sig(ix.Get.Smoke(), suite.ClassSmoke,
			"Get survives a call with a seeded key",
			func(tb testing.TB, r Reader) {
				readerAssertGetSmoke(tb, r, fx)
			}).At(suite.StrengthErrorOnly),
		sig(ix.Get.Cancels(), suite.ClassCancel,
			"Get reports a cancelled context as cancelled",
			func(tb testing.TB, r Reader) {
				readerAssertGetCancels(tb, r, fx)
			}).At(suite.StrengthErrorOnly),
		sig(ix.Get.NilContext(), suite.ClassNilContext,
			"Get returns an error rather than panicking on a nil context",
			func(tb testing.TB, r Reader) {
				readerAssertGetToleratesNilContext(tb, r, fx)
			}).At(suite.StrengthErrorOnly),
		sig(ix.Get.Deadline(), suite.ClassDeadline,
			"Get reports an expired deadline as exceeded",
			func(tb testing.TB, r Reader) {
				readerAssertGetHonoursDeadline(tb, r, fx)
			}).At(suite.StrengthErrorOnly),
		sig(ix.Get.ZeroOnError(), suite.ClassZeroValue,
			"Get returns the zero Value alongside any error",
			func(tb testing.TB, r Reader) {
				readerAssertGetZeroOnError(tb, r, fx)
			}).At(suite.StrengthObserved),
		sig(ix.Get.Miss(), suite.ClassReader,
			"Get reports ErrNotFound for a key nothing wrote",
			func(tb testing.TB, r Reader) {
				readerAssertGetMiss(tb, r, fx)
			}).At(suite.StrengthErrorOnly),
	}
}

// readerAssertGetSmoke asserts Get survives a call with a seeded key.
func readerAssertGetSmoke(
	tb testing.TB,
	r Reader,
	fx ReaderFixture,
) {
	tb.Helper()
	suite.Survives(tb, readerGet, func(ctx context.Context) {
		_, _ = r.Get(ctx, fx.Key())
	})
}

// readerAssertGetCancels asserts Get reports a cancelled context as cancelled.
func readerAssertGetCancels(
	tb testing.TB,
	r Reader,
	fx ReaderFixture,
) {
	tb.Helper()
	suite.ReportsCancelled(tb, readerGet, func(ctx context.Context) error {
		_, err := r.Get(ctx, fx.Key())
		return err
	})
}

// readerAssertGetToleratesNilContext asserts Get returns an error rather than panicking on a nil context.
func readerAssertGetToleratesNilContext(
	tb testing.TB,
	r Reader,
	fx ReaderFixture,
) {
	tb.Helper()
	suite.ToleratesNilContext(tb, readerGet, func(ctx context.Context) error {
		_, err := r.Get(ctx, fx.Key())
		return err
	})
}

// readerAssertGetHonoursDeadline asserts Get reports an expired deadline as exceeded.
func readerAssertGetHonoursDeadline(
	tb testing.TB,
	r Reader,
	fx ReaderFixture,
) {
	tb.Helper()
	suite.ReportsDeadlineExceeded(tb, readerGet, func(ctx context.Context) error {
		_, err := r.Get(ctx, fx.Key())
		return err
	})
}

// readerAssertGetZeroOnError asserts Get returns the zero Value alongside any error.
func readerAssertGetZeroOnError(
	tb testing.TB,
	r Reader,
	fx ReaderFixture,
) {
	tb.Helper()
	ctx := tb.Context()
	got, err := r.Get(ctx, fx.KeyOther())
	if err == nil {
		tb.Skipf("Get answered for an input nothing wrote, so this check has no error to " +
			"inspect; seed a miss through ReaderConfig.KeyPool")
	}

	var zero reader.Value
	if got != zero {
		tb.Errorf("Get must return the zero value alongside an error: got %+v, want %+v (err %v)",
			got, zero, err)
	}
}

// readerAssertGetMiss asserts Get reports ErrNotFound for a key nothing wrote.
func readerAssertGetMiss(
	tb testing.TB,
	r Reader,
	fx ReaderFixture,
) {
	tb.Helper()
	ctx := tb.Context()
	_, err := r.Get(ctx, fx.KeyOther())
	if !errors.Is(err, reader.ErrNotFound) {
		tb.Errorf("Get must report %v: got %v", reader.ErrNotFound, err)
	}
}

// ReaderDefect is a deliberately broken implementation, used as
// evidence that a check can fail. In practice you build one with
// BrokenReader over the generated test double.
type ReaderDefect interface {
	Subject() (ReaderSubject, error)
}

// BrokenReader describes an implementation built to break one
// specific claim, so that a check can be shown to catch it.
//
// Give it a name saying what is wrong, and a constructor. The best
// broken implementation is the generated double wrapping a correct one,
// with a single method overridden — correct everywhere except the one
// place the check is about.
func BrokenReader[T Reader](
	name string, build func() T,
) ReaderHarness[T] {
	return ReaderHarness[T]{
		Name: name, New: build,
	}
}

// ReaderChecks is a table of checks you write yourself, for the
// claims that cannot be worked out from the declaration — the ones that
// carry your domain.
//
// They are the same kind of value as the generated checks: they appear
// in the report, they can be dropped by name, and they can say what they
// need from an implementation. There is no second mechanism for them.
//
//	var myChecks = ReaderChecks{
//		{Method: "Get", Name: "my-claim",
//			Claim:    "a sentence stating exactly what this check proves",
//			Run:      myClaimBody,
//			ProvenBy: BrokenReader("an implementation that breaks it", newBroken)},
//	}
type ReaderChecks []ReaderCheck

func (c ReaderChecks) applyTo(rc *readerRunConfig) {
	rc.rows = append(rc.rows, c...)
}

// ReaderCheck is one check you wrote. The body is a plain named
// function; which field you put it in decides what it is handed.
type ReaderCheck struct {
	// Method groups this check under one of your methods, so it is named
	// Get/<Name> in output and reruns with the rest of that
	// method's checks. Leave it empty for a check that is not about one
	// method in particular.
	Method string

	// Name identifies this check, in output and when dropping it. Keep it
	// stable: it is what a colleague's Without call refers to.
	Name string

	// Claim is one sentence saying exactly what this check proves. It is
	// recorded in the manifest and read out in the report.
	//
	// Write only what the body actually establishes. "a second write
	// leaves the value unchanged" is a promise that something reads the
	// value back; if the body only checks the write returned no error,
	// say that instead. Nothing here can catch a claim that is wider
	// than its check, and a claim nobody verifies is worse than none.
	Claim string

	// Set exactly one.
	//
	// Run is handed one fresh instance, which suits nearly every check.
	// RunWith is handed something that can build instances, for a claim
	// one instance cannot state on its own: build two and compare them,
	// move the clock forward, put one into a failure state.
	//
	// Both are also handed the sample inputs, so a check you write draws
	// from the same values the generated ones do — override an input and
	// your check sees the override too.
	Run     func(tb testing.TB, s Reader, fx ReaderFixture)
	RunWith func(tb testing.TB, sub ReaderSubject, fx ReaderFixture)

	// Class groups this check in the report's summary. Optional; checks
	// you write are grouped as hand-written by default.
	Class suite.Class

	// Needs says what this check requires from an implementation beyond
	// being constructed — a clock it can move, a failure it can induce.
	//
	// An implementation that cannot supply it fails this check by name,
	// with the field to fill in named in the message. It never skips: a
	// check that quietly skipped for want of wiring would look exactly
	// like one that passed.
	Needs suite.Caps

	// ProvenBy is an implementation built to break this check and nothing
	// else. Setting it makes two statements at once — that the check can
	// fail, and here is the proof — and ProveReader fails unless the
	// broken implementation really does turn this check red.
	//
	// ProvenReason, if set, is text the failure must contain. Use it so
	// that a broken implementation which fails for some unrelated reason
	// stops counting as evidence.
	//
	// Argued is for when no such implementation can be built: record why,
	// in a sentence. Set at most one of the two. Setting neither is
	// allowed and the report says so — the check is unproven, which is
	// honest, and different from proven.
	ProvenBy     ReaderDefect
	ProvenReason string
	Argued       string
}

// readerMethods is the interface's method names, used to catch a typo in
// a check's Method field before the run starts.
//
// Without it a misspelled name would be accepted — it looks like any
// other method name — and the check would be filed under a method that
// does not exist, where nobody could find or drop it.
var readerMethods = suite.NewNameSet("Reader", readerGet)

// bind converts one of your checks into the form the runner uses, tying
// it to this run's sample inputs — which is what lets a check you wrote
// see the same values, and the same overrides, as the generated ones.
func (c ReaderCheck) bind(
	fx ReaderFixture,
) (suite.Check[Reader], error) {
	out := suite.Check[Reader]{
		Claim: c.Claim, Class: c.Class, Needs: c.Needs,
	}
	if out.Class == "" {
		out.Class = suite.ClassHandWritten
	}

	var err error
	bodies := 0
	if c.Run != nil {
		bodies++
		if out.ID, err = suite.RowID("Run", c.Method, c.Name, readerMethods); err != nil {
			return out, err
		}
		run := c.Run
		out.Run = func(tb testing.TB, s Reader) {
			run(tb, s, fx)
		}
	}
	if c.RunWith != nil {
		bodies++
		out.ID = suite.HandRowID(c.Name)
		rw := c.RunWith
		out.RunWith = func(tb testing.TB, sub ReaderSubject) {
			rw(tb, sub, fx)
		}
	}
	if err := suite.OneBody(c.Name, bodies, "Run, RunWith"); err != nil {
		return out, err
	}
	if c.Method != "" && c.Run == nil {
		return out, fmt.Errorf(
			"check %q sets Method, but its body fixes its own scope; drop Method", c.Name)
	}
	if out.Falsifiable, err = suite.Falsify(c.Name, c.ProvenBy != nil, c.Argued); err != nil {
		return out, err
	}
	return out, nil
}

// RunReader runs every check — the generated ones and any you
// wrote — against every implementation you pass it.
//
// Each argument describes one thing to do, in any order: an
// implementation to test, a table of your own checks, sample inputs to
// use, or checks to leave out.
//
//	RunReader(t,
//		ReaderHarness[*InMemory]{Name: "in-memory", New: NewInMemory},
//		ReaderSuite.Without(ReaderSuite.Checks.Get.Smoke()),
//	)
//
// Pass two implementations to compare them against each other, and mark
// the one you trust as the Oracle. Every check runs as its own subtest
// named after the implementation and the check, so `go test -run` can
// select one.
//
// A check that needs something your implementation has not supplied
// fails rather than skipping, and says which field to fill in. That is
// deliberate: a skipped check is how a claim goes unchecked while the
// run stays green.
func RunReader(
	t *testing.T, opts ...ReaderRunOpt,
) {
	t.Helper()
	var rc readerRunConfig
	for _, o := range opts {
		o.applyTo(&rc)
	}
	fx := readerNewFixture()
	for _, row := range rc.rows {
		rc.AddCheck(row.bind(fx))
	}
	// Checked here, after reading every argument and before running
	// anything: a misconfigured run reports all of its problems at once
	// rather than one per attempt.
	rc.Fail(t, "RunReader")
	suite.Run(t,
		readerSuite(fx).With(rc.Extra...).Without(rc.Drops...),
		rc.Subjects...)
}

// ProveReader runs each of your checks against the deliberately
// broken implementation it names, and fails if the check does not catch
// it.
//
//	func TestMyChecksCanFail(t *testing.T) { ProveReader(t, myChecks) }
//
// A check that always passes is indistinguishable from a working one
// until something breaks in production. This is what tells them apart:
// give each check a ProvenBy, and this proves the check can fail.
//
// A check with no ProvenBy is not ignored — it has to say why, in
// Argued. The two are held level in both directions: claiming proof
// without a broken implementation fails here, and supplying one for a
// check that claims nothing fails too.
func ProveReader(
	t *testing.T, checks ReaderChecks,
) {
	t.Helper()
	// The RUN's config, not the derived one: a check proven at default
	// pools carries no evidence about the pools a run actually uses.
	fx := readerNewFixture()
	bound := make([]suite.Check[Reader], 0, len(checks))
	defects := prove.Defects[Reader]{}
	for _, row := range checks {
		bd, err := row.bind(fx)
		if err != nil {
			t.Fatalf("ProveReader: %v", err)
		}
		bound = append(bound, bd)
		if row.ProvenBy == nil {
			continue
		}
		sub, err := row.ProvenBy.Subject()
		if err != nil {
			t.Fatalf("ProveReader: check %q: defect: %v", bd.ID, err)
		}
		defects[bd.ID] = prove.Defect[Reader]{
			Subject: sub, Reason: row.ProvenReason,
		}
	}
	prove.All(t, bound, defects)
}

// testkit: end of generated content.
// testkit:provenance c7a5161dce57517dc0f5dd63eb09311c543ff924a461f3bb9a74c901cb67c067
