// Code generated by testkit. DO NOT EDIT.
//
// Source:    corpus/iface/composite/tx-with-retry/iface.go
// Plugins:   golang 1.0.0, suite 1.19.0, backend.golang 1.0.0
// Command:   testkit run ./corpus/...

package txwithretrytest

import (
	"context"
	"fmt"
	"testing"

	txwithretry "go.thesmos.sh/testkit/conformance/corpus/iface/composite/tx-with-retry"
	"go.thesmos.sh/testkit/engine/legs"
	"go.thesmos.sh/testkit/engine/model"
	"go.thesmos.sh/testkit/engine/model/action"
	"go.thesmos.sh/testkit/engine/model/law"
	"go.thesmos.sh/testkit/engine/suite"
	"go.thesmos.sh/testkit/engine/suite/prove"
)

// Conformance checks for TxWithRetry, worked out from its declaration.
//
// One call runs all of them against one implementation. Describe the
// implementation in a literal and hand it over:
//
//	func TestMine(t *testing.T) {
//		RunTxWithRetry(t, TxWithRetryHarness[*Mine]{Name: "mine", New: NewMine})
//	}
//
// Nothing else is required to start. The rest is here when you need it:
//
//	TxWithRetryHarness
//	    one implementation under test. Add a field only when a check
//	    fails asking for it — the failure names the field to fill in.
//	TxWithRetryChecks
//	    checks you write yourself, for the claims only you can make.
//	    They run beside the generated ones and are the same kind of value.
//	ProveTxWithRetry
//	    runs each of your checks against the broken implementation it
//	    names, and fails if the check does not catch it.
//	TxWithRetrySuite.Checks.<Method>.<Check>()
//	    names one check, so you can drop it. Written this way it stops
//	    compiling if a later regeneration no longer emits that check,
//	    rather than silently dropping nothing.
//
// The checks this file runs:
//
//	Begin/cancel
//	Begin/nilcontext
//	Begin/smoke
//	Commit/cancel
//	Commit/nilcontext
//	Commit/smoke
//	Rollback/cancel
//	Rollback/nilcontext
//	Rollback/smoke
//
// Claims this file does NOT make. Each was worked out from your
// declaration and then declined, because something needed to state it
// is missing. The reason and the fix are given for each: the list above
// tells you what you have, and this tells you what you do not.
//
//	retrysucceeds on Commit — testkit has no rule for deriving a check from this declaration yet, so nothing here states it. To close it: write the check yourself, or report the gap — this one is testkit's to close, not yours.
//
// A version check, performed by the compiler. If this file was generated
// against a testkit whose check format differs from the one you are
// building with, this line fails to compile and names the mismatch —
// instead of the two disagreeing quietly while the tests still pass.
// Regenerate the file to clear it.
var _ = suite.CompatV2

// TxWithRetryFixture holds the sample inputs the checks call your
// implementation with, worked out from each method's parameter types.
//
// Every input comes as a pair: a value, and a second one guaranteed to
// differ from it. Both are needed for a check to mean anything — looking
// up a key that was just stored proves nothing on its own unless there
// is also a key that was never stored.
//
// A parameter whose type has no value that can be written down — a func,
// a channel, a type your declaration does not import — is left at its
// zero value, and the checks that needed it were not emitted at all
// rather than run against something meaningless. Those are listed above.
// A check you write yourself is handed this either way.
type TxWithRetryFixture struct {
}

// DefaultTxWithRetryFixture is what a run with no config draws.
func DefaultTxWithRetryFixture() TxWithRetryFixture {
	return txWithRetryNewFixture()
}

// txWithRetryNewFixture builds the sample inputs for one run.
//
// Read these through the methods below rather than as fields. A value you
// supplied through the config and one worked out from the type are read
// the same way, and no check should be able to tell them apart.
func txWithRetryNewFixture() TxWithRetryFixture {
	return TxWithRetryFixture{}
}

// TxWithRetry is your interface, under a local name.
//
// An alias, so it is the same type — this is here only so the rest of
// this file can refer to it without repeating its import path, and so a
// check you write can name it too.
type TxWithRetry = txwithretry.TxWithRetry

// TxWithRetrySubject is what a RunWith check receives instead of a single
// instance: a handle that can build more of them.
//
// Use it for a claim one instance cannot state on its own — that two
// instances do not share state, that a value survives being closed and
// reopened.
type TxWithRetrySubject = suite.Subject[TxWithRetry]

// TxWithRetryRunOpt is anything you can pass to RunTxWithRetry: an
// implementation to test, a table of your own checks, a config, or a
// check to drop. Order does not matter.
type TxWithRetryRunOpt interface {
	applyTo(*txWithRetryRunConfig)
}

type txWithRetryRunConfig struct {
	suite.Bundle[TxWithRetry]

	// rows are the checks you wrote, held until every argument has been
	// read and then tied to this run's inputs. Tying them on arrival
	// would bind them to inputs a later argument replaces.
	rows TxWithRetryChecks
}

// TxWithRetryHarness describes one TxWithRetry implementation to test.
//
// Name and one constructor are all that is required. Every other field
// unlocks the checks that need it, and you do not have to work out which
// in advance: run it, and any check that needs more fails saying which
// field to add.
type TxWithRetryHarness[T TxWithRetry] struct {
	Name string

	// Set exactly one.
	//
	// Use New if construction cannot fail; use Start if it needs the
	// test's lifetime — a temp directory to clean up, a connection to
	// close. Start is handed the testing.TB to register that on.
	New   func() T
	Start func(tb testing.TB) T

	// Excuse lists checks this implementation cannot meaningfully take —
	// not ones it fails, ones it has no way to answer. An in-memory
	// implementation has no storage to survive a restart, so a check
	// about restarting it is asking the impossible.
	//
	// Excused checks are reported as excused, never as passed.
	Excuse []suite.ID

	// Oracle marks this implementation as the one others are compared
	// against, when you are testing more than one. At most one may set it.
	// Pick the implementation you trust most.
	Oracle bool

	// Serial runs this implementation's checks one at a time, and never
	// alongside another implementation's. Set it for something that
	// cannot take being constructed many times at once — a real database,
	// a fixed port.
	Serial bool

	// Provide supplies anything a check needs that has no field of its
	// own above. You will not need it unless a check fails asking for a
	// named capability, and that failure tells you the name to use here.
	Provide map[suite.Capability]any
}

// Subject converts this description into the form the runner uses, and
// reports anything wrong with it — no constructor, or two.
func (h TxWithRetryHarness[T]) Subject() (suite.Subject[TxWithRetry], error) {
	build, err := suite.OneCtor(h.Name, h.New, h.Start)
	if err != nil {
		return suite.Subject[TxWithRetry]{}, err
	}
	return suite.Subject[TxWithRetry]{
		Name:     h.Name,
		Provides: h.Provide,
		New:      func(tb testing.TB) TxWithRetry { return build(tb) },
		Oracle:   h.Oracle,
		Serial:   h.Serial,
		Excused:  suite.ExcuseSet(h.Excuse),
	}, nil
}

func (h TxWithRetryHarness[T]) applyTo(rc *txWithRetryRunConfig) {
	rc.AddSubject(h.Subject())
}

type txWithRetryDropOpt []suite.ID

func (d txWithRetryDropOpt) applyTo(rc *txWithRetryRunConfig) {
	rc.AddDrops(d...)
}

// txWithRetryWithout drops the named checks from the run.
func txWithRetryWithout(ids ...suite.ID) TxWithRetryRunOpt {
	return txWithRetryDropOpt(ids)
}

// --- Naming checks ----------------------------------------------------------

// TxWithRetrySuite is how you name a check — to drop it, or to
// point at it from a tool.
var TxWithRetrySuite = txWithRetryVeneer{Checks: txWithRetryCheckIndex}

type txWithRetryVeneer struct {
	// Checks names every check this file runs, by method:
	//
	//	TxWithRetrySuite.Checks.<Method>.<Check>()
	//
	// Prefer this over writing the check's name as a string. If a later
	// regeneration stops emitting that check, this stops compiling —
	// where the string would silently drop nothing.
	Checks txWithRetryCheckIndexT
}

// Without drops the named checks from the run.
//
//	RunTxWithRetry(t, mine, TxWithRetrySuite.Without(
//		TxWithRetrySuite.Checks.Begin.Smoke()))
//
// Dropping is recorded in the run's report, so a check you removed is
// visible rather than simply absent.
func (txWithRetryVeneer) Without(ids ...suite.ID) TxWithRetryRunOpt {
	return txWithRetryWithout(ids...)
}

// Suite returns the checks as plain data, if you are building a tool over
// them or running them yourself.
//
// RunTxWithRetry is the normal way in; this is for when you need the
// checks as values rather than as a run.
func (txWithRetryVeneer) Suite() suite.Suite[TxWithRetry] {
	return txWithRetrySuite()
}

// --- Failure messages -------------------------------------------------------

// txWithRetryIndexPath maps each check to the expression you would
// write to drop it, so that a check which cannot run tells you what to
// type rather than only what went wrong.
var txWithRetryIndexPath = map[suite.ID]string{
	txWithRetryCheckIndex.Begin.Smoke():         "TxWithRetrySuite.Checks.Begin.Smoke()",
	txWithRetryCheckIndex.Begin.Cancels():       "TxWithRetrySuite.Checks.Begin.Cancels()",
	txWithRetryCheckIndex.Begin.NilContext():    "TxWithRetrySuite.Checks.Begin.NilContext()",
	txWithRetryCheckIndex.Commit.Smoke():        "TxWithRetrySuite.Checks.Commit.Smoke()",
	txWithRetryCheckIndex.Commit.Cancels():      "TxWithRetrySuite.Checks.Commit.Cancels()",
	txWithRetryCheckIndex.Commit.NilContext():   "TxWithRetrySuite.Checks.Commit.NilContext()",
	txWithRetryCheckIndex.Rollback.Smoke():      "TxWithRetrySuite.Checks.Rollback.Smoke()",
	txWithRetryCheckIndex.Rollback.Cancels():    "TxWithRetrySuite.Checks.Rollback.Cancels()",
	txWithRetryCheckIndex.Rollback.NilContext(): "TxWithRetrySuite.Checks.Rollback.NilContext()",
	txWithRetryCheckIndex.Model.Laws():          "TxWithRetrySuite.Checks.Model.Laws()",
}

var txWithRetryDropHint = suite.DropHinter(
	"TxWithRetrySuite", txWithRetryIndexPath,
)

// The names this file uses in more than one place, declared once each so
// they cannot drift apart.
const (
	txWithRetryBegin    = "Begin"
	txWithRetryCommit   = "Commit"
	txWithRetryRollback = "Rollback"

	// The interface's word inside a family-scoped identity.
	txWithRetryQualifier = "tx-with-retry"
)

// txWithRetryCheckIndex names every check in this file, grouped by method.
// Reach it through TxWithRetrySuite.Checks.
var txWithRetryCheckIndex = txWithRetryCheckIndexT{
	Begin:    txWithRetryBeginChecks{},
	Commit:   txWithRetryCommitChecks{},
	Rollback: txWithRetryRollbackChecks{},
	Model:    txWithRetryModelChecks{},
}

type txWithRetryCheckIndexT struct {
	Begin    txWithRetryBeginChecks
	Commit   txWithRetryCommitChecks
	Rollback txWithRetryRollbackChecks
	Model    txWithRetryModelChecks
}

// All returns every ID this package emits.
func (txWithRetryCheckIndexT) All() []suite.ID {
	var out []suite.ID
	out = append(out, txWithRetryBeginChecks{}.All()...)
	out = append(out, txWithRetryCommitChecks{}.All()...)
	out = append(out, txWithRetryRollbackChecks{}.All()...)
	out = append(out, txWithRetryModelChecks{}.All()...)
	return out
}

type txWithRetryBeginChecks struct{}

func (txWithRetryBeginChecks) Smoke() suite.ID {
	return suite.MethodID(txWithRetryBegin, suite.SegSmoke)
}

func (txWithRetryBeginChecks) Cancels() suite.ID {
	return suite.MethodID(txWithRetryBegin, suite.SegCancel)
}

func (txWithRetryBeginChecks) NilContext() suite.ID {
	return suite.MethodID(txWithRetryBegin, suite.SegNilContext)
}

func (txWithRetryBeginChecks) All() []suite.ID {
	return []suite.ID{
		txWithRetryBeginChecks{}.Smoke(),
		txWithRetryBeginChecks{}.Cancels(),
		txWithRetryBeginChecks{}.NilContext(),
	}
}

type txWithRetryCommitChecks struct{}

func (txWithRetryCommitChecks) Smoke() suite.ID {
	return suite.MethodID(txWithRetryCommit, suite.SegSmoke)
}

func (txWithRetryCommitChecks) Cancels() suite.ID {
	return suite.MethodID(txWithRetryCommit, suite.SegCancel)
}

func (txWithRetryCommitChecks) NilContext() suite.ID {
	return suite.MethodID(txWithRetryCommit, suite.SegNilContext)
}

func (txWithRetryCommitChecks) All() []suite.ID {
	return []suite.ID{
		txWithRetryCommitChecks{}.Smoke(),
		txWithRetryCommitChecks{}.Cancels(),
		txWithRetryCommitChecks{}.NilContext(),
	}
}

type txWithRetryRollbackChecks struct{}

func (txWithRetryRollbackChecks) Smoke() suite.ID {
	return suite.MethodID(txWithRetryRollback, suite.SegSmoke)
}

func (txWithRetryRollbackChecks) Cancels() suite.ID {
	return suite.MethodID(txWithRetryRollback, suite.SegCancel)
}

func (txWithRetryRollbackChecks) NilContext() suite.ID {
	return suite.MethodID(txWithRetryRollback, suite.SegNilContext)
}

func (txWithRetryRollbackChecks) All() []suite.ID {
	return []suite.ID{
		txWithRetryRollbackChecks{}.Smoke(),
		txWithRetryRollbackChecks{}.Cancels(),
		txWithRetryRollbackChecks{}.NilContext(),
	}
}

type txWithRetryModelChecks struct{}

func (txWithRetryModelChecks) Laws() suite.ID {
	return suite.FamilyID(suite.FamilyModel, txWithRetryQualifier, suite.SegLaws)
}

func (txWithRetryModelChecks) All() []suite.ID {
	return []suite.ID{
		txWithRetryModelChecks{}.Laws(),
	}
}

// txWithRetrySuite returns the checks as data, using the given inputs.
//
// It takes the built inputs rather than a config, because that is what
// the checks read. To start from the defaults, pass what a default run
// passes — TxWithRetrySuite.Suite does exactly that.
func txWithRetrySuite() suite.Suite[TxWithRetry] {
	return suite.Suite[TxWithRetry]{
		Name:     "TxWithRetry",
		DropHint: txWithRetryDropHint,
		Checks: append(txWithRetrySignatureChecks(),
			txWithRetryModelRows()...),
	}
}

// txWithRetrySignatureChecks builds every check in this file.
//
// A check is marked as proven able to fail only when a deliberately
// broken implementation for it exists in the file beside this one.
// Where none could be built, the check says so instead — claiming proof
// without the evidence is refused, in both directions.
func txWithRetrySignatureChecks() []suite.Check[TxWithRetry] {
	sig := suite.ProvenCheck[TxWithRetry]
	ix := txWithRetryCheckIndex
	return []suite.Check[TxWithRetry]{
		sig(ix.Begin.Smoke(), suite.ClassSmoke,
			"Begin survives a call",
			func(tb testing.TB, t TxWithRetry) {
				txWithRetryAssertBeginSmoke(tb, t)
			}).At(suite.StrengthErrorOnly),
		sig(ix.Begin.Cancels(), suite.ClassCancel,
			"Begin reports a cancelled context as cancelled",
			func(tb testing.TB, t TxWithRetry) {
				txWithRetryAssertBeginCancels(tb, t)
			}).At(suite.StrengthErrorOnly),
		sig(ix.Begin.NilContext(), suite.ClassNilContext,
			"Begin returns an error rather than panicking on a nil context",
			func(tb testing.TB, t TxWithRetry) {
				txWithRetryAssertBeginToleratesNilContext(tb, t)
			}).At(suite.StrengthErrorOnly),
		sig(ix.Commit.Smoke(), suite.ClassSmoke,
			"Commit survives a call",
			func(tb testing.TB, t TxWithRetry) {
				txWithRetryAssertCommitSmoke(tb, t)
			}).At(suite.StrengthErrorOnly),
		sig(ix.Commit.Cancels(), suite.ClassCancel,
			"Commit reports a cancelled context as cancelled",
			func(tb testing.TB, t TxWithRetry) {
				txWithRetryAssertCommitCancels(tb, t)
			}).At(suite.StrengthErrorOnly),
		sig(ix.Commit.NilContext(), suite.ClassNilContext,
			"Commit returns an error rather than panicking on a nil context",
			func(tb testing.TB, t TxWithRetry) {
				txWithRetryAssertCommitToleratesNilContext(tb, t)
			}).At(suite.StrengthErrorOnly),
		sig(ix.Rollback.Smoke(), suite.ClassSmoke,
			"Rollback survives a call",
			func(tb testing.TB, t TxWithRetry) {
				txWithRetryAssertRollbackSmoke(tb, t)
			}).At(suite.StrengthErrorOnly),
		sig(ix.Rollback.Cancels(), suite.ClassCancel,
			"Rollback reports a cancelled context as cancelled",
			func(tb testing.TB, t TxWithRetry) {
				txWithRetryAssertRollbackCancels(tb, t)
			}).At(suite.StrengthErrorOnly),
		sig(ix.Rollback.NilContext(), suite.ClassNilContext,
			"Rollback returns an error rather than panicking on a nil context",
			func(tb testing.TB, t TxWithRetry) {
				txWithRetryAssertRollbackToleratesNilContext(tb, t)
			}).At(suite.StrengthErrorOnly),
	}
}

// txWithRetryAssertBeginSmoke asserts Begin survives a call.
func txWithRetryAssertBeginSmoke(
	tb testing.TB,
	t TxWithRetry,
) {
	tb.Helper()
	suite.Survives(tb, txWithRetryBegin, func(ctx context.Context) {
		_ = t.Begin(ctx)
	})
}

// txWithRetryAssertBeginCancels asserts Begin reports a cancelled context as cancelled.
func txWithRetryAssertBeginCancels(
	tb testing.TB,
	t TxWithRetry,
) {
	tb.Helper()
	suite.ReportsCancelled(tb, txWithRetryBegin, func(ctx context.Context) error {
		return t.Begin(ctx)
	})
}

// txWithRetryAssertBeginToleratesNilContext asserts Begin returns an error rather than panicking on a nil context.
func txWithRetryAssertBeginToleratesNilContext(
	tb testing.TB,
	t TxWithRetry,
) {
	tb.Helper()
	suite.ToleratesNilContext(tb, txWithRetryBegin, func(ctx context.Context) error {
		return t.Begin(ctx)
	})
}

// txWithRetryAssertCommitSmoke asserts Commit survives a call.
func txWithRetryAssertCommitSmoke(
	tb testing.TB,
	t TxWithRetry,
) {
	tb.Helper()
	suite.Survives(tb, txWithRetryCommit, func(ctx context.Context) {
		_ = t.Commit(ctx)
	})
}

// txWithRetryAssertCommitCancels asserts Commit reports a cancelled context as cancelled.
func txWithRetryAssertCommitCancels(
	tb testing.TB,
	t TxWithRetry,
) {
	tb.Helper()
	suite.ReportsCancelled(tb, txWithRetryCommit, func(ctx context.Context) error {
		return t.Commit(ctx)
	})
}

// txWithRetryAssertCommitToleratesNilContext asserts Commit returns an error rather than panicking on a nil context.
func txWithRetryAssertCommitToleratesNilContext(
	tb testing.TB,
	t TxWithRetry,
) {
	tb.Helper()
	suite.ToleratesNilContext(tb, txWithRetryCommit, func(ctx context.Context) error {
		return t.Commit(ctx)
	})
}

// txWithRetryAssertRollbackSmoke asserts Rollback survives a call.
func txWithRetryAssertRollbackSmoke(
	tb testing.TB,
	t TxWithRetry,
) {
	tb.Helper()
	suite.Survives(tb, txWithRetryRollback, func(ctx context.Context) {
		_ = t.Rollback(ctx)
	})
}

// txWithRetryAssertRollbackCancels asserts Rollback reports a cancelled context as cancelled.
func txWithRetryAssertRollbackCancels(
	tb testing.TB,
	t TxWithRetry,
) {
	tb.Helper()
	suite.ReportsCancelled(tb, txWithRetryRollback, func(ctx context.Context) error {
		return t.Rollback(ctx)
	})
}

// txWithRetryAssertRollbackToleratesNilContext asserts Rollback returns an error rather than panicking on a nil context.
func txWithRetryAssertRollbackToleratesNilContext(
	tb testing.TB,
	t TxWithRetry,
) {
	tb.Helper()
	suite.ToleratesNilContext(tb, txWithRetryRollback, func(ctx context.Context) error {
		return t.Rollback(ctx)
	})
}

// TxWithRetryDefect is a deliberately broken implementation, used as
// evidence that a check can fail. In practice you build one with
// BrokenTxWithRetry over the generated test double.
type TxWithRetryDefect interface {
	Subject() (TxWithRetrySubject, error)
}

// BrokenTxWithRetry describes an implementation built to break one
// specific claim, so that a check can be shown to catch it.
//
// Give it a name saying what is wrong, and a constructor. The best
// broken implementation is the generated double wrapping a correct one,
// with a single method overridden — correct everywhere except the one
// place the check is about.
func BrokenTxWithRetry[T TxWithRetry](
	name string, build func() T,
) TxWithRetryHarness[T] {
	return TxWithRetryHarness[T]{
		Name: name, New: build,
	}
}

// TxWithRetryChecks is a table of checks you write yourself, for the
// claims that cannot be worked out from the declaration — the ones that
// carry your domain.
//
// They are the same kind of value as the generated checks: they appear
// in the report, they can be dropped by name, and they can say what they
// need from an implementation. There is no second mechanism for them.
//
//	var myChecks = TxWithRetryChecks{
//		{Method: "Begin", Name: "my-claim",
//			Claim:    "a sentence stating exactly what this check proves",
//			Run:      myClaimBody,
//			ProvenBy: BrokenTxWithRetry("an implementation that breaks it", newBroken)},
//	}
type TxWithRetryChecks []TxWithRetryCheck

func (c TxWithRetryChecks) applyTo(rc *txWithRetryRunConfig) {
	rc.rows = append(rc.rows, c...)
}

// TxWithRetryCheck is one check you wrote. The body is a plain named
// function; which field you put it in decides what it is handed.
type TxWithRetryCheck struct {
	// Method groups this check under one of your methods, so it is named
	// Begin/<Name> in output and reruns with the rest of that
	// method's checks. Leave it empty for a check that is not about one
	// method in particular.
	Method string

	// Name identifies this check, in output and when dropping it. Keep it
	// stable: it is what a colleague's Without call refers to.
	Name string

	// Claim is one sentence saying exactly what this check proves. It is
	// recorded in the manifest and read out in the report.
	//
	// Write only what the body actually establishes. "a second write
	// leaves the value unchanged" is a promise that something reads the
	// value back; if the body only checks the write returned no error,
	// say that instead. Nothing here can catch a claim that is wider
	// than its check, and a claim nobody verifies is worse than none.
	Claim string

	// Set exactly one.
	//
	// Run is handed one fresh instance, which suits nearly every check.
	// RunWith is handed something that can build instances, for a claim
	// one instance cannot state on its own: build two and compare them,
	// move the clock forward, put one into a failure state.
	//
	// Both are also handed the sample inputs, so a check you write draws
	// from the same values the generated ones do — override an input and
	// your check sees the override too.
	Run     func(tb testing.TB, s TxWithRetry, fx TxWithRetryFixture)
	RunWith func(tb testing.TB, sub TxWithRetrySubject, fx TxWithRetryFixture)

	// Class groups this check in the report's summary. Optional; checks
	// you write are grouped as hand-written by default.
	Class suite.Class

	// Needs says what this check requires from an implementation beyond
	// being constructed — a clock it can move, a failure it can induce.
	//
	// An implementation that cannot supply it fails this check by name,
	// with the field to fill in named in the message. It never skips: a
	// check that quietly skipped for want of wiring would look exactly
	// like one that passed.
	Needs suite.Caps

	// ProvenBy is an implementation built to break this check and nothing
	// else. Setting it makes two statements at once — that the check can
	// fail, and here is the proof — and ProveTxWithRetry fails unless the
	// broken implementation really does turn this check red.
	//
	// ProvenReason, if set, is text the failure must contain. Use it so
	// that a broken implementation which fails for some unrelated reason
	// stops counting as evidence.
	//
	// Argued is for when no such implementation can be built: record why,
	// in a sentence. Set at most one of the two. Setting neither is
	// allowed and the report says so — the check is unproven, which is
	// honest, and different from proven.
	ProvenBy     TxWithRetryDefect
	ProvenReason string
	Argued       string
}

// txWithRetryMethods is the interface's method names, used to catch a typo in
// a check's Method field before the run starts.
//
// Without it a misspelled name would be accepted — it looks like any
// other method name — and the check would be filed under a method that
// does not exist, where nobody could find or drop it.
var txWithRetryMethods = suite.NewNameSet("TxWithRetry", txWithRetryBegin, txWithRetryCommit, txWithRetryRollback)

// bind converts one of your checks into the form the runner uses, tying
// it to this run's sample inputs — which is what lets a check you wrote
// see the same values, and the same overrides, as the generated ones.
func (c TxWithRetryCheck) bind(
	fx TxWithRetryFixture,
) (suite.Check[TxWithRetry], error) {
	out := suite.Check[TxWithRetry]{
		Claim: c.Claim, Class: c.Class, Needs: c.Needs,
	}
	if out.Class == "" {
		out.Class = suite.ClassHandWritten
	}

	var err error
	bodies := 0
	if c.Run != nil {
		bodies++
		if out.ID, err = suite.RowID("Run", c.Method, c.Name, txWithRetryMethods); err != nil {
			return out, err
		}
		run := c.Run
		out.Run = func(tb testing.TB, s TxWithRetry) {
			run(tb, s, fx)
		}
	}
	if c.RunWith != nil {
		bodies++
		out.ID = suite.HandRowID(c.Name)
		rw := c.RunWith
		out.RunWith = func(tb testing.TB, sub TxWithRetrySubject) {
			rw(tb, sub, fx)
		}
	}
	if err := suite.OneBody(c.Name, bodies, "Run, RunWith"); err != nil {
		return out, err
	}
	if c.Method != "" && c.Run == nil {
		return out, fmt.Errorf(
			"check %q sets Method, but its body fixes its own scope; drop Method", c.Name)
	}
	if out.Falsifiable, err = suite.Falsify(c.Name, c.ProvenBy != nil, c.Argued); err != nil {
		return out, err
	}
	return out, nil
}

// RunTxWithRetry runs every check — the generated ones and any you
// wrote — against every implementation you pass it.
//
// Each argument describes one thing to do, in any order: an
// implementation to test, a table of your own checks, sample inputs to
// use, or checks to leave out.
//
//	RunTxWithRetry(t,
//		TxWithRetryHarness[*InMemory]{Name: "in-memory", New: NewInMemory},
//		TxWithRetrySuite.Without(TxWithRetrySuite.Checks.Begin.Smoke()),
//	)
//
// Pass two implementations to compare them against each other, and mark
// the one you trust as the Oracle. Every check runs as its own subtest
// named after the implementation and the check, so `go test -run` can
// select one.
//
// A check that needs something your implementation has not supplied
// fails rather than skipping, and says which field to fill in. That is
// deliberate: a skipped check is how a claim goes unchecked while the
// run stays green.
func RunTxWithRetry(
	t *testing.T, opts ...TxWithRetryRunOpt,
) {
	t.Helper()
	var rc txWithRetryRunConfig
	for _, o := range opts {
		o.applyTo(&rc)
	}
	fx := txWithRetryNewFixture()
	for _, row := range rc.rows {
		rc.AddCheck(row.bind(fx))
	}
	// Checked here, after reading every argument and before running
	// anything: a misconfigured run reports all of its problems at once
	// rather than one per attempt.
	rc.Fail(t, "RunTxWithRetry")
	suite.Run(t,
		txWithRetrySuite().With(rc.Extra...).Without(rc.Drops...),
		rc.Subjects...)
}

// ProveTxWithRetry runs each of your checks against the deliberately
// broken implementation it names, and fails if the check does not catch
// it.
//
//	func TestMyChecksCanFail(t *testing.T) { ProveTxWithRetry(t, myChecks) }
//
// A check that always passes is indistinguishable from a working one
// until something breaks in production. This is what tells them apart:
// give each check a ProvenBy, and this proves the check can fail.
//
// A check with no ProvenBy is not ignored — it has to say why, in
// Argued. The two are held level in both directions: claiming proof
// without a broken implementation fails here, and supplying one for a
// check that claims nothing fails too.
func ProveTxWithRetry(
	t *testing.T, checks TxWithRetryChecks,
) {
	t.Helper()
	// The RUN's config, not the derived one: a check proven at default
	// pools carries no evidence about the pools a run actually uses.
	fx := txWithRetryNewFixture()
	bound := make([]suite.Check[TxWithRetry], 0, len(checks))
	defects := prove.Defects[TxWithRetry]{}
	for _, row := range checks {
		bd, err := row.bind(fx)
		if err != nil {
			t.Fatalf("ProveTxWithRetry: %v", err)
		}
		bound = append(bound, bd)
		if row.ProvenBy == nil {
			continue
		}
		sub, err := row.ProvenBy.Subject()
		if err != nil {
			t.Fatalf("ProveTxWithRetry: check %q: defect: %v", bd.ID, err)
		}
		defects[bd.ID] = prove.Defect[TxWithRetry]{
			Subject: sub, Reason: row.ProvenReason,
		}
	}
	prove.All(t, bound, defects)
}

// txWithRetryModelRows is what this package's model tier claims.
//
// Every row here needs sequences of calls judged against something
// outside the subject, which is what separates them from the rows
// above: those settle a claim with a fixed call sequence, and these
// cannot be stated that way at all. That is also why each takes the
// Subject rather than an instance — a sequence run builds its own, and
// some of them build two.
func txWithRetryModelRows() []suite.Check[TxWithRetry] {
	return []suite.Check[TxWithRetry]{
		{
			ID:          txWithRetryCheckIndex.Model.Laws(),
			Class:       suite.ClassLaws,
			Claim:       "every bound law holds over random operation sequences",
			Falsifiable: suite.Argued("no defect is planted for it: the proofs beside this file break one method at a time, and a claim about sequences needs a subject that is wrong over a history"),
			Strength:    suite.StrengthDifferential,
			RunWith: func(tb testing.TB, sub suite.Subject[TxWithRetry]) {
				txWithRetryAssertLaws(tb, sub)
			},
		},
	}
}

// --- TxWithRetry's model tier -------------------------------------------
//
// Random sequences of TxWithRetry's methods, run against every subject and
// something that judges them from outside. The rows on the run surface
// above carry it, and TxWithRetrySuite.Without declines any of them by name.
//
//	Reference: the subject's own factory — no reader/writer pair derives a store,
//	           so a second instance driven identically stands in: twins must
//	           agree, which catches nondeterminism and hidden shared state but
//	           not a subject wrong the same way twice; ref= raises the floor
//	Sequences: Begin (lifecycle), Commit (lifecycle), Rollback (lifecycle)
//	Laws:      AUTO-LIFECYCLE-RESPECTS-CONTEXT, AUTO-LIFECYCLE-RESPECTS-CONTEXT, AUTO-LIFECYCLE-RESPECTS-CONTEXT
//	Not bound:
//	           AUTO-TRANSACTION-NO-MID-TX-VISIBILITY — observes through Begin, which answers nothing to observe
//	           AUTO-TWO-PHASE-MUTEX — observes through Begin, which answers nothing to observe
//	           AUTO-TWO-PHASE-ROLLBACK-AFTER-COMMIT — observes through Begin, which answers nothing to observe
//
// txWithRetryModelActions is the operation vocabulary both legs drive.
//
// One constructor per method shape, from the engine's action set rather
// than hand-written closures: the constructors record inputs and outputs
// into the trace a law reads, compare the two sides the same way for every
// action, and shrink a failing sequence to the shortest one that still
// fails.
func txWithRetryModelActions() []model.Action[TxWithRetry] {
	return []model.Action[TxWithRetry]{
		action.Lifecycle("Begin",
			func(ctx context.Context, s txwithretry.TxWithRetry) error {
				return s.Begin(ctx)
			}),
		action.Lifecycle("Commit",
			func(ctx context.Context, s txwithretry.TxWithRetry) error {
				return s.Commit(ctx)
			}),
		action.Lifecycle("Rollback",
			func(ctx context.Context, s txwithretry.TxWithRetry) error {
				return s.Rollback(ctx)
			}),
	}
}

// txWithRetryModelLaws is the laws the classifications earned and this build
// could fill.
//
// Observational, every one of them: a law never mutates, so running them
// inside the sequences is safe for every step that follows. What they
// judge is the subject's own behaviour, which is why they are a separate
// leg from the reference comparison rather than more oracles on it.
func txWithRetryModelLaws() []law.Law[TxWithRetry] {
	return []law.Law[TxWithRetry]{
		law.LifecycleRespectsContext[txwithretry.TxWithRetry]{
			Op: func(ctx context.Context, s txwithretry.TxWithRetry) error {
				return s.Begin(ctx)
			},
		},
		law.LifecycleRespectsContext[txwithretry.TxWithRetry]{
			Op: func(ctx context.Context, s txwithretry.TxWithRetry) error {
				return s.Commit(ctx)
			},
		},
		law.LifecycleRespectsContext[txwithretry.TxWithRetry]{
			Op: func(ctx context.Context, s txwithretry.TxWithRetry) error {
				return s.Rollback(ctx)
			},
		},
	}
}

// txWithRetryAssertLaws drives the same sequences with the bound laws as the only
// oracle, and reports when they engaged nothing.
//
// The differential verdict is off here, and that is the whole reason this
// is a second leg rather than more options on the first: with it armed, a
// subject broken anywhere disagrees at step 0 and no law is ever reached,
// which makes "can this law catch a defect" unanswerable.
//
// The report is the other half. A law behind a precondition the subject
// refuses on every draw passes every time and asserts nothing, and from
// outside that is indistinguishable from a law that held.
func txWithRetryAssertLaws(
	tb testing.TB,
	sub suite.Subject[TxWithRetry],
) {
	tb.Helper()

	// The run's declared oracle where one exists, the derived reference
	// otherwise — and the report says which, because a law held against a
	// second copy of the subject is a weaker claim than the same law held
	// against something written independently.
	buildRef, tier := legs.Reference(tb, sub, func() TxWithRetry { return sub.New(tb) })
	sub.NoteTier(tier)
	legs.Law(tb, sub,
		func() TxWithRetry { return sub.New(tb) }, buildRef,
		txWithRetryModelActions(),
		txWithRetryModelLaws())
}

// testkit: end of generated content.
// testkit:provenance 00194345c1c82b3a773d50331eb67a4e1b96f0d3f061711a40b5375d773b4aca
