// Code generated by testkit. DO NOT EDIT.
//
// Source:    corpus/errors/noprefix/iface.go
// Plugins:   golang 1.0.0, sentinel 1.0.0, backend.golang 1.0.0
// Command:   testkit run ./corpus/...

package noprefix_test

import (
	"errors"
	"strings"
	"testing"

	"go.thesmos.sh/testkit"
	"go.thesmos.sh/testkit/conformance/corpus/errors/noprefix"
)

// TestNoprefixSentinels pins the contract every sentinel in this package
// carries. Callers match on these values, read them in logs, and branch on
// them, so their messages and identities are as much an API as any exported
// signature — and nothing in the compiler holds them to it.
func TestNoprefixSentinels(t *testing.T) {
	t.Parallel()

	all := []struct {
		name string
		err  error
	}{
		{"ErrRetry", noprefix.ErrRetry},
		{"ErrGiveUp", noprefix.ErrGiveUp},
	}

	t.Run("every sentinel is non-nil", func(t *testing.T) {
		t.Parallel()
		// A var declared and never assigned is nil, compiles, and satisfies
		// errors.Is against nothing — so every caller's branch on it is dead
		// and no other check here can even run without panicking.
		for _, e := range all {
			testkit.True(t, e.err != nil, e.name+" must be assigned")
		}
	})

	t.Run("every sentinel has a message", func(t *testing.T) {
		t.Parallel()
		// An empty message reaches a log as nothing at all, which is worse
		// than a bad one: the operator sees that something failed and no
		// indication of what.
		for _, e := range all {
			testkit.NotEqual(t, e.err.Error(), "", e.name+" must carry a message")
		}
	})

	// No prefix check: this package declares prefix=off, so its messages are
	// deliberately bare. Suppression is explicit because a generator that
	// quietly dropped a failing check would be worse than having none.

	t.Run("no two sentinels share a message", func(t *testing.T) {
		t.Parallel()
		// Two identical messages cannot be told apart in a log, and the second
		// is usually a copy-paste that was meant to be edited.
		seen := map[string]string{}
		for _, e := range all {
			testkit.Equal(t, seen[e.err.Error()], "",
				e.name+" must not repeat another sentinel's message")
			seen[e.err.Error()] = e.name
		}
	})

	t.Run("no sentinel's message is a prefix of another's", func(t *testing.T) {
		t.Parallel()
		// Distinct from sharing a message. One message that starts with
		// another makes every grep for the shorter one match the longer, and
		// any code matching on message text ambiguous — which is why the two
		// are separate checks rather than one equality.
		for _, a := range all {
			for _, b := range all {
				if a.name == b.name {
					continue
				}
				testkit.False(t, strings.HasPrefix(a.err.Error(), b.err.Error()),
					a.name+" must not begin with the whole of "+b.name)
			}
		}
	})

	t.Run("no sentinel matches another", func(t *testing.T) {
		t.Parallel()
		// Two that match collapse a caller's branches into one, and the caller
		// cannot see it from the declarations.
		for _, a := range all {
			for _, b := range all {
				if a.name == b.name {
					continue
				}
				testkit.False(t, errors.Is(a.err, b.err),
					a.name+" must not satisfy errors.Is against "+b.name)
			}
		}
	})

	// No check that a sentinel survives %w or errors.Join. errors.Is compares
	// identity before it consults anything a type declares, so every value
	// passes both — including one whose Is always refuses. The assertion would
	// be about the standard library rather than about this package.
}

// testkit: end of generated content.
// testkit:provenance d3dceee1bfb23126d5a91336252ac495f517caf31ab64643e521ee8042bf91be
