// Code generated by testkit. DO NOT EDIT.
//
// Source:    corpus/iface/detector/multireader/iface.go
// Plugins:   golang 1.0.0, suite 1.24.0, backend.golang 1.0.0
// Command:   testkit run ./corpus/...

// Conformance checks worked out from the interfaces this package doubles.
//
// One call runs every check for an interface against one implementation.
// Describe the implementation in a literal and hand it over — each
// interface's own Run function is documented beside it, with the names
// to use.
//
// Nothing else is required to start. The rest is there when you need it:
// a harness field to add only when a check fails asking for it, checks of
// your own that run beside the generated ones, a Prove entry that drives
// each of yours against the broken implementation it names, and a typed
// index for dropping a check by identity rather than by string.
//
// Nothing here is written by hand. Regenerate rather than edit: an edit
// survives until the next run and no longer.
package multireadertest

import (
	"context"
	"errors"
	"fmt"
	"testing"

	"go.thesmos.sh/testkit/conformance/corpus/iface/detector/multireader"
	"go.thesmos.sh/testkit/engine/suite"
	"go.thesmos.sh/testkit/engine/suite/prove"
)

// Conformance checks for MultiReader, worked out from its declaration.
//
// The package comment above says what these are and how to start. This is
// MultiReader's half of it — the names to use:
//
//	func TestMine(t *testing.T) {
//		RunMultiReader(t, MultiReaderHarness[*Mine]{Name: "mine", New: NewMine})
//	}
//
//	MultiReaderHarness
//	    one implementation under test.
//	MultiReaderChecks
//	    checks you write yourself, run beside the generated ones.
//	ProveMultiReader
//	    drives each of yours against the broken implementation it names.
//	GreenMultiReader
//	    drives them all against one that is correct but different, and
//	    fails if a check rejects it.
//	MultiReaderSuite.Checks.<Method>.<Check>()
//	    names one check, so you can drop it. Written this way it stops
//	    compiling if a later regeneration no longer emits that check,
//	    rather than silently dropping nothing.
//
// The checks this file runs:
//
//	GetWithMeta/cancel
//	GetWithMeta/deadline
//	GetWithMeta/nilcontext
//	GetWithMeta/smoke
//	GetWithMeta/zero-on-error
//
// Claims this file does NOT make. Each was worked out from your
// declaration and then declined, because something needed to state it
// is missing. The reason and the fix are given for each: the list above
// tells you what you have, and this tells you what you do not.
//
//	GetWithMeta's miss check — no method here stores anything and nothing loads it with starting data, so there is no input this check could ask for and be sure was never stored. To close it: say what a lookup reports when it finds nothing, with //testkit:mixin notfound sentinel=Err…, or write the check yourself.
//
// A version check, performed by the compiler. If this file was generated
// against a testkit whose check format differs from the one you are
// building with, this line fails to compile and names the mismatch —
// instead of the two disagreeing quietly while the tests still pass.
// Regenerate the file to clear it.
var _ = suite.CompatV2

// MultiReaderFixture holds the sample inputs the checks call your
// implementation with, worked out from each method's parameter types.
//
// Every input comes as a pair: a value, and a second one guaranteed to
// differ from it. Both are needed for a check to mean anything — looking
// up a key that was just stored proves nothing on its own unless there
// is also a key that was never stored.
//
// A parameter whose type has no value that can be written down — a func,
// a channel, a type your declaration does not import — is left at its
// zero value, and the checks that needed it were not emitted at all
// rather than run against something meaningless. Those are listed above.
// A check you write yourself is handed this either way.
type MultiReaderFixture struct {
	key      string
	keyOther string
}

// DefaultMultiReaderFixture is what a run with no config draws.
func DefaultMultiReaderFixture() MultiReaderFixture {
	return multiReaderNewFixture()
}

// multiReaderNewFixture builds the sample inputs for one run.
//
// Read these through the methods below rather than as fields. A value you
// supplied through the config and one worked out from the type are read
// the same way, and no check should be able to tell them apart.
func multiReaderNewFixture() MultiReaderFixture {
	return MultiReaderFixture{
		key:      "test-key",
		keyOther: "other-key",
	}
}

// Key is the key the checks call your implementation with.
func (f MultiReaderFixture) Key() string { return f.key }

// KeyOther is a second key, guaranteed to differ from the
// first — so a check that expects to find nothing is asking about
// something your implementation has genuinely never been given.
func (f MultiReaderFixture) KeyOther() string { return f.keyOther }

// MultiReader is your interface, under a local name.
//
// An alias, so it is the same type — this is here only so the rest of
// this file can refer to it without repeating its import path, and so a
// check you write can name it too.
type MultiReader = multireader.MultiReader

// MultiReaderSubject is what a RunWith check receives instead of a single
// instance: a handle that can build more of them.
//
// Use it for a claim one instance cannot state on its own — that two
// instances do not share state, that a value survives being closed and
// reopened.
type MultiReaderSubject = suite.Subject[MultiReader]

// MultiReaderRunOpt is anything you can pass to RunMultiReader: an
// implementation to test, a table of your own checks, a config, or a
// check to drop. Order does not matter.
type MultiReaderRunOpt interface {
	applyTo(*multiReaderRunConfig)
}

type multiReaderRunConfig struct {
	suite.Bundle[MultiReader]

	// rows are the checks you wrote, held until every argument has been
	// read and then tied to this run's inputs. Tying them on arrival
	// would bind them to inputs a later argument replaces.
	rows MultiReaderChecks
}

// MultiReaderHarness describes one MultiReader implementation to test.
//
// Name and one constructor are all that is required. Every other field
// unlocks the checks that need it, and you do not have to work out which
// in advance: run it, and any check that needs more fails saying which
// field to add.
type MultiReaderHarness[T MultiReader] struct {
	Name string

	// Set exactly one.
	//
	// Use New if construction cannot fail; use Start if it needs the
	// test's lifetime — a temp directory to clean up, a connection to
	// close. Start is handed the testing.TB to register that on.
	New   func() T
	Start func(tb testing.TB) T

	// Excuse lists checks this implementation cannot meaningfully take —
	// not ones it fails, ones it has no way to answer. An in-memory
	// implementation has no storage to survive a restart, so a check
	// about restarting it is asking the impossible.
	//
	// Excused checks are reported as excused, never as passed.
	Excuse []suite.ID

	// Oracle marks this implementation as the one others are compared
	// against, when you are testing more than one. At most one may set it.
	// Pick the implementation you trust most.
	Oracle bool

	// Serial runs this implementation's checks one at a time, and never
	// alongside another implementation's. Set it for something that
	// cannot take being constructed many times at once — a real database,
	// a fixed port.
	Serial bool

	// Provide supplies anything a check needs that has no field of its
	// own above. You will not need it unless a check fails asking for a
	// named capability, and that failure tells you the name to use here.
	Provide map[suite.Capability]any
}

// Subject converts this description into the form the runner uses, and
// reports anything wrong with it — no constructor, or two.
func (h MultiReaderHarness[T]) Subject() (suite.Subject[MultiReader], error) {
	build, err := suite.OneCtor(h.Name, h.New, h.Start)
	if err != nil {
		return suite.Subject[MultiReader]{}, err
	}
	return suite.Subject[MultiReader]{
		Name:     h.Name,
		Provides: h.Provide,
		New:      func(tb testing.TB) MultiReader { return build(tb) },
		Oracle:   h.Oracle,
		Serial:   h.Serial,
		Excused:  suite.ExcuseSet(h.Excuse),
	}, nil
}

func (h MultiReaderHarness[T]) applyTo(rc *multiReaderRunConfig) {
	rc.AddSubject(h.Subject())
}

type multiReaderDropOpt []suite.ID

func (d multiReaderDropOpt) applyTo(rc *multiReaderRunConfig) {
	rc.AddDrops(d...)
}

// multiReaderWithout drops the named checks from the run.
func multiReaderWithout(ids ...suite.ID) MultiReaderRunOpt {
	return multiReaderDropOpt(ids)
}

// --- Naming checks ----------------------------------------------------------

// MultiReaderSuite is how you name a check — to drop it, or to
// point at it from a tool.
var MultiReaderSuite = multiReaderVeneer{Checks: multiReaderCheckIndex}

type multiReaderVeneer struct {
	// Checks names every check this file runs, by method:
	//
	//	MultiReaderSuite.Checks.<Method>.<Check>()
	//
	// Prefer this over writing the check's name as a string. If a later
	// regeneration stops emitting that check, this stops compiling —
	// where the string would silently drop nothing.
	Checks multiReaderCheckIndexT
}

// Without drops the named checks from the run.
//
//	RunMultiReader(t, mine, MultiReaderSuite.Without(
//		MultiReaderSuite.Checks.GetWithMeta.Smoke()))
//
// Dropping is recorded in the run's report, so a check you removed is
// visible rather than simply absent.
func (multiReaderVeneer) Without(ids ...suite.ID) MultiReaderRunOpt {
	return multiReaderWithout(ids...)
}

// Suite returns the checks as plain data, if you are building a tool over
// them or running them yourself.
//
// RunMultiReader is the normal way in; this is for when you need the
// checks as values rather than as a run.
func (multiReaderVeneer) Suite(fx MultiReaderFixture) suite.Suite[MultiReader] {
	return multiReaderSuite(fx)
}

// --- Failure messages -------------------------------------------------------

// multiReaderIndexPath maps each check to the expression you would
// write to drop it, so that a check which cannot run tells you what to
// type rather than only what went wrong.
var multiReaderIndexPath = map[suite.ID]string{
	multiReaderCheckIndex.GetWithMeta.Smoke():       "MultiReaderSuite.Checks.GetWithMeta.Smoke()",
	multiReaderCheckIndex.GetWithMeta.Cancels():     "MultiReaderSuite.Checks.GetWithMeta.Cancels()",
	multiReaderCheckIndex.GetWithMeta.NilContext():  "MultiReaderSuite.Checks.GetWithMeta.NilContext()",
	multiReaderCheckIndex.GetWithMeta.Deadline():    "MultiReaderSuite.Checks.GetWithMeta.Deadline()",
	multiReaderCheckIndex.GetWithMeta.ZeroOnError(): "MultiReaderSuite.Checks.GetWithMeta.ZeroOnError()",
}

var multiReaderDropHint = suite.DropHinter(
	"MultiReaderSuite", multiReaderIndexPath,
)

// The names this file uses in more than one place, declared once each so
// they cannot drift apart.
const (
	multiReaderGetWithMeta = "GetWithMeta"
)

// multiReaderCheckIndex names every check in this file, grouped by method.
// Reach it through MultiReaderSuite.Checks.
var multiReaderCheckIndex = multiReaderCheckIndexT{
	GetWithMeta: multiReaderGetWithMetaChecks{},
}

type multiReaderCheckIndexT struct {
	GetWithMeta multiReaderGetWithMetaChecks
}

// All returns every ID this package emits.
func (multiReaderCheckIndexT) All() []suite.ID {
	var out []suite.ID
	out = append(out, multiReaderGetWithMetaChecks{}.All()...)
	return out
}

type multiReaderGetWithMetaChecks struct{}

func (multiReaderGetWithMetaChecks) Smoke() suite.ID {
	return suite.MethodID(multiReaderGetWithMeta, suite.SegSmoke)
}

func (multiReaderGetWithMetaChecks) Cancels() suite.ID {
	return suite.MethodID(multiReaderGetWithMeta, suite.SegCancel)
}

func (multiReaderGetWithMetaChecks) NilContext() suite.ID {
	return suite.MethodID(multiReaderGetWithMeta, suite.SegNilContext)
}

func (multiReaderGetWithMetaChecks) Deadline() suite.ID {
	return suite.MethodID(multiReaderGetWithMeta, suite.SegDeadline)
}

func (multiReaderGetWithMetaChecks) ZeroOnError() suite.ID {
	return suite.MethodID(multiReaderGetWithMeta, suite.SegZeroValue)
}

func (multiReaderGetWithMetaChecks) All() []suite.ID {
	return []suite.ID{
		multiReaderGetWithMetaChecks{}.Smoke(),
		multiReaderGetWithMetaChecks{}.Cancels(),
		multiReaderGetWithMetaChecks{}.NilContext(),
		multiReaderGetWithMetaChecks{}.Deadline(),
		multiReaderGetWithMetaChecks{}.ZeroOnError(),
	}
}

// multiReaderSuite returns the checks as data, using the given inputs.
//
// It takes the built inputs rather than a config, because that is what
// the checks read. To start from the defaults, pass what a default run
// passes — MultiReaderSuite.Suite does exactly that.
func multiReaderSuite(fx MultiReaderFixture) suite.Suite[MultiReader] {
	return suite.Suite[MultiReader]{
		Name:     "MultiReader",
		DropHint: multiReaderDropHint,
		Checks:   multiReaderSignatureChecks(fx),
	}
}

// multiReaderSignatureChecks builds every check in this file.
//
// A check is marked as proven able to fail only when a deliberately
// broken implementation for it exists in the file beside this one.
// Where none could be built, the check says so instead — claiming proof
// without the evidence is refused, in both directions.
func multiReaderSignatureChecks(fx MultiReaderFixture) []suite.Check[MultiReader] {
	sig := suite.ProvenCheck[MultiReader]
	ix := multiReaderCheckIndex
	return []suite.Check[MultiReader]{
		sig(ix.GetWithMeta.Smoke(), suite.ClassSmoke,
			"GetWithMeta survives a call with a seeded key",
			func(tb testing.TB, m MultiReader) {
				multiReaderAssertGetWithMetaSmoke(tb, m, fx)
			}).At(suite.StrengthErrorOnly),
		sig(ix.GetWithMeta.Cancels(), suite.ClassCancel,
			"GetWithMeta reports a cancelled context as cancelled",
			func(tb testing.TB, m MultiReader) {
				multiReaderAssertGetWithMetaCancels(tb, m, fx)
			}).At(suite.StrengthErrorOnly),
		sig(ix.GetWithMeta.NilContext(), suite.ClassNilContext,
			"GetWithMeta returns an error rather than panicking on a nil context",
			func(tb testing.TB, m MultiReader) {
				multiReaderAssertGetWithMetaToleratesNilContext(tb, m, fx)
			}).At(suite.StrengthErrorOnly),
		sig(ix.GetWithMeta.Deadline(), suite.ClassDeadline,
			"GetWithMeta reports an expired deadline as exceeded",
			func(tb testing.TB, m MultiReader) {
				multiReaderAssertGetWithMetaHonoursDeadline(tb, m, fx)
			}).At(suite.StrengthErrorOnly),
		sig(ix.GetWithMeta.ZeroOnError(), suite.ClassZeroValue,
			"GetWithMeta returns the zero Value and Meta alongside any error",
			func(tb testing.TB, m MultiReader) {
				multiReaderAssertGetWithMetaZeroOnError(tb, m, fx)
			}).At(suite.StrengthObserved),
	}
}

// multiReaderAssertGetWithMetaSmoke asserts GetWithMeta survives a call with a seeded key.
func multiReaderAssertGetWithMetaSmoke(
	tb testing.TB,
	m MultiReader,
	fx MultiReaderFixture,
) {
	tb.Helper()
	suite.Survives(tb, multiReaderGetWithMeta, func(ctx context.Context) {
		_, _, _ = m.GetWithMeta(ctx, fx.Key())
	})
}

// multiReaderAssertGetWithMetaCancels asserts GetWithMeta reports a cancelled context as cancelled.
func multiReaderAssertGetWithMetaCancels(
	tb testing.TB,
	m MultiReader,
	fx MultiReaderFixture,
) {
	tb.Helper()
	suite.ReportsCancelled(tb, multiReaderGetWithMeta, func(ctx context.Context) error {
		_, _, err := m.GetWithMeta(ctx, fx.Key())
		return err
	})
}

// multiReaderAssertGetWithMetaToleratesNilContext asserts GetWithMeta returns an error rather than panicking on a nil context.
func multiReaderAssertGetWithMetaToleratesNilContext(
	tb testing.TB,
	m MultiReader,
	fx MultiReaderFixture,
) {
	tb.Helper()
	suite.ToleratesNilContext(tb, multiReaderGetWithMeta, func(ctx context.Context) error {
		_, _, err := m.GetWithMeta(ctx, fx.Key())
		return err
	})
}

// multiReaderAssertGetWithMetaHonoursDeadline asserts GetWithMeta reports an expired deadline as exceeded.
func multiReaderAssertGetWithMetaHonoursDeadline(
	tb testing.TB,
	m MultiReader,
	fx MultiReaderFixture,
) {
	tb.Helper()
	suite.ReportsDeadlineExceeded(tb, multiReaderGetWithMeta, func(ctx context.Context) error {
		_, _, err := m.GetWithMeta(ctx, fx.Key())
		return err
	})
}

// multiReaderAssertGetWithMetaZeroOnError asserts GetWithMeta returns the zero Value and Meta alongside any error.
func multiReaderAssertGetWithMetaZeroOnError(
	tb testing.TB,
	m MultiReader,
	fx MultiReaderFixture,
) {
	tb.Helper()
	ctx, cancel := context.WithCancel(tb.Context())
	cancel()
	got, got2, err := m.GetWithMeta(ctx, fx.Key())
	if err == nil {
		tb.Skip("GetWithMeta answered for a cancelled context, so this check has no error to inspect")
	}

	var zero multireader.Value
	if got != zero {
		tb.Errorf("GetWithMeta must return the zero Value alongside an error: got %+v, want %+v (err %v)",
			got, zero, err)
	}
	var zero2 multireader.Meta
	if got2 != zero2 {
		tb.Errorf("GetWithMeta must return the zero Meta alongside an error: got %+v, want %+v (err %v)",
			got2, zero2, err)
	}
}

// MultiReaderDefect is a deliberately broken implementation, used as
// evidence that a check can fail. In practice you build one with
// BrokenMultiReader over the generated test double.
type MultiReaderDefect interface {
	Subject() (MultiReaderSubject, error)
}

// BrokenMultiReader describes an implementation built to break one
// specific claim, so that a check can be shown to catch it.
//
// Give it a name saying what is wrong, and a constructor. The best
// broken implementation is the generated double wrapping a correct one,
// with a single method overridden — correct everywhere except the one
// place the check is about.
func BrokenMultiReader[T MultiReader](
	name string, build func() T,
) MultiReaderHarness[T] {
	return MultiReaderHarness[T]{
		Name: name, New: build,
	}
}

// MultiReaderChecks is a table of checks you write yourself, for the
// claims that cannot be worked out from the declaration — the ones that
// carry your domain.
//
// They are the same kind of value as the generated checks: they appear
// in the report, they can be dropped by name, and they can say what they
// need from an implementation. There is no second mechanism for them.
//
//	var myChecks = MultiReaderChecks{
//		{Method: "GetWithMeta", Name: "my-claim",
//			Claim:    "a sentence stating exactly what this check proves",
//			Run:      myClaimBody,
//			ProvenBy: BrokenMultiReader("an implementation that breaks it", newBroken)},
//	}
type MultiReaderChecks []MultiReaderCheck

func (c MultiReaderChecks) applyTo(rc *multiReaderRunConfig) {
	rc.rows = append(rc.rows, c...)
}

// MultiReaderCheck is one check you wrote. The body is a plain named
// function; which field you put it in decides what it is handed.
type MultiReaderCheck struct {
	// Method groups this check under one of your methods, so it is named
	// GetWithMeta/<Name> in output and reruns with the rest of that
	// method's checks. Leave it empty for a check that is not about one
	// method in particular.
	Method string

	// Name identifies this check, in output and when dropping it. Keep it
	// stable: it is what a colleague's Without call refers to.
	Name string

	// Claim is one sentence saying exactly what this check proves. It is
	// recorded in the manifest and read out in the report.
	//
	// Write only what the body actually establishes. "a second write
	// leaves the value unchanged" is a promise that something reads the
	// value back; if the body only checks the write returned no error,
	// say that instead. Nothing here can catch a claim that is wider
	// than its check, and a claim nobody verifies is worse than none.
	Claim string

	// Set exactly one.
	//
	// Run is handed one fresh instance, which suits nearly every check.
	// RunWith is handed something that can build instances, for a claim
	// one instance cannot state on its own: build two and compare them,
	// move the clock forward, put one into a failure state.
	//
	// Both are also handed the sample inputs, so a check you write draws
	// from the same values the generated ones do.
	Run     func(tb testing.TB, s MultiReader, fx MultiReaderFixture)
	RunWith func(tb testing.TB, sub MultiReaderSubject, fx MultiReaderFixture)

	// Class groups this check in the report's summary. Optional; checks
	// you write are grouped as hand-written by default.
	Class suite.Class

	// Needs says what this check requires from an implementation beyond
	// being constructed — a clock it can move, a failure it can induce.
	//
	// An implementation that cannot supply it fails this check by name,
	// with the field to fill in named in the message. It never skips: a
	// check that quietly skipped for want of wiring would look exactly
	// like one that passed.
	Needs suite.Caps

	// ProvenBy is an implementation built to break this check and nothing
	// else. Setting it makes two statements at once — that the check can
	// fail, and here is the proof — and ProveMultiReader fails unless the
	// broken implementation really does turn this check red.
	//
	// ProvenReason, if set, is text the failure must contain. Use it so
	// that a broken implementation which fails for some unrelated reason
	// stops counting as evidence.
	//
	// Argued is for when no such implementation can be built: record why,
	// in a sentence. Set at most one of the two. Setting neither is
	// allowed and the report says so — the check is unproven, which is
	// honest, and different from proven.
	ProvenBy     MultiReaderDefect
	ProvenReason string
	Argued       string
}

// multiReaderMethods is the interface's method names, used to catch a typo in
// a check's Method field before the run starts.
//
// Without it a misspelled name would be accepted — it looks like any
// other method name — and the check would be filed under a method that
// does not exist, where nobody could find or drop it.
var multiReaderMethods = suite.NewNameSet("MultiReader", multiReaderGetWithMeta)

// bind converts one of your checks into the form the runner uses, tying
// it to this run's sample inputs — which is what lets a check you wrote
// see the same values, and the same overrides, as the generated ones.
func (c MultiReaderCheck) bind(
	fx MultiReaderFixture,
) (suite.Check[MultiReader], error) {
	out := suite.Check[MultiReader]{
		Claim: c.Claim, Class: c.Class, Needs: c.Needs,
	}
	if out.Class == "" {
		out.Class = suite.ClassHandWritten
	}

	var err error

	// bodies counts what this row set and the runtime refuses any answer
	// but one; fields is the listing that refusal offers, which has to
	// name what THIS interface can set; scoped says the body it set is
	// one that reads the row's Method. A contributing tier's dispatch
	// lands below and may move all three.
	bodies, fields, scoped := 0, "Run, RunWith", false
	if c.Run != nil {
		scoped = true
		bodies++
		if out.ID, err = suite.RowID("Run", c.Method, c.Name, multiReaderMethods); err != nil {
			return out, err
		}
		run := c.Run
		out.Run = func(tb testing.TB, s MultiReader) {
			run(tb, s, fx)
		}
	}
	if c.RunWith != nil {
		bodies++
		out.ID = suite.HandRowID(c.Name)
		rw := c.RunWith
		out.RunWith = func(tb testing.TB, sub MultiReaderSubject) {
			rw(tb, sub, fx)
		}
	}
	if err := suite.OneBody(c.Name, bodies, fields); err != nil {
		return out, err
	}
	if c.Method != "" && !scoped {
		return out, fmt.Errorf(
			"check %q sets Method, but its body fixes its own scope; drop Method", c.Name)
	}
	if out.Falsifiable, err = suite.Falsify(c.Name, c.ProvenBy != nil, c.Argued); err != nil {
		return out, err
	}
	return out, nil
}

// RunMultiReader runs every check — the generated ones and any you
// wrote — against every implementation you pass it.
//
// Each argument describes one thing to do, in any order: an
// implementation to test, a table of your own checks, sample inputs to
// use, or checks to leave out.
//
//	RunMultiReader(t,
//		MultiReaderHarness[*InMemory]{Name: "in-memory", New: NewInMemory},
//		MultiReaderSuite.Without(MultiReaderSuite.Checks.GetWithMeta.Smoke()),
//	)
//
// Pass two implementations to compare them against each other, and mark
// the one you trust as the Oracle. Every check runs as its own subtest
// named after the implementation and the check, so `go test -run` can
// select one.
//
// A check that needs something your implementation has not supplied
// fails rather than skipping, and says which field to fill in. That is
// deliberate: a skipped check is how a claim goes unchecked while the
// run stays green.
func RunMultiReader(
	t *testing.T, opts ...MultiReaderRunOpt,
) {
	t.Helper()
	var rc multiReaderRunConfig
	for _, o := range opts {
		o.applyTo(&rc)
	}
	fx := multiReaderNewFixture()
	for _, row := range rc.rows {
		rc.AddCheck(row.bind(fx))
	}
	// Checked here, after reading every argument and before running
	// anything: a misconfigured run reports all of its problems at once
	// rather than one per attempt.
	rc.Fail(t, "RunMultiReader")
	suite.Run(t,
		multiReaderSuite(fx).With(rc.Extra...).Without(rc.Drops...),
		rc.Subjects...)
}

// multiReaderProofs is every defect this run derived and can spell.
//
// Each is the smallest implementation that breaks exactly one claim: the
// generated double with one method overridden, and nothing else changed.
// The reason beside it is the substring the red must contain, so a defect
// that died on an unrelated guard stops counting as evidence.
//
// Unexported and built fresh per call. A defect carries a constructor
// that registers cleanup on the test it is handed, so a shared map would
// hand one test's cleanup to the next.
func multiReaderProofs() prove.Defects[MultiReader] {
	ix := MultiReaderSuite.Checks
	return prove.Defects[MultiReader]{
		ix.GetWithMeta.Smoke(): prove.One("a MultiReader whose GetWithMeta panics",
			func(tb testing.TB) MultiReader {
				return NewMultiReaderStub(tb, WithMultiReaderGetWithMeta(
					func(_ context.Context, _ string) (multireader.Value, multireader.Meta, error) {
						panic("planted: GetWithMeta panics")
					}))
			}).Reasoned(suite.RedPanicked),
		ix.GetWithMeta.Cancels(): prove.One("a MultiReader whose GetWithMeta ignores the context it is handed",
			func(tb testing.TB) MultiReader {
				return NewMultiReaderStub(tb, WithMultiReaderGetWithMeta(
					func(_ context.Context, _ string) (r0 multireader.Value, r1 multireader.Meta, err error) {
						// The call arrives and nothing is done with it; the bare
						// return answers every slot's zero, which for the error
						// slot is the nil this claim forbids.
						return
					}))
			}).Reasoned(suite.RedCancelled),
		ix.GetWithMeta.NilContext(): prove.One("a MultiReader whose GetWithMeta forgives a nil context and answers",
			func(tb testing.TB) MultiReader {
				return NewMultiReaderStub(tb, WithMultiReaderGetWithMeta(
					func(_ context.Context, _ string) (r0 multireader.Value, r1 multireader.Meta, err error) {
						// The call arrives and nothing is done with it; the bare
						// return answers every slot's zero, which for the error
						// slot is the nil this claim forbids.
						return
					}))
			}).Reasoned(suite.RedNilContext),
		ix.GetWithMeta.Deadline(): prove.One("a MultiReader whose GetWithMeta ignores the context it is handed",
			func(tb testing.TB) MultiReader {
				return NewMultiReaderStub(tb, WithMultiReaderGetWithMeta(
					func(_ context.Context, _ string) (r0 multireader.Value, r1 multireader.Meta, err error) {
						// The call arrives and nothing is done with it; the bare
						// return answers every slot's zero, which for the error
						// slot is the nil this claim forbids.
						return
					}))
			}).Reasoned(suite.RedDeadline),
		ix.GetWithMeta.ZeroOnError(): prove.One("a MultiReader whose GetWithMeta answers a believable value beside its error",
			func(tb testing.TB) MultiReader {
				return NewMultiReaderStub(tb, WithMultiReaderGetWithMeta(
					func(_ context.Context, _ string) (r0 multireader.Value, r1 multireader.Meta, err error) {
						// A believable answer beside the refusal. A caller
						// reading the error and one reading the value disagree
						// about what happened, which is the claim's own
						// violation rather than a subject that merely failed.
						r0 = multireader.Value{Key: "other-value"}
						err = errors.New("planted: GetWithMeta refused with a believable value")
						return
					}))
			}),
	}
}

// ProveMultiReader runs every check — the generated ones and any you
// wrote — against the deliberately broken implementation it names, and
// fails if the check does not catch it.
//
//	func TestMyChecksCanFail(t *testing.T) {
//		ProveMultiReader(t, MultiReaderHarness[*InMemory]{Name: "in-memory", New: NewInMemory}, myChecks)
//	}
//
// A check that always passes is indistinguishable from a working one
// until something breaks in production. This is what tells them apart:
// give each check a ProvenBy, and this proves the check can fail.
//
// A check with no ProvenBy is not ignored — it has to say why, in
// Argued. The two are held level in both directions: claiming proof
// without a broken implementation fails here, and supplying one for a
// check that claims nothing fails too.
//
// It takes the same arguments RunMultiReader does, and for one reason: a
// check may need a capability, and the answer is a fact about this
// interface rather than about any one implementation. The harness is
// where you write it once. A planted defect stands in for a real
// subject, so it borrows the same answer rather than being asked for one
// of its own — which nothing here could supply.
func ProveMultiReader(
	t *testing.T, opts ...MultiReaderRunOpt,
) {
	t.Helper()
	var rc multiReaderRunConfig
	for _, o := range opts {
		o.applyTo(&rc)
	}
	// The RUN's config, not the derived one: a check proven at default
	// pools carries no evidence about the pools a run actually uses.
	fx := multiReaderNewFixture()
	for _, row := range rc.rows {
		rc.AddCheck(row.bind(fx))
	}
	rc.Fail(t, "ProveMultiReader")
	s := multiReaderSuite(fx).With(rc.Extra...).Without(rc.Drops...)
	// Read off the subjects, because a door is answered once for the
	// interface and every subject of it reads the same answer.
	doors := suite.Doors(rc.Subjects...)
	defects := multiReaderProofs()
	for _, row := range rc.rows {
		if row.ProvenBy == nil {
			continue
		}
		bd, err := row.bind(fx)
		if err != nil {
			t.Fatalf("ProveMultiReader: %v", err)
		}
		sub, err := row.ProvenBy.Subject()
		if err != nil {
			t.Fatalf("ProveMultiReader: check %q: defect: %v", bd.ID, err)
		}
		defects[bd.ID] = prove.Defect[MultiReader]{
			Subject: sub, Reason: row.ProvenReason,
		}
	}
	// A declined check takes its proof with it: proving a row the run was
	// told to leave out reports on a claim this package no longer makes,
	// and the parity gate fails naming a check the set does not hold.
	for _, id := range rc.Drops {
		delete(defects, id)
	}
	prove.All(t, s.Checks, defects.Answering(doors))
}

// GreenMultiReader runs every check — the generated ones and any you
// wrote — against an implementation that is CORRECT but different, and
// fails if a check rejects it.
//
//	func TestAnotherPolicyIsAllowed(t *testing.T) {
//		GreenMultiReader(t, suite.Subject[MultiReader]{
//			Name: "evicts the newest", New: newNewestFirst,
//		})
//	}
//
// ProveMultiReader measures whether these checks can fire. This measures
// whether they fire SELECTIVELY. Nothing else here can tell a check that
// is right from one that is too strong: a check forbidding something the
// declaration permits looks exactly like a suite working, until somebody
// writes a legal implementation and it fails.
//
// The control is a real alternative, not a broken one — a different
// eviction victim, a delivery that duplicates where the contract allows
// it, a lazier evaluation behind the same boundary. Where a check
// genuinely cannot apply to your control, put its ID in the subject's
// Excused map: an excused check is skipped by name, because it yields no
// evidence either way.
//
// Same arguments as RunMultiReader, so the control meets the checks
// the run does — including the ones you wrote, which no caller can bind
// for themselves.
func GreenMultiReader(
	t *testing.T,
	control suite.Subject[MultiReader],
	opts ...MultiReaderRunOpt,
) {
	t.Helper()
	var rc multiReaderRunConfig
	for _, o := range opts {
		o.applyTo(&rc)
	}
	fx := multiReaderNewFixture()
	for _, row := range rc.rows {
		rc.AddCheck(row.bind(fx))
	}
	rc.Fail(t, "GreenMultiReader")
	s := multiReaderSuite(fx).With(rc.Extra...).Without(rc.Drops...)
	// The doors the run answers, so a control is refused for being wrong
	// rather than for being unwired — a wiring red recorded as "the suite
	// rejected correct code" would poison the measurement it exists for.
	for door, answer := range suite.Doors(rc.Subjects...) {
		if control.Provides == nil {
			control.Provides = map[suite.Capability]any{}
		}
		if _, answered := control.Provides[door]; !answered {
			control.Provides[door] = answer
		}
	}
	prove.Green(t, s.Checks, control)
}

// --- MultiReader's model tier: not emitted ----------------------------------
//
// MultiReader carries //testkit:model, and no rows above come from it:
// no claim this tier knows how to state reached this interface,
// so it contributes no checks. Each reason below is one it tried:
//   nothing was tried: no law's classification is stamped here, and
//   no reference derives from these methods, so there is no sequence
//   claim to make. A directive naming a partner method is what opens one.
//
// Nothing to do about it here. The claims that needed sequences are the
// ones this package does not check, and this says so rather than letting
// the run surface read as complete.

// testkit: end of generated content.
// testkit:provenance 466781c80137b015563ab69079a2d5440bf8cf110448d228ba62fa359a52a6b8
