// Code generated by testkit. DO NOT EDIT.
//
// Source:    corpus/iface/mixin/bounded/iface.go
// Plugins:   golang 1.0.0, suite 1.24.0, backend.golang 1.0.0
// Command:   testkit run ./corpus/...

package boundedtest_test

import (
	"testing"

	"go.thesmos.sh/testkit/conformance/corpus/iface/mixin/bounded/boundedtest"
	"go.thesmos.sh/testkit/engine/suite"
)

// The planted defects live in the file beside this one, on ProveMixed.
//
// They were here once, and could not stay: a check may need a capability,
// and only your harness answers it. A defect stands in for a real subject
// and borrows the same answer — which a test function in this package has
// no way to reach, because the harness is written in yours. So the map
// went where the entry point that takes it lives, and ProveMixed
// drives every defect below alongside the ones your own rows name:
//
//	Add.Smoke — a Mixed whose Add panics
//
//	Add.Cancels — a Mixed whose Add ignores the context it is handed
//
//	Add.NilContext — a Mixed whose Add forgives a nil context and answers
//
//	Add.Deadline — a Mixed whose Add ignores the context it is handed
//
//	List.Smoke — a Mixed whose List panics
//
//	List.Cancels — a Mixed whose List ignores the context it is handed
//
//	List.NilContext — a Mixed whose List forgives a nil context and answers
//
//	List.Deadline — a Mixed whose List ignores the context it is handed
//
//	List.ZeroOnError — a Mixed whose List answers a believable value beside its error

// TestMixedInvariants holds this package to what it says about itself.
//
// Four claims, none of which a consumer writes and none of which any
// other gate makes. The manifest pins the assertion SET, so a check that
// stops being emitted reads as a removed row in review rather than as a
// suite that quietly got smaller. The index and the drop hints pin the
// two ways a check is NAMED — an index entry pointing at nothing
// compiles, and a drop hint that falls back to the string form forfeits
// exactly the compile-break the index exists to give. The distinct-ID
// check catches two interfaces in one package claiming one identity,
// which method-name scopes make possible.
func TestMixedInvariants(t *testing.T) {
	t.Parallel()

	s := boundedtest.MixedSuite.Suite(boundedtest.DefaultMixedFixture())

	rows, err := suite.LockLines(s)
	if err != nil {
		t.Fatalf("render the manifest rows: %v", err)
	}
	suite.VerifyLock(t, "mixed.checks.lock", rows)
	suite.VerifyIndex(t, "Mixed",
		boundedtest.MixedSuite.Checks.All(), s.IDs())
	suite.VerifyDropHints(t, "Mixed", s.IDs(), s.DropHint)
	suite.VerifyDistinctIDs(t, s.IDs())
}

// testkit: end of generated content.
// testkit:provenance 2e4bfcdeb4273aebe8ae79b5c15de7d7767ded20edc0b9bc2820f502c93a3740
