// Code generated by testkit. DO NOT EDIT.
//
// Source:    corpus/iface/composite/leased-idempotent-writer/iface.go
// Plugins:   golang 1.0.0, stub 1.4.0, backend.golang 1.0.0
// Command:   testkit run ./corpus/...

// Conformance checks worked out from the interfaces this package doubles.
//
// One call runs every check for an interface against one implementation.
// Describe the implementation in a literal and hand it over — each
// interface's own Run function is documented beside it, with the names
// to use.
//
// Nothing else is required to start. The rest is there when you need it:
// a harness field to add only when a check fails asking for it, checks of
// your own that run beside the generated ones, a Prove entry that drives
// each of yours against the broken implementation it names, and a typed
// index for dropping a check by identity rather than by string.
//
// Nothing here is written by hand. Regenerate rather than edit: an edit
// survives until the next run and no longer.
package leasedidempotentwritertest

import (
	"context"
	"testing"

	"go.thesmos.sh/testkit/clock"
	leasedidempotentwriter "go.thesmos.sh/testkit/conformance/corpus/iface/composite/leased-idempotent-writer"
	"go.thesmos.sh/testkit/rand"
	"go.thesmos.sh/testkit/stub"
)

// LeasedWriterAcquireCall records one invocation of LeasedWriter.Acquire.
//
// Fields take their names from the source signature — parameters and named
// returns alike — so a failure message names what the author named. A slot
// the source left unnamed or blank falls back to a positional name.
type LeasedWriterAcquireCall struct {
	Ctx context.Context
	Key string
	Err error
}

// LeasedWriterReleaseCall records one invocation of LeasedWriter.Release.
//
// Fields take their names from the source signature — parameters and named
// returns alike — so a failure message names what the author named. A slot
// the source left unnamed or blank falls back to a positional name.
type LeasedWriterReleaseCall struct {
	Ctx context.Context
	Key string
	Err error
}

// --- Per-method configuration ---

// LeasedWriterAcquireStub controls how the double answers Acquire and records
// what it was asked.
//
// The embedded MethodStub supplies the machinery every method shares: call
// recording, fault injection, latency against a virtual clock, gates,
// call-count expectations, and strict mode.
type LeasedWriterAcquireStub struct {
	*stub.MethodStub[LeasedWriterAcquireCall]

	fn       func(context.Context, string) error
	fallback *LeasedWriterAcquireReturn
}

// LeasedWriterAcquireReturn holds the fixed answer configured through Returns.
type LeasedWriterAcquireReturn struct {
	Err error
}

// Returns pins a fixed result for every call to Acquire. A Func
// override and an injected fault both take precedence over it.
func (s *LeasedWriterAcquireStub) Returns(err error) *LeasedWriterAcquireStub {
	s.fallback = &LeasedWriterAcquireReturn{Err: err}
	return s
}

// Func supplies a body for Acquire, for when the answer depends on the
// arguments. An injected fault still takes precedence.
func (s *LeasedWriterAcquireStub) Func(fn func(context.Context, string) error) *LeasedWriterAcquireStub {
	s.fn = fn
	return s
}

// LeasedWriterReleaseStub controls how the double answers Release and records
// what it was asked.
//
// The embedded MethodStub supplies the machinery every method shares: call
// recording, fault injection, latency against a virtual clock, gates,
// call-count expectations, and strict mode.
type LeasedWriterReleaseStub struct {
	*stub.MethodStub[LeasedWriterReleaseCall]

	fn       func(context.Context, string) error
	fallback *LeasedWriterReleaseReturn
}

// LeasedWriterReleaseReturn holds the fixed answer configured through Returns.
type LeasedWriterReleaseReturn struct {
	Err error
}

// Returns pins a fixed result for every call to Release. A Func
// override and an injected fault both take precedence over it.
func (s *LeasedWriterReleaseStub) Returns(err error) *LeasedWriterReleaseStub {
	s.fallback = &LeasedWriterReleaseReturn{Err: err}
	return s
}

// Func supplies a body for Release, for when the answer depends on the
// arguments. An injected fault still takes precedence.
func (s *LeasedWriterReleaseStub) Func(fn func(context.Context, string) error) *LeasedWriterReleaseStub {
	s.fn = fn
	return s
}

// --- LeasedWriterStub ---

// The double-runtime witness for the surface this double rides. A
// breaking change to the runtime renames it, and this file stops
// compiling with the skew named.
var _ = stub.CompatV1

// LeasedWriterStubOption configures a [LeasedWriterStub] at construction time.
type LeasedWriterStubOption func(*LeasedWriterStub)

// LeasedWriterStubStrict makes an unconfigured method fail the test rather than
// return its zero value, which turns a call nobody planned for into a failure
// at the call site instead of a puzzling zero further downstream.
func LeasedWriterStubStrict() LeasedWriterStubOption {
	return func(s *LeasedWriterStub) { s.strict = true }
}

// LeasedWriterStubDelegateTo wraps a real implementation: every method forwards to
// impl and is recorded on the double on the way through.
//
// This is what lets one generated suite run against both the double and the
// production type, which is the point of conformance testing.
func LeasedWriterStubDelegateTo(impl leasedidempotentwriter.LeasedWriter) LeasedWriterStubOption {
	return func(s *LeasedWriterStub) {
		s.OnAcquire.Func(impl.Acquire)
		s.OnRelease.Func(impl.Release)
	}
}

// LeasedWriterStubWithClock drives latency and time-windowed faults from clk
// rather than from wall time, so a test asserting on a five-second timeout
// does not take five seconds.
func LeasedWriterStubWithClock(clk clock.Clock) LeasedWriterStubOption {
	return func(s *LeasedWriterStub) { s.group.SetClock(clk) }
}

// LeasedWriterStubWithRandSource makes probabilistic fault injection reproducible.
// A failure nobody can replay is not a finding.
func LeasedWriterStubWithRandSource(src rand.Source) LeasedWriterStubOption {
	return func(s *LeasedWriterStub) { s.group.SetRandSource(src) }
}

// LeasedWriterStubBenchMode disables call recording. Dispatch still works; only
// the accumulating call log is dropped, because its allocations are what a
// benchmark would otherwise be measuring.
func LeasedWriterStubBenchMode() LeasedWriterStubOption {
	return func(s *LeasedWriterStub) { s.group.BenchMode() }
}

// WithLeasedWriterAcquire sets Acquire's body at construction
// time, for the common case of configuring one method and taking the
// defaults for the rest.
func WithLeasedWriterAcquire(fn func(context.Context, string) error) LeasedWriterStubOption {
	return func(s *LeasedWriterStub) { s.OnAcquire.Func(fn) }
}

// WithLeasedWriterRelease sets Release's body at construction
// time, for the common case of configuring one method and taking the
// defaults for the rest.
func WithLeasedWriterRelease(fn func(context.Context, string) error) LeasedWriterStubOption {
	return func(s *LeasedWriterStub) { s.OnRelease.Func(fn) }
}

// LeasedWriterStub is a recording test double for LeasedWriter.
//
// Each On<Method> field is that method's configuration point. Left alone, a
// method returns its zero value and records the call.
type LeasedWriterStub struct {
	OnAcquire *LeasedWriterAcquireStub
	OnRelease *LeasedWriterReleaseStub

	// group is every method stub above, viewed through the surface that
	// does not depend on a signature — one home for the settings and the
	// lifecycle that apply to the whole double.
	group  *stub.Group
	strict bool
}

// Compile-time proof that LeasedWriterStub satisfies LeasedWriter.
//
// It lives here rather than in the companion so a drifted signature fails
// `go build` rather than waiting for a test run — the double is unusable the
// moment it stops satisfying the interface, and that is worth learning at the
// earliest point it can be known.
var _ leasedidempotentwriter.LeasedWriter = (*LeasedWriterStub)(nil)

// NewLeasedWriterStub returns a double bound to tb.
//
// Passing tb registers a cleanup that verifies every method's call-count
// expectations when the test ends, so an unmet Times is reported without the
// caller remembering to check. A nil tb skips that, which is what benchmarks
// and non-test callers want.
func NewLeasedWriterStub(tb testing.TB, opts ...LeasedWriterStubOption) *LeasedWriterStub {
	s := &LeasedWriterStub{
		OnAcquire: &LeasedWriterAcquireStub{MethodStub: stub.NewMethodStub[LeasedWriterAcquireCall](tb, "LeasedWriter.Acquire")},
		OnRelease: &LeasedWriterReleaseStub{MethodStub: stub.NewMethodStub[LeasedWriterReleaseCall](tb, "LeasedWriter.Release")},
	}
	s.group = stub.NewGroup(
		s.OnAcquire.MethodStub,
		s.OnRelease.MethodStub,
	)
	for _, opt := range opts {
		opt(s)
	}
	if s.strict {
		s.group.StrictAll()
	}
	s.group.Bind(tb)
	return s
}

// ResetCalls clears recorded calls, fault counters, and call-count
// expectations. Func and Returns configuration is deliberately preserved, so
// a test can reuse one double across phases without rebuilding it.
func (s *LeasedWriterStub) ResetCalls() {
	s.group.Reset()
}

// --- Interface methods ---

// invoke adapts the Func override to the shape [stub.Answer] consumes, or
// returns nil when no override is set — which is how Answer tells "no
// override" from "an override that returns zero".
func (s *LeasedWriterAcquireStub) invoke(ctx context.Context, key string) func() LeasedWriterAcquireReturn {
	if s.fn == nil {
		return nil
	}
	return func() LeasedWriterAcquireReturn {
		r0 := s.fn(ctx, key)
		return LeasedWriterAcquireReturn{Err: r0}
	}
}

// Acquire records the call and answers it.
//
// Which arm answers — injected fault, Func override, Returns fallback, or the
// zero value — is [stub.Answer]'s to decide, so every generated double
// resolves a call the same way and the ordering is tested once rather than
// restated per method.
func (s *LeasedWriterStub) Acquire(ctx context.Context, key string) error {
	call := LeasedWriterAcquireCall{Ctx: ctx, Key: key}
	r := stub.Answer(s.OnAcquire.MethodStub, &call, stub.Arms[LeasedWriterAcquireCall, LeasedWriterAcquireReturn]{
		Invoke:   s.OnAcquire.invoke(ctx, key),
		Fallback: s.OnAcquire.fallback,
		Fault:    func(err error) LeasedWriterAcquireReturn { return LeasedWriterAcquireReturn{Err: err} },
		Stamp: func(c *LeasedWriterAcquireCall, r LeasedWriterAcquireReturn) {
			c.Err = r.Err
		},
	})
	return r.Err
}

// invoke adapts the Func override to the shape [stub.Answer] consumes, or
// returns nil when no override is set — which is how Answer tells "no
// override" from "an override that returns zero".
func (s *LeasedWriterReleaseStub) invoke(ctx context.Context, key string) func() LeasedWriterReleaseReturn {
	if s.fn == nil {
		return nil
	}
	return func() LeasedWriterReleaseReturn {
		r0 := s.fn(ctx, key)
		return LeasedWriterReleaseReturn{Err: r0}
	}
}

// Release records the call and answers it.
//
// Which arm answers — injected fault, Func override, Returns fallback, or the
// zero value — is [stub.Answer]'s to decide, so every generated double
// resolves a call the same way and the ordering is tested once rather than
// restated per method.
func (s *LeasedWriterStub) Release(ctx context.Context, key string) error {
	call := LeasedWriterReleaseCall{Ctx: ctx, Key: key}
	r := stub.Answer(s.OnRelease.MethodStub, &call, stub.Arms[LeasedWriterReleaseCall, LeasedWriterReleaseReturn]{
		Invoke:   s.OnRelease.invoke(ctx, key),
		Fallback: s.OnRelease.fallback,
		Fault:    func(err error) LeasedWriterReleaseReturn { return LeasedWriterReleaseReturn{Err: err} },
		Stamp: func(c *LeasedWriterReleaseCall, r LeasedWriterReleaseReturn) {
			c.Err = r.Err
		},
	})
	return r.Err
}

// testkit: end of generated content.
// testkit:provenance fc858d584dc2392b378e02336ad6607033983005d832393182c7f010c6fe2cd2
